   <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'stockout';
                                        $variable = 'Simple';        
                                        require_once('views/scripts/template/template.phtml');
                                       
                                    ?>
                                    
                                    
                                     <div class="row">
                                         
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                      <?php require_once('views/scripts/dashboard/top_buttons.phtml');?>
				
                                           </div>
                                    
                                           <div  class="col-sm-7 pull-right box-shadow clearfix"  style="height:500px;" >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                 <?php echo  "Percent of facilities with an FP trained HW stocked out of any FP commodity, $this->date"; ?>
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                              
                                                                               <div id="infobutton" class="infobutton">
                                                                              <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                              <div id="" class="infodiv" >
                                                                                This chart shows the percentage of reporting facilities that have a 
                                                                                health worker trained in FP that report being stocked out of FP commodities for 
                                                                                seven consecutive days in the most recent month. <br/><br/>
                                                                                
                                                                                The chart helps to understand whether stock outs are a barrier to 
                                                                                FP service provision at facilities that should be providing FP because they 
                                                                                have a trained health worker. <br/><br/>
                                                                                
                                                                                FP training includes Contraceptive Technology Update, FP Technology, Injectable 
                                                                                Contraceptives for CHEWs, LARC, and Post Partum IUCD in-service trainings.<br/><br/>
                                                                            </div>
                                                                        </div>
                                                                
                                                                            </div>
                                                                             
                                                                          </div>   
                                             
                                               <div id="chart11_div" style="width:100%; height:350px;"></div>
                                         
				                           </div>                           
                                    </div>
                                    
                                    <div  class="row" style="margin-top:50px;margin-bottom:45px;">
                                         
                                           <div class="col-sm-7 box-shadow" style="height:500px;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                <?php echo  "Percent of facilities with a LARC trained HW stocked out of implants, $this->date"; ?>
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                             
			         	                                                      <div id="infobutton" class="infobutton">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                        This chart shows the percentage of reporting facilities that have a 
                                                                                        health worker trained in LARC that report being stocked out of implants 
                                                                                        in the most recent month. <br/><br/>
                                                                                        
                                                                                        The chart helps to understand whether stock outs are a barrier to LARC 
                                                                                        service provision at facilities that should be providing LARC because they 
                                                                                        have a trained health worker. <br/><br/>
                                                                                        
                                                                                        LARC training includes LARC and Post Partum IUCD in-service trainings.
                                                                                    </div>
                                                                                </div>
                                                                             
                                                                          </div>   
	
										<div id="chart12_div" style="width:100%; height:350px;"></div>
				
                                           </div>
                                               
                                           <div class=" col-sm-6"  >
                                               
                                           </div>
                                               
                                           </div>
                                    </div>
                                    
                                
                                </div>

		
		<div class="clear"></div>
                </div>
            
        
           
           </div><!-- content -->
           <br/><br/><br/>


		<script type="text/javascript">
		
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);

  $(function() {
	 // document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	drawChart12();
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;

<?php  //file_put_contents('c:\wamp\logs\php_debug.log', 'dash3 193 >'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();
	   //var_dump("location_data=", $this->location_data[0],"END");
	   //var_dump("facility_data=",$this->facility_data[0],"END");
	   //$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX); 
?>
		 
  });

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->
  //TA:17:18 Out of stock chart
  function drawChart11() {
      var jNumData = new Array();
      var jDenomData = new Array();
    <?php
        reset($this->fp_data); 
        $firstKey = key($this->fp_data); 
        $locationsString = ""; $valuesString = "";
	foreach ($this->fp_data as $key=>$row){
           $locationsString .= "'" . $row['location'] . "',";
           $location = $row['location'];
           $numerator = $this->fp_numerator[''.$location.''];
           $denominator = $this->fp_denominator[''.$location.''];
            if($firstKey == $key)
                $valuesString .= "{y:" . round($row['percent']*100, 1) . ", color: '#000000'},"; 
            else
                $valuesString .= round($row['percent']*100, 1) . ",";
            
              
                    ?>
                   jNumData['<?php echo $row['location']; ?>']  = <?php echo $numerator; ?> ; 
                   jDenomData['<?php echo $row['location']; ?>']  = <?php echo $denominator; ?> ; 
                    <?php
	}
        $locationsString = substr($locationsString, 0 , -1);
        $valuesString = substr($valuesString, 0 , -1);
    ?>

		    
          var titleText = '';
          var subtitleText = '(<?php echo  $this->date; ?>)';

	  $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 350
                },
                title: {
                    text: titleText,
                    x: -40,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                    title:{
                     text:'Geography',
                     style:{ "fontWeight": "bold" }
                   },
                    categories: [<?php echo $locationsString; ?>]
                },
                yAxis: {
                    title: {
                        text: 'Percent Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.x]);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: [<?php echo $valuesString; ?>]
                }]
            });
  }

 <!-------   /////////////////////////// script 1,2 ////////////////////// -->

//TA:17:18 Out of stock chart
 function drawChart12() {
 var jNumData = new Array();
 var jDenomData = new Array();
	                                                           
    <?php
            reset($this->fp_data); 
            $firstKey = key($this->fp_data); 
            $locationsString = ""; $valuesString = "";
            foreach ($this->larc_data as $key=>$row){
                $locationsString .= "'" . $row['location'] . "',";
                $location = $row['location'];
                $numerator = $this->larc_numerator[''.$location.''];
                $denominator = $this->larc_denominator[''.$location.''];
                    
                if($firstKey == $key)
                    $valuesString .= "{y:" . round($row['percent']*100, 1) . ", color: '#000000'},"; 
                else
                    $valuesString .= round($row['percent']*100, 1) . ",";
               ?>
                   jNumData['<?php echo $row['location']; ?>']  = <?php echo $numerator; ?> ; 
                   jDenomData['<?php echo $row['location']; ?>']  = <?php echo $denominator; ?> ; 
                            <?php
            }
            $locationsString = substr($locationsString, 0 , -1);
            $valuesString = substr($valuesString, 0 , -1);
    ?>


          var titleText = '';
          var subtitleText = '(<?php echo  $this->date; ?>)';
	  
	  $('#chart12_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart12_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 350
                },
                title: {
                    text: titleText,
                    x: -40,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                    title:{
                     text:'Geography',
                     style:{ "fontWeight": "bold" }
                   },
                    categories: [<?php echo $locationsString; ?>]
                },
                yAxis: {
                    title: {
                        text: 'Percent Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.x]);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: [<?php echo $valuesString; ?>]
                }]
            });
  }

  <!-------   /////////////////////////// 2,1 script gnr  ////////////////////// -->

	

  <!-------   /////////////////////////// 2,1 end script ////////////////////// -->


  <!-------   /////////////////////////// 2,2 script ////////////////////// -->

	


  <!-------   /////////////////////////// 2,2 end script ////////////////////// -->
  

  

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	
                
  <script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

<script src="../js/tp/functions.js"></script>

</body>

</html>



<?php


?>
