   <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'stockout';
                                       // $variable = 'Simple';        
                                        require_once('views/scripts/template/template.phtml');
                                       
                                    ?>
                                    
                                    
                                    
                                     <div class="row">
                                         
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                       <?php require_once('views/scripts/dashboard/top_buttons.phtml');?>
				
				
                                           </div>
                                    
                                           <div  class="col-sm-7 pull-right box-shadow clearfix"  style="height:auto;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                              
                                                                              <div id="infobutton" class="infobutton hidden">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                            <div id="" class="infodiv" >
                                                                                This chart shows the percentage of reporting facilities providing any FP 
                                                                                commodity in the last six months that report they stocked out of FP 
                                                                                commodities for 7 consecutive days in the most recent month or selected date(s). The chart 
                                                                                illustrates the proportion of facilities able to provide FP, based on 
                                                                                historical consumption, that are stocked out of FP commodities.
                                                                            </div>
                                                                        </div>
                                                                          </div>  
				                           </div>
                                               <div id="chart11_div" style="width:100%; height:auto;"></div>
                                    </div>
                                         
                                    </div>
                                    
                                    <div  class="row" style="margin-top:50px;">
                                         
                                           <div class="col-sm-7 box-shadow" style="height:auto;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                              <div id="infobutton" class="infobutton hidden">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                        This chart shows the percentage of reporting facilities providing at least 
                                                                                        one implant in the last six months that report they stocked out of implants 
                                                                                        in the most recent month or selected date(s). The chart illustrates the proportion of facilities 
                                                                                        able to provide implants, based on historical consumption, that are stocked 
                                                                                        out of implants.
                                                                                    </div>
                                                                                </div>
                                                                          </div>
				
                                           </div>
                                               
                                               
                                               <div id="chart12_div" style="width:100%; height:auto;"></div>
                                               
                                           
                                               
                                           </div>
                                    </div>
                                    
                                
                                   
                                

		
		<div class="clear"></div>
                </div>
            
          
            
           
            
          
           
           </div><!-- content -->
           <br/><br/><br/>
        

		<script type="text/javascript">
		
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);
  $(function() {
	 // document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	drawChart12();
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;

<?php  //file_put_contents('c:\wamp\logs\php_debug.log', 'dash3 193 >'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();
	   //var_dump("location_data=", $this->location_data[0],"END");
	   //var_dump("facility_data=",$this->facility_data[0],"END");
	   //$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX); 
?>
		 
  });

  function drawChart11() {
      var FPData = <?= $this->fp_data; ?>;
       var locations = new Array(); var values = new Array();
       
       for(key in FPData){
            row = FPData[key];
            locations.push(row['location']);
            
            if(key == 0)
                values.push({y: row['percent'], color: '#000000'}); 
            else 
                values.push(row['percent']);
       }
       
            <?php if($this->freshVisit) { ?>
                var titleText = '<?php echo  "Percent of facilities providing FP stocked out of any FP for 7 days,<br/> $this->date"; ?>';
            <?php } else { ?>
                var titleText = '<?php echo  "Percent of facilities providing FP stocked out of any FP for 7 days <br/>in selected geographies as of $this->date"; ?>';
            <?php } ?>
          
          $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                },
                title: {
                    text: titleText,
                    x: -20,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                    title:{
                     text:'Geography',
                     style:{ "fontWeight": "bold" }
                   },
                    categories: locations
                },
                yAxis: {
                   title: {
                        text: '%  Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                },
                tooltip: {
                    formatter: function () {
                        var location = this.x;
                        index = -1;
                        for(key in FPData){
                            if(FPData[key]['location'].toUpperCase() === location.toUpperCase()){
                                index = key;
                                break;
                            }   
                        }
                        
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/>' + 
                                '<b>Numerator</b>:' + thousandSeparator(FPData[index]['numer'])+'<br/>' +
                                '<b>Denominator</b>:'+thousandSeparator(FPData[index]['denom']);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: values
                }]
            });
	  
  }


 function drawChart12() {
       var LARCData = <?= $this->larc_data; ?>;
       var locations = new Array(); var values = new Array();
       
       for(key in LARCData){
            row = LARCData[key];
            locations.push(row['location']);
            
            if(key == 0)
                values.push({y: row['percent'], color: '#000000'}); 
            else 
                values.push(row['percent']);
       }
            
            <?php if($this->freshVisit) { ?>
                var titleText = '<?php echo  "Percent of facilities providing implants stocked out of implants,<br/> $this->date"; ?>';
            <?php } else { ?>
                var titleText = '<?php echo  "Percent of facilities providing implants stocked out of implants <br/>in selected geographies as of $this->date"; ?>';
            <?php } ?>
            
            $('#chart12_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart12_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                },
                title: {
                    text: titleText,
                    x: -20,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                    title:{
                     text:'Geography',
                     style:{ "fontWeight": "bold" }
                   },
                    categories: locations
                },
                yAxis: {
                    title: {
                        text: '%  Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                },
                tooltip: {
                    formatter: function () {
                        var location = this.x;
                        index = -1;
                        for(key in LARCData){
                            if(LARCData[key]['location'].toUpperCase() === location.toUpperCase()){
                                index = key;
                                break;
                            }   
                        }
                        
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/>' + 
                                '<b>Numerator</b>:' + thousandSeparator(LARCData[index]['numer'])+'<br/>' +
                                '<b>Denominator</b>:'+thousandSeparator(LARCData[index]['denom']);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: values
                }]
            });
  }

  

</script>

                </div>
  <script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
                </div>

</body>

</html>