<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />
<!--<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">-->

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
<!--<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />-->
<!--<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css">-->

<style>
    
    .infobutton {
        padding-right: 13px;
    }

</style>    

<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" defer async></script>

<!--<script src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>-->
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>-->

<script>
  $(function() {
    $( "#accordion" ).accordion({header: "h3", collapsible: true,active: 2});
    
       //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  </script>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  
                                    $singleSelection = true;
                                    require_once('views/scripts/dashboard/top_buttons.phtml');
                                ?>
					
			</div>



			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			<div class="nav-buttons">
				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    require_once('views/scripts/dashboard/left_buttons.phtml');
                                ?>				
			</div>
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->


			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">
				<div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv" style="margin-left: 20px;">
                                                                        <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    This chart shows stock out rates over time at facilities that have provided 
                                                                                    any FP services or implants specifically in the past. <br/><br/>
                                                                                    
                                                                                    For FP, this is the percentage of facilities reporting in the given month that 
                                                                                    have provided any FP commodities any time in the last six months that were 
                                                                                    stocked out of any FP commodity for at least seven days in the given month. <br/><br/>
                                                                                    
                                                                                    For implants, this is the percentage of facilities reporting in the given month that 
                                                                                    have consumed implants any time in the last six months that are stocked out of 
                                                                                    implants in the given month.
                                                                                </div>
                                                                            </div>
									<div id="chart11_div" style="width: 600px; height: 440px;"></div>
									</div>
									<div class="main-search">
										<div id="chart12_div" style="width: 600px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>			
					</div>

				<div class="clear"></div>
				<div class="hrGrey"></div>
				<div class="clear"></div>

				

								<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
<!--								
					<div id="bottomrow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
									<div id="chart13_div" style="width: 800px; height: 300px;"></div>
									</div>
									<div class="main-search">
										<div id="chart14_div" style="width: 500px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>
								
								-----   /////////////////////////// chart 2,2 ////////////////////// 
								
								
								<div class="main-search"></div>

					</div>-->
				</div>
		
	</div>

		<div class="clear"></div>
		<div class="hrGrey"></div>
		<div class="clear"></div>
		
		<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->

		<!-------   /////////////////////////// main gnr ////////////////////// -->

		<script type="text/javascript">
		
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);
  $(function(){
	  document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	//drawChart12();
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;
	
<?php  //file_put_contents('c:\wamp\logs\php_debug.log', 'dash3 193 >'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();
	   //var_dump("location_data=", $this->location_data[0],"END");
	   //var_dump("facility_data=",$this->facility_data[0],"END");
	   //$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX); 
?>
		 
  });

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->

    function drawChart11() {
         var jNumData = new Array();
         var jDenomData = new Array();
         
         jNumData['% FP facilities stocked out of any FP commodity for 7 days'] = [];
         jDenomData['% FP facilities stocked out of any FP commodity for 7 days'] = [];
         
         jNumData['% implant facilities stocked out of implants'] = [];
         jDenomData['% implant facilities stocked out of implants'] = [];
         
         
       
            var sevenObject = {name: '% FP facilities stocked out of any FP commodity for 7 days', data: []};
            var implantsObject = {name: '% implant facilities stocked out of implants', data: []};

            <?php 
                $month = "";
                if(!empty($this->fp_facs_providing_stockedout)){
                    foreach ($this->fp_facs_providing_stockedout as $key=>$monthProviders){ 
                        $month .= "'" . $monthProviders['month'] . "',";
                        $monthName = $monthProviders['month'];
                        $numeratorFP = $this->fp_numerator[$monthName];
                        $denominatorFP = $this->fp_denominator[$monthName];
                        
                        $numeratorLARC = $this->larc_numerator[$monthName];
                        $denominatorLARC = $this->larc_denominator[$monthName];
                        
                        
                        $seven_days_percent = round($monthProviders['seven_days_percent'] * 100,1);
                        $implant_percent = round($this->larc_facs_providing_stockedout[$key]['implant_percent'] * 100,1);
            ?>
                    jNumData['% FP facilities stocked out of any FP commodity for 7 days']['<?php echo $monthName; ?>'] = <?php echo $numeratorFP ?>;
                    
                    jDenomData['% FP facilities stocked out of any FP commodity for 7 days']['<?php echo $monthName; ?>'] = <?php echo $denominatorFP ?>;
                    
                    jNumData['% implant facilities stocked out of implants']['<?php echo $monthName; ?>'] = <?php echo $numeratorLARC ?>;
                    
                    jDenomData['% implant facilities stocked out of implants']['<?php echo $monthName; ?>'] = <?php echo $denominatorLARC ?>;
                    
                        //set PHP values into JS objects
                        sevenObject.data.push(<?php echo $seven_days_percent; ?>);
                        implantsObject.data.push(<?php echo $implant_percent; ?>);
            <?php
                    }//end foreach
                } //end if

                //strip trailing comma
                $month = substr($month, 0, -1);
            ?>
                    
                <?php 
                if(!empty($this->selectedDatemultiple)){
                    if(sizeof($this->selectedDatemultiple) > 1){
                  $title = ($this->freshvisit) ? "Stock outs at facilities providing FP, across selected dates" : "Stock outs in selected geographies across, selected dates";
                  $subtitle = "(across selected dates)";   
                    }else{
                       $title = ($this->freshvisit) ? "Stock outs at facilities providing FP, across selected date" : "Stock outs in selected geographies across, selected date";
                  $subtitle = "(across selected date(s))";  
                    }
                }else{
                     $title = ($this->freshvisit) ? "Stocks out at facilities providing FP, $this->start_date to $this->end_date" : "Stock outs in selected geographies, $this->start_date to $this->end_date";
                    $subtitle = "($this->start_date to $this->end_date)"; 
                }
              ?>;


                  $('#chart11_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 440,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                            }
                        }
                    },
                    title: {
                        text: '<?php echo $title; ?>',
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        x: -20 //center
                    },
                    xAxis: {
                        title:{
                     text:'Month',
                     style:{ "fontWeight": "bold" }
                   },
                        categories: [<?php echo $month; ?>]
                    },
                    yAxis: {
                       title: {
                        text: '%Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                        labels: {
                            format: '{value}%'
                        },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.series.name][this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.series.name][this.x]);
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        borderWidth: 1
                    },
                    series: [sevenObject, implantsObject]
                });
    }
  

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

      <script src="../js/highcharts/highcharts.js"></script>
      <script src="../js/highcharts/modules/exporting.js"></script>
                </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
                </div>
    <script src="../js/tp/functions.js"></script>
</body>

</html>