   <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'stockout';
                                       // $variable = 'Simple';        
                                        require_once('views/scripts/template/template.phtml');
                                       
                                    ?>
                                    
                                    
                                    
                                    
                                     <div class="row">
                                         
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                      <?php require_once('views/scripts/dashboard/top_buttons.phtml');?>
				
                                           </div>
                                    
                                           <div  class="col-sm-7 pull-right box-shadow clearfix"  style="height:500px;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >

                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                                  <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    This chart shows stock out rates over time at facilities that have provided 
                                                                                    any FP services or implants specifically in the past. <br/><br/>
                                                                                    
                                                                                    For FP, this is the percentage of facilities reporting in the given month that 
                                                                                    have provided any FP commodities any time in the last six months that were 
                                                                                    stocked out of any FP commodity for at least seven days in the given month. <br/><br/>
                                                                                    
                                                                                    For implants, this is the percentage of facilities reporting in the given month that 
                                                                                    have consumed implants any time in the last six months that are stocked out of 
                                                                                    implants in the given month.
                                                                                </div>
                                                                            </div>
                                                                            </div>
                                                                             
                                                                          </div>   
                                             
                                               <div id="chart11_div" style="width: 600px; height: 440px;"></div>
                                             
				                           </div>                           
                                    </div>
                                    
                                    <br/><br/>
                                
                                </div>

		<div class="clear"></div>
                </div>
          
           </div><!-- content -->
           <br/><br/><br/>













<script>
  $(function(){
	drawChart11();
	//drawChart12();
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;
		 
  });

  function drawChart11() {
            var FPSO = <?= $this->fp_facs_providing_stockedout; ?>;
            var LARCSO = <?= $this->larc_facs_providing_stockedout; ?>;
            var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
            var startDate = '<?= $this->end_date; ?>';
            
            var sevenObject = {name: '% FP facilities stocked out of any FP commodity for 7 days', data: []};
            var implantsObject = {name: '% implant facilities stocked out of implants', data: []};
            
            var monthNames = new Array();
            for(key in FPSO){
                var monthName = FPSO[key]['month'];
                monthNames.push(monthName);
                sevenObject.data.push(FPSO[key]['percent']);
                implantsObject.data.push(LARCSO[key]['percent']);
            }

            var monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
            var dateLength = selectedDatemultiple.length;
            
            <?php 
                if(!empty($this->selectedDatemultiple)){
                    if(sizeof($this->selectedDatemultiple) > 1)
                        {
                            $title = ($this->freshvisit) ? 
                                    "Stock outs at facilities providing FP, across selected date(s)" : 
                                    "Stock outs in selected geographies, across selected dates";
                            $subtitle = "(across selected dates)";   
                    } else {
                       $title = ($this->freshvisit) ? 
                                "Stock outs at facilities providing FP, across selected date(s)" : 
                                "Stock outs in selected geographies, across selected date(s)";
                        $subtitle = "(across selected date(s))";  
                    }
                }else{
                     $title = ($this->freshvisit) ? 
                             "Stock outs at facilities providing FP, $this->start_date to $this->end_date" : 
                             "Stock outs in selected geographies, $this->start_date to $this->end_date";
                    $subtitle = "($this->start_date to $this->end_date)"; 
                }
              ?>;

                var dateText = '<?= $this->start_date . " to " . $this->end_date ?>';
                    if(dateLength > 0){
                        dateText = dateLength === 1 ? 
                                monthNamesWithYears[0] : 
                                "across selected dates";
                    }
                <?php if($this->freshVisit) { ?>
                    var titleText = "Stock outs at facilities providing FP, <br/>" + dateText;
                <?php } else { ?>
                    var titleText = "Stock outs in selected geographies, <br/>" + dateText;
                <?php } ?>

                  $('#chart11_div').highcharts({
                    chart: {
                        type: dateLength == 1 ? 'column' : 'line',
                        height: 440,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                            }
                        }
                    },
                    title: {
                        text: titleText,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        x: -20 //center
                    },
                    xAxis: {
                        title:{
                     text:'Month',
                     style:{ "fontWeight": "bold" }
                   },
                        categories: monthNamesWithYears
                    },
                    yAxis: {
                       title: {
                        text: '% Faacilities',
                        style:{ "fontWeight": "bold" }
                    },
                        labels: {
                            format: '{value}%'
                        },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            var monthArray = (this.x).split(" ");
                            var month = monthArray[0];
                            
                            dataObj = new Array(); percentText = '';
                            if((this.series.name).includes('FP')){
                                dataObj = FPSO;
                            }
                            else if((this.series.name).includes('implant')){
                                dataObj = LARCSO;
                            }
                            
                            index = -1; 
                            for(key in dataObj){
                                if ((dataObj[key]['month']).toUpperCase() === month.toUpperCase()){
                                    index = key;
                                    break;
                                }
                            }
                        
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                                '<b>Numerator</b>:'+thousandSeparator(dataObj[index]['numer'])+'<br/>' + 
                                '<b>Denominator</b>:'+thousandSeparator(dataObj[index]['denom']);
                        }
                    },
                    plotOptions: {
                        series: {
                            marker: {
                                enabled: true
                            }
                        },
                        column: dateLength === 1  
                                 ? {    
                                    dataLabels: {
                                          enabled: true,
                                          format: '{y}%'
                                      }
                                  }
                                  : {}  
                    },
                    legend: {
                        layout: 'horizontal',
                        borderWidth: 1
                    },
                    series: [sevenObject, implantsObject]
                });
            
    }
  

</script>

      <script src="../js/highcharts/highcharts.js"></script>
      <script src="../js/highcharts/modules/exporting.js"></script>
                </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
                </div>
    <script src="../js/tp/overtime-ops.js"></script>
</body>

</html>