<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0 transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}
    
 
.hometabs.ui-widget-header {
    background: #eeeeee !important;
    font-size: 12px;
    border-top: solid 2px; 
}
    
.small-tab{
    background-color:white;
    font-size:12px;
    padding:2px;
}
    
   

body {font-family: "Lato", sans-serif;}


    
    

</style>

 <?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
    
<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">



<!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css"></link>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />


<link rel="stylesheet" href="<?php echo $this->base_url; ?>bootstrap/css/bootstrap.min.css"></link>
<!--<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css"></link>-->
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></link>

<link rel="stylesheet" href="<?php echo $this->base_url; ?>css/cssfile.css"></link>

<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>-->
<!--<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" ></script>-->

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script src="<?php echo $this->base_url; ?>bootstrap/js/bootstrap.min.js"></script>

                



<script>
  $(function() {
    //$( "#accordion" ).accordion({header: "h3", collapsible: true, active: false, animated:200, animated:"slide"});
    $( "#tabs").tabs();
    
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  
  $(document).ready(function(){
       $( "#tabs" ).tabs({
        activate: function( event, ui ) {
            var selectedTab = $("#tabs").tabs('option', 'active');
            if(selectedTab == 1){
                //redrawChart(chart11Options, chart11Data, chart11Div); 
                $("#chart11_div").highcharts().reflow();
            }
        }
      });
//      
//      $('.infobutton').click(function(){
//        console.log("inside click");
//      });
  });
  
//  function redrawChart(chartOptions, chartData, chartDiv) {      
//    var chart = new google.visualization.ColumnChart(document.getElementById(chartDiv));
//     chart.draw(chartData, chartOptions);
//  }
  
  </script>

           

</head>
    
<body class="yui-skin-sam" style="background-color:#EEEEEE;overflow-x:hidden;" >
    <?php
        
        //var_dump(array_keys($this->national_consumption_by_method)); exit;
    ?>
	<div id="pageHolder" style="margin:0px;background-color:#EEEEEE;padding-bottom:0px;">

		<div id="header"><?php require_once('views/scripts/headerhome.phtml');?></div>
		<div id="content" style="padding:0px;background-color:#EEEEEE;">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  //require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>
			
			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->

			<!--<body class="docs slim framebox_body">-->
                            
                            
                          
                                
                                
                                
				
                            <div class="row sidebar" style="background-color:#EEEEEE;margin-top:20px;height:100%;">
                                <div class="col-sm-2" style="height:100%;">
		
                                    
                                     <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'stockout';
                                        require_once('views/scripts/dashboard/left_buttonshome.phtml');
                                    ?>	
        
                                </div>
                                <div class="col-sm-10 " style="background-color:white;height:100%;padding-top:10px;">
                                    
                                    
                                    
                                     <div class="row">
                                         
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                      <?php require_once('views/scripts/dashboard/top_buttons.phtml');?>
				
                                           </div>
                                    
                                           <div  class="col-sm-7 pull-right box-shadow clearfix"  style="height:500px;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                <?php 
                                                                                    if(!empty($this->selectedDatemultiple)){
                                                                                        if(sizeof($this->selectedDatemultiple) > 1){
                                                                                      $title = ($this->freshvisit) ? "Stock out at facilities providing FP, across selected dates" : "Stock outs in selected geographies across, selected dates";
                                                                                      $subtitle = "(across selected dates)";   
                                                                                        }else{
                                                                                           $title = ($this->freshvisit) ? "Stock out at facilities providing FP, across selected date" : "Stock outs in selected geographies across, selected date";
                                                                                      $subtitle = "(across selected date)";  
                                                                                        }
                                                                                    }else{
                                                                                         $title = ($this->freshvisit) ? "Stock out at facilities providing FP, $this->start_date to $this->end_date" : "Stock outs in selected geographies, $this->start_date to $this->end_date";
                                                                                        $subtitle = "($this->start_date to $this->end_date)"; 
                                                                                    }
                                                                                    echo $title;
                                                                                  ?>

                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                                  <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    This chart shows stock out rates over time at facilities that have provided 
                                                                                    any FP services or implants specifically in the past. <br/><br/>
                                                                                    
                                                                                    For FP, this is the percentage of facilities reporting in the given month that 
                                                                                    have provided any FP commodities any time in the last six months that were 
                                                                                    stocked out of any FP commodity for at least seven days in the given month. <br/><br/>
                                                                                    
                                                                                    For implants, this is the percentage of facilities reporting in the given month that 
                                                                                    have consumed implants any time in the last six months that are stocked out of 
                                                                                    implants in the given month.
                                                                                </div>
                                                                            </div>
                                                                            </div>
                                                                             
                                                                          </div>   
                                             
                                               <div id="chart11_div" style="width: 600px; height: 440px;"></div>
                                             
				                           </div>                           
                                    </div>
                                    
                                    <br/><br/>
                                
                                </div>

		<div class="clear"></div>
                </div>
          
           </div><!-- content -->
           <br/><br/><br/>













<script>
  $(function(){
	drawChart11();
	//drawChart12();
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;
		 
  });

  function drawChart11() {
            var FPSO = <?= $this->fp_facs_providing_stockedout; ?>;
            var LARCSO = <?= $this->larc_facs_providing_stockedout; ?>;
            var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
            var startDate = '<?= $this->end_date; ?>';
            
            var sevenObject = {name: '% FP facilities stocked out of any FP commodity for 7 days', data: []};
            var implantsObject = {name: '% implant facilities stocked out of implants', data: []};
            
            monthNames = new Array();
            for(key in FPSO){
                var monthName = FPSO[key]['month'];
                monthNames.push(monthName);
                sevenObject.data.push(FPSO[key]['percent']);
                implantsObject.data.push(LARCSO[key]['percent']);
            }

            monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
            
            <?php 
                if(!empty($this->selectedDatemultiple)){
                    if(sizeof($this->selectedDatemultiple) > 1)
                        {
                            $title = ($this->freshvisit) ? 
                                    "Stock outs at facilities providing FP, across selected date(s)" : 
                                    "Stock outs in selected geographies, across selected dates";
                            $subtitle = "(across selected dates)";   
                    } else {
                       $title = ($this->freshvisit) ? 
                                "Stock outs at facilities providing FP, across selected date(s)" : 
                                "Stock outs in selected geographies, across selected date(s)";
                        $subtitle = "(across selected date(s))";  
                    }
                }else{
                     $title = ($this->freshvisit) ? 
                             "Stock outs at facilities providing FP, $this->start_date to $this->end_date" : 
                             "Stock outs in selected geographies, $this->start_date to $this->end_date";
                    $subtitle = "($this->start_date to $this->end_date)"; 
                }
              ?>;


                  $('#chart11_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 440,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                            }
                        }
                    },
                    title: {
                        text: '<?php //echo $title; ?>',
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        x: -20 //center
                    },
                    xAxis: {
                        title:{
                     text:'Month',
                     style:{ "fontWeight": "bold" }
                   },
                        categories: monthNamesWithYears
                    },
                    yAxis: {
                       title: {
                        text: 'Percent  Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                        labels: {
                            format: '{value}%'
                        },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            var monthArray = (this.x).split(",");
                            var month = monthArray[0];
                            
                            dataObj = new Array(); percentText = '';
                            if((this.series.name).includes('FP')){
                                dataObj = FPSO;
                            }
                            else if((this.series.name).includes('implant')){
                                dataObj = LARCSO;
                            }
                            
                            index = -1; 
                            for(key in dataObj){
                                if ((dataObj[key]['month']).toUpperCase() === month.toUpperCase()){
                                    index = key;
                                    break;
                                }
                            }
                        
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                                '<b>Numerator</b>:'+thousandSeparator(dataObj[index]['numer'])+'<br/>' + 
                                '<b>Denominator</b>:'+thousandSeparator(dataObj[index]['denom']);
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        borderWidth: 1
                    },
                    series: [sevenObject, implantsObject]
                });
            
    }
  

</script>

      <script src="../js/highcharts/highcharts.js"></script>
      <script src="../js/highcharts/modules/exporting.js"></script>
                </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
                </div>
    <script src="../js/tp/functions.js"></script>
    <script src="../js/tp/overtime-ops.js"></script>
</body>

</html>