<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0 transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}
    
 
.hometabs.ui-widget-header {
    background: #eeeeee !important;
    font-size: 12px;
    border-top: solid 2px; 
}
    
.small-tab{
    background-color:white;
    font-size:12px;
    padding:2px;
}
    
   

body {font-family: "Lato", sans-serif;}


    
    

</style>

 <?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
    
<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">



<!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css"></link>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />


<link rel="stylesheet" href="<?php echo $this->base_url; ?>bootstrap/css/bootstrap.min.css"></link>
<!--<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css"></link>-->
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></link>

<link rel="stylesheet" href="<?php echo $this->base_url; ?>css/cssfile.css"></link>

<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>-->
<!--<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" ></script>-->

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script src="<?php echo $this->base_url; ?>bootstrap/js/bootstrap.min.js"></script>

                



<script>
  $(function() {
    //$( "#accordion" ).accordion({header: "h3", collapsible: true, active: false, animated:200, animated:"slide"});
    $( "#tabs").tabs();
    
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  
  $(document).ready(function(){
       $( "#tabs" ).tabs({
        activate: function( event, ui ) {
            var selectedTab = $("#tabs").tabs('option', 'active');
            if(selectedTab == 1){
                //redrawChart(chart11Options, chart11Data, chart11Div); 
                $("#chart11_div").highcharts().reflow();
            }
        }
      });
//      
//      $('.infobutton').click(function(){
//        console.log("inside click");
//      });
  });
  
//  function redrawChart(chartOptions, chartData, chartDiv) {      
//    var chart = new google.visualization.ColumnChart(document.getElementById(chartDiv));
//     chart.draw(chartData, chartOptions);
//  }
  
  </script>

           

</head>
    
<body class="yui-skin-sam" style="background-color:#EEEEEE;overflow-x:hidden;" >
    <?php
        
        //var_dump(array_keys($this->national_consumption_by_method)); exit;
    ?>
	<div id="pageHolder" style="margin:0px;background-color:#EEEEEE;padding-bottom:0px;">

		<div id="header"><?php require_once('views/scripts/headerhome.phtml');?></div>
		<div id="content" style="padding:0px;background-color:#EEEEEE;">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  //require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>
			
			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->

			<!--<body class="docs slim framebox_body">-->
                            
                            
                          
                                
                                
                                
				
                            <div class="row sidebar" style="background-color:#EEEEEE;margin-top:20px;height:100%;">
                                <div class="col-sm-2" style="height:100%;">
	
                                    <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        require_once('views/scripts/dashboard/left_buttonshome.phtml');
                                    ?>				
        
                                </div>
                                <div class="col-sm-10 " style="background-color:white;height:100%;padding-top:10px;">
                                    
                                    
                                    
                                     <div class="row">
                                         
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                      <?php require_once('views/scripts/dashboard/top_buttons.phtml');?>
				
                                           </div>
                                    
                                           <div  class="col-sm-7 pull-right box-shadow clearfix"  style="height:500px;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                Total HWs trained nationally as of <?php echo $this->tp_date; ?>
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                              <div id="infobutton " class="infobutton firstInfoButton">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                            <div id="" class="infodiv" >
                                                                                The chart displays the cumulative number of health workers trained in FP 
                                                                                and trained in LARC as of each year shown. This chart also compares progress 
                                                                                to the national target. FP training includes Contraceptive Technology Update, 
                                                                                FP Technology, Injectable Contraceptives for CHEWs, LARC, and Post Partum IUCD 
                                                                                in-service trainings. LARC training includes LARC and Post Partum IUCD in-service trainings. 
                                                                            </div>
                                                                        </div>
                                                                            </div>
                                                                             
                                                                          </div>   
                                             
                                               <div id="chart_div"  style="width:100%; height: 400px;"></div>
                                         
				                           </div>                           
                                    </div>
                                    
                                    <div id="first-div" class="row" style="margin-top:50px;display:none;">
                                         
                                           <div class="col-sm-7 box-shadow" style="height:500px;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                Number of HWs trained in FP as of <?php echo $this->tp_date; ?>
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                              <div id="infobutton" class="infobutton">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The chart displays the cumulative number of health workers trained in FP 
                                                                                    as of each year shown in the selected geographies. FP training includes Contraceptive 
                                                                                    Technology Update, FP Technology, Injectable Contraceptives for CHEWs, LARC, 
                                                                                    and Post Partum IUCD in-service trainings.
                                                                                </div>
                                                                            </div>
                                                                             
                                                                          </div>   
	
			         	                      <div id="fpchart_div" style="width:100%; height: 300px;"></div>
				
                                           </div>
                                               
                                           <div class=" col-sm-6"  >
                                               
                                           </div>
                                               
                                           </div>
                                    </div>
                                    
                                    <div id="second-div" class="row" style="margin-top:50px;display:none;">
                                    
                                           <div  class="col-sm-7 box-shadow" style="height:500px;"   >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                Number of HWs trained in LARC as of <?php echo $this->tp_date; ?>
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                               <div id="infobutton" class="infobutton">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The chart displays the cumulative number of health workers trained in 
                                                                                    LARC as of each year shown in the selected geographies. LARC training 
                                                                                    includes LARC and Post Partum IUCD in-service trainings. 
                                                                                </div>
                                                                            </div>
                                                                             
                                                                          </div>   
	
			         	                      <div id="fpchart_div" class="box-shadow" style="width: 600px; height: 100%;"></div>
				
                                           </div>
                                               
                                               <div id="larcchart_div"  style="width:100%; height:400px;"></div>
	
				                           </div>  
                                       
                                    </div>
                                    
                                     
                                
                                   
                                </div>

		
		<div class="clear"></div>
                </div>
            
          
            
           
            
          
           
           </div><!-- content -->
           <br/><br/><br/>
        
         
		<!-------   /////////////////////////// main gnr ////////////////////// -->
<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->
<script type="text/javascript">                
/*************************    Prepare the values for FP and LARC when GEO is selected *********************/
<?php
        $fp_chartData =  $larc_chartData =  "";
        
        if(isset($this->fp_cumm_location)){
            reset($this->fp_cumm_location);
            $firstLocation = current($this->fp_cumm_location);  // get the location to be used as key in next stmt
            $yearsArray = array_keys($firstLocation);

            $yearsString = "";
            foreach ($yearsArray as $year){
                $yearsString .= "'$year',";
            }
            $yearsString = substr($yearsString, 0, -1);
            
            $locationsString = "";
            foreach($this->fp_cumm_location as $key=>$locationData) {
                $locationsString .= "'$key',";
            }
            $locationsString = substr($locationsString, 0, -1);
?>
            //JS: declare the arrays to store data
            var FPDataArray = new Array();
            var LARCDataArray = new Array();

<?php            
            foreach($yearsArray as $year){
?>                
                //JS
                var FPObj = {name:'', data:[]};  //define the object for this name/legend
                var LARCObj = {name:'', data:[]}
                FPObj.name = LARCObj.name = '<?php echo $year; ?>';
                
<?php             
                foreach($this->fp_cumm_location as $key=>$locationData) {
?>                  
                    //JS: push into the data array of each of object
                    //FPObj.data.push($locationData[$year]);
                    FPObj.data.push(<?php echo $this->fp_cumm_location[$key][$year]; ?>);
                    LARCObj.data.push(<?php echo $this->larc_cumm_location[$key][$year]; ?>);
<?php                    
                }//cumm_location loop
?>                    
                //JS: add the completed objects to wrapper dataArray(s) 
                FPDataArray.push(FPObj);
                LARCDataArray.push(LARCObj);
                
<?php   
            }//year loop

            $hAxisTitle = '2015 target number of HWs to be trained in LARC: 5500';
            $national_title = "";
            $nationalSubtitle = "";    
        }
        else{
            $hAxisTitle = '';
            $national_title = "";
            $nationalSubtitle = "";    
        }
  ?>
                

		
  //console.log("inside JS at least");
//  google.load('visualization', '1.0', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.setOnLoadCallback(apiLoaded);
  //function apiLoaded() {
  $(function() {
      
       drawNationalChart();
      
      // drawFPChart();
      
      // drawLARCChart();
        
	//document.getElementById("allCharts").style.marginLeft="130px";
        

		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;
		 
    
        <?php if(isset($this->fp_cumm_location)) { ?>
    
                
                drawNationalChart();
                drawFPChart();
                drawLARCChart();
        <?php } else { ?>
                console.log("combo");
                drawNationalComboChart();
        <?php } ?>
   
  });

    
    
  <!-------   /////////////////////////// script 1,1 ////////////////////// -->
  //TA:17:17: Coverage HW Trained chart
  function drawNationalComboChart() {
        
        var dataArray = new Array();
                
        <?php
             $yearsArray = array_keys($this->cumm_data);
             $namesArray = array('fp'=>'Total FP Trained', 'larc'=>'Total LARC Trained');
             foreach($namesArray as $nameKey=>$name){
        ?>
                //JS
                var obj = {name:'', data:[]};  //define the object for this name/legend
                obj.name = '<?php echo $name; ?>';
        
        <?php   foreach ($yearsArray as $year){  ?>
            
                    //JS
                    obj.data.push(<?php echo $this->cumm_data[$year][$nameKey]; ?>); //push the element into the array
                    
        <?php   } //inner for loop ?>
            
                //JS: add the obj to the dataArray 
                dataArray.push(obj);
                
        <?php }//outer for loop: $namesArray
             
            //now treat the categories
            $yearsString = '';
            foreach ($yearsArray as $year ){
                $yearsString .= "'" . $year . "',";
            }
            //drop trailing comma, use result as categories value
            $yearsString = substr($yearsString, 0, strlen($yearsString)-1); 
        ?>

              var hAxisTitle = <?php echo "'$hAxisTitle'"; ?>;
              var national_title = '<?php echo "$national_title $nationalSubtitle"; ?>';
              var nationalSubtitle = '(<?php echo $nationalSubtitle; ?>)';
              
               var lineObject = {
                    type: 'line',
                    name: '2015 Target # HWs <br/>to be Trained in LARC',
                    data: [5500, 5500, 5500],
                    marker: {
                        enabled: false,
                        lineWidth: 3,
                        //lineColor: Highcharts.getOptions().colors[2]
                        //fillColor: 'white'
                    }
                }
              
              dataArray.push(lineObject);
              console.log(dataArray);
              
              $("#chart_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#chart_div").siblings("#infobutton").removeClass("hidden");
                                }
                            }
                    },
                    title: {
                        text: national_title,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                    },
                    xAxis: {
                        title:{
                            text:'Year',
                            style:{ "fontWeight": "bold" }
                        },
                        categories: [<?php echo $yearsString; ?>],
                        
                    },
                    yAxis: {
                        title: {
                            text: '#HWs Trained',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'top',
                        //borderWidth: 0,
                        //layout: 'horizontal',
                        //align: 'right',
                        //verticalAlign: 'top',
                        //x: 40,
                        y: 60,
                        //width:100,
                        //floating: true,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        shadow: true
                    },
                    credits: {enabled: false},
                    series:dataArray

              });
      
    }
    
    
    function drawNationalChart(){
        
        var dataArray = new Array();
                
        <?php
             $yearsArray = array_keys($this->cumm_data);
             $namesArray = array('fp'=>'Total FP Trained', 'larc'=>'Total LARC Trained');
             foreach($namesArray as $nameKey=>$name){
        ?>
                //JS
                var obj = {name:'', data:[]};  //define the object for this name/legend
                obj.name = '<?php echo $name; ?>';
        
        <?php   foreach ($yearsArray as $year){  ?>
            
                    //JS
                    obj.data.push(<?php echo $this->cumm_data[$year][$nameKey]; ?>); //push the element into the array
                    
        <?php   } //inner for loop ?>
            
                //JS: add the obj to the dataArray 
                dataArray.push(obj);
                
        <?php }//outer for loop: $namesArray
             
            //now treat the categories
            $yearsString = '';
            foreach ($yearsArray as $year ){
                $yearsString .= "'" . $year . "',";
            }
            //drop trailing comma, use result as categories value
            $yearsString = substr($yearsString, 0, strlen($yearsString)-1); 
        ?>

              var hAxisTitle = <?php echo "'$hAxisTitle'"; ?>;
              var national_title = '<?php echo "$national_title $nationalSubtitle"; ?>';
              var nationalSubtitle = '(<?php echo $nationalSubtitle; ?>)';
              
              $("#chart_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#chart_div").siblings("#infobutton").removeClass("hidden");
                                }
                            },
                       
                    },
                    title: {
                        text: national_title,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                    },
                    xAxis: {
                        categories: [<?php echo $yearsString; ?>],
                        title: {
                            text: 'Year<br/><br/><?php echo $hAxisTitle; ?>',
                            style:{ "fontWeight": "bold" }
                        }
                        
                    },
                    yAxis: {
                        title: {
                            text: '#HWs Trained',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'top',
                        //x: 40,
                        y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        shadow: true
                    },
                    credits: {enabled: false},
                    series:dataArray

              });
    }
    
    
  
   function drawFPChart(){  
       
       document.getElementById('first-div').style.display = 'block'; 
                
       document.getElementById('second-div').style.display = 'block'; 
    
      <?php if(isset($this->fp_cumm_location)){ ?>
        var titleText = '';
        var subtitle = '(<?php echo  "as of $this->tp_date"; ?>)';
                
        $("#fpchart_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#fpchart_div").siblings("#infobutton").removeClass("hidden");
                                }
                            },
                       
                        height: 350
                    },
                    title: {
                        text: titleText,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                    },
                    xAxis: {
                        categories: [<?php echo $locationsString; ?>],
                        title: {
                            text: 'Geography',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    yAxis: {
                        title: {
                            text: '#HWs Trained',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'top',
                        //x: 40,
                        y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        shadow: true,
                        width: 100                                
                    },
                    credits: {enabled: false},
                    series:FPDataArray

              });
              
       
      <?php } ?>              
}
  
  function  drawLARCChart(){
    <?php if(isset($this->larc_cumm_location)){ ?>
        var titleText = '';
        var subtitle = '(<?php echo  "as of $this->tp_date"; ?>)';
                
        $("#larcchart_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#larcchart_div").siblings("#infobutton").removeClass("hidden");
                                }
                            },
                 
                        height: 350
                    },
                    title: {
                        text: titleText,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                    },
                    xAxis: {
                        categories: [<?php echo $locationsString; ?>],
                        title: {
                        text: 'Geography',
                        style:{ "fontWeight": "bold" }
                            }
                    },
                    yAxis: {
                        title: {
                            text: '#HWs Trained',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'top',
                        //x: 40,
                        y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        shadow: true,
                        width: 100
                    },
                    credits: {enabled: false},
                    series:LARCDataArray

              });
              
    <?php } ?>           
  }

</script>

<style type="text/css">
    .mclass{
        max-width:174px;
        overflow-wrap:break-word;
    }
</style>
<script>
  //devsite.github.Link.convertAnchors();
  //window.prettyPrint();
</script>	

<!--<script src="https://code.highcharts.com/highcharts.js"></script>-->
<!--<script src="https://code.highcharts.com/modules/exporting.js"></script>-->

<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

<script src="../js/tp/functions.js"></script>
        
 <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
        
</div>
           		


</body>

</html>