<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0 transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}
    
.small-box{
   background-color:#00E3E3;
   padding:24px;   
}
    
.img-box{

  width:25px;
  height:25px;
  margin-right:5px;
        
}

.big-box{
    background-color:white;
    color:black;
    font-size:12px;
    text-transform:uppercase;
    height:74px;
    padding-top:5px;
}
    

.font-20{
  font-size:16px;
}
    
.green{
    
    background-color:#06A259;
        
}

.red{
    
   background-color:#DD4C39;
        
}
    
.total-participant-color{
    background-color: #F39C11;  
}
    
.line-color-pie-chart{
     background-color:#262F31;   
}
    
.hometabs.ui-widget-header {
    background: #eeeeee !important;
    font-size: 12px;
    border-top: solid 2px; 
}
    
.small-tab{
    background-color:white;
    font-size:12px;
    padding:2px;
}
    
    .title-bar{
        width: 100%;
        
        margin-bottom:10px;
    }
    
    .border-hr{
        border-top: solid 2px #E36856;
    }
    
    
    
    .title-bar-info-btn{
        background-color:white;
        border-left:solid 1px #FAFAFA;
        padding-top:3px;
        padding-bottom:13px;
        
    }
    
    .border-fa{
        border-top: solid 2px #E36856;
    }
    
    .border-st{
        border-top: solid 2px #289D6C;
    }
    

body {font-family: "Lato", sans-serif;}

/* Style the tab */
div.tab {
    overflow: hidden;
    border: 1px solid #ccc;
    background-color: #f1f1f1;
}

/* Style the buttons inside the tab */
div.tab button {
    background-color: inherit;
    float: right;
    border: none;
    outline: none;
    cursor: pointer;
    padding: 8px;
    padding-top:8px;
    transition: 0.3s;
    font-size: 10px;
    width:50px;
    height:0px;
}

/* Change background color of buttons on hover */
div.tab button:hover {
    background-color: #ddd;
}

/* Create an active/current tablink class */
div.tab button.active {
    background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
    display: none;
    padding: 6px 12px;
    border: 1px solid #ccc;
    border-top: none;
}

    .box-shadow{
        box-shadow: 5px 5px 5px #cccccc;
    }
    
    @media screen and (max-width: 1000px) and (min-width: 300px) {
    .big-box{
    background-color:white;
    color:black;
    font-size:10px;
    text-transform:uppercase;
    height:74px;
}
        
        .font-20{
            font-size:12px;
        }
    
}
    
    

</style>

 <?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
    
<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">



<!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css"></link>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />


<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css"></link>
<!--<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css"></link>-->
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></link>

<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>-->
<!--<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" ></script>-->

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script src="bootstrap/js/bootstrap.min.js"></script>

                



<script>
  $(function() {
    //$( "#accordion" ).accordion({header: "h3", collapsible: true, active: false, animated:200, animated:"slide"});
    $( "#tabs").tabs();
    
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  
  $(document).ready(function(){
       $( "#tabs" ).tabs({
        activate: function( event, ui ) {
            var selectedTab = $("#tabs").tabs('option', 'active');
            if(selectedTab == 1){
                //redrawChart(chart11Options, chart11Data, chart11Div); 
                $("#chart11_div").highcharts().reflow();
            }
        }
      });
//      
//      $('.infobutton').click(function(){
//        console.log("inside click");
//      });
  });
  
//  function redrawChart(chartOptions, chartData, chartDiv) {      
//    var chart = new google.visualization.ColumnChart(document.getElementById(chartDiv));
//     chart.draw(chartData, chartOptions);
//  }
  
  </script>

</head>
    
<body class="yui-skin-sam" style="background-color:#EEEEEE;overflow-x:hidden;">
    <?php
        
        //var_dump(array_keys($this->national_consumption_by_method)); exit;
    ?>
	<div id="pageHolder" style="margin:0px;background-color:#EEEEEE;">

		<div id="header"><?php require_once('views/scripts/headerhome.phtml');?></div>
		<div id="content" style="padding:0px;background-color:white;">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  //require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>
			
			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->

			<!--<body class="docs slim framebox_body">-->
                            
                            
                          
                                
                                
                                
				
                            <div class="row sidebar" style="background-color:#EEEEEE;margin-top:20px;height:100%;">
                                <div class="col-md-2">
	
                                    <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        require_once('views/scripts/dashboard/left_buttonshome.phtml');
                                    ?>				
        
                                </div>
                                
                              <div class="col-md-10" style="background-color:white;padding-left:0px;padding-right:30px;">
                                  
                                    <div class="row" style="margin-bottom: 25px;text-align:center; ">
                                        
                                         <div class="col-sm-12 " style="margin-bottom:100px;"  >
                                
                                             <div class="col-sm-3 width-20 box-shadow">
                                    
                                                <div class="col-sm-4 text-center small-box" >
                                                    
                                                    <img src="images/map of 9ja.png" class="img-box" />
                                        
                                                </div>
                                    
                                                <div class="col-sm-8 text-left big-box" >
                                                   National Contraceptive Prevalence Rate <br>
                                                    <b class="font-20" > 15% (NDHS 2013) </b>
                                                
                                                </div>
                                    
                                             </div>
                                             
                                             <div class="col-sm-3 width-20 box-shadow">
                                    
                                                 <div class="col-sm-4 text-center small-box green">
                                                    
                                                     <img src="images/map of 9ja.png" class="img-box" />
                                        
                                                 </div>
                                    
                                                 <div class="col-sm-8 text-left big-box" >
                                                    2018 Contraceptive Prevalence Rate Target
                                                     
                                                     <br>

                                                     <b class="font-20" >36% </b>
                                                
                                                 </div>
                                    
                                              </div>
                                             
                                               <div class="col-sm-3 width-20 box-shadow">
                                    
                                                 <div class="col-sm-4 text-center small-box red">
                                                    
                                                     <img src="images/icon_x.png" class="img-box" />
                                        
                                                 </div>
                                    
                                                 <div class="col-sm-8 text-left big-box" >
                                                    Total number of trainings conducted
                                                      <br>
                                                     <b class="font-20" >6000</b>
                                                    
                                                 </div>
                                    
                                              </div>
                                             
                                             <div class="col-sm-3 width-20 box-shadow">
                                    
                                                 <div class="col-sm-4 text-center small-box total-participant-color">
                                                    
                                                     <img src="images/multiple-users-silhouette.png" class="img-box" />
                                        
                                                 </div>
                                    
                                                 <div class="col-sm-8 text-left big-box ">
                                                     Total Health Workers Trained
                                                      <br>
                                                     <b class="font-20" >7000 </b> 
                                                   
                                                 </div>
                                    
                                              </div>
                                             
                                             <div class="col-sm-12" style="padding-left:0px;padding-right:0px;">
                                                 
                                           <div class="col-sm-12" style="padding-left:0px;padding-right:0px;margin-top:15px;" >      
                                             
                                                 <div class="col-sm-6 " style="padding-right:3px; margin-top:14px;">
                                                     
                                                  

                                              
                                               <div id="tabs"    style="overflow:visible !important; min-height: 450px; border: 0;">
                                                   <div style="z-index:5000;margin-bottom:-23px;font-size:13px;">Consumption by method, <?php echo $this->title_date; ?></div>
                                                                         <div id="infobutton" class="infobutton hidden info11 align-left" style="margin-bottom: -47px;width: 55%;margin-left: 50%;">
                                                                                    <span class="infowrap" ><i class="fa fa-info-circle"></i></span>
                                                                                        <div id="" class="infodiv" style="margin-top:26px !important;">
                                                                                            This chart shows total national consumption of each FP commodity in the most 
                                                                                            recent month. Given the different scale of male condom consumption, 
                                                                                            consumption is reflected in units of 10 male condoms, while all other 
                                                                                            commodities are reflected as a single commodity.
                                                                                        </div>
                                                                                    </div><br/>
                                                                         
                                                                         
                                                                         
                                                                             <ul class="hometabs hidden" >
                                                                                 <li class=""><a href="#tab1">Pie</a></li>
                                                                                 <li class=""><a href="#tab2">Bar</a></li>
                                                                             </ul>
                                                                             
                                                                           
                                                                         
                                                                            <div id="tab1" class="sliderdiv" style="overflow:visible !important;width: 100%;"> 
                                                                                <div class="hrNav"></div>
                                                                                <div id="piechart" class="box-shadow" style="width: 100%; height: 0px; margin-top: -30px"></div>
                                                                                <!--<div id="chart11_div" style="width: 100%; height: 430px;"></div>-->
                                                                            </div>
                                                                         
                                                                            <div id="tab2" class="sliderdiv" style="overflow:visible !important;width: 100%; margin-top:0px;"> 
                                                                                <div class="hrNav"></div>
                                                                                <div id="chart11_div" class="box-shadow" style="width: 100%; height: 0px;overflow:visible !important;margin-top: -30px;margin-left: -20px;"></div>
                                                                            </div>
                                                                         
                                                                            
                                                                     </div>
                                                       </div>
                                               
                                               <?php
        $cs_fp_trained_facility_count = $this->csummary['cs_fp_trained_facility_count'];
        $cs_fp_consumption_facility_count = $this->csummary['cs_fp_consumption_facility_count'];
        $cs_fp_stock_out_facility_count = $this->csummary['cs_fp_stock_out_facility_count'];

        $cs_larc_trained_facility_count = $this->csummary['cs_larc_trained_facility_count'];
        $cs_larc_consumption_facility_count = $this->csummary['cs_larc_consumption_facility_count'];
        $cs_larc_stock_out_facility_count = $this->csummary['cs_larc_stock_out_facility_count'];
     ?> 
                                    
                                                 <div class="col-sm-6 " style="margin-top:5px;" >
                                                                         <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                HR Summary, <?php echo $this->title_date; ?>
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                             <div id="infobutton" class="infobutton" style="margin-left:4px;">
                                                                             
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The blue bars show the percent of all facilities in the country that have at 
                                                                                    least one trained health worker in FP or LARC as of the most recent month.<br/><br/>
                                                                                    
                                                                                    The red bars show the percentage of facilities with a trained health 
                                                                                    worker that reported in the most recent month and consumed at least one FP/LARC 
                                                                                    commodity in the most recent month. <br/><br/>
                                                                                    
                                                                                    The yellow bars show the  percentage of facilities with a trained health 
                                                                                    worker that reported in the most recent month and are stocked out of any FP commodity or implants. <br/><br/>
                                                                                    
                                                                                    FP training includes Contraceptive Technology Update, FP Technology, Injectable Contraceptives for CHEWs, 
                                                                                    LARC, and Post Partum IUCD in-service trainings. <br/><br/>
                                                                                    
                                                                                    LARC training includes LARC and Post Partum IUCD in-service trainings. 
                                                                                    <br/><br/>
                                                                                    
                                                                                    Together, these charts can provide a snapshot of barriers to service delivery 
                                                                                    (lack of training, lack of commodity availability, or lack of service provision due to some other barrier).
                                                                                </div>
                                                                            </div>
                                                                            </div>
                                                                             
                                                                          </div>   
                                               
                                                                         
                                                                          
                                                                    <div class="main-search box-shadow" style="width: 100%;height:425px;">
                                                                       
                                                                            <div id="infobutton" class="infobutton hidden" style="margin-bottom: 0;padding-right:15px;margin-top:-15px;">
                                                                                <br>
                                                                                
                                                                                <div id="" class="infodiv" >
                                                                                    The blue bars show the percent of all facilities in the country that have at 
                                                                                    least one trained health worker in FP or LARC as of the most recent month.<br/><br/>
                                                                                    
                                                                                    The red bars show the percentage of facilities with a trained health 
                                                                                    worker that reported in the most recent month and consumed at least one FP/LARC 
                                                                                    commodity in the most recent month. <br/><br/>
                                                                                    
                                                                                    The yellow bars show the  percentage of facilities with a trained health 
                                                                                    worker that reported in the most recent month and are stocked out of any FP commodity or implants. <br/><br/>
                                                                                    
                                                                                    FP training includes Contraceptive Technology Update, FP Technology, Injectable Contraceptives for CHEWs, 
                                                                                    LARC, and Post Partum IUCD in-service trainings. <br/><br/>
                                                                                    
                                                                                    LARC training includes LARC and Post Partum IUCD in-service trainings. 
                                                                                    <br/><br/>
                                                                                    
                                                                                    Together, these charts can provide a snapshot of barriers to service delivery 
                                                                                    (lack of training, lack of commodity availability, or lack of service provision due to some other barrier).
                                                                                </div>
                                                                            </div>
                                                                        <div class="hrNav" ></div>
                                                                       <div id="chart12_div" style="width: 100%;margin-top: 20px;height:320px;"></div>
                                                                    
                                                                     
						                      </div>	
                                                         
                                                 
                                             </div>
                                               
                                     </div>   
                                               
                                             
                                             <div class="col-sm-12" style="padding-left:0px;padding-right:0px;">
                                             
                                                   <div class="col-sm-6 " style="padding-right:3px;margin-top:5px;">
                                                       
                 
                                                       
                                                        <div class="title-bar border-fa col-xs-12"  style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font"  >
                                                                                Facilities Providing(%), <?php echo $this->start_date . ' to ' . $this->end_date; ?>
                                                                            </div>
                                                                            <div class="col-xs-1 title-bar-info-btn" style="min-height:20px;">
                                                                                <div id="infobutton" class="infobutton " style="margin-left:4px;">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The red line shows the percentage of reporting facilities that consumed at 
                                                                                    least one implant or IUCD in the given month. <br/><br/>
                                                                                    The blue line shows the percentage of reporting facilities that consumed at 
                                                                                    least one FP commodity in the given month. <br/><br/>
                                                                                    Together, these lines illustrate the gap between the availability of LARC 
                                                                                    services and short-acting FP services and whether this is improving over time.
                                                                                </div>
                                                                            </div>
                                                                            </div>
                                                                         </div>
                                                       
                                                                        <div class="sliderdiv" style="width: 100%;">
                                                                            <div id="infobutton" class="infobutton hidden" style="margin-bottom: -30px;padding-right:20px;">
                                                                               
                                                                                <div id="" class="infodiv" >
                                                                                    The red line shows the percentage of reporting facilities that consumed at 
                                                                                    least one implant or IUCD in the given month. <br/><br/>
                                                                                    The blue line shows the percentage of reporting facilities that consumed at 
                                                                                    least one FP commodity in the given month. <br/><br/>
                                                                                    Together, these lines illustrate the gap between the availability of LARC 
                                                                                    services and short-acting FP services and whether this is improving over time.
                                                                                </div>
                                                                            </div><br/>
                                                                        <div class="hrNav"></div>
                                                                        <div id="chart13_div" class="box-shadow" style="width: 100%; height: 430px;"></div>
                                                                    </div>
                                                                    </div>
                                                 
                                    
                                                                    <div class="col-sm-6" style="margin-top:5px;">

                                                                         <div class="title-bar border-st col-xs-12" style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font"  >
                                                                                <?php echo  "Stock outs, $this->start_date to $this->end_date"; ?>
                                                                            </div>
                                                                            <div class="col-xs-1 title-bar-info-btn" style="min-height:20px;">
                                                                                <div id="infobutton" class="infobutton" style="margin-left:4px;">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                        This chart shows stock out rates over time at facilities that have provided 
                                                                                        any FP services or implants specifically in the past. <br/><br/>

                                                                                        For FP, this is the percentage of facilities reporting in the given month that 
                                                                                        have provided any FP commodities any time in the last six months that were 
                                                                                        stocked out of any FP commodity for at least seven days in the given month. <br/><br/>

                                                                                        For implants, this is the percentage of facilities reporting in the given month that 
                                                                                        have consumed implants any time in the last six months that are stocked out of 
                                                                                        implants in the given month.
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                         </div>
                                                                       
                                                                        <div class="sliderdiv" style="width: 100%;">
                                                                                <div id="infobutton" class="infobutton hidden" style="margin-bottom: -30px;">
                                                                                    
                                                                                    <div id="" class="infodiv" >
                                                                                        This chart shows stock out rates over time at facilities that have provided 
                                                                                        any FP services or implants specifically in the past. <br/><br/>

                                                                                        For FP, this is the percentage of facilities reporting in the given month that 
                                                                                        have provided any FP commodities any time in the last six months that were 
                                                                                        stocked out of any FP commodity for at least seven days in the given month. <br/><br/>

                                                                                        For implants, this is the percentage of facilities reporting in the given month that 
                                                                                        have consumed implants any time in the last six months that are stocked out of 
                                                                                        implants in the given month.
                                                                                    </div>
                                                                                </div>
                                                                            <div class="hrNav"></div>
                                                                            <div id="chart14_div" class="box-shadow" style="width: 100%; height: 430px;margin-top: 20px;"></div>
                                                                        </div>
                                                                    </div>
                                                 
                                             </div>
                                             
                                              
                            
                            
                                         </div>
                                      
                                       
                                    </div>
                                
                                                              
						
                                 </div>
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
                                </div>			
					
                            
                                      
                                </div>

		
		<div class="clear"></div>
                </div>
           
           </div><!-- content -->
           <br/><br/><br/>
           <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
        </div> <!-- pagehoder -->
		<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->

		<!-------   /////////////////////////// main gnr ////////////////////// -->

<?php 
    //var_dump($this->facs_providing_stockedout);  
    //$this->national_percent_facilities_providing = array();
    //$this->national_percent_facilities_stock_out = array();   
?>
                
<script type="text/javascript">

		
  //google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
  //google.load('visualization', '1.1', {'packages':['bar']});
  //google.setOnLoadCallback(apiLoaded);
  
//  var chart11Options = "", chart11Data ="", chart11Div =""; 
  
  $(function() {
	  //document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	drawChart12();
	drawChart13();
	drawChart14();
     drawPieChart();
        //drawColumnChart();

	//var currentLevel;
	//currentLevel = <?php //echo '\'' . $this->location_data[0][name] . '\''; ?>;		 
  });
  
    function drawChart11(){
            <?php
                $methodString = ""; $consumptionString = "";
                foreach ($this->consumption_by_method as $key=>$row){
                   $malecondoms = 0;
                   
                   if($key == 1){
                       $methodString .= "'" . $row['method'] . '(unit x10)' . "',";
                       $consumptionString .= (int)round($row['consumption']/10) . ",";
                   }
                   else{
                       $methodString .= "'" . $row['method'] . "',";
                       $consumptionString .= $row['consumption'] . ",";
                   }
                 }

                 $methodString = substr($methodString, 0, strlen($methodString)-1);
                 $consumptionString = substr($consumptionString, 0, strlen($consumptionString)-1);
            ?>

            $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                        }
                    },
                    
                     height:420
                    
                },
                title: {
                    text: ''
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + thousandSeparator(this.y);
                    }
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                    title: {
                        text: 'FP Commodity',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: [<?php echo $methodString; ?>]
                },
                yAxis: {
                    title: {
                        text: 'No of Commodities Consumed',
                        style:{ "fontWeight": "bold" }
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: [<?php echo $consumptionString; ?>]
                }]
            });
    }
  
  
    function drawPieChart() {

	  $('#piechart').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    type: 'pie',
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $(".chart-title, .chart-subtitle, .hometabs, .hometabs li, .info11").removeClass("hidden");
                        }
                    },
                },
                title: {
                    text: ''
                },
                tooltip: {
                    //pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                    pointFormat: '<b>{point.percentage:.1f}%</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '{point.name}: {point.percentage:.1f} %',
//                            style: {
//                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black',
//                                fontWeight: 'normal'
//                            }
                             style: {
                                    "color": "black",
                                    "fontSize": "13px",
                                    "fontWeight": "normal"
                                }
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    name: 'Methods',
                    colorByPoint: true,
                    data: [
                            <?php
                                foreach ($this->consumption_by_method as $key=>$row){
                                           $consumption = $row['consumption'];
                                           $malecondoms = 0;
                                           $method = $row['method'];
                                           $color = 'blue';

                                           if($key == 1){
                                               //$malecondoms = $consumption;
                                               $consumption = round($consumption/10,0);  
                                               $method = $row['method'] . '<br/>(unit x10)';
                                           } 
                            ?>
                                          {<?php echo "name: '$method', y: $consumption"; ?>},
                            <?php
                                }
                            ?>
                    ]
                }]
            });
                  
   }
  
  

  function drawChart12() {
     
     <?php
        $cs_fp_trained_facility_count = $this->csummary['cs_fp_trained_facility_count'];
        $cs_fp_consumption_facility_count = $this->csummary['cs_fp_consumption_facility_count'];
        $cs_fp_stock_out_facility_count = $this->csummary['cs_fp_stock_out_facility_count'];

        $cs_larc_trained_facility_count = $this->csummary['cs_larc_trained_facility_count'];
        $cs_larc_consumption_facility_count = $this->csummary['cs_larc_consumption_facility_count'];
        $cs_larc_stock_out_facility_count = $this->csummary['cs_larc_stock_out_facility_count'];
     ?>        
        
        //var categories = "'FP', 'LARC'";
        var dataArray = [ 
                            {
                                //name: 'Facilities with FP-trained HW',
                                data: [<?php echo $cs_fp_trained_facility_count . "," . $cs_larc_trained_facility_count; ?>]
                            },
                            {
                                //name: 'FP-trained facilities providing FP',
                                data: [<?php echo $cs_fp_consumption_facility_count . "," . $cs_larc_consumption_facility_count; ?>]
                            },
                            {
                                //name: 'FP-trained facilities stocked out of FP or implants',
                                data: [<?php echo $cs_fp_stock_out_facility_count . "," . $cs_larc_stock_out_facility_count; ?>]
                            }                                                       
                        ];
      
      
      $("#chart12_div").highcharts({
            chart: {
                type: 'column',
                spacingLeft: 20,
                events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart12_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                height:375
            },

            title: {
                text: null
            },

            xAxis: {
                title: {
                    text: 'Category of Training',
                    style:{ "fontWeight": "bold" }
                },
                categories: ['FP','LARC']
            },
            yAxis: {
                title: {
                    text: 'No of Facilities',
                    style:{ "fontWeight": "bold" }
                },
                labels: {
                    formatter: function () {
                        return thousandSeparator(this.value);
                    }
                }
            },
            tooltip: {
                formatter: function () {
                    var seriesName='';
                    if(this.x == 'FP'){
                        if(this.series.index == 0) seriesName = 'Facilities with FP-trained HW';
                        if(this.series.index == 1) seriesName = 'FP-trained facilities providing FP';
                        if(this.series.index == 2) seriesName = 'FP-trained facilities stocked out of FP or implants';
                    } else if(this.x == 'LARC'){
                        if(this.series.index == 0) seriesName = 'Facilities with LARC-trained HW';
                        if(this.series.index == 1) seriesName = 'LARC-trained facilities providing LARC';
                        if(this.series.index == 2) seriesName = 'LARC-trained facilities stocked out of LARC or implants';
                    }
                    
                    return '<b>' + this.x + '</b><br/>' +
                                seriesName + ': ' + thousandSeparator(this.y) + '<br/>';
                        //this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                }
            },
            plotOptions: {
                column: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            legend: {
                //layout: 'vertical',
                //align: 'right',
                //verticalAlign: 'middle',
                //borderWidth: 0,
                layout: 'horizontal',
                align: 'right',
                //verticalAlign: 'top',
                //x: 40,
                //y: 40,
                //width:100,
                //floating: true,
                borderWidth: 1,
                backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                shadow: true
            },
            credits: {enabled: false},
            series:dataArray
      });
      
  }//end HR Summary
  
  
  function drawChart13() {
	var jNumData = new Array();
        var jDenomData = new Array();
         
         jNumData['FP'] = [];
         jDenomData['FP'] = [];
         
         jNumData['LARC'] = [];
         jDenomData['LARC'] = [];
         
        var FPObject = {name: "FP", data: []};
        var LARCObject = {name: "LARC", data: []};
                    
        <?php 
            //$locationNamesArray = explode(',', $locationNames);
            $month = $fpList = $larcList = "";
            if(!empty($this->fp_facs_providing)){
                foreach ($this->fp_facs_providing as $key=>$value){ 
                    $month .= "'" . $this->fp_facs_providing[$key]['month'] . "',";
                    $monthName = $this->fp_facs_providing[$key]['month'];
                    
                    
                    $numeratorFP = $this->fp_numerator_facsprov[$monthName];
                    $denominatorFP = $this->fp_denominator_facsprov[$monthName];
                        
                    $numeratorLARC = $this->larc_numerator_facsprov[$monthName];
                    $denominatorLARC = $this->larc_denominator_facsprov[$monthName];
                    
                    $fp_percent = round($this->fp_facs_providing[$key]['percent'] * 100,1);
                    $larc_percent = round($this->larc_facs_providing[$key]['percent'] * 100,1);
            ?>
                    jNumData['FP']['<?php echo $monthName; ?>'] = <?php echo $numeratorFP ?>;
                    
                    jDenomData['FP']['<?php echo $monthName; ?>'] = <?php echo $denominatorFP ?>;
                    
                    jNumData['LARC']['<?php echo $monthName; ?>'] = <?php echo $numeratorLARC ?>;
                    
                    jDenomData['LARC']['<?php echo $monthName; ?>'] = <?php echo $denominatorLARC ?>;
                    
                    //set PHP values into JS objects
                    FPObject.data.push(<?php echo $fp_percent; ?>);
                    LARCObject.data.push(<?php echo $larc_percent; ?>);
            <?php
                   }//end foreach
                } //end if
                
                //strip trailing commas
                $month = substr($month, 0, strlen($month)-1);
            ?>
        
        var titleText = '';
        var subtitleText = '(<?php echo $this->start_date . ' to ' . $this->end_date; ?>)';
        
              $('#chart13_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 430,
                        
                        spacingLeft: 0,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                            }
                        }
                    },
                    title: {
                        text: titleText,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                        title: {
                            text: 'Month',
                            style:{ "fontWeight": "bold" }
                        },
                        categories: [<?php echo $month; ?>]
                    },
                    yAxis: {
                        title: {
                            text: 'Percent of Facilities',
                            style:{ "fontWeight": "bold" }
                        },
                        labels: {
                            format: '{value}%'
                        },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.series.name][this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.series.name][this.x]);
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        borderWidth: 1,
                        shadow: true
                        
                    },
                    series: [FPObject, LARCObject]
                });

    }
    
    
    function drawChart14() {
        var jNumData = new Array();
        var jDenomData = new Array();
         
         jNumData['Percent FP facilities stocked out of any FP commodity for 7 days'] = [];
         jDenomData['Percent FP facilities stocked out of any FP commodity for 7 days'] = [];
         
         jNumData['Percent implant facilities stocked out of implants'] = [];
         jDenomData['Percent implant facilities stocked out of implants'] = [];
        
        var sevenObject = {name: 'Percent FP facilities stocked out of any FP commodity for 7 days', data: []};
        var implantsObject = {name: 'Percent implant facilities stocked out of implants', data: []};
                                    
       <?php 
            $month = "";
            if(!empty($this->fp_facs_providing_stockedout)){
                foreach ($this->fp_facs_providing_stockedout as $key=>$monthProviders){ 
                    $month .= "'" . $monthProviders['month'] . "',";
                    $monthName = $monthProviders['month'];
                    
                    $numeratorFP = $this->fp_numerator_stockout[$monthName];
                    $denominatorFP = $this->fp_denominator_stockout[$monthName];
                        
                    $numeratorLARC = $this->larc_numerator_stockout[$monthName];
                    $denominatorLARC = $this->larc_denominator_stockout[$monthName];
                        
                    $seven_days_percent = round($monthProviders['seven_days_percent'] * 100,1);
                    $implant_percent = round($this->larc_facs_providing_stockedout[$key]['implant_percent'] * 100,1);
        ?>                    
                  jNumData['Percent FP facilities stocked out of any FP commodity for 7 days']['<?php echo $monthName; ?>'] = <?php echo $numeratorFP ?>;
                    
                    jDenomData['Percent FP facilities stocked out of any FP commodity for 7 days']['<?php echo $monthName; ?>'] = <?php echo $denominatorFP ?>;
                    
                    jNumData['Percent implant facilities stocked out of implants']['<?php echo $monthName; ?>'] = <?php echo $numeratorLARC ?>;
                    
                    jDenomData['Percent implant facilities stocked out of implants']['<?php echo $monthName; ?>'] = <?php echo $denominatorLARC ?>;
                    //set PHP values into JS objects
                    sevenObject.data.push(<?php echo $seven_days_percent; ?>);
                    implantsObject.data.push(<?php echo $implant_percent; ?>);
        <?php
                        
                    }//end foreach
                } //end if
                
                //strip trailing commas
                $month = substr($month, 0, strlen($month)-1);
        ?>
                

        var titleText = '';
        var subtitleText = '(<?php echo $this->start_date . ' to ' . $this->end_date; ?>)';

              $('#chart14_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 430,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart14_div").siblings("#infobutton").removeClass("hidden");
                            }
                        }
                    },
                    title: {
                        text: titleText,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                        title: {
                            text: 'Month',
                            style:{ "fontWeight": "bold" }
                        },
                        categories: [<?php echo $month; ?>]
                    },
                    yAxis: {
                        title: {
                            text: 'Percent of Facilities',
                            style:{ "fontWeight": "bold" }
                        },
                        labels: {
                            format: '{value}%'
                        },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.series.name][this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.series.name][this.x]);
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        borderWidth: 1,
                        shadow: true
                    },
                    series: [sevenObject, implantsObject]
                });

   }
    
    

</script>


<!--<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	-->

<!--<script src="https://code.highcharts.com/highcharts.js"></script>-->
<!--<script src="https://code.highcharts.com/modules/exporting.js"></script>-->

<script src="js/highcharts/highcharts.js"></script>
<script src="js/highcharts/modules/exporting.js"></script>
<script src="js/tp/functions.js"></script>
<script src="css/sidebar.css"></script>
<div id="footer"><?php //require_once('views/scripts/footer.phtml');?></div>



</body>

</html>