<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0 transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}



</style>

 <?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
    
<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">



<!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css"></link>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />


<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css"></link>
<!--<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css"></link>-->
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></link>

<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>-->
<!--<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" ></script>-->

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script src="bootstrap/js/bootstrap.min.js"></script>

                



<script>
  $(function() {
    //$( "#accordion" ).accordion({header: "h3", collapsible: true, active: false, animated:200, animated:"slide"});
    $( "#tabs").tabs();
    
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  
  $(document).ready(function(){
       $( "#tabs" ).tabs({
        activate: function( event, ui ) {
            var selectedTab = $("#tabs").tabs('option', 'active');
            if(selectedTab == 1){
                //redrawChart(chart11Options, chart11Data, chart11Div); 
                $("#chart11_div").highcharts().reflow();
            }
        }
      });
//      
//      $('.infobutton').click(function(){
//        console.log("inside click");
//      });
  });
  
//  function redrawChart(chartOptions, chartData, chartDiv) {      
//    var chart = new google.visualization.ColumnChart(document.getElementById(chartDiv));
//     chart.draw(chartData, chartOptions);
//  }
  
  </script>

</head>
    
<body class="yui-skin-sam">
    <?php
        
        //var_dump(array_keys($this->national_consumption_by_method)); exit;
    ?>
	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/headerhome.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  //require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>
			
			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->

			<!--<body class="docs slim framebox_body">-->
                            <div align="right" ><font size="4"><label><?php echo 'National Contraceptive Prevalence Rate 15% Target 36%'; ?></label></font></div>
				
                            <div class="row sidebar" style="margin-top: 30px;">
                                <div class="col-md-2">
	
                                    <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        require_once('views/scripts/dashboard/left_buttonshome.phtml');
                                    ?>				
        
                                </div>
                                
                              <div class="col-md-10" style="margin-top: 10px;" >
                                    <div class="row" style="margin-bottom: 25px;margin-top: -15px;text-align:center; ">
                                        <div id="" class="col-md-1" style=""></div>
                                        <div id="" class="col-md-4" style="display:block !important;"><span class="chart-title hidden">Consumption by method, <?php echo $this->title_date; ?></span></div>
                                        <div id="" class="col-md-2" style=""></div>
                                        <div id="" class="col-md-5" style="display:block !important;"><span class="chart-title hidden">HR Summary, <?php echo $this->title_date; ?></span></div>
                                    </div>
                                  
                                  <div class="row">
						
                                                                     <div id="tabs" class="col-md-6" style="overflow:visible !important; min-height: 450px; border: 0;">
                                                                         <div id="infobutton" class="infobutton hidden info11 align-left" style="margin-bottom: -47px;width: 55%;margin-left: 50%;">
                                                                                    <span class="infowrap" ><i class="fa fa-info-circle"></i></span>
                                                                                        <div id="" class="infodiv" style="margin-top:26px !important;">
                                                                                            This chart shows total national consumption of each FP commodity in the most 
                                                                                            recent month. Given the different scale of male condom consumption, 
                                                                                            consumption is reflected in units of 10 male condoms, while all other 
                                                                                            commodities are reflected as a single commodity.
                                                                                        </div>
                                                                                    </div><br/>
                                                                         
                                                                          <ul class="hometabs hidden">
                                                                              <li class=""><a href="#tab1">Pie</a></li>
                                                                              <li class=""><a href="#tab2">Bar</a></li>
                                                                          </ul>     
                                                                         
                                                                            <div id="tab1" class="sliderdiv" style="overflow:visible !important;width: 100%;"> 
                                                                                <div class="hrNav"></div>
                                                                                <div id="piechart" style="width: 100%; height: 300px; margin-top: -30px"></div>
                                                                                <!--<div id="chart11_div" style="width: 100%; height: 430px;"></div>-->
                                                                            </div>
                                                                         
                                                                            <div id="tab2" class="sliderdiv" style="overflow:visible !important;width: 100%; margin-top:0px;"> 
                                                                                <div class="hrNav"></div>
                                                                                <div id="chart11_div" style="width: 100%; height: 350px;overflow:visible !important;margin-top: -30px;margin-left: -20px;"></div>
                                                                            </div>
                                                                         
                                                                            
                                                                     </div>
                                    
                                                                     <div class="col-md-6">
                                                                        
                                                                    <div class="main-search" style="width: 100%; margin: 0px !important;">
                                                                       
                                                                            <div id="infobutton" class="infobutton hidden" style="margin-bottom: -25px;padding-right:15px;">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The blue bars show the percent of all facilities in the country that have at 
                                                                                    least one trained health worker in FP or LARC as of the most recent month.<br/><br/>
                                                                                    
                                                                                    The red bars show the percentage of facilities with a trained health 
                                                                                    worker that reported in the most recent month and consumed at least one FP/LARC 
                                                                                    commodity in the most recent month. <br/><br/>
                                                                                    
                                                                                    The yellow bars show the  percentage of facilities with a trained health 
                                                                                    worker that reported in the most recent month and are stocked out of any FP commodity or implants. <br/><br/>
                                                                                    
                                                                                    FP training includes Contraceptive Technology Update, FP Technology, Injectable Contraceptives for CHEWs, 
                                                                                    LARC, and Post Partum IUCD in-service trainings. <br/><br/>
                                                                                    
                                                                                    LARC training includes LARC and Post Partum IUCD in-service trainings. 
                                                                                    <br/><br/>
                                                                                    
                                                                                    Together, these charts can provide a snapshot of barriers to service delivery 
                                                                                    (lack of training, lack of commodity availability, or lack of service provision due to some other barrier).
                                                                                </div>
                                                                            </div>
                                                                        <div class="hrNav"></div>
                                                                       <div id="chart12_div" style="width: 100%; height: 430px;margin-top: 20px;"></div>
                                                                    
                                                                     
						</div>		</div>	
				
					
					<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
                                </div>
                                 <div class="row">
                                    
					
						
                                                                    <div class="col-md-6">
                                                                        <div class="sliderdiv" style="width: 100%;">
                                                                            <div id="infobutton" class="infobutton hidden" style="margin-bottom: -30px;padding-right:20px;">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The red line shows the percentage of reporting facilities that consumed at 
                                                                                    least one implant or IUCD in the given month. <br/><br/>
                                                                                    The blue line shows the percentage of reporting facilities that consumed at 
                                                                                    least one FP commodity in the given month. <br/><br/>
                                                                                    Together, these lines illustrate the gap between the availability of LARC 
                                                                                    services and short-acting FP services and whether this is improving over time.
                                                                                </div>
                                                                            </div><br/>
                                                                        <div class="hrNav"></div>
                                                                        <div id="chart13_div" style="width: 100%; height: 300px;"></div>
                                                                    </div>
                                                                    </div>
                                        
                                                                    <div class="col-md-6">
                                                                       
                                                                        <div class="sliderdiv" style="width: 100%;padding-left:15px;">
                                                                                <div id="infobutton" class="infobutton hidden" style="margin-bottom: -30px;padding-right: 60px;">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                        This chart shows stock out rates over time at facilities that have provided 
                                                                                        any FP services or implants specifically in the past. <br/><br/>

                                                                                        For FP, this is the percentage of facilities reporting in the given month that 
                                                                                        have provided any FP commodities any time in the last six months that were 
                                                                                        stocked out of any FP commodity for at least seven days in the given month. <br/><br/>

                                                                                        For implants, this is the percentage of facilities reporting in the given month that 
                                                                                        have consumed implants any time in the last six months that are stocked out of 
                                                                                        implants in the given month.
                                                                                    </div>
                                                                                </div>
                                                                            <div class="hrNav"></div>
                                                                            <div id="chart14_div" style="width: 90%; height: 300px;margin-top: 20px;"></div>
                                                                        </div>
                                                                    </div>

						
                                 </div>
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
                                </div>			
					
                            
                                      
                                </div>

		<div class="hrNav"></div>
		<div class="clear"></div>
                </div>
           
           </div><!-- content -->
        </div> <!-- pagehoder -->
		<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->

		<!-------   /////////////////////////// main gnr ////////////////////// -->

<?php 
    //var_dump($this->facs_providing_stockedout);  
    //$this->national_percent_facilities_providing = array();
    //$this->national_percent_facilities_stock_out = array();   
?>
                
<script type="text/javascript">

		
  //google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
  //google.load('visualization', '1.1', {'packages':['bar']});
  //google.setOnLoadCallback(apiLoaded);
  
//  var chart11Options = "", chart11Data ="", chart11Div =""; 
  
  $(function() {
	  //document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	drawChart12();
	drawChart13();
	drawChart14();
        drawPieChart();
        //drawColumnChart();

	//var currentLevel;
	//currentLevel = <?php //echo '\'' . $this->location_data[0][name] . '\''; ?>;		 
  });
  
    function drawChart11(){
            <?php
                $methodString = ""; $consumptionString = "";
                foreach ($this->consumption_by_method as $key=>$row){
                   $malecondoms = 0;
                   
                   if($key == 1){
                       $methodString .= "'" . $row['method'] . '(unit x10)' . "',";
                       $consumptionString .= (int)round($row['consumption']/10) . ",";
                   }
                   else{
                       $methodString .= "'" . $row['method'] . "',";
                       $consumptionString .= $row['consumption'] . ",";
                   }
                 }

                 $methodString = substr($methodString, 0, strlen($methodString)-1);
                 $consumptionString = substr($consumptionString, 0, strlen($consumptionString)-1);
            ?>

            $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                        }
                    },
                    height: 430
                },
                title: {
                    text: ''
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + thousandSeparator(this.y);
                    }
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                    title: {
                        text: 'FP Commodity',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: [<?php echo $methodString; ?>]
                },
                yAxis: {
                    title: {
                        text: '#Commodities Consumed',
                        style:{ "fontWeight": "bold" }
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: [<?php echo $consumptionString; ?>]
                }]
            });
    }
  
  
   function drawPieChart() {

	  $('#piechart').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    type: 'pie',
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $(".chart-title, .chart-subtitle, .hometabs, .hometabs li, .info11").removeClass("hidden");
                        }
                    },
                },
                title: {
                    text: ''
                },
                tooltip: {
                    //pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                    pointFormat: '<b>{point.percentage:.1f}%</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '{point.name}: {point.percentage:.1f} %',
//                            style: {
//                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black',
//                                fontWeight: 'normal'
//                            }
                             style: {
                                    "color": "black",
                                    "fontSize": "13px",
                                    "fontWeight": "normal"
                                }
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    name: 'Methods',
                    colorByPoint: true,
                    data: [
                            <?php
                                foreach ($this->consumption_by_method as $key=>$row){
                                           $consumption = $row['consumption'];
                                           $malecondoms = 0;
                                           $method = $row['method'];
                                           $color = 'blue';

                                           if($key == 1){
                                               //$malecondoms = $consumption;
                                               $consumption = round($consumption/10,0);  
                                               $method = $row['method'] . '(unit x10)';
                                           } 
                            ?>
                                          {<?php echo "name: '$method', y: $consumption"; ?>},
                            <?php
                                }
                            ?>
                    ]
                }]
            });
                  
   }
  
  

  function drawChart12() {
     
     <?php
        $cs_fp_trained_facility_count = $this->csummary['cs_fp_trained_facility_count'];
        $cs_fp_consumption_facility_count = $this->csummary['cs_fp_consumption_facility_count'];
        $cs_fp_stock_out_facility_count = $this->csummary['cs_fp_stock_out_facility_count'];

        $cs_larc_trained_facility_count = $this->csummary['cs_larc_trained_facility_count'];
        $cs_larc_consumption_facility_count = $this->csummary['cs_larc_consumption_facility_count'];
        $cs_larc_stock_out_facility_count = $this->csummary['cs_larc_stock_out_facility_count'];
     ?>        
        
        //var categories = "'FP', 'LARC'";
        var dataArray = [ 
                            {
                                //name: 'Facilities with FP-trained HW',
                                data: [<?php echo $cs_fp_trained_facility_count . "," . $cs_larc_trained_facility_count; ?>]
                            },
                            {
                                //name: 'FP-trained facilities providing FP',
                                data: [<?php echo $cs_fp_consumption_facility_count . "," . $cs_larc_consumption_facility_count; ?>]
                            },
                            {
                                //name: 'FP-trained facilities stocked out of FP or implants',
                                data: [<?php echo $cs_fp_stock_out_facility_count . "," . $cs_larc_stock_out_facility_count; ?>]
                            }                                                       
                        ];
      
      
      $("#chart12_div").highcharts({
            chart: {
                type: 'column',
                spacingLeft: 20,
                events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart12_div").siblings("#infobutton").removeClass("hidden");
                        }
                    }
            },

            title: {
                text: null
            },

            xAxis: {
                title: {
                    text: 'Category of Training',
                    style:{ "fontWeight": "bold" }
                },
                categories: ['FP','LARC']
            },
            yAxis: {
                title: {
                    text: '#Facilities',
                    style:{ "fontWeight": "bold" }
                },
                labels: {
                    formatter: function () {
                        return thousandSeparator(this.value);
                    }
                }
            },
            tooltip: {
                formatter: function () {
                    var seriesName='';
                    if(this.x == 'FP'){
                        if(this.series.index == 0) seriesName = 'Facilities with FP-trained HW';
                        if(this.series.index == 1) seriesName = 'FP-trained facilities providing FP';
                        if(this.series.index == 2) seriesName = 'FP-trained facilities stocked out of FP or implants';
                    } else if(this.x == 'LARC'){
                        if(this.series.index == 0) seriesName = 'Facilities with LARC-trained HW';
                        if(this.series.index == 1) seriesName = 'LARC-trained facilities providing LARC';
                        if(this.series.index == 2) seriesName = 'LARC-trained facilities stocked out of LARC or implants';
                    }
                    
                    return '<b>' + this.x + '</b><br/>' +
                                seriesName + ': ' + thousandSeparator(this.y) + '<br/>';
                        //this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                }
            },
            plotOptions: {
                column: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            legend: {
                //layout: 'vertical',
                //align: 'right',
                //verticalAlign: 'middle',
                //borderWidth: 0,
                layout: 'horizontal',
                align: 'right',
                //verticalAlign: 'top',
                //x: 40,
                //y: 40,
                //width:100,
                //floating: true,
                borderWidth: 1,
                backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                shadow: true
            },
            credits: {enabled: false},
            series:dataArray
      });
      
  }//end HR Summary
  
  
  function drawChart13() {
	
        var FPObject = {name: "FP", data: []};
        var LARCObject = {name: "LARC", data: []};
                    
        <?php 
            //$locationNamesArray = explode(',', $locationNames);
            $month = $fpList = $larcList = "";
            if(!empty($this->fp_facs_providing)){
                foreach ($this->fp_facs_providing as $key=>$value){ 
                    $month .= "'" . $this->fp_facs_providing[$key]['month'] . "',";
                    $fp_percent = round($this->fp_facs_providing[$key]['percent'] * 100,1);
                    $larc_percent = round($this->larc_facs_providing[$key]['percent'] * 100,1);
            ?>
                    //set PHP values into JS objects
                    FPObject.data.push(<?php echo $fp_percent; ?>);
                    LARCObject.data.push(<?php echo $larc_percent; ?>);
            <?php
                   }//end foreach
                } //end if
                
                //strip trailing commas
                $month = substr($month, 0, strlen($month)-1);
            ?>
        
        var titleText = 'Percent of facilities providing FP and LARC, <?php echo $this->start_date . ' to ' . $this->end_date; ?>';
        var subtitleText = '(<?php echo $this->start_date . ' to ' . $this->end_date; ?>)';
        
              $('#chart13_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 400,
                        width: 500,
                        spacingLeft: 0,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                            }
                        }
                    },
                    title: {
                        text: titleText,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                        title: {
                            text: 'Month',
                            style:{ "fontWeight": "bold" }
                        },
                        categories: [<?php echo $month; ?>]
                    },
                    yAxis: {
                        title: {
                            text: '%Facilities',
                            style:{ "fontWeight": "bold" }
                        },
                        labels: {
                            format: '{value}%'
                        },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>';
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        borderWidth: 1,
                        shadow: true
                        
                    },
                    series: [FPObject, LARCObject]
                });

    }
    
    
    function drawChart14() {
        
        var sevenObject = {name: '% FP facilities stocked out of any FP commodity for 7 days', data: []};
        var implantsObject = {name: '% implant facilities stocked out of implants', data: []};
                                    
       <?php 
            $month = "";
            if(!empty($this->fp_facs_providing_stockedout)){
                foreach ($this->fp_facs_providing_stockedout as $key=>$monthProviders){ 
                    $month .= "'" . $monthProviders['month'] . "',";
                    $seven_days_percent = round($monthProviders['seven_days_percent'] * 100,1);
                    $implant_percent = round($this->larc_facs_providing_stockedout[$key]['implant_percent'] * 100,1);
        ?>                    
                    //set PHP values into JS objects
                    sevenObject.data.push(<?php echo $seven_days_percent; ?>);
                    implantsObject.data.push(<?php echo $implant_percent; ?>);
        <?php
                        
                    }//end foreach
                } //end if
                
                //strip trailing commas
                $month = substr($month, 0, strlen($month)-1);
        ?>
                

        var titleText = '<?php echo  "Stock outs, $this->start_date to $this->end_date"; ?>';
        var subtitleText = '(<?php echo $this->start_date . ' to ' . $this->end_date; ?>)';

              $('#chart14_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 440,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart14_div").siblings("#infobutton").removeClass("hidden");
                            }
                        }
                    },
                    title: {
                        text: titleText,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                        title: {
                            text: 'Month',
                            style:{ "fontWeight": "bold" }
                        },
                        categories: [<?php echo $month; ?>]
                    },
                    yAxis: {
                        title: {
                            text: '%Facilities',
                            style:{ "fontWeight": "bold" }
                        },
                        labels: {
                            format: '{value}%'
                        },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>';
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        borderWidth: 1,
                        shadow: true
                    },
                    series: [sevenObject, implantsObject]
                });

   }
    
    

</script>


<!--<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	-->

<!--<script src="https://code.highcharts.com/highcharts.js"></script>-->
<!--<script src="https://code.highcharts.com/modules/exporting.js"></script>-->

<script src="js/highcharts/highcharts.js"></script>
<script src="js/highcharts/modules/exporting.js"></script>
<script src="js/tp/functions.js"></script>
<div id="footer"><?php //require_once('views/scripts/footer.phtml');?></div>



</body>

</html>