<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0 transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
    <link rel="stylesheet"
	href="bootstrap/css/bootstrap.css"
	type="text/css" />
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script src="../bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="../bootstrap/js/bootstrap.min.js"></script>
<script src="../js/tp/functions.js"></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

<script>
  $(function() {
    $( "#accordion" ).accordion({header: "h3", collapsible: true, active: false, animated:200, animated:"slide"})
  });
  </script>

</head>
<body class="yui-skin-sam">
    <?php
        
        //var_dump(array_keys($this->national_consumption_by_method)); exit;
    ?>
	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  //require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>
			
			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->

			<body class="docs slim framebox_body">
                            <div align="right" ><font size="4"><label><?php echo 'National Contraceptive Prevalence Rate 15% Target 36%'; ?></label></font></div>
				
                            <div class="row">
                                <div class="col-md-2">

				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    require_once('views/scripts/dashboard/left_buttonshome.phtml');
                                ?>				
			
                            </div>
                                
                                <div class="col-md-10">
                                    
                              <div class="row">
				
				
				
				
				   
						
                                                                     <div class="col-md-6" style="overflow:visible !important;">
                                                                    <div class="sliderdiv" style="overflow:visible !important;width: 100%;"> 
                                                                            <div id="infobutton" class="infobutton hidden" style="margin-bottom:-40px">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    This chart shows total national consumption of each FP commodity in the most 
                                                                                    recent month. Given the different scale of male condom consumption, 
                                                                                    consumption is reflected in units of 10 male condoms, while all other 
                                                                                    commodities are reflected as a single commodity.
                                                                                </div>
                                                                            </div>
                                                                        <div class="hrNav"></div>
                                                                        <div id="chart11_div" style="width: 100%; height: 430px;overflow:visible !important;"></div>
                                                                    </div>
                                                                     </div>
                                    
                                                                     <div class="col-md-6">
                                                                        
                                                                    <div class="main-search" style="width: 100%;">
                                                                       
                                                                            <div id="infobutton" class="infobutton hidden" style="margin-bottom: -40px;">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The blue bars show the  percentage of facilities with a trained health worker 
                                                                                    that reported in the most recent month and are stocked out of any FP commodity 
                                                                                    or implants. FP training includes Contraceptive Technology Update, FP Technology, 
                                                                                    and Injectable Contraceptives for CHEWs in-service trainings. LARC training 
                                                                                    includes LARC and Post Partum IUCD in-service trainings. <br/><br/>
                                                                                    
                                                                                    The red bars show the percent of all facilities in the country that have at 
                                                                                    least one trained health worker in FP or LARC as of the most recent month. <br/><br/>
                                                                                    
                                                                                    The orange bars show the percentage of facilities with a trained health worker 
                                                                                    that reported in the most recent month and consumed at least one FP/LARC commodity 
                                                                                    in the most recent month. <br/><br/>
                                                                                    
                                                                                    Together, these charts can provide a snapshot of barriers to service delivery 
                                                                                    (lack of training, lack of commodity availability, or lack of service provision
                                                                                    due to some other barrier).
                                                                                </div>
                                                                            </div>
                                                                        <div class="hrNav"></div>
                                                                        <div id="chart12_div" style="width: 100%; height: 430px;"></div>
                                                                    
                                                                     
						</div>		</div>	
				
					
					<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
                                </div>
                                 <div class="row">
                                    
					
						
                                                                    <div class="col-md-6">
                                                                        <div class="sliderdiv" style="width: 100%;">
                                                                            <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The red line shows the percentage of reporting facilities that consumed at 
                                                                                    least one FP commodity in the given month. <br/><br/>
                                                                                    The blue line shows the percentage of reporting facilities that consumed at 
                                                                                    least one implant or IUCD in the given month. <br/><br/>
                                                                                    Together, these lines illustrate the gap between the availability of LARC 
                                                                                    services and short-acting FP services and whether this is improving over time.
                                                                                </div>
                                                                            </div>
                                                                        <div class="hrNav"></div>
                                                                        <div id="chart13_div" style="width: 100%; height: 300px;"></div>
                                                                    </div>
                                                                    </div>
                                        
                                                                    <div class="col-md-6">
                                                                       
                                                                    <div class="sliderdiv" style="width: 100%;">
                                                                            <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    This chart shows stock out rates over time at facilities that have provided 
                                                                                    any FP services or implants specifically in the past. <br/><br/>
                                                                                    
                                                                                    For FP, this is the percentage of facilities reporting in the given month that 
                                                                                    have provided any FP commodities any time in the last six months that were 
                                                                                    stocked out of any FP commodity for at least seven days in the given month. <br/><br/>
                                                                                    
                                                                                    For implants, this is the percentage of facilities reporting in the given month that 
                                                                                    have consumed implants any time in the last six months that are stocked out of 
                                                                                    implants in the given month.
                                                                                </div>
                                                                            </div>
                                                                        <div class="hrNav"></div>
                                                                        <div id="chart14_div" style="width: 100%; height: 300px;"></div>
                                                                    </div></div>

						
                                 </div>
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
                                </div>			
					
                            
                                      
                                </div>

		<div class="hrNav"></div>
		<div class="clear"></div>
                </div>
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>

		<!-------   /////////////////////////// main gnr ////////////////////// -->

<?php 
    //var_dump($this->facs_providing_stockedout);  
    //$this->national_percent_facilities_providing = array();
    //$this->national_percent_facilities_stock_out = array();
?>
                
<script type="text/javascript">

		
  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.load('visualization', '1.1', {'packages':['bar']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  //document.getElementById("allCharts").style.marginLeft="";

	drawChart11();
	drawChart12();
	drawChart13();
	drawChart14();
		

	//var currentLevel;
	//currentLevel = <?php //echo '\'' . $this->location_data[0][name] . '\''; ?>;
		 
  }


  function drawChart11() {

	  // Create and populate the data table.
          //,{ role: 'style' }
	var chart11Data = google.visualization.arrayToDataTable([
            ['', ''],
        <?php
             foreach ($this->consumption_by_method as $key=>$row){
                        $consumption = $row['consumption'];
                        $malecondoms = 0;
                        $method = $row['method'];
                        $color = 'blue';

                        if($key == 1){
                            //$malecondoms = $consumption;
                            $consumption = round($consumption/10,0);  
                            $method = $row['method'] . '(unit x10)';
                        } 
                ?>
                        [<?php echo  "'$method', $consumption"; ?>],
                <?php
             } 
                ?>
        ]);


                  <?php //echo  " var title_date = 'Monthly Consumption by Method$this->title_date ' " ?>;

                  var title_data = <?php echo "'Consumption by method, $this->title_date'"; ?>;

                  var chart11Options = {  
                              title: title_data,
                              titleTextStyle: { fontSize: 16 },
                              is3D:true,
                              legend: 'none',
                              chartArea: {width: '100%', left: 80},//new
                              groupWidth : 10,
                              hAxis : {textStyle: {fontSize: 12}}                      
                        };

                  
                   var formatter = new google.visualization.NumberFormat(
                    { groupingSymbol:','});
                      var formating = new google.visualization.NumberFormat(
                    {pattern:'###,###,##0'});

                  formatter.format(chart11Data, 1);
                  formating.format(chart11Data, 1);
                  
                  var chart11 = new google.visualization.ColumnChart(document.getElementById('chart11_div'));
                  
                  //show info icon
                  google.visualization.events.addListener(chart11, 'ready', function(){
                            $("#chart11_div").siblings('#infobutton').removeClass('hidden');
                  });
                  
                  chart11.draw(chart11Data, chart11Options);
                  
   }
  
  

  function drawChart12() {
      var chart12Data = google.visualization.arrayToDataTable([
        [' ', 
         '% of facilities with FP or LARC-trained HW' ,
         { role: 'tooltip', type: 'string', 'p': {'html': true} },
         '% of FP or LARC-trained facilities providing FP or LARC' ,
         { role: 'tooltip', type: 'string', 'p': {'html': true} },
         '% of FP or LARC-trained facilities stocked out of FP or implants',
         { role: 'tooltip', type: 'string', 'p': {'html': true} },],
     <?php
     $cs_fp_trained_facility_count = round($this->csummary['cs_fp_trained_facility_count']*100,1);
     $cs_fp_consumption_facility_count = round($this->csummary['cs_fp_consumption_facility_count']*100,1);
     $cs_fp_stock_out_facility_count = round($this->csummary['cs_fp_stock_out_facility_count']*100,1);
     
     $cs_larc_trained_facility_count = round($this->csummary['cs_larc_trained_facility_count']*100,1);
     $cs_larc_consumption_facility_count = round($this->csummary['cs_larc_consumption_facility_count']*100,1);
     $cs_larc_stock_out_facility_count = round($this->csummary['cs_larc_stock_out_facility_count']*100,1);
     
     
     $fpandLarcTrainedToolTip  ="<p style=\"padding:5px 7px;\"><b>FP</b><br/>Percent of facilities with FP-trained HW: ". $cs_fp_trained_facility_count. "\%</p>";
     $fporLarcTrainedFacProvToolTip = "<p style=\"padding:5px 7px;\"><b>FP</b><br/>Percent of FP-trained facilities providing FP : ".$cs_fp_consumption_facility_count. "\%</p>";
     $fporLarcTrainedStockOutToolTip  = "<p style=\"padding:5px 7px;\"><b>FP</b><br/>Percent of FP-trained facilities stocked out of FP : ".$cs_fp_stock_out_facility_count. "\%</p>";
     
     
     $larcandLarcTrainedToolTip  = "<p style=\"padding:5px 7px;\"><b>LARC</b><br/>Percent of facilities with LARC-trained HW: " .$cs_larc_trained_facility_count. "\%</p>";
     $larcorLarcTrainedFacProvToolTip = "<p style=\"padding:5px 7px;\"><b>LARC</b><br/>Percent of LARC-trained facilities providing FP : " .$cs_larc_consumption_facility_count . "\%</p>";
     $larcorLarcTrainedStockOutToolTip  = "<p style=\"padding:5px 7px;\"><b>LARC</b><br/>Percent of LARC-trained facilities stocked out of FP : " .$cs_larc_stock_out_facility_count. "\%</p>";
     
     
     
     ?>
        [ <?php echo "'FP',$cs_fp_trained_facility_count,'$fpandLarcTrainedToolTip',$cs_fp_consumption_facility_count,'$fporLarcTrainedFacProvToolTip',$cs_fp_stock_out_facility_count,'$fporLarcTrainedStockOutToolTip' "; ?>],
        [<?php echo " 'LARC',$cs_larc_trained_facility_count,'$larcandLarcTrainedToolTip',$cs_larc_consumption_facility_count,'$larcorLarcTrainedFacProvToolTip',$cs_larc_stock_out_facility_count,'$larcorLarcTrainedStockOutToolTip'"; ?> ],	        
      ]);


      <?php //echo  " var title_data = 'Coverage summary, $this->cs_date ' " ?>;
      
      //var date = <?php //echo "'" . $this->csummary['cs_date'] . "'"; ?>;
      var title_data = <?php echo "'HR summary, $this->title_date '"; ?>;

      var chart12Options = {
    		  title: title_data,
    		  titleTextStyle: { fontSize: 16 },
    		  bar: {groupWidth: "70%"},
                  chartArea: {width: '100%'},//new
    		  vAxis: {format: '#\'%\''}, //new
    		  chartArea: {width: '60%', left: 80},//new
                  legend: {textStyle: {'margin-bottom': '100px'}},
                  tooltip : {isHtml : true },
                  //vAxis: {format:'#\'%\''},
                  //vAxis: { ticks: [{v:1, f:'1%'}, {v:2, f:'2%'}, {v:3, f:'3%'}, {v:4, f:'4%'}] }
                  //% of FP or LARC trained facilities stocked out of FP or implants
      };

      var chart12 = new google.visualization.ColumnChart(document.getElementById('chart12_div'));

      //show info icon
      google.visualization.events.addListener(chart12, 'ready', function(){
                $("#chart12_div").siblings('#infobutton').removeClass('hidden');
      });
      
      chart12.draw(chart12Data, chart12Options);
  }
  
  function drawChart13() {
	  
      var chart13Data = google.visualization.arrayToDataTable([
        ['Month',
         'FP',{ role: 'tooltip', type: 'string', 'p': {'html': true} }, 
         'LARC',{ role: 'tooltip', type: 'string', 'p': {'html': true} },],            
            
                    <?php 
                        //$locationNamesArray = explode(',', $locationNames);

                        if(!empty($this->fp_facs_providing)){
                            foreach ($this->fp_facs_providing as $key=>$value){ 
                                $month = $this->fp_facs_providing[$key]['month'];
                                $fp_percent = round($this->fp_facs_providing[$key]['percent'] * 100,1);
                                $fpToolTip = "<p style=\"padding:5px 7px;\"><b>$month</b><br/>FP: " . $fp_percent . "\%</p>";
                                $larc_percent = round($this->larc_facs_providing[$key]['percent'] * 100,1);
                                $larcToolTip = "<p style=\"padding:5px 7px;\"><b>$month</b><br/>LARC: " . $larc_percent . "\%</p>";
                        ?>
                                [<?php echo "'$month', $fp_percent,'$fpToolTip', $larc_percent,'$larcToolTip'"; ?>],

                        <?php
                                }//end foreach
                            } //end if
                        ?>
        ]);

              <?php echo  " var title_data = 'Percent of facilities providing FP and LARC, " . $this->start_date . " to " . $this->end_date ."' " ?>;

              var chart13Options = {
                title: title_data,
                chartArea: {width: '100%', left: 30},//new
                titleTextStyle: { fontSize: 16 },
                vAxis: {format: '#\'%\''},
                legend: {textStyle: {'margin-bottom': '100px', 'margin-top': '50px'}, position: 'bottom'},
                tooltip : {isHtml : true },
              };

              var chart13 = new google.visualization.LineChart(document.getElementById('chart13_div'));
              
              //show info icon
                google.visualization.events.addListener(chart13, 'ready', function(){
                          $("#chart13_div").siblings('#infobutton').removeClass('hidden');
                });
      
              chart13.draw(chart13Data, chart13Options);

    }
    
    
    function drawChart14() {


        var chart14Data = google.visualization.arrayToDataTable([
        ['Month',
         '% FP facilities stocked out of any FP commodity for 7 days',
         { role: 'tooltip', type: 'string', 'p': {'html': true} },
         '% implant facilities stocked out of implants',
     { role: 'tooltip', type: 'string', 'p': {'html': true} }],
                            
               <?php 
                    //$locationNamesArray = explode(',', $locationNames);

                    if(!empty($this->fp_facs_providing_stockedout)){
                        foreach ($this->fp_facs_providing_stockedout as $key=>$monthProviders){ 
                            $month = $monthProviders['month'];
                            $seven_days_percent = round($monthProviders['seven_days_percent'] * 100,1);
                            $seven_days_percentToolTip = "<p style=\"padding:5px 7px;\"><b>$month</b><br/>Percent of FP facilities stocked out of any FP commodity for 7 days: " . $seven_days_percent . "\%</p>";
                            $implant_percent = round($this->larc_facs_providing_stockedout[$key]['implant_percent'] * 100,1);
                            $implant_percentToolTip = "<p style=\"padding:5px 7px;\"><b>$month</b><br/>Percent of implant facilities stocked out of implants: " . $implant_percent . "\%</p>";
                            ?>
                            [<?php echo "'$month',$seven_days_percent,'$seven_days_percentToolTip',$implant_percent,'$implant_percentToolTip'"; ?>],

                    <?php
                            }//end foreach
                        } //end if
                    ?>

        ]);

             <?php echo  " var title_data = 'Stock outs, " . $this->start_date . " to " . $this->end_date ."' " ?>;

              var chart14Options = {
                title: title_data,
                titleTextStyle: { fontSize: 16 },
                vAxis: {format: '#\'%\'', minValue: 4},
                chartArea: {width: '100%', left: 60},//new
                legend: {textStyle: {'margin-bottom': '100px', 'margin-top': '100px'}, position: 'bottom'},
                tooltip : {isHtml : true },
              };

              var chart14 = new google.visualization.LineChart(document.getElementById('chart14_div'));

              //show info icon
                google.visualization.events.addListener(chart14, 'ready', function(){
                          $("#chart14_div").siblings('#infobutton').removeClass('hidden');
                });
              chart14.draw(chart14Data, chart14Options);

   }
    
    

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>

