<?php
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        require_once('views/scripts/template/template.phtml');
                                    ?>
                                  
                                    <div class="row" style="text-align:center; ">
                                        
                                         <div class="col-sm-12" style="padding-top:10px;" >
                                             
                                             <div class="row" style="margin:0">
                                                 
                                                  <div class="col-sm-3" style="" >
                                                 
                                               <div class="row box-shadow" style="margin:0">
                                                   
                                                   <div class="col-sm-4 text-center small-box"  >
                                                    
                                                      <img src="images/map of 9ja.png" class="img-box" />
                                        
                                                   </div>
                                    
                                                  <div class="col-sm-8 text-left big-box" >
                                                     National Contraceptive Prevalence Rate <br>
                                                    <b class="font-20" > 15% (NDHS 2013) </b>
                                                
                                                  </div>
                                    
                                                </div>
                                    
                                             </div>
                                             
                                             <div class="col-sm-3" style="">
                                                 
                                                 <div class="row box-shadow" style="margin:0">
                                                     
                                                     <div class="col-sm-4 text-center small-box green">
                                                    
                                                     <img src="images/map of 9ja.png" class="img-box" />
                                        
                                                    </div>
                                    
                                                   <div class="col-sm-8 text-left big-box" >
                                                       2018 Contraceptive Prevalence Rate Target
                                                     
                                                       <br>

                                                        <b class="font-20" >36% </b>
                                                
                                                      </div>
                                    
                                                    </div>
                                    
                                              </div>
                                             
                                               <div class="col-sm-3" style="">
                                                   
                                                    <div class="row box-shadow" style="margin:0">
                                                        
                                                          <div class="col-sm-4 text-center small-box red">
                                                    
                                                              <img src="images/icon_x.png" class="img-box" />
                                        
                                                          </div>
                                    
                                                         <div class="col-sm-8 text-left big-box" >
                                                            Total number of trainings conducted
                                                            <br>
                                                            <b class="font-20" ><?= number_format($this->trainingsCount); ?></b>
                                                    
                                                        </div>
                                                        
                                                   </div>
                                    
                                    
                                               
                                              </div>
                                             
                                             <div class="col-sm-3" style="">
                                                 
                                                 <div class="row box-shadow" style="margin:0">
                                                     
                                                      <div class="col-sm-4 text-center small-box total-participant-color">
                                                    
                                                        <img src="images/multiple-users-silhouette.png" class="img-box" />
                                        
                                                     </div>
                                    
                                                    <div class="col-sm-8 text-left big-box ">
                                                        Total Health Workers <br/>Trained
                                                        <br>
                                                       <b class="font-20" ><?= number_format($this->uniqueTrainedPersonsCount); ?> </b> 
                                                   
                                                     </div>
                                    
                                                 </div>
                                    
                                              </div>
                                                 
                                             </div>
                                        </div>
                                        
                                  </div>
                                    
                                
                                    <div class="row">
                                             
                                            
                                                 
                                           <div class="col-sm-12" style="padding-left:0px;padding-right:0px;margin-top:15px;" >      
                                             
                                                 <div class="col-sm-6 " style="padding-right:3px; margin-top:14px;">
                                                     
                                                  

                                              
                                               <div id="tabs" class="box-shadow"    style="overflow:visible !important; min-height: 450px; border: 0;">
                                                   <!--<div style="z-index:5000;margin-bottom:-18px;margin-left:100px;font-weight:bold;">Consumption by method, <?php //echo $this->title_date; ?></div>-->
                                                                         <div id="infobutton" class="infobutton hidden info11 align-left" style="margin-bottom: -47px;width: 55%;margin-left: 50%;">
                                                                                    <span class="infowrap" ><i class="fa fa-info-circle"></i></span>
                                                                                        <div id="" class="infodiv" style="margin-top:26px !important;">
                                                                                            This chart shows total national consumption of each FP commodity in the most 
                                                                                            recent month. Given the different scale of male condom consumption, 
                                                                                            consumption is reflected in units of 10 male condoms, while all other 
                                                                                            commodities are reflected as a single commodity.
                                                                                        </div>
                                                                                    </div><br/>
                                                                         
                                                                         
                                                                         
                                                                             <ul class="hometabs hidden" style="border-top: 2px solid #E36856;" >
                                                                                 <li class=""><a href="#tab1">Pie</a></li>
                                                                                 <li class=""><a href="#tab2">Bar</a></li>
                                                                             </ul>
                                                                             
                                                                           
                                                                         
                                                                            <div id="tab1" class="sliderdiv" style="overflow:visible !important;width: 100%;"> 
                                                                                <div class="hrNav"></div>
                                                                                <div id="piechart" class="box-shadow" style="width: 100%; height: 0px; margin-top: -30px"></div>
                                                                                <!--<div id="chart11_div" style="width: 100%; height: 430px;"></div>-->
                                                                            </div>
                                                                         
                                                                            <div id="tab2" class="sliderdiv" style="overflow:visible !important;width: 100%; margin-top:0px;"> 
                                                                                <div class="hrNav"></div>
                                                                                <div id="chart11_div" class="box-shadow" style="width: 100%; height: 0px;overflow:visible !important;margin-top: -30px;margin-left: -20px;"></div>
                                                                            </div>
                                                                         
                                                                            
                                                                     </div>
                                                       </div>
                                               
                                               <?php
        $cs_fp_trained_facility_count = $this->csummary['cs_fp_trained_facility_count'];
        $cs_fp_consumption_facility_count = $this->csummary['cs_fp_consumption_facility_count'];
        $cs_fp_stock_out_facility_count = $this->csummary['cs_fp_stock_out_facility_count'];

        $cs_larc_trained_facility_count = $this->csummary['cs_larc_trained_facility_count'];
        $cs_larc_consumption_facility_count = $this->csummary['cs_larc_consumption_facility_count'];
        $cs_larc_stock_out_facility_count = $this->csummary['cs_larc_stock_out_facility_count'];
     ?> 
                                    
                                                 <div class="col-sm-6 " style="margin-top:5px;" >
                                                                         <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                             <div id="infobutton" class="infobutton" style="margin-left:4px;">
                                                                             
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    <strong><u>FP Chart</u></strong><br/>
                                                                                    The blue bar shows the numberof allfacilities in the country that 
                                                                                    have at least one trained health worker in FP as of the most recent month. <br/><br/>
                                                                                    
                                                                                    The red bar shows thenumberof facilities with an FP-trained health 
                                                                                    worker that reported in the most recent month and consumed at least 
                                                                                    one FP commodity in the most recent month. <br/><br/>
                                                                                    
                                                                                    The yellow bar shows the numberof facilities with an FP-trained health 
                                                                                    worker that reported in the most recent month and that werestocked out 
                                                                                    of any FP commodity for seven consecutive days in that month. 
                                                                                    FP training includes Contraceptive Technology Update, FP Technology, 
                                                                                    Injectable Contraceptives for CHEWs, LARC, and Post Partum IUD in-service trainings. 
                                                                                    <br/><br/><br/>
                                                                                    
                                                                                    
                                                                                    <strong><u>LARC Chart</u></strong><br/>
                                                                                    The blue bar shows the numberof all facilities in the country that have at least one 
                                                                                    trained health worker in LARC as of the most recent month. <br/><br/>
                                                                                    
                                                                                    The red bars show the numberof facilities with aLARC-trained health worker that reported 
                                                                                    in the most recent month andconsumed at least one LARC commodity in the most 
                                                                                    recent month. <br/><br/>
                                                                                    
                                                                                    The yellow bar shows the numberof facilities with a LARC-trained health worker that 
                                                                                    reported in the most recent month and that werestocked out of implants. LARC training 
                                                                                    includes LARC andPost Partum IUD in-service trainings.
                                                                                </div>
                                                                            </div>
                                                                            </div>
                                                                             
                                                                          </div>   
                                               
                                                                         
                                                                          
                                                                    <div class="main-search box-shadow" style="width: 100%;">
                                                                       
                                                                            <!--<div id="infobutton" class="infobutton hidden" style="margin-bottom: 0;padding-right:15px;margin-top:-15px;">-->
                                                                                <!--<br>-->
                                                                                
<!--                                                                                <div id="" class="infodiv" >
                                                                                    zzzThe blue bars show the percent of all facilities in the country that have at 
                                                                                    least one trained health worker in FP or LARC as of the most recent month.<br/><br/>
                                                                                    
                                                                                    The red bars show the percentage of facilities with a trained health 
                                                                                    worker that reported in the most recent month and consumed at least one FP/LARC 
                                                                                    commodity in the most recent month. <br/><br/>
                                                                                    
                                                                                    The yellow bars show the  percentage of facilities with a trained health 
                                                                                    worker that reported in the most recent month and are stocked out of any FP commodity or implants. <br/><br/>
                                                                                    
                                                                                    FP training includes Contraceptive Technology Update, FP Technology, Injectable Contraceptives for CHEWs, 
                                                                                    LARC, and Post Partum IUCD in-service trainings. <br/><br/>
                                                                                    
                                                                                    LARC training includes LARC and Post Partum IUCD in-service trainings. 
                                                                                    <br/><br/>
                                                                                    
                                                                                    Together, these charts can provide a snapshot of barriers to service delivery 
                                                                                    (lack of training, lack of commodity availability, or lack of service provision due to some other barrier).
                                                                                </div>-->
                                                                            <!--</div>-->
                                                                        <div class="hrNav" ></div>
                                                                       <div id="chart12_div" style="width: 100%;"></div>
                                                                    
                                                                     
						                      </div>	
                                                         
                                                 
                                             </div>
                                               
                                     </div>   
                                                 
                                    </div>
                                             
                                    <div class="row">
                                               
                                             
                                             <div class="col-sm-12" style="padding-left:0px;padding-right:0px;">
                                             
                                                   <div class="col-sm-6 " style="padding-right:3px;margin-top:5px;">
                                                       
                 
                                                       
                                                        <div class="title-bar border-fa col-xs-12"  style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font"  >
                                                                            </div>
                                                                            <div class="col-xs-1 title-bar-info-btn" style="min-height:20px;">
                                                                                <div id="infobutton" class="infobutton " style="margin-left:4px;">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The red line shows the percentage of reporting facilities that consumed at 
                                                                                    least one implant or IUCD in the given month. <br/><br/>
                                                                                    The blue line shows the percentage of reporting facilities that consumed at 
                                                                                    least one FP commodity in the given month. <br/><br/>
                                                                                    Together, these lines illustrate the gap between the availability of LARC 
                                                                                    services and short-acting FP services and whether this is improving over time.
                                                                                </div>
                                                                            </div>
                                                                            </div>
                                                                         </div>
                                                       
                                                                        <div class="sliderdiv" style="width: 100%;">
                                                                            <div id="infobutton" class="infobutton hidden" style="margin-bottom: -30px;padding-right:20px;">
                                                                               
                                                                                <div id="" class="infodiv" >
                                                                                    The red line shows the percentage of reporting facilities that consumed at 
                                                                                    least one implant or IUCD in the given month. <br/><br/>
                                                                                    The blue line shows the percentage of reporting facilities that consumed at 
                                                                                    least one FP commodity in the given month. <br/><br/>
                                                                                    Together, these lines illustrate the gap between the availability of LARC 
                                                                                    services and short-acting FP services and whether this is improving over time.
                                                                                </div>
                                                                            </div><br/>
                                                                        <div class="hrNav"></div>
                                                                        <div id="chart13_div" class="box-shadow" style="width: 100%; height: 430px;"></div>
                                                                    </div>
                                                                    </div>
                                                 
                                    
                                                                    <div class="col-sm-6" style="margin-top:5px; height: 430px;">

                                                                         <div class="title-bar border-fa border-st col-xs-12" style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font"  >
                                                                                
                                                                            </div>
                                                                            <div class="col-xs-1 title-bar-info-btn" style="min-height:20px;">
                                                                                <div id="infobutton" class="infobutton" style="margin-left:4px;">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                        This chart shows stock out rates over time at facilities that have provided 
                                                                                        any FP services or implants specifically in the past. <br/><br/>

                                                                                        For FP, this is the percentage of facilities reporting in the given month that 
                                                                                        have provided any FP commodities any time in the last six months that were 
                                                                                        stocked out of any FP commodity for at least seven days in the given month. <br/><br/>

                                                                                        For implants, this is the percentage of facilities reporting in the given month that 
                                                                                        have consumed implants any time in the last six months that are stocked out of 
                                                                                        implants in the given month.
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                         </div>
                                                                       
                                                                        <div class="sliderdiv" style="width: 100%;">
                                                                                <div id="infobutton" class="infobutton hidden" style="margin-bottom: -30px;">
                                                                                    
                                                                                    <div id="" class="infodiv" >
                                                                                        This chart shows stock out rates over time at facilities that have provided 
                                                                                        any FP services or implants specifically in the past. <br/><br/>

                                                                                        For FP, this is the percentage of facilities reporting in the given month that 
                                                                                        have provided any FP commodities any time in the last six months that were 
                                                                                        stocked out of any FP commodity for at least seven days in the given month. <br/><br/>

                                                                                        For implants, this is the percentage of facilities reporting in the given month that 
                                                                                        have consumed implants any time in the last six months that are stocked out of 
                                                                                        implants in the given month.
                                                                                    </div>
                                                                                </div>
                                                                            <div class="hrNav"></div>
                                                                            <div id="chart14_div" class="box-shadow" style="width: 100%; height: 430px;margin-top: 20px;"></div>
                                                                        </div>
                                                                    </div>
                                                 
                                             </div>
                                    </div>
                                             
                                              
                            
                            
                                       
                                             
                                        </div>
                                      
                                       
                                    </div>
                                
                                                              
						
                                 </div>
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
                                </div>			
					
                            
                                      
                                </div>

		
		<div class="clear"></div>
                </div>
           
           </div><!-- content -->
           <br/><br/><br/>
           <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
        </div> <!-- pagehoder -->
		<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->

		<!-------   /////////////////////////// main gnr ////////////////////// -->

<?php 
    //var_dump($this->facs_providing_stockedout);  
    //$this->national_percent_facilities_providing = array();
    //$this->national_percent_facilities_stock_out = array();   
?>
                
<script type="text/javascript">

		
  //google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
  //google.load('visualization', '1.1', {'packages':['bar']});
  //google.setOnLoadCallback(apiLoaded);
  
//  var chart11Options = "", chart11Data ="", chart11Div =""; 
  
  $(function() {
	  //document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	drawChart12();
	drawChart13();
	drawChart14();
     drawPieChart();
        //drawColumnChart();

	//var currentLevel;
	//currentLevel = <?php //echo '\'' . $this->location_data[0][name] . '\''; ?>;		 
  });
  
    function drawChart11(){
            <?php
                $methodString = ""; $consumptionString = "";
                foreach ($this->consumption_by_method as $key=>$row){
                   $malecondoms = 0;
                   
                   if($key == 1){
                       $methodString .= "'" . $row['method'] . '(unit x10)' . "',";
                       $consumptionString .= (int)round($row['consumption']/10) . ",";
                   }
                   else{
                       $methodString .= "'" . $row['method'] . "',";
                       $consumptionString .= $row['consumption'] . ",";
                   }
                 }

                 $methodString = substr($methodString, 0, strlen($methodString)-1);
                 $consumptionString = substr($consumptionString, 0, strlen($consumptionString)-1);
            ?>
                    
            var title = 'Consumption by method, ' + '<?php echo $this->title_date; ?>';
            $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                        }
                    },
                    height: 430
                },
                title: {
                    text: title,
                    style: {
                        fontFamily: 'Arial',
                        fontSize: '12pt',
                        fontWeight: 'bold'
                    }
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + thousandSeparator(this.y);
                    }
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                    title: {
                        text: 'FP Commodity',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: [<?php echo $methodString; ?>]
                },
                yAxis: {
                    title: {
                        text: '#Commodities Consumed',
                        style:{ "fontWeight": "bold" }
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: [<?php echo $consumptionString; ?>]
                }]
            });
    }
  
  
   function drawPieChart() {
          var consumptionByMethod = <?= json_encode($this->consumption_by_method); ?>;
          var dataArray = new Array();
          
          for(key in consumptionByMethod){
              row = consumptionByMethod[key];
              consumption = parseInt(row['consumption']);
              method = row['method'];
              
              if(key == 1){
                   consumption = parseInt(consumption/10);
                   method = row['method'] + "<br/>(unit x10)";
               }
               
               dataArray.push({name: method, y: consumption});
          }
                     
          var title = 'Consumption by method, ' + '<?php echo $this->title_date; ?>';
          
	  $('#piechart').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    type: 'pie',
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $(".chart-title, .chart-subtitle, .hometabs, .hometabs li, .info11").removeClass("hidden");
                        }
                    },
                },
                title: {
                    text: title,
                    style: {
                        fontFamily: 'Arial',
                        fontSize: '12pt',
                        fontWeight: 'bold'
                    }
                },
                tooltip: {
                    //pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                    //pointFormat: '<b>{point.percentage:.1f}%</b>'
                    formatter: function () {
                        //var maleCondomsInPieChart = parseInt(consumptionByMethod[1] / 10);
                        //var maleCondomsRealValue = consumptionByMethod[1];
                        
                        return '<strong>' + this.key + ':</strong> ' + this.percentage.toFixed(1) + '%<br/>' +
                               '<strong>Numerator:</strong> ' + thousandSeparator(this.y) + '<br/>' +
                               '<strong>Denominator:</strong> ' + thousandSeparator(this.total);
                    }
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '{point.name}: {point.percentage:.1f} %',
//                            style: {
//                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black',
//                                fontWeight: 'normal'
//                            }
                             style: {
                                    "color": "black",
                                    "fontSize": "13px",
                                    "fontWeight": "normal"
                                }
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    name: 'Methods',
                    colorByPoint: true,
                    data: dataArray
                }]
            });
                  
   }
  
  

  function drawChart12() {
     
     <?php
        $cs_fp_trained_facility_count = $this->csummary['cs_fp_trained_facility_count'];
        $cs_fp_consumption_facility_count = $this->csummary['cs_fp_consumption_facility_count'];
        $cs_fp_stock_out_facility_count = $this->csummary['cs_fp_stock_out_facility_count'];

        $cs_larc_trained_facility_count = $this->csummary['cs_larc_trained_facility_count'];
        $cs_larc_consumption_facility_count = $this->csummary['cs_larc_consumption_facility_count'];
        $cs_larc_stock_out_facility_count = $this->csummary['cs_larc_stock_out_facility_count'];
     ?>        
        
        //var categories = "'FP', 'LARC'";
        var dataArray = [ 
                            {
                                name: 'No. of facilities with FP-trained HW / No. of FP facilities with LARC-trained HW',
                                data: [<?php echo $cs_fp_trained_facility_count . "," . $cs_larc_trained_facility_count; ?>]
                            },
                            {
                                name: 'No. of FP-trained facilities providing FP / No. of LARC-trained facilities providing LARC',
                                data: [<?php echo $cs_fp_consumption_facility_count . "," . $cs_larc_consumption_facility_count; ?>]
                            },
                            {
                                name: 'No. of FP-trained facilities stocked out of any FP commodity / No. of LARC-trained facilities stocked <br/>out of Implants',
                                //name: 'Stockout',
                                data: [<?php echo $cs_fp_stock_out_facility_count . "," . $cs_larc_stock_out_facility_count; ?>]
                            }                                                       
                        ];
      
      var title = 'HR Summary, ' + '<?php echo $this->title_date; ?>';
      
      $("#chart12_div").highcharts({
            chart: {
                type: 'column',
                spacingLeft: 20,
                events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart12_div").siblings("#infobutton").removeClass("hidden");
                        }
                    }
            },

            title: {
                text: title,
                style: {
                    fontFamily: 'Arial',
                    fontSize: '12pt',
                    fontWeight: 'bold'
                }
            },

            xAxis: {
                title: {
                    text: 'Category of Training',
                    style:{ "fontWeight": "bold" }
                },
                categories: ['FP','LARC']
            },
            yAxis: {
                title: {
                    text: '# Facilities',
                    style:{ "fontWeight": "bold" }
                },
                labels: {
                    formatter: function () {
                        return thousandSeparator(this.value);
                    }
                }
            },
            tooltip: {
                formatter: function () {
                    var seriesName='';
                    if(this.x == 'FP'){
                        if(this.series.index == 0) seriesName = 'No. of facilities with FP-trained HW';
                        if(this.series.index == 1) seriesName = 'No. of FP-trained facilities providing FP';
                        if(this.series.index == 2) seriesName = 'No. of FP trained facilities stocked out of any FP commodity';
                    } else if(this.x == 'LARC'){
                        if(this.series.index == 0) seriesName = 'No. of FP facilities with LARC-trained HW';
                        if(this.series.index == 1) seriesName = 'No. of LARC-trained facilities providing LARC';
                        if(this.series.index == 2) seriesName = 'No. of LARC-trained facilities stocked out of implants';
                    }
                    
                    return '<b>' + this.x + '</b><br/>' +
                                seriesName + ': ' + thousandSeparator(this.y) + '<br/>';
                        //this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                }
            },
            plotOptions: {
                column: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            legend: {
             
             layout: 'vertical',
             //align: 'right',
             verticalAlign: 'bottom',
           
            floating: false,
            borderWidth: 1,
            backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
            shadow: true,
            itemStyle: {
                 fontSize: '7pt'
             }
            },
//              legend: {
//                        layout: 'horizontal',
//                        borderWidth: 1,
//                        shadow: true
//                        
//                    },
            credits: {enabled: false},
            series:dataArray
      });
      
  }//end HR Summary
  
  
  function drawChart13() {
        var FPProviding = <?= $this->fp_facs_providing; ?>;
        var LARCProviding = <?= $this->larc_facs_providing; ?>;
         
        var FPObject = {name: "FP", data: []};
        var LARCObject = {name: "LARC", data: []};
             
        for(key in FPProviding){
            monthName = FPProviding[key]['month'];
            FPObject.data.push(FPProviding[key]['percent']);
            LARCObject.data.push(LARCProviding[key]['percent'])
        }
        
        var startDate = '<?= $this->start_date; ?>';
        var monthNamesWithYears = getLastTwelveMonthsWithYears(<?= "'$this->end_date'"; ?>);
        
        var titleText = 'Percent of facilities providing FP and LARC,<br/> <?php echo $this->start_date . ' to ' . $this->end_date; ?>';
        var subtitleText = '(<?php echo $this->start_date . ' to ' . $this->end_date; ?>)';
        //Facilities Providing(%), <?php //echo $this->start_date . ' to ' . $this->end_date; ?>
        
              $('#chart13_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 400,
                        width: 500,
                        spacingLeft: 0,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                            }
                        }
                    },
                    title: {
                        text: titleText,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '12pt'
                        },
                    },
                    xAxis: {
                        title: {
                            text: 'Month',
                            style:{ "fontWeight": "bold" }
                        },
                        categories: monthNamesWithYears
                    },
                    yAxis: {
                        title: {
                            text: '% Facilities',
                            style:{ "fontWeight": "bold" }
                        },
                        labels: {
                            format: '{value}%'
                        },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            monthArray = this.x.split(" ");
                            month = monthArray[0];
                            
                            if(this.series.name.includes("FP"))
                                dataObj = FPProviding;
                            else 
                                dataObj = LARCProviding;
                            
                            index = -1;
                            for(key in dataObj) {
                                if(dataObj[key]['month'].toUpperCase() === month.toUpperCase()){
                                    index = key;
                                    break;
                                }
                            }
                            
                            return '<b>' + this.x + '</b><br/>' +
                                   '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                                   '<b>Numerator</b>:' + thousandSeparator(dataObj[key]['numer'])+'<br/>' +
                                   '<b>Denominator</b>:' + thousandSeparator(dataObj[key]['denom']);
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        borderWidth: 1,
                        shadow: true
                        
                    },
                    series: [FPObject, LARCObject]
                });

    }
    
    
    function drawChart14() {
        var FPSO = <?= $this->fp_facs_providing_stockedout; ?>;
        var LARCSO = <?= $this->larc_facs_providing_stockedout; ?>;
        var monthNamesWithYears = getLastTwelveMonthsWithYears(<?= "'$this->end_date'"; ?>);
        var startDate = '<?= $this->end_date; ?>';

        var sevenObject = {name: 'Percent FP facilities stocked out of any FP commodity for 7 days', data: []};
        var implantsObject = {name: 'Percent implant facilities stocked out of implants', data: []};
        
        monthNames = new Array();
        for(key in FPSO){
            var monthName = FPSO[key]['month'];
            monthNames.push(monthName);
            sevenObject.data.push(FPSO[key]['percent']);
            implantsObject.data.push(LARCSO[key]['percent']);
        }
                

        var titleText = '<?php echo  "Stock outs, $this->start_date to $this->end_date"; ?>';
        var subtitleText = '(<?php echo $this->start_date . ' to ' . $this->end_date; ?>)';
        
              $('#chart14_div').highcharts({
                    chart: {
                        //type: 'line',
                        //height: 440,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart14_div").siblings("#infobutton").removeClass("hidden");
                            }
                        }
                    },
                    title: {
                        text: titleText,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '12pt'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                        title: {
                            text: 'Month',
                            style:{ "fontWeight": "bold" }
                        },
                        categories: monthNamesWithYears
                    },
                    yAxis: {
                        title: {
                            text: '% Facilities',
                            style:{ "fontWeight": "bold" }
                        },
                        labels: {
                            format: '{value}%'
                        },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            var monthArray = (this.x).split(" ");
                            var month = monthArray[0];
                            
                            dataObj = new Array();
                            if((this.series.name).includes('FP')){
                                dataObj = FPSO;
                            }
                            else if((this.series.name).includes('implant')){
                                dataObj = LARCSO;
                            }
                            
                            index = -1; 
                            for(key in dataObj){
                                if ((dataObj[key]['month']).toUpperCase() === month.toUpperCase()){
                                    index = key;
                                    break;
                                }
                            }
                        
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                                '<b>Numerator</b>:'+thousandSeparator(dataObj[index]['numer'])+'<br/>' + 
                                '<b>Denominator</b>:'+thousandSeparator(dataObj[index]['denom']);
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        borderWidth: 1,
                        shadow: true
                    },
                    series: [sevenObject, implantsObject]
                });

   }
    
    

</script>


<!--<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	-->

<!--<script src="https://code.highcharts.com/highcharts.js"></script>-->
<!--<script src="https://code.highcharts.com/modules/exporting.js"></script>-->

<script src="js/highcharts/highcharts.js"></script>
<script src="js/highcharts/modules/exporting.js"></script>
<script src="js/tp/overtime-ops.js"></script>
<script src="css/sidebar.css"></script>
<div id="footer"><?php //require_once('views/scripts/footer.phtml');?></div>



</body>

</html>