<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0 transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}
.error{
    color:red !important;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}
div#dialog-message {
    min-height: 50px !important;
}
#dialog-message{
    display:none;
    
   }
   
.ui-tooltip {
    max-width: 350px;
  }
</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">
<?php
require_once('views/helpers/Location.php');

?>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot--.com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

<script>
  $(function() {
    dialogs = $( "#dialog-message" ).dialog({
                                  autoOpen: false,
                                  modal: true,
                                  draggable: false,
                                  resizable: false,
                                      });
  });
  
  var captchaResponse = function(){
                            //grecaptcha.getResponse();
                            alert("response");
                        }
        
  </script>
  <script src='https://www.google.com/recaptcha/api.js'></script>
  
</head>
<body class="yui-skin-sam">
    <?php
        
        //var_dump(array_keys($this->national_consumption_by_method)); exit;
    ?>
	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			

			<!-------   /////////////////////////// charts ////////////////////// -->

			<body class="docs slim framebox_body">
                            <div id="statusMessage">
    
                            </div>
                            <div id="dialog-message" title="" >
 
                                <p style="text-align:center;v-align:middle;padding:10px !important" id="data"><img src="<?php echo $this->base_url;?>/images/ajax_load.gif"/></p>
          </div>
<form action="" id="userForm" method="POST">
        <div>
            <input type="hidden" name="province_id" value="0" id="province" disabled />
            <input type="hidden" name="district_id" value="0_0" id="district" disabled />
            <input type="hidden" name="region_c_id" value="0_0_0" id="region" disabled />
        </div>
       
        <div class="clear"></div>
        <div class="fieldLabel" id="designation_lbl"><span class="required">*</span><?php echo tp('Designation');?></div>
	<div class="fieldInput">
            <select name="designation" id="designation" onchange="onDesignationChange()" title="Enter your role eg: Federal user, State user, LGA user, Partner.<br/> NB: Partners can select multiple locations in both zone and state">
            <option value="">--select--</option>
            <?php if(isset($this->user['designation'])) { ?>
            <option value="fed_user" <?php echo $this->user['designation'] == 'fed_user'?'selected':'' ;?>>FEDERAL USER</option>
            <option value="state_user" <?php echo $this->user['designation'] == 'state_user'?'selected':'' ;?>>STATE USER</option>
            <option value="lga_user" <?php echo $this->user['designation'] == 'lga_user'?'selected':'' ;?>>LGA USER</option>
            <option value="partner_user" <?php echo $this->user['designation'] == 'partner_user'?'selected':'' ;?>>PARTNER USER</option>
            <?php } else { ?>
            <option value="fed_user" >FEDERAL USER</option>
            <option value="state_user" >STATE USER</option>
            <option value="lga_user" >LGA USER</option>
            <option value="partner_user">PARTNER USER</option>
            <?php } ?>
            </select>
        </div>
        
        
        <div class="fieldLabel" id="title_lbl"><span class="required">*</span><?php echo tp('Title');?></div>
        <div class="fieldInput"><input type="text" name="title" size="32" maxlength="32" value="<?php echo (isset($this->user['title']))?$this->user['title']:""; ?>" title="E.g Dr, Mr, Mrs, Ms"/></div>
	<div class="fieldLabel" id="first_name_lbl"><span class="required">*</span><?php echo $this->translation['First Name'];?></div>
	<div class="fieldInput"><input type="text" onblur="generateUsername()" id="first_name" name="first_name" size="32" maxlength="32" value="<?php echo (isset($this->user['first_name']))?$this->user['first_name']:""; ?>"/></div>
	<div class="fieldLabel" id="last_name_lbl"><span class="required">*</span><?php echo $this->translation['Last Name'];?></div>
        <div class="fieldInput"><input type="text" onblur="generateUsername()" id="last_name" name="last_name" size="32" maxlength="32" value="<?php echo (isset($this->user['last_name']))?$this->user['last_name']:""; ?>"/></div>
	<div class="fieldLabel"  id="username_lbl"><span class="required">*</span><?php tp('Preferred Username');?></div>
        <div class="fieldInput"><input type="text" id="username" name="username" size="32" maxlength="32" readonly value="<?php echo (isset($this->user['username']))?$this->user['username']:""; ?>" title="Preferred username is automatically generated for you using your first name and last name"/></div>
	<div class="fieldLabel"  id="password_lbl"><span class="required">*</span><?php tp('Password');?></div>
	<div class="fieldInput"><input type="text" name="password" size="32" maxlength="32" value=""/></div>
        <div class="fieldLabel"  id="password2_lbl"><span class="required">*</span><?php tp('Confirm Password');?></div>
        <div class="fieldInput"><input type="text" name="password2" size="32" maxlength="32" value="" title="Confirm password must match password"/></div>
        
	<div class="fieldLabel"  id="email_lbl"><span class="required">*</span><?php tp('E-mail');?></div>
        <div class="fieldInput"><input type="text" name="email" size="32" maxlength="256" value="<?php echo (isset($this->user['email']))?$this->user['email']:""; ?>" title="E.g: Biola@yahoo.com"/></div>
	
        <div class="fieldLabel"  id="mobile_no_lbl"><span class="required">*</span><?php tp('Mobile no');?></div>
	<div class="fieldInput"><input type="text" name="mobile_no" size="32" maxlength="20" value="<?php echo (isset($this->user['mobile_no']))?$this->user['mobile_no']:""; ?>" title="E.g: 0804xxxxxxx"/></div>
        
        <input type="hidden" name="id" value="<?php echo (isset($this->user['req_id']))?$this->user['req_id']:""; ?>" />
	
        
        <div class="fieldLabel" id="province_id_lbl"><span class="required">*</span>Zone</div><br/>
        <div class="fieldselect"><?php renderFilter($this->locations, 1, 'province_id', (isset($this->user['province_id']))?$this->user['province_id']:"", 'district_id', false,false); ?></div>
        <div class="clear pad20">&nbsp;</div>
        <div class="fieldLabel" id="district_id_lbl"><span class="required">*</span>State</div><br/>
        <div class="fieldselect"><?php renderFilter($this->locations, 2, 'district_id', (isset($this->user['district_id']))?$this->user['district_id']:"", 'region_c_id', false,false); ?></div>
        <div class="clear pad20">&nbsp;</div>
        <div class="fieldLabel" id="region_c_id_lbl"><span class="required">*</span>LGA </div><br/>
        <div class="fieldselect"><?php renderFilter($this->locations, 3, 'region_c_id', (isset($this->user['region_c_id']))?$this->user['region_c_id']:"",'', false, false); ?></div>
        <div class="clear pad20">&nbsp;</div>
           
        <!--<div class="g-recaptcha" data-sitekey="6LeOjhUUAAAAABSp46VQ3XoGT-Cs0bNFUomRpfPH" onclick="alert('click');"></div>-->

        <div class="clear"></div>



        <div style="min-width:40px !important;margin:0 auto;">
	<input type="button" id="Finished" title="save this record" class="submitNoArrow" value="<?php tp('Submit Application');?>" style="margin: 0 auto;"/>
        </div>
        <div class="clear"></div>

</form>
				


		
		
		

		<!-------   /////////////////////////// main gnr ////////////////////// -->

<?php 
    //var_dump($this->facs_providing_stockedout);  
    //$this->national_percent_facilities_providing = array();
    //$this->national_percent_facilities_stock_out = array();
?>
                
<script type="text/javascript">
   function removeAllErrorMessages(){
       $("#title_lbl .errorText").remove(); //TP: added 6/20/2016
       $("#mobile_no_lbl .errorText").remove(); //TP: added 6/20/2016
       $("#password2_lbl .errorText").remove(); //TP: added 6/20/2016
       $('#designation_lbl .errorText').remove();
       $('#first_name_lbl .errorText').remove();
       $('#last_name_lbl .errorText').remove();
       $('#username_lbl .errorText').remove();
       $('#password_lbl .errorText').remove();
       $('#email_lbl .errorText').remove();
       $('#province_id_lbl .errorText').remove();
       $('#district_id_lbl .errorText').remove();
       $('#region_c_id_lbl .errorText').remove();
   } 
     $(function() {
$('#Finished').click(function() {
    //Enable the disabled fields, so the data can get sent to the server
    //$("#province_id, #district_id, #region_c_id").removeProp("disabled");
    //Assign default value to province,district, or region dropdown when designation is Fed_user or State user
    setSelectDefaultValue();
    console.log($("#province").val());
     $.ajax({
            type: "POST",
            url: "<?php echo $this->base_url;?>/index/requestaccess",
            data: $("#userForm").serialize(),
            beforeSend: function() {
             //alert("before");
           removeAllErrorMessages();
           $("#statusMessage").html("");
             $(".ui-dialog").show();
               document.getElementById("dialog-message").style.display = "block";
               
              
                 
             $('.ui-dialog-titlebar').hide();
               dialogCert = $( "#dialog-message" ).dialog();
               $('#dialog-message').dialog('open');
               },
            success: function(data) {
             //alert("successful");
           //alert(data);
           console.log(data);
           
           var responseData =   jQuery.parseJSON(data);
           var status = responseData.status;
           var statusMessage = status.status;
           var errorMessages = status.messages;
            jQuery.each( errorMessages, function( key, value ) {
                var id = key+"_lbl";
                $("#"+id).append('<span class="errorText">'+value+'</span>');
       //alert(value+" "+key);
}); 
            $("#statusMessage").html("<div id='statusBox'>"+statusMessage+"</div>");
            
          dialogCert = $( "#dialog-message" ).dialog();
               $('#dialog-message').dialog('close');
             $('.ui-dialog-titlebar').show();
     
   },
            error: function(jqXHR, textStatus, errorThrown){
              console.log(" The following error occured: "+ textStatus, errorThrown );
              alert(" The following error occured: "+ textStatus+" "+ errorThrown);
               dialogCert = $( "#dialog-message" ).dialog();
               $('#dialog-message').dialog('close');
             $('.ui-dialog-titlebar').show();
            
            }

        })
    
      
});
 });
 
    function onDesignationChange()
    {
        console.log("entered onDesignationChange")
        var desg = $("#designation" ).val();
        console.log("Selected : " + desg)
        if(desg == "fed_user")
        {
            $("#province_id, #district_id").removeProp("multiple");
            $("#province_id, #district_id, #region_c_id").prop("disabled",true);
            
        }
        else if(desg == "state_user")
        {
            $("#province_id, #district_id").removeProp("multiple");
            $("#province_id, #district_id").removeProp("disabled");
            $("#region_c_id").prop("disabled",true);
            
        }
        else if(desg == "lga_user")
        {
            $("#province_id, #district_id").removeProp("multiple");
            $("#province_id, #district_id, #region_c_id").removeProp("disabled");
        }
        else if(desg == "partner_user")
        {
            
            $("#province_id, #district_id").removeProp("disabled");
            $("#province_id, #district_id").prop("multiple","multiple");
            $("#region_c_id").prop("disabled",true);
        }
        else
        {
           $("#province_id, #district_id, #region_c_id").removeProp("disabled");
           $("#province_id, #district_id").removeProp("multiple");
        }
    }
    
    function setSelectDefaultValue()
    {
//        var province = $("#province_id").val();
//        var district = $("#distric_id").val();
//        var lga = $("#region_c_id").val();

            var desg = $("#designation" ).val();
        
            if(desg == "fed_user")
            {
               $("#province,#district,#region").removeProp('disabled');
            }
            else if(desg == "state_user" || desg == "partner_user")
            {
                $("#region").removeProp('disabled');
            }
    }
    
    function disableHiddenField()
    {
        $("#province,#district,#region").prop('disabled',true);
    }
 
 function generateUsername() {
        console.log("Left surname field");
         var fname = $("#first_name").val();
         var lname = $("#last_name").val();
         
         var uname = "";
         if(fname.length > 0)
         {
             uname += fname.charAt(0);
         }
         uname += lname;
         
         $("#username").val(uname);
         console.log("Finished event processing");
     };
 
$(document).ready(function()
{
    $("#province_id, #district_id").change(function()
    {
        onDesignationChange();
    })
    
    $(document).tooltip({
      show: {
        effect: "slideDown",
        delay: 250
      },
      position: { my: "left top", at: "right top" },
    });
})
</script>

                </div>
        </div>

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>

