
     <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'coverage';
                                        $variable = 'Simple';        
                                        require_once('views/scripts/template/template.phtml');
                                       
                                    ?>

                                      <?php 
                                    if(empty($this->selectedDatemultiple)){
                                         $titleText = $this->end_date." to ".$this->start_date;
                                     }else{
                                         $titleText = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date";
                                     }
                                          $title = ($this->freshvisit) 
                                                      ? "Percent of facilities with an FP-trained HW providing FP, " 
                                                      : "Percent of facilities with a trained HW providing FP in selected geographies, ";
                                          $title .= $titleText;    //echo  " var title_data = 'FP HR coverage for $this->location_name, $this->start_date to $this->end_date' " ;
                                    ?>
                                    
                                    
                                    
                              
                                    
                                    <div  class="row" style="margin-top:20px;">
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                      <?php require_once('views/scripts/dashboard/top_buttons.phtml');?>
				
                                           </div>
                                        
                                           <div class="col-sm-7 box-shadow" style="height:auto;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                 
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                                <div id="infobutton" class="infobutton">
                                                                                   <span class="infowrap"><i class="fa fa-info-circle"></i></span>        
                                                                                  <div id="" class="infodiv" >
                                                                                      This chart shows the coverage of FP-trained health workers, the coverage of service 
                                                                                      provision at facilities with FP-trained health workers, and the rate of stock outs 
                                                                                      at facilities with FP-trained health workers. <br/><br/>
                                                                                
                                                                                      Together, these trend lines demonstrate whether the coverage of FP services at facilities 
                                                                                      that should be providing FP is improving over time and provides some clues as to the possible 
                                                                                      barriers (insufficient coverage of trained health workers, high stock outs, or another service 
                                                                                      delivery challenge). <br/><br/>
                                                                                
                                                                                      FP training includes Contraceptive Technology Update, FP Technology, 
                                                                                      Injectable Contraceptives for CHEWs, LARC, and Post Partum IUCD in-service trainings.  
                                                                             </div>
                                                                      </div>
                                                                             
                                                                          </div>   
	
			         	                          
									           
				
                                           </div>
                                               
                                               
								     	<div id="chart_div" style="width:100%; height: auto;"></div>
                                               
                                           
                                               
                                           </div>
                                    </div>
                                    
                                     <div class="row" style="margin-top:50px;">
                                    
                                           <div  class="col-sm-7 box-shadow" style="height:auto;"   >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                 
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                              <div id="infobutton" class="infobutton">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                            <div id="" class="infodiv" >
                                                                                This chart shows the coverage of LARC-trained health workers, the coverage 
                                                                                of service provision at facilities with LARC-trained health workers, and the 
                                                                                rate of stock outs at facilities with LARC-trained health workers. <br/><br/>
                                                                                
                                                                                Together, these trend lines demonstrate whether the coverage of LARC services at 
                                                                                facilities that should be providing LARC is improving over time and provides 
                                                                                some clues as to the possible barriers (insufficient coverage of trained health workers, 
                                                                                high stock outs, or another service delivery challenge). <br/><br/>
                                                                                
                                                                                LARC training includes LARC and Post Partum IUCD in-service trainings.
                                                                            </div>
                                                                    </div>
                                                                             
                                                                          </div>   
	
				
                                           </div>
                                                                 
                                                                    <div id="chart13_div" style="width:100%; height:auto;"></div>
                                               
                                             
				                           </div>  
                                       
                                    </div>
                                
                                </div>

		
		<div class="clear"></div>
                </div>
       
           </div><!-- content -->
           <br/><br/><br/>



                
<script type="text/javascript">
		
//  google.load('visualization', '1.0', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.setOnLoadCallback(apiLoaded);
  $(function() {
	//  document.getElementById("allCharts").style.marginLeft="130px";

	
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;
		 
    
        drawFPChart();
        drawLARCChart();
   
  });

  function drawFPChart() {
        FPOvertime = <?= $this->fp_overtime; ?>;
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = '<?= $this->end_date; ?>';
        
        var hwCoverage = FPOvertime[0];
        var providingCoverage = FPOvertime[1];
        var soCoverage = FPOvertime[2];
        
        var facTrainedObject = {name:'% of facilities with FP-trained HW', data: [],alias:'factrained'};
        var facProvObject = {name:'% of FP-trained facilities providing FP', data: [],alisa:'facprov'};
        var facSOObject = {name:'% of FP-trained facilities stocked out of FP', data: [],alias:'facSO'};
       
        var monthNames = new Array();
        for(key in hwCoverage){
            var monthName = hwCoverage[key]['month'];
            monthNames.push(monthName);
            facTrainedObject.data.push(hwCoverage[key]['percent']);
            facProvObject.data.push(monthName == providingCoverage[key]['month'] ? providingCoverage[key]['percent'] : 0);
            facSOObject.data.push(monthName == soCoverage[key]['month'] ? soCoverage[key]['percent'] : 0);
        }
        
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        dateLength = selectedDatemultiple.length;
              
        var dateText = '<?= $this->start_date . " to " . $this->end_date ?>';
        if(dateLength > 0){
            dateText = dateLength === 1 ? 
                    monthNamesWithYears[0] : 
                    "across selected dates";
        } 
        
        <?php if($this->freshVisit) { ?>
            var titleText = "Percent of facilities with an FP-trained HW providing FP, <br/>" + dateText;
        <?php } else { ?>
            var titleText = "Percent of facilities with an FP-trained HW providing FP <br/>in selected geographies, " + dateText;
        <?php } ?>
          
          $('#chart_div').highcharts({
                chart: {
                    type: dateLength == 1 ? 'column' : 'line',
                    height: 470,
                    //spacingLeft: -20,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart_div").siblings("#infobutton").removeClass("hidden");
                        }
                    }
                },
                title: {
                    text: titleText,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                    x: -20 //center
                },
                xAxis: {
                     title:{
                        text:'Month',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: monthNamesWithYears
                },
                yAxis: {
                    title: {
                        text: '% Faacilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    max: 100,
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        var monthArray = (this.x).split(" ");
                        var month = monthArray[0];
                        var dataObj = [];
                        
                        if((this.series.name).includes('HW'))
                            dataObj = hwCoverage;
                        else if((this.series.name).includes('providing'))
                            dataObj = providingCoverage;
                        else if((this.series.name).includes('stocked out'))
                            dataObj = soCoverage;
                                                
                        index = -1;
                        for(key in dataObj){
                            if ((dataObj[key]['month']).toUpperCase() === month.toUpperCase()){
                                index = key;
                                break;
                            }
                        }
                        
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                            '<b>Numerator</b>:'+thousandSeparator(dataObj[index]['numer'])+'<br/>' + 
                            '<b>Denominator</b>:'+thousandSeparator(dataObj[index]['denom']);
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    },
                    column: dateLength === 1  
                         ? {    
                            dataLabels: {
                                  enabled: true,
                                  format: '{y}%'
                              }
                          }
                          : {}  
                },
                legend: {
                    layout: 'vertical',
                    //verticalAlign: 'center',
                    align: 'center',
                    borderWidth: 1,
                    //shadow: true
                },
                series: [facTrainedObject, facProvObject, facSOObject]
            });      

    }//end fp chart
    
    
    function drawLARCChart() {
        LARCOvertime = <?= $this->larc_overtime; ?>;
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = '<?= $this->end_date; ?>';
        
        var hwCoverage = LARCOvertime[0];
        var providingCoverage = LARCOvertime[1];
        var soCoverage = LARCOvertime[2];
        
        var facTrainedObject = {name:'% of FP facilities with LARC-trained HW', data: []};
        var facProvObject = {name:'% of LARC-trained facilities providing LARC', data: []};
        var facSOObject = {name:'% of LARC-trained facilities stocked out of FP', data: []};
       
        var monthNames = new Array();
        for(key in hwCoverage){
            var monthName = hwCoverage[key]['month'];
            monthNames.push(monthName);
            facTrainedObject.data.push(hwCoverage[key]['percent']);
            facProvObject.data.push(monthName == providingCoverage[key]['month'] ? providingCoverage[key]['percent'] : 0);
            facSOObject.data.push(monthName == soCoverage[key]['month'] ? soCoverage[key]['percent'] : 0);
        }
        
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        dateLength = selectedDatemultiple.length;
        
        var dateText = '<?= $this->start_date . " to " . $this->end_date ?>';
          if(dateLength > 0){
              dateText = dateLength === 1 ? 
                      monthNamesWithYears[0] : 
                      "across selected dates";
          } 

          <?php if($this->freshVisit) { ?>
              var titleText = "Percent of FP facilities with a LARC-trained HW providing LARC, <br/>" + dateText;
          <?php } else { ?>
              var titleText = "Percent of FP facilities with a LARC-trained HW providing LARC <br/>in selected geographies, " + dateText;
          <?php } ?>
          
          
          $('#chart13_div').highcharts({
                chart: {
                    type: dateLength == 1 ? 'column' : 'line',
                    height: 470,
                    //spacingLeft: -20,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart_div").siblings("#infobutton").removeClass("hidden");
                        }
                    }
                },
                title: {
                    text: titleText,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                    x: -20 //center
                },
                xAxis: {
                     title:{
                        text:'Month',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: monthNamesWithYears
                },
                yAxis: {
                    title: {
                       text: '% Faacilities',
                       style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    max: 100,
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        var monthArray = (this.x).split(" ");
                        var month = monthArray[0];
                        var dataObj = [];
                        
                        if((this.series.name).includes('HW'))
                            dataObj = hwCoverage;
                        else if((this.series.name).includes('providing'))
                            dataObj = providingCoverage;
                        else if((this.series.name).includes('stocked out'))
                            dataObj = soCoverage;
                                                
                        index = -1;
                        for(key in dataObj){
                            if ((dataObj[key]['month']).toUpperCase() === month.toUpperCase()){
                                index = key;
                                break;
                            }
                        }
                        
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                            '<b>Numerator</b>:'+thousandSeparator(dataObj[index]['numer'])+'<br/>' + 
                            '<b>Denominator</b>:'+thousandSeparator(dataObj[index]['denom']);
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    },
                    column: dateLength === 1  
                         ? {    
                            dataLabels: {
                                  enabled: true,
                                  format: '{y}%'
                              }
                          }
                          : {}  
                },
                legend: {
                    layout: 'vertical',
                    //verticalAlign: 'center',
                    align: 'center',
                    borderWidth: 1,
                    //shadow: true
                },
                series: [facTrainedObject, facProvObject, facSOObject]
            });      

    }//end fp chart
    
  

</script>


<script>
  //devsite.github.Link.convertAnchors();
  //window.prettyPrint();
</script>	
    
<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

<script src="../js/tp/overtime-ops.js"></script>

</body>

</html>