<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}


</style>
   
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />  
<!--<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">-->

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
<!--<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />-->
<!--<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css">-->

    

<style>

    .infobutton {
        padding-right: 13px !important;
        padding-bottom : 6px;
    }

</style>
    


<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" defer async></script>

<!--<script src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>-->
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>-->

<script>
  $(function() {
    $( "#accordion" ).accordion({header: "h3", collapsible: true,active: 0});
    
     //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
   $(".accordion").on("click", "dd", function (event) {
 $("div.active").slideToggle("slow");
 $(this).find(".content").slideToggle("slow");
 });
  </script>
</head>
<body class="yui-skin-sam">
    
	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>
				<?php  // require_once('views/scripts/dashboard/load_data.phtml');?>

			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php 
                                    $singleSelection = true;
                                    require_once('views/scripts/dashboard/top_buttons.phtml');
                                ?>
			</div>

			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			<div class="nav-buttons">
				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    require_once('views/scripts/dashboard/left_buttons.phtml');
                                ?>
			</div>
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->


			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">

				<div id="toprow" class="container chartrow">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
                                                                <div id="homebanner" class="rounded">
                                                                    <div class="sliderdiv" style="margin-left: 20px;">
                                                                        <div id="infobutton" class="infobutton hidden">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>        
                                                                            <div id="" class="infodiv" >
                                                                                This chart shows the coverage of FP-trained health workers, the coverage of service 
                                                                                provision at facilities with FP-trained health workers, and the rate of stock outs 
                                                                                at facilities with FP-trained health workers. <br/><br/>
                                                                                
                                                                                Together, these trend lines demonstrate whether the coverage of FP services at facilities 
                                                                                that should be providing FP is improving over time and provides some clues as to the possible 
                                                                                barriers (insufficient coverage of trained health workers, high stock outs, or another service 
                                                                                delivery challenge). <br/><br/>
                                                                                
                                                                                FP training includes Contraceptive Technology Update, FP Technology, 
                                                                                Injectable Contraceptives for CHEWs, LARC, and Post Partum IUCD in-service trainings.  
                                                                            </div>
                                                                    </div>
									<div id="chart_div" style="width: 600px; height: 400px;"></div>
                                                                    </div>
                                                                    
                                                                  
								</div>
							</div>
						</div>			
					</div>
					
					

								<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
								
					<div id="bottomrow" class="container chartrow">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv" style="margin-left: 20px; margin-top: 50px;">
                                                                    <div id="infobutton" class="infobutton hidden">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                            <div id="" class="infodiv" >
                                                                                This chart shows the coverage of LARC-trained health workers, the coverage 
                                                                                of service provision at facilities with LARC-trained health workers, and the 
                                                                                rate of stock outs at facilities with LARC-trained health workers. <br/><br/>
                                                                                
                                                                                Together, these trend lines demonstrate whether the coverage of LARC services at 
                                                                                facilities that should be providing LARC is improving over time and provides 
                                                                                some clues as to the possible barriers (insufficient coverage of trained health workers, 
                                                                                high stock outs, or another service delivery challenge). <br/><br/>
                                                                                
                                                                                LARC training includes LARC and Post Partum IUCD in-service trainings.
                                                                            </div>
                                                                    </div>
                                                                    
                                                                    <div id="chart13_div" style="width: 600px; height: 400px;"></div>
                                                                    </div>
								</div>
							</div>
						</div>
								
						<!-------   /////////////////////////// chart 2,2 ////////////////////// -->		
                                                <div class="main-search"></div>

					</div>
                                </div>
				</div>
		
	</div>

		<div class="clear"></div>
		<div class="hrGrey"></div> 
		<div class="clear"></div>
		
		<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->

		<!-------   /////////////////////////// main gnr ////////////////////// -->

                
<!----------------------    Prepare the values for FP and LARC when GEO is selected -------------->
<?php
        
            
  ?>
                
<script type="text/javascript">
		
//  google.load('visualization', '1.0', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.setOnLoadCallback(apiLoaded);
  $(function() {
	  document.getElementById("allCharts").style.marginLeft="130px";

	
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;
		 
    
        drawFPChart();
        drawLARCChart();
   
  });

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->
  //TA:17:17: Coverage HW Trained chart
  function drawFPChart() {
      var jNumData = new Array();
      var jDenomData = new Array();
      jNumData['% of facilities with FP-trained HW'] = [];
      jNumData['% of FP-trained facilities providing FP'] = [];
      jNumData['% of FP-trained facilities stocked out of FP'] = [];
      
      jDenomData['% of facilities with FP-trained HW'] = [];
      jDenomData['% of FP-trained facilities providing FP'] = [];
      jDenomData['% of FP-trained facilities stocked out of FP'] = [];
      
      <?php
        $hwCoverage = $this->fp_overtime[0]; 
        $providingCoverage = $this->fp_overtime[1]; 
        $soCoverage = $this->fp_overtime[2]; 
        
        $hwNumDenom = $this->fp_numerator_denominator[0];
        $providingNumDenom = $this->fp_numerator_denominator[1];
        $soNumDenom = $this->fp_numerator_denominator[2];
      ?>
          
       var facTrainedObject = {name:'% of facilities with FP-trained HW', data: [],alias:'factrained'};
       var facProvObject = {name:'% of FP-trained facilities providing FP', data: [],alisa:'facprov'};
       var facSOObject = {name:'% of FP-trained facilities stocked out of FP', data: [],alias:'facSO'};
       
        <?php
        
        foreach($hwNumDenom as $i => $det) {
            $month = $det['month'];
             
             $numerator = $det['numerator'];   
             $denominator = $det['denominator'];
            ?>
           jNumData['% of facilities with FP-trained HW']['<?php echo $month; ?>'] = <?php echo $numerator; ?>;
           jDenomData['% of facilities with FP-trained HW']['<?php echo $month; ?>'] = <?php echo $denominator; ?>;
            <?php
             
        }
        
        
         foreach($providingNumDenom as $i => $det) {
            $month = $det['month'];
             
             $numerator = $det['numerator'];   
             $denominator = $det['denominator'];
            ?>
           jNumData['% of FP-trained facilities providing FP']['<?php echo $month; ?>'] = <?php echo $numerator; ?>;
           jDenomData['% of FP-trained facilities providing FP']['<?php echo $month; ?>'] = <?php echo $denominator; ?>;
            <?php
             
        }
        
        foreach($soNumDenom as $i => $det) {
            $month = $det['month'];
             
             $numerator = $det['numerator'];   
             $denominator = $det['denominator'];
            ?>
           jNumData['% of FP-trained facilities stocked out of FP']['<?php echo $month; ?>'] = <?php echo $numerator; ?>;
           jDenomData['% of FP-trained facilities stocked out of FP']['<?php echo $month; ?>'] = <?php echo $denominator; ?>;
            <?php
             
        }
        
        
                    $monthNames = array();
                    foreach($hwCoverage as $i => $details) {
                        $monthNames[] = $details['month'];
                        $hwCount = round($details['percent']*100, 1);                
                        $provCount = array_key_exists($i, $providingCoverage) ? round($providingCoverage[$i]['percent']*100, 1) : 0;
                        $soCount = array_key_exists($i, $soCoverage) ? round($soCoverage[$i]['percent']*100, 1) : 0;
        ?> 
                        //JS
                        facTrainedObject.data.push(<?php echo $hwCount; ?>);
                        facProvObject.data.push(<?php echo $provCount; ?>);
                        facSOObject.data.push(<?php echo $soCount; ?>);
        <?php
                    }
        ?>                                        

      <?php 
      if(empty($this->selectedDatemultiple)){
           $titleText = $this->end_date." to ".$this->start_date;
       }else{
           $titleText = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date(s)";
       }
            $title = ($this->freshvisit) 
                        ? "Percent of facilities with an FP-trained HW providing FP, " 
                        : "Percent of facilities with an FP-trained HW providing FP in selected geographies, ";
            $title .= $titleText;    //echo  " var title_data = 'FP HR coverage for $this->location_name, $this->start_date to $this->end_date' " ;
      ?>;
          
          
      $('#chart_div').highcharts({
                chart: {
                    //type: 'line',
                    height: 470,
                    //spacingLeft: -20,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart_div").siblings("#infobutton").removeClass("hidden");
                        }
                    }
                },
                title: {
                    text: '<?php echo $title; ?>',
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                    x: -20 //center
                },
                xAxis: {
                     title:{
                        text:'Month',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: <?php echo json_encode($monthNames); ?>
                },
                yAxis: {
                    title: {
                        text: '%  Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    max: 100,
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.series.name][this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.series.name][this.x]);
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    }
                },
                legend: {
                    layout: 'horizontal',
                    //verticalAlign: 'center',
                    align: 'center',
                    borderWidth: 1,
                    //shadow: true
                },
                series: [facTrainedObject, facProvObject, facSOObject]
            });


    }//end fp chart
    
    
    
    function drawLARCChart() {
       var jNumData = new Array();
      var jDenomData = new Array();
      jNumData['% of facilities with LARC-trained HW'] = [];
      jNumData['% of LARC-trained facilities providing LARC'] = [];
      jNumData['% of LARC-trained facilities stocked out of LARC'] = [];
      
      jDenomData['% of facilities with LARC-trained HW'] = [];
      jDenomData['% of LARC-trained facilities providing LARC'] = [];
      jDenomData['% of LARC-trained facilities stocked out of LARC'] = [];
      <?php
        $hwCoverage = $this->larc_overtime[0]; 
        $providingCoverage = $this->larc_overtime[1]; 
        $soCoverage = $this->larc_overtime[2]; 
        
         $hwNumDenom = $this->larc_numerator_denominator[0];
        $providingNumDenom = $this->larc_numerator_denominator[1];
        $soNumDenom = $this->larc_numerator_denominator[2];
      ?>
              
       var facTrainedObject = {name:'% of facilities with LARC-trained HW', data: []};
       var facProvObject = {name:'% of LARC-trained facilities providing LARC', data: []};
       var facSOObject = {name:'% of LARC-trained facilities stocked out of LARC', data: []};
          
        <?php
        
         foreach($hwNumDenom as $i => $det) {
            $month = $det['month'];
             
             $numerator = $det['numerator'];   
             $denominator = $det['denominator'];
            ?>
           jNumData['% of facilities with LARC-trained HW']['<?php echo $month; ?>'] = <?php echo $numerator; ?>;
           jDenomData['% of facilities with LARC-trained HW']['<?php echo $month; ?>'] = <?php echo $denominator; ?>;
            <?php
             
        }
        
        
         foreach($providingNumDenom as $i => $det) {
            $month = $det['month'];
             
             $numerator = $det['numerator'];   
             $denominator = $det['denominator'];
            ?>
           jNumData['% of LARC-trained facilities providing LARC']['<?php echo $month; ?>'] = <?php echo $numerator; ?>;
           jDenomData['% of LARC-trained facilities providing LARC']['<?php echo $month; ?>'] = <?php echo $denominator; ?>;
            <?php
             
        }
        
        foreach($soNumDenom as $i => $det) {
            $month = $det['month'];
             
             $numerator = $det['numerator'];   
             $denominator = $det['denominator'];
            ?>
           jNumData['% of LARC-trained facilities stocked out of LARC']['<?php echo $month; ?>'] = <?php echo $numerator; ?>;
           jDenomData['% of LARC-trained facilities stocked out of LARC']['<?php echo $month; ?>'] = <?php echo $denominator; ?>;
            <?php
             
        }
        
        
                    $monthNames = array();
                     foreach($hwCoverage as $i => $details) {
                         $monthNames[] = $details['month'];
                         $hwCount = round($details['percent']*100, 1);
                         $provCount = array_key_exists($i, $providingCoverage) ? round($providingCoverage[$i]['percent']*100, 1) : 0;
                         $soCount = array_key_exists($i, $soCoverage) ? round($soCoverage[$i]['percent']*100, 1) : 0;
        ?> 
                        //JS
                        facTrainedObject.data.push(<?php echo $hwCount; ?>);
                        facProvObject.data.push(<?php echo $provCount; ?>);
                        facSOObject.data.push(<?php echo $soCount; ?>);
         <?php
                     }
        ?>                                        
      
      <?php 
        if(empty($this->selectedDatemultiple)){
           $titleText = $this->end_date." to ".$this->start_date;
       }else{
           $titleText = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date(s)";
       }
            $title = ($this->freshvisit) 
                        ? "Percent of facilities with an FP-trained HW providing LARC, " 
                        : "Percent of facilities with an FP-trained HW providing LARC in selected geographies, ";
            $title .= $titleText;    //echo  " var title_data = 'FP HR coverage for $this->location_name, $this->start_date to $this->end_date' " ;
      ?>;
          
          
      $('#chart13_div').highcharts({
                chart: {
                    //type: 'line',
                    height: 470,
                    //spacingLeft: -20,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    }
                },
                title: {
                    text: '<?php echo $title; ?>',
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                    x: -20 //center
                },
                xAxis: {
                     title:{
                        text:'Month',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: <?php echo json_encode($monthNames); ?>
                },
                yAxis: {
                    title: {
                       text: '%  Facilities',
                       style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    max: 100,
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + this.y + '%<br/><br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.series.name][this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.series.name][this.x]);
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    }
                },
                legend: {
                    layout: 'horizontal',
                    //verticalAlign: 'center',
                    align: 'center',
                    borderWidth: 1,
                    //shadow: true
                },
                series: [facTrainedObject, facProvObject, facSOObject]
            });
          
          
    }
    
  

</script>


<script>
  //devsite.github.Link.convertAnchors();
  //window.prettyPrint();
</script>	
    
<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

<script src="../js/tp/functions.js"></script>

</body>

</html>