   <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'coverage';
                                        $variable = 'Simple';        
                                        require_once('views/scripts/template/template.phtml');
                                       
                                    ?>
    
                                     <div class="row" style="margin-bottom:20px;">
                                         
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                      <?php require_once('views/scripts/dashboard/top_buttons.phtml');?>
                                               
                                           </div>
				
                                        
                                    
                                           <div  class="col-sm-7 pull-right box-shadow clearfix"  style="height:auto;"  >
                                               
                                                          <?php
                                                                       $chart_title = "";
                                                                        $info_text =  "The chart displays the cumulative number of health workers trained in FP 
                                                                                and trained in LARC as of each year shown. This chart also compares progress 
                                                                                to the national target. FP training includes Contraceptive Technology Update, 
                                                                                FP Technology, Injectable Contraceptives for CHEWs, LARC, and Post Partum IUCD 

                                                                                in-service trainings. LARC training includes LARC and Post Partum IUCD in-service trainings. ";
                                                                        
                                                                        include('views/scripts/template/chart_title.phtml');
                                                            
                                                           ?>
                                                         
                                     
                                             
                                               <div id="chart_div"  style="width:100%; height: 400px;"></div>
                                         
				                           </div>                           
                                    </div>

                                <?php if(isset($this->fp_cumm_location)){ ?>
                                    
                                    <div id="first-div" class="row" style="margin-top:30px;display:none;">
                                         
                                           <div class="col-sm-7 box-shadow" style="height:auto;"  >
                                               
                                               
                                                          <?php
                                                                       $chart_title = ""; 
                                                                        $info_text =  "The chart displays the cumulative number of health workers trained in FP 
                                                                                    as of each year shown in the selected geographies. FP training includes Contraceptive 
                                                                                    Technology Update, FP Technology, Injectable Contraceptives for CHEWs, LARC, 
                                                                                    and Post Partum IUCD in-service trainings.";
                                                                        
                                                                        include('views/scripts/template/chart_title.phtml');
                                                            
                                                           ?>
                                               
                                         
	
			         	                      <div id="fpchart_div" style="width:100%; height: auto;"></div>
				
                                           </div>
                                         
                                               
                                           </div>

                                <?php } ?>

                                <?php if(isset($this->larc_cumm_location)){ ?>
                                
                                    
                                    <div id="second-div" class="row" style="margin-top:50px;display:none;padding-bottom:45px;">
                                    
                                           <div  class="col-sm-7 box-shadow" style="height:auto;"   >
                                               
                                                 
                                                          <?php
                                                                       $chart_title =  "";
                                                                        $info_text =  " The chart displays the cumulative number of health workers trained in FP 
                                                                                    as of each year shown in the selected geographies. FP training includes Contraceptive 
                                                                                    Technology Update, FP Technology, Injectable Contraceptives for CHEWs, LARC, 
                                                                                    and Post Partum IUCD in-service trainings.";
                                                                        
                                                                        include('views/scripts/template/chart_title.phtml');
                                                            
                                                           ?>
                                               
                                            
                                               
                                               <div id="larcchart_div"  style="width:100%; height:400px;"></div>
	
				                           </div>  
                                       
                                    </div>
                                
                                <?php } ?>
                                    
                                     
                                
                                   
                                </div>


		
		<div class="clear"></div>
                </div>
            
          
            
           
            
          
           
           </div><!-- content -->
           <br/><br/><br/>
        
         
		<!-------   /////////////////////////// main gnr ////////////////////// -->
<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->
<script type="text/javascript">                
/*************************    Prepare the values for FP and LARC when GEO is selected *********************/
<?php
        $fp_chartData =  $larc_chartData =  "";
        
        if(isset($this->fp_cumm_location)){
            reset($this->fp_cumm_location);
            $firstLocation = current($this->fp_cumm_location);  // get the location to be used as key in next stmt
            $yearsArray = array_keys($firstLocation);

            $yearsString = "";
            foreach ($yearsArray as $year){
                $yearsString .= "'$year',";
            }
            $yearsString = substr($yearsString, 0, -1);
            
            $locationsString = "";
            foreach($this->fp_cumm_location as $key=>$locationData) {
                $locationsString .= "'$key',";
            }
            $locationsString = substr($locationsString, 0, -1);
?>
            //JS: declare the arrays to store data
            var FPDataArray = new Array();
            var LARCDataArray = new Array();

<?php            
            foreach($yearsArray as $year){
?>                
                //JS
                var FPObj = {name:'', data:[]};  //define the object for this name/legend
                var LARCObj = {name:'', data:[]}
                FPObj.name = LARCObj.name = '<?php echo $year; ?>';
                
<?php             
                foreach($this->fp_cumm_location as $key=>$locationData) {
?>                  
                    //JS: push into the data array of each of object
                    //FPObj.data.push($locationData[$year]);
                    FPObj.data.push(<?php echo $this->fp_cumm_location[$key][$year]; ?>);
                    LARCObj.data.push(<?php echo $this->larc_cumm_location[$key][$year]; ?>);
<?php                    
                }//cumm_location loop
?>                    
                //JS: add the completed objects to wrapper dataArray(s) 
                FPDataArray.push(FPObj);
                LARCDataArray.push(LARCObj);
                
<?php   
            }//year loop

            $hAxisTitle = '2015 target number of HWs to be trained in LARC: 5500';
            $national_title = "";
            $nationalSubtitle = "";    
        }
        else{
            $hAxisTitle = '';
            $national_title = "";
            $nationalSubtitle = "";    
        }
  ?>
                

		
  //console.log("inside JS at least");
//  google.load('visualization', '1.0', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.setOnLoadCallback(apiLoaded);
  //function apiLoaded() {
  $(function() {
      
       //drawNationalChart();
      
      // drawFPChart();
      
      // drawLARCChart();
        
	//document.getElementById("allCharts").style.marginLeft="130px";
        

		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;
		 
    
        <?php if(isset($this->fp_cumm_location)) { ?>    
                drawNationalChart();
                drawFPChart();
                drawLARCChart();
        <?php } else { ?>
                //console.log("combo");
                drawNationalComboChart();
        <?php } ?>
   
  });

    
    
  function drawNationalComboChart() {
        
        var dataArray = new Array();
                
        <?php
             $yearsArray = array_keys($this->cumm_data);
             $namesArray = array('fp'=>'Total FP Trained', 'larc'=>'Total LARC Trained');
             foreach($namesArray as $nameKey=>$name){
        ?>
                //JS
                var obj = {name:'', data:[]};  //define the object for this name/legend
                obj.name = '<?php echo $name; ?>';
        
        <?php   foreach ($yearsArray as $year){  ?>
            
                    //JS
                    obj.data.push(<?php echo $this->cumm_data[$year][$nameKey]; ?>); //push the element into the array
                    
        <?php   } //inner for loop ?>
            
                //JS: add the obj to the dataArray 
                dataArray.push(obj);
                
        <?php }//outer for loop: $namesArray
             
            //now treat the categories
            $yearsString = '';
            foreach ($yearsArray as $year ){
                $yearsString .= "'" . $year . "',";
            }
            //drop trailing comma, use result as categories value
            $yearsString = substr($yearsString, 0, strlen($yearsString)-1); 
        ?>

              var hAxisTitle = <?php echo "'$hAxisTitle'"; ?>;
              var national_title = '<?php echo "$national_title $nationalSubtitle"; ?>';
              var nationalSubtitle = '(<?php echo $nationalSubtitle; ?>)';
              var title = 'Total HWs trained nationally as of ' + '<?= $this->tp_date; ?>';
              
               var lineObject = {
                    type: 'line',
                    name: '2015 Target # HWs <br/>to be Trained in LARC',
                    data: [5500, 5500, 5500],
                    marker: {
                        enabled: false,
                        lineWidth: 3,
                        //lineColor: Highcharts.getOptions().colors[2]
                        //fillColor: 'white'
                    }
                }
              
              dataArray.push(lineObject);
              console.log(dataArray);
              
              $("#chart_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#chart_div").siblings("#infobutton").removeClass("hidden");
                                }
                            }
                    },
                    title: {
                        text: title,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '12pt'
                        },
                    },
                    xAxis: {
                        title:{
                            text:'Year',
                            style:{ "fontWeight": "bold" }
                        },
                        categories: [<?php echo $yearsString; ?>],
                        
                    },
                    yAxis: {
                        title: {
                            text: 'Number of HWs Trained',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'top',
                        //borderWidth: 0,
                        //layout: 'horizontal',
                        //align: 'right',
                        //verticalAlign: 'top',
                        //x: 40,
                        y: 60,
                        //width:100,
                        //floating: true,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        shadow: true
                    },
                    credits: {enabled: false},
                    series:dataArray

              });
      
    }
    
    
    function drawNationalChart(){
        var dataArray = new Array();
                
        <?php
             $yearsArray = array_keys($this->cumm_data);
             $namesArray = array('fp'=>'Total FP Trained', 'larc'=>'Total LARC Trained');
             foreach($namesArray as $nameKey=>$name){
        ?>
                //JS
                var obj = {name:'', data:[]};  //define the object for this name/legend
                obj.name = '<?php echo $name; ?>';
        
        <?php   foreach ($yearsArray as $year){  ?>
            
                    //JS
                    obj.data.push(<?php echo $this->cumm_data[$year][$nameKey]; ?>); //push the element into the array
                    
        <?php   } //inner for loop ?>
            
                //JS: add the obj to the dataArray 
                dataArray.push(obj);
                
        <?php }//outer for loop: $namesArray
             
            //now treat the categories
            $yearsString = '';
            foreach ($yearsArray as $year ){
                $yearsString .= "'" . $year . "',";
            }
            //drop trailing comma, use result as categories value
            $yearsString = substr($yearsString, 0, strlen($yearsString)-1); 
        ?>

              var hAxisTitle = <?php echo "'$hAxisTitle'"; ?>;
              var national_title = '<?php echo "$national_title $nationalSubtitle"; ?>';
              var nationalSubtitle = '(<?php echo $nationalSubtitle; ?>)';
              
              var title = 'Total HWs trained in selected geographies as of ' + '<?= $this->tp_date; ?>';
                  
              $("#chart_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#chart_div").siblings("#infobutton").removeClass("hidden");
                                }
                            },
                       
                    },
                    title: {
                        text: title,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '12pt'
                        },
                    },
                    xAxis: {
                        categories: [<?php echo $yearsString; ?>],
                        title: {
                            text: 'Year<br/><br/><?php echo $hAxisTitle; ?>',
                            style:{ "fontWeight": "bold" }
                        }
                        
                    },
                    yAxis: {
                        title: {
                            text: 'Number of HWs Trained',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'top',
                        //x: 40,
                        y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        shadow: true
                    },
                    credits: {enabled: false},
                    series:dataArray

              });
    }
    
    
  
   function drawFPChart(){  
       
       document.getElementById('first-div').style.display = 'block'; 
                
       document.getElementById('second-div').style.display = 'block'; 
    
      <?php if(isset($this->fp_cumm_location)){ ?>
        var titleText = 'Number of HWs trained in FP in selected geographies as of ' + '<?= $this->tp_date; ?>';
        var subtitle = '(<?php echo  "as of $this->tp_date"; ?>)';
                
        $("#fpchart_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#fpchart_div").siblings("#infobutton").removeClass("hidden");
                                }
                            },
                       
                        height: 350
                    },
                    title: {
                        text: titleText,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                    },
                    xAxis: {
                        categories: [<?php echo $locationsString; ?>],
                        title: {
                            text: 'Geography',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    yAxis: {
                        title: {
                            text: 'Number of HWs Trained',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'top',
                        //x: 40,
                        y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        shadow: true,
                        width: 100                                
                    },
                    credits: {enabled: false},
                    series:FPDataArray

              });
              
       
      <?php } ?>              
}
  
  function  drawLARCChart(){
    <?php if(isset($this->larc_cumm_location)){ ?>
        var titleText = 'Number of HWs trained in LARC in selected geographies as of ' + '<?= $this->tp_date; ?>';
        var subtitle = '(<?php echo  "as of $this->tp_date"; ?>)';
                
        $("#larcchart_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#larcchart_div").siblings("#infobutton").removeClass("hidden");
                                }
                            },
                 
                        height: 350
                    },
                    title: {
                        text: titleText,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                    },
                    xAxis: {
                        categories: [<?php echo $locationsString; ?>],
                        title: {
                        text: 'Geography',
                        style:{ "fontWeight": "bold" }
                            }
                    },
                    yAxis: {
                        title: {
                            text: 'Number of HWs Trained',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'top',
                        //x: 40,
                        y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        shadow: true,
                        width: 100
                    },
                    credits: {enabled: false},
                    series:LARCDataArray

              });
              
    <?php } ?>           
  }

</script>

<style type="text/css">
    .mclass{
        max-width:174px;
        overflow-wrap:break-word;
    }
</style>
<script>
  //devsite.github.Link.convertAnchors();
  //window.prettyPrint();
</script>	

<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

<!--<script src="../js/tp/functions.js"></script>-->
        
 <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>