<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />

      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
    
    
<style>

    .infobutton {
        padding-right: 13px !important;
        padding-bottom : 6px;
    }
    
    .firstInfoButton {
        padding-right : 0px !important;
        margin-right: -16px !important;
        padding-bottom : 6px;
    }
    
    <?php if(!isset($this->fp_cumm_location)) { ?>
        
        .firstInfoButton {
            
            padding-right : 29px !important;
            padding-bottom : 6px;
            
        }
    
    <?php } ?>
    
</style>
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>






<!--<script src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>-->
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>-->

<script>
  $(function() {
    $( "#accordion" ).accordion({header: "h3", collapsible: true,active: 0})
    
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
    
    
  
  </script>

</head>
<body class="yui-skin-sam">
    
	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

                        

			<div>
				<?php  // require_once('views/scripts/dashboard/load_data.phtml');?>

			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php require_once('views/scripts/dashboard/top_buttons.phtml');?>
			</div>

			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			<div class="nav-buttons">
				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    require_once('views/scripts/dashboard/left_buttons.phtml');
                                ?>
			</div>
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->


			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">

				<div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
                                                                <div id="homebanner" class="rounded">
                                                                    <div class="sliderdiv">
                                                                        <div id="infobutton " class="infobutton firstInfoButton">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                            <div id="" class="infodiv" >
                                                                                The chart displays the cumulative number of health workers trained in FP 
                                                                                and trained in LARC as of each year shown. This chart also compares progress 
                                                                                to the national target. FP training includes Contraceptive Technology Update, 
                                                                                FP Technology, Injectable Contraceptives for CHEWs, LARC, and Post Partum IUCD 
                                                                                in-service trainings. LARC training includes LARC and Post Partum IUCD in-service trainings. 
                                                                            </div>
                                                                        </div>
									<div id="chart_div" style="width: 600px; height: 400px; margin-left: 20px;"></div>
                                                                    </div>
								</div>
							</div>
						</div>			
					</div>
					
					

                                        <!-------   /////////////////////////// chart 2,1 - FP ////////////////////// -->
					<div id="bottomrow" class="container" style="width:550px !important;">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
                                                                    <div class="sliderdiv" style="margin-left: 20px;">
                                                                            <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The chart displays the cumulative number of health workers trained in FP 
                                                                                    as of each year shown in the selected geographies. FP training includes Contraceptive 
                                                                                    Technology Update, FP Technology, Injectable Contraceptives for CHEWs, LARC, 
                                                                                    and Post Partum IUCD in-service trainings.
                                                                                </div>
                                                                            </div>
                                                                            <div id="fpchart_div" style="width: 600px; height: 300px;"></div>
                                                                    </div>
								</div>
							</div>
						</div>									
								<!--<div class="main-search"></div>-->
					</div>
                                        
                                        <div id="bottomrow" class="container" style="width:550px !important;">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
                                                                    <div class="sliderdiv" style="margin-top: 60px !important; margin-left: 20px;">
                                                                            <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The chart displays the cumulative number of health workers trained in 
                                                                                    LARC as of each year shown in the selected geographies. LARC training 
                                                                                    includes LARC and Post Partum IUCD in-service trainings. 
                                                                                </div>
                                                                            </div>
                                                                            <div id="larcchart_div" style="width: 600px; height: 300px;"></div>
                                                                    </div>
								</div>
							</div>
						</div>									
					</div><!--larc chart ends -->
                                        
                                    </div><!-- allcharts -->
				</div>
		
	</div>

		<div class="clear"></div>
		<div class="hrGrey"></div> 
		<div class="clear"></div>

		

		<!-------   /////////////////////////// main gnr ////////////////////// -->
<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->
<script type="text/javascript">                
/*************************    Prepare the values for FP and LARC when GEO is selected *********************/
<?php
        $fp_chartData =  $larc_chartData =  "";
        
        if(isset($this->fp_cumm_location)){
            reset($this->fp_cumm_location);
            $firstLocation = current($this->fp_cumm_location);  // get the location to be used as key in next stmt
            $yearsArray = array_keys($firstLocation);

            $yearsString = "";
            foreach ($yearsArray as $year){
                $yearsString .= "'$year',";
            }
            $yearsString = substr($yearsString, 0, -1);
            
            $locationsString = "";
            foreach($this->fp_cumm_location as $key=>$locationData) {
                $locationsString .= "'$key',";
            }
            $locationsString = substr($locationsString, 0, -1);
?>
            //JS: declare the arrays to store data
            var FPDataArray = new Array();
            var LARCDataArray = new Array();

<?php            
            foreach($yearsArray as $year){
?>                
                //JS
                var FPObj = {name:'', data:[]};  //define the object for this name/legend
                var LARCObj = {name:'', data:[]}
                FPObj.name = LARCObj.name = '<?php echo $year; ?>';
                
<?php             
                foreach($this->fp_cumm_location as $key=>$locationData) {
?>                  
                    //JS: push into the data array of each of object
                    //FPObj.data.push($locationData[$year]);
                    FPObj.data.push(<?php echo $this->fp_cumm_location[$key][$year]; ?>);
                    LARCObj.data.push(<?php echo $this->larc_cumm_location[$key][$year]; ?>);
<?php                    
                }//cumm_location loop
?>                    
                //JS: add the completed objects to wrapper dataArray(s) 
                FPDataArray.push(FPObj);
                LARCDataArray.push(LARCObj);
                
<?php   
            }//year loop

            $hAxisTitle = '2015 target number of HWs to be trained in LARC: 5500';
            $national_title = "Total HWs trained in selected geographies";
            $nationalSubtitle = "as of $this->tp_date";    
        }
        else{
            $hAxisTitle = '';
            $national_title = "Total HWs trained nationally";
            $nationalSubtitle = "as of $this->tp_date";    
        }
  ?>
                

		
  //console.log("inside JS at least");
//  google.load('visualization', '1.0', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.setOnLoadCallback(apiLoaded);
  //function apiLoaded() {
  $(function() {
        
	document.getElementById("allCharts").style.marginLeft="130px";
        

		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;
		 
    
        <?php if(isset($this->fp_cumm_location)) { ?>
                drawNationalChart();
                drawFPChart();
                drawLARCChart();
        <?php } else { ?>
                console.log("combo");
                drawNationalComboChart();
        <?php } ?>
   
  });

    
    
  <!-------   /////////////////////////// script 1,1 ////////////////////// -->
  //TA:17:17: Coverage HW Trained chart
  function drawNationalComboChart() {
        
        var dataArray = new Array();
                
        <?php
             $yearsArray = array_keys($this->cumm_data);
             $namesArray = array('fp'=>'Total FP Trained', 'larc'=>'Total LARC Trained');
             foreach($namesArray as $nameKey=>$name){
        ?>
                //JS
                var obj = {name:'', data:[]};  //define the object for this name/legend
                obj.name = '<?php echo $name; ?>';
        
        <?php   foreach ($yearsArray as $year){  ?>
            
                    //JS
                    obj.data.push(<?php echo $this->cumm_data[$year][$nameKey]; ?>); //push the element into the array
                    
        <?php   } //inner for loop ?>
            
                //JS: add the obj to the dataArray 
                dataArray.push(obj);
                
        <?php }//outer for loop: $namesArray
             
            //now treat the categories
            $yearsString = '';
            foreach ($yearsArray as $year ){
                $yearsString .= "'" . $year . "',";
            }
            //drop trailing comma, use result as categories value
            $yearsString = substr($yearsString, 0, strlen($yearsString)-1); 
        ?>

              var hAxisTitle = <?php echo "'$hAxisTitle'"; ?>;
              var national_title = '<?php echo "$national_title $nationalSubtitle"; ?>';
              var nationalSubtitle = '(<?php echo $nationalSubtitle; ?>)';
              
               var lineObject = {
                    type: 'line',
                    name: '2015 Target # HWs <br/>to be Trained in LARC',
                    data: [5500, 5500, 5500],
                    marker: {
                        enabled: false,
                        lineWidth: 3,
                        //lineColor: Highcharts.getOptions().colors[2]
                        //fillColor: 'white'
                    }
                }
              
              dataArray.push(lineObject);
              console.log(dataArray);
              
              $("#chart_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#chart_div").siblings("#infobutton").removeClass("hidden");
                                }
                            }
                    },
                    title: {
                        text: national_title,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                    },
                    xAxis: {
                        title:{
                            text:'Year',
                            style:{ "fontWeight": "bold" }
                        },
                        categories: [<?php echo $yearsString; ?>],
                        
                    },
                    yAxis: {
                        title: {
                            text: '#HWs Trained',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'top',
                        //borderWidth: 0,
                        //layout: 'horizontal',
                        //align: 'right',
                        //verticalAlign: 'top',
                        //x: 40,
                        y: 60,
                        //width:100,
                        //floating: true,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        shadow: true
                    },
                    credits: {enabled: false},
                    series:dataArray

              });
      
    }
    
    
    function drawNationalChart(){
        
        var dataArray = new Array();
                
        <?php
             $yearsArray = array_keys($this->cumm_data);
             $namesArray = array('fp'=>'Total FP Trained', 'larc'=>'Total LARC Trained');
             foreach($namesArray as $nameKey=>$name){
        ?>
                //JS
                var obj = {name:'', data:[]};  //define the object for this name/legend
                obj.name = '<?php echo $name; ?>';
        
        <?php   foreach ($yearsArray as $year){  ?>
            
                    //JS
                    obj.data.push(<?php echo $this->cumm_data[$year][$nameKey]; ?>); //push the element into the array
                    
        <?php   } //inner for loop ?>
            
                //JS: add the obj to the dataArray 
                dataArray.push(obj);
                
        <?php }//outer for loop: $namesArray
             
            //now treat the categories
            $yearsString = '';
            foreach ($yearsArray as $year ){
                $yearsString .= "'" . $year . "',";
            }
            //drop trailing comma, use result as categories value
            $yearsString = substr($yearsString, 0, strlen($yearsString)-1); 
        ?>

              var hAxisTitle = <?php echo "'$hAxisTitle'"; ?>;
              var national_title = '<?php echo "$national_title $nationalSubtitle"; ?>';
              var nationalSubtitle = '(<?php echo $nationalSubtitle; ?>)';
              
              $("#chart_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#chart_div").siblings("#infobutton").removeClass("hidden");
                                }
                            },
                        width: 630
                    },
                    title: {
                        text: national_title,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                    },
                    xAxis: {
                        categories: [<?php echo $yearsString; ?>],
                        title: {
                            text: 'Year<br/><br/><?php echo $hAxisTitle; ?>',
                            style:{ "fontWeight": "bold" }
                        }
                        
                    },
                    yAxis: {
                        title: {
                            text: '#HWs Trained',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'top',
                        //x: 40,
                        y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        shadow: true
                    },
                    credits: {enabled: false},
                    series:dataArray

              });
    }
    
    
  
   function drawFPChart(){  
      <?php if(isset($this->fp_cumm_location)){ ?>
        var titleText = '<?php echo  "Number of HWs trained in FP as of $this->tp_date"; ?>';
        var subtitle = '(<?php echo  "as of $this->tp_date"; ?>)';
                
        $("#fpchart_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#fpchart_div").siblings("#infobutton").removeClass("hidden");
                                }
                            },
                        width: 600,
                        height: 350
                    },
                    title: {
                        text: titleText,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                    },
                    xAxis: {
                        categories: [<?php echo $locationsString; ?>],
                        title: {
                            text: 'Geography',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    yAxis: {
                        title: {
                            text: '#HWs Trained',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'top',
                        //x: 40,
                        y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        shadow: true,
                        width: 100                                
                    },
                    credits: {enabled: false},
                    series:FPDataArray

              });
              
       
      <?php } ?>              
}
  
  function  drawLARCChart(){
    <?php if(isset($this->larc_cumm_location)){ ?>
        var titleText = '<?php echo  "Number of HWs trained in LARC as of $this->tp_date"; ?>';
        var subtitle = '(<?php echo  "as of $this->tp_date"; ?>)';
                
        $("#larcchart_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#larcchart_div").siblings("#infobutton").removeClass("hidden");
                                }
                            },
                        width: 600,
                        height: 350
                    },
                    title: {
                        text: titleText,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                    },
                    xAxis: {
                        categories: [<?php echo $locationsString; ?>],
                        title: {
                        text: 'Geography',
                        style:{ "fontWeight": "bold" }
                            }
                    },
                    yAxis: {
                        title: {
                            text: '#HWs Trained',
                            style:{ "fontWeight": "bold" }
                        }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'top',
                        //x: 40,
                        y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        shadow: true,
                        width: 100
                    },
                    credits: {enabled: false},
                    series:LARCDataArray

              });
              
    <?php } ?>           
  }

</script>

<style type="text/css">
    .mclass{
        max-width:174px;
        overflow-wrap:break-word;
    }
</style>
<script>
  //devsite.github.Link.convertAnchors();
  //window.prettyPrint();
</script>	

<!--<script src="https://code.highcharts.com/highcharts.js"></script>-->
<!--<script src="https://code.highcharts.com/modules/exporting.js"></script>-->

<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>

<?php //print_r($this->locations); ?>