<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}





.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}
  .mclass{
        min-width:182px !important;
    }
</style>
   

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script src="../bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="../bootstrap/js/bootstrap.min.js"></script>
<script src="../js/tp/functions.js"></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

<script>
  $(function() {
    $( "#accordion" ).accordion({header: "h3", collapsible: true,active: 0})
  });
  </script>

</head>
<body class="yui-skin-sam">
    
	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/headerhome.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

                        

			
				<?php  // require_once('views/scripts/dashboard/load_data.phtml');?>

			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			
			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
           

			<!-------   /////////////////////////// charts ////////////////////// -->


			<body class="docs slim framebox_body">
                            <div class="row">
                            <div class="col-md-2">

				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    require_once('views/scripts/dashboard/left_buttonshome.phtml');
                                ?>
                            </div>
                                <div class="col-md-10">
                                    <div class="row">
                                        <div class="col-md-2 col-md-push-9">
                                  
				<?php require_once('views/scripts/dashboard/top_buttonshome.phtml');?>
			
                                        </div>
                            <div class="col-md-8 col-md-pull-2">
                            <div class="row">
                                <div class="col-md-12">
                                                                    <div class="sliderdiv">
                                                                        <div id="infobutton" class="infobutton hidden" style="margin-bottom:-27px !important">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                            <div id="" class="infodiv" >
                                                                                The chart displays the cumulative number of health workers trained in FP 
                                                                                and trained in LARC as of each year shown. This chart also compares progress 
                                                                                to the national target. FP training includes Contraceptive Technology Update,
                                                                                FP Technology, and Injectable Contraceptives for CHEWs in-service trainings.
                                                                                LARC training includes LARC and Post Partum IUCD in-service trainings. 
                                                                            </div>
                                                                        </div>
									<div id="chart_div" style="width: 100%; height: 400px;"></div>
                                                                    </div>
                                </div>
					
					

                                        <!-------   /////////////////////////// chart 2,1 - FP ////////////////////// -->
					 <div class="col-md-12">
                                                                    <div class="sliderdiv">
                                                                            <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The chart displays the cumulative number of health workers trained in FP as 
                                                                                    of each year shown in the selected geographies. FP training includes Contraceptive 
                                                                                    Technology Update, FP Technology, and Injectable Contraceptives for CHEWs 
                                                                                    in-service trainings.
                                                                                </div>
                                                                            </div>
                                                                            <div id="fpchart_div" style="width: 100%; height: 300px;"></div>
                                                                    </div>
                                         </div>
                                        
                                        <div class="col-md-12">
                                                                    <div class="sliderdiv">
                                                                            <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    The chart displays the cumulative number of health workers trained in 
                                                                                    LARC as of each year shown in the selected geographies. LARC training 
                                                                                    includes LARC and Post Partum IUCD in-service trainings. 
                                                                                </div>
                                                                            </div>
                                                                            <div id="larcchart_div" style="width: 100%; height: 300px;"></div>
                                                                    </div>
                                        </div>
                            </div>
                                    </div>
                                        
                                        
                                    </div>
                                </div>
                                </div>
	</div>

		<div class="clear"></div>
		<div class="hrGrey"></div> 
		<div class="clear"></div>
		
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>

		<!-------   /////////////////////////// main gnr ////////////////////// -->

                
<!----------------------    Prepare the values for FP and LARC when GEO is selected -------------->
<?php
        //$this->fp_cumm_location = is_array($this->fp_cumm_location) ? $this->fp_cumm_location : array();
        //$this->larc_cumm_location = is_array($this->larc_cumm_location) ? $this->larc_cumm_location : array();
        
        if(isset($this->fp_cumm_location)){
            //echo 'if'; exit;
            reset($this->fp_cumm_location);
            $firstLocation = current($this->fp_cumm_location);  // get the location to be used as key in next stmts
            //$firstElement = $this->fp_cumm_location[$firstLocation]; //years are keys for each child element
            //var_dump($firstLocation); 
            $yearsArray = array_keys($firstLocation);
            //var_dump($yearsArray); exit;


            $legend = "[' ', ";
            foreach ($yearsArray as $year)
                $legend .= "'$year',";

            $legend = substr($legend, 0, -1) . "],";
            //echo $legend . ","; exit;

            $fp_series = ''; $larc_series = '';
            foreach($this->fp_cumm_location as $key=>$locationData) {
                $fp_series .= "['" . $key . "',";
                $larc_series .= "['" . $key . "',";
                foreach ($locationData as $year=>$data){
                    $fp_series .= $data . ",";
                    //echo 'larcyear: ' . $year . ' Key: ' . $key . '<br/>'; 
                    //echo 'lv: ' .($this->larc_cumm_location[$key][$year]['larc']);//[$year]['larc']; 
                    //exit;
                    $larc_series .= $this->larc_cumm_location[$key][$year] . ",";
                }
                $fp_series = substr($fp_series, 0, -1) . "],";
                $larc_series = substr($larc_series, 0, -1) . "],";
            }

                $fp_series = substr($fp_series, 0, -1);
                $larc_series = substr($larc_series, 0, -1);

    //            echo 'fp: ' .$fp_chartData =  $legend . $fp_series; 
    //            echo '<br/>';
    //            echo 'larc: ' . $larc_chartData =  $legend . $larc_series; 
    //            exit;

                $fp_chartData =  $legend . $fp_series; 
                $larc_chartData =  $legend . $larc_series; 

                $hAxisTitle = '2015 target number of HWs to be trained in LARC: 5500';
                $national_title = "Total HWs trained in selected geographies as of $this->tp_date";
                
        }
        else{
            //echo 'else'; exit;
            $hAxisTitle = '';
            $national_title = "Total HWs trained nationally as of $this->tp_date";
        }

  ?>
                
<script type="text/javascript">
		
  google.load('visualization', '1.0', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {

	//document.getElementById("allCharts").style.marginLeft="130px";

		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0][name] . '\''; ?>;
		 
    
        <?php if(isset($this->fp_cumm_location)) { ?>
                drawNationalChart();
                drawFPChart();
                drawLARCChart();
        <?php } else { ?>
                drawNationalComboChart();

        <?php } ?>
   
  }

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->
  //TA:17:17: Coverage HW Trained chart
  function drawNationalComboChart() {
      //alert('This is from drwChart');
      //console.log('This is from drwChart'); 
      //var trainedHw = new Array();
      
      <?php //for($i=0; $i < $this->cumm_data; $i++) {?>
              //trainedHW.push(<?php //echo $this->data[$i]['tp_fp'], $this->data[$i]['tp_larc']; ?>);
      <?php //} ?>

      
      var chartData = google.visualization.arrayToDataTable([

        [' ', 'Total FP Trained', 'Total LARC Trained', '2015 Target # HWs to be Trained in LARC'],
        //[' ', 'Total FP Trained', 'Total LARC Trained'],
        <?php
                     foreach($this->cumm_data as $key=> $value) {
                        echo "['" . $key . "', " . $value['fp'] . ", " . $value['larc'] . ", 5500],";
                     }
        ?>                                        
      ]);


              var hAxisTitle = <?php echo "'$hAxisTitle'"; ?>;
              var national_title = <?php echo "'$national_title'"; ?>;
              
              
      var chartOptions = {
                title: national_title,
                titleTextStyle: { fontSize: 16 },
                vAxis: {format: '#', minValue: 4}, 
                //seriesType: "bars",

                series: {2: {type: "line", color: 'red'}},
                chartArea: {width: '70%', left: 80}//new       
                //tooltip: {'text' : 'both', isHtml : true}
      };

            var formatter = new google.visualization.NumberFormat({ 
                                        groupingSymbol:','
                                    });
                  var formating = new google.visualization.NumberFormat({
                                        pattern:'###,###,##0'
                                    });

              formatter.format(chartData, 1);
              formatter.format(chartData, 2);
              formatter.format(chartData, 3);

              formating.format(chartData, 1);
              formating.format(chartData, 2);
              formating.format(chartData, 3);

              var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
    
      //show info icon
      google.visualization.events.addListener(chart, 'ready', function(){
             $("#chart_div").siblings('#infobutton').removeClass('hidden');
      });
     chart.draw(chartData, chartOptions);
      
      
    }
    
    
    
    function drawNationalChart() {
      //alert('This is from drwChart');
      //console.log('This is from drwChart'); 
      //var trainedHw = new Array();
      
      <?php //for($i=0; $i < $this->cumm_data; $i++) {?>
              //trainedHW.push(<?php //echo $this->data[$i]['tp_fp'], $this->data[$i]['tp_larc']; ?>);
      <?php //} ?>
      
      var chartData = google.visualization.arrayToDataTable([

        //[' ', 'Total FP Trained', 'Total LARC Trained', '2015 Target # HWs to be Trained in LARC'],
        [' ', 'Total FP Trained', 'Total LARC Trained'],
        <?php
                     foreach($this->cumm_data as $key=> $value) {
                        echo "['" . $key . "', " . $value['fp'] . ", " . $value['larc'] . "],";
                     }
        ?>                                        
      ]);

              var hAxisTitle = <?php echo "'$hAxisTitle'"; ?>;
              var national_title = <?php echo "'$national_title'"; ?>;
              
              
      var chartOptions = {
                title: national_title,
                titleTextStyle: { fontSize: 16 },
                vAxis: {format: '#', minValue: 4}, 
                //seriesType: "bars",
               bar: {groupWidth: "70%"},
                //series: {2: {type: "line", color: 'red'}},
                hAxis: {title:hAxisTitle, bold: true},
                chartArea: {width: '70%', left: 80}//new       
                //tooltip: {'text' : 'both', isHtml : true}
      };

     
         var formatter = new google.visualization.NumberFormat({ 
                                groupingSymbol:','
                    });
        var formating = new google.visualization.NumberFormat(
       {pattern:'###,###,##0'});
        formatter.format(chartData, 1);
        formatter.format(chartData, 2);

        formating.format(chartData, 1);
        formating.format(chartData, 2);

    var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
    
        //show info icon
      google.visualization.events.addListener(chart, 'ready', function(){
                $("#chart_div").siblings('#infobutton').removeClass('hidden');
      });
      
     chart.draw(chartData, chartOptions); 
 }
  
   function drawFPChart(){           
            var chartData = google.visualization.arrayToDataTable([
                                <?php echo $fp_chartData; ?>
                            ]);
      
       

      <?php echo  " var title_data = 'Number of HWs trained in FP as of $this->tp_date' " ?>;

      var chartOptions = {
                title: title_data,
                titleTextStyle: { fontSize: 16 },
                vAxis: {format: '#', minValue: 4}, 
                //seriesType: "bars",
                //series: {2: {type: "line", color: 'red'}},
                 bar: {groupWidth: "70%"},
                chartArea: {width: '70%', left: 80}//new       
                //tooltip: {'text' : 'both', isHtml : true}
      };

     
        var formatter = new google.visualization.NumberFormat(
            { groupingSymbol:','});
  
  
        formatter.format(chartData, 1);
        formatter.format(chartData, 2);
        formatter.format(chartData, 3);

        var formating = new google.visualization.NumberFormat(
          {pattern:'###,###,##0'});
        formating.format(chartData, 1);
        formating.format(chartData, 2);
        formating.format(chartData, 3);

        var chart = new google.visualization.ColumnChart(document.getElementById('fpchart_div'));
        
        //show info icon
        google.visualization.events.addListener(chart, 'ready', function(){
                   $("#fpchart_div").siblings('#infobutton').removeClass('hidden');
        });
      
        chart.draw(chartData, chartOptions);
}
  
  function  drawLARCChart(){
      var chartData = google.visualization.arrayToDataTable([
                                <?php echo $larc_chartData; ?>
                        ]);

      <?php echo  " var title_data = 'Number of HWs trained in LARC as of $this->tp_date' " ?>;

      var chartOptions = {
                title: title_data,
                titleTextStyle: { fontSize: 16 },
                vAxis: {format: '#', minValue: 4}, 
                //seriesType: "bars",
                //series: {2: {type: "line", color: 'red'}},
                 bar: {groupWidth: "70%"},
                chartArea: {width: '70%', left: 80}//new       
                //tooltip: {'text' : 'both', isHtml : true}
      };

     
      var formatter = new google.visualization.NumberFormat(
                                { groupingSymbol:','}
                           );
                   
      formatter.format(chartData, 1);
      formatter.format(chartData, 2);
      formatter.format(chartData, 3);


      var formating = new google.visualization.NumberFormat({
                                pattern:'###,###,##0'
                            });
      formating.format(chartData, 1);
      formating.format(chartData, 2);
      formating.format(chartData, 3);
      
      var chart = new google.visualization.ColumnChart(document.getElementById('larcchart_div'));
      
      //show info icon
        google.visualization.events.addListener(chart, 'ready', function(){
                   $("#larcchart_div").siblings('#infobutton').removeClass('hidden');
        });
        
     chart.draw(chartData, chartOptions);
  }

</script>


<script>
  //devsite.github.Link.convertAnchors();
  //window.prettyPrint();
</script>	

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>

