<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

</style>

<!--<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">-->

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />
<!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
<!--<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />-->
<!--<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css">-->

    
<style>

    .infobutton {
        padding-right: 13px !important;
        padding-bottom : 6px;
    }
    
    
</style>
    
    
<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" defer async></script>
<!--<script src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>-->
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>-->

<script>
  $(function() {
    $( "#accordion" ).accordion({header: "h3", collapsible: true,active: 0});
    
     //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  </script>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>



			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			<div class="nav-buttons">
				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    require_once('views/scripts/dashboard/left_buttons.phtml');
                                ?>
				
			</div>
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->


			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">
				<div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
                                                                    <div class="sliderdiv" style="margin-left: 20px;">
                                                                        <div id="infobutton" class="infobutton hidden">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                            <div id="" class="infodiv" >
                                                                                This chart shows the percentage of facilities reporting in the most recent 
                                                                                month or selected date(s) that have at least one health worker trained in FP and provided at 
                                                                                least one FP commodity. This chart illustrates the percentage of 
                                                                                facilities that should be providing FP that are actually providing the 
                                                                                service. 
                                                                            </div>
                                                                        </div>
									<div id="chart11_div" style="width: 600px; height: 350px;"></div>
								</div>
                                                                    
									<div class="main-search" style="margin-left: 20px; margin-top: 50px;">
                                                                            <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    This chart shows the percentage of facilities reporting in the most recent 
                                                                                    month or selected date(s) that have at least one health worker trained in LARC and provided at 
                                                                                    least one implant or IUCD. This chart illustrates the percentage of 
                                                                                    facilities that should be providing LARC that are actually providing the 
                                                                                    service. 
                                                                                </div>
                                                                            </div>
                                                                            <div id="chart12_div" style="width: 600px; height: 350px;"></div>
									</div>
								</div>
							</div>
						</div>			
					</div>

				<div class="clear"></div>
				<div class="hrGrey"></div>
				<div class="clear"></div>

				

								<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
<!--								
					<div id="bottomrow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
									<div id="chart13_div" style="width: 800px; height: 300px;"></div>
									</div>
									<div class="main-search">
										<div id="chart14_div" style="width: 500px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>
								
								-----   /////////////////////////// chart 2,2 ////////////////////// 
								
								
								<div class="main-search"></div>

					</div>-->
				</div>
		
	</div>

		<div class="clear"></div>
		<div class="hrGrey"></div>
		<div class="clear"></div>
		
		<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->

		<!-------   /////////////////////////// main gnr ////////////////////// -->

		<script type="text/javascript">
		
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);

  $(function() {
	  document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	drawChart12();
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;
		 
  });

  
  function drawChart11() {
       var FPData = <?= $this->fp_data; ?>;
       var locations = new Array(); var values = new Array();
       
       for(key in FPData){
            row = FPData[key];
            locations.push(row['location']);
            
            if(key == 0)
                values.push({y: row['percent'], color: '#000000'}); 
            else 
                values.push(row['percent']);
       }
            
        var titleText = '<?php //echo  "Percent of facilities with an FP-trained HW providing FP, $this->date"; ?>';
        var subtitleText = '(<?php echo  $this->date; ?>)';
        
		                                                     	  

	  $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 350
                },
                title: {
                    text: titleText,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                     title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: locations
                },
                yAxis: {
                    title: {
                       text: '%  Facilities',
                       style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        var location = this.x;
                        index = -1;
                        for(key in FPData){
                            if(FPData[key]['location'].toUpperCase() === location.toUpperCase()){
                                index = key;
                                break;
                            }   
                        }
                        
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/>' + 
                                '<b>Numerator</b>:' + thousandSeparator(FPData[index]['numer'])+'<br/>' +
                                '<b>Denominator</b>:'+thousandSeparator(FPData[index]['denom']);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: values
                }]
            });
              
              
    }

 function drawChart12() {
       var LARCData = <?= $this->fp_data; ?>;
       var locations = new Array(); var values = new Array();
       
       for(key in LARCData){
            row = LARCData[key];
            locations.push(row['location']);
            
            if(key == 0)
                values.push({y: row['percent'], color: '#000000'}); 
            else 
                values.push(row['percent']);
       }

          var titleText = '<?php echo  "Percent of FP facilities with an FP-trained HW providing LARC, $this->date"; ?>';
          var subtitleText = '(<?php echo  $this->date; ?>)';
	  
          $('#chart12_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart12_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 350
                },
                title: {
                    text: titleText,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                     title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: locations
                },
                yAxis: {
                    title: {
                        text: '%  Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        var location = this.x;
                        index = -1;
                        for(key in LARCData){
                            if(LARCData[key]['location'].toUpperCase() === location.toUpperCase()){
                                index = key;
                                break;
                            }   
                        }
                        
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/>' + 
                                '<b>Numerator</b>:' + thousandSeparator(LARCData[index]['numer'])+'<br/>' +
                                '<b>Denominator</b>:'+thousandSeparator(LARCData[index]['denom']);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: values
                }]
            });
    }

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
<script src="../js/tp/functions.js"></script>


</body>

</html>