
     <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'coverage';
                                        $variable = 'Simple';        
                                        require_once('views/scripts/template/template.phtml');
                                       
                                    ?>
                                    
                                    
                                    
                                    
                                     <div class="row">
                                         
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                        <?php  
                                                   require_once('views/scripts/dashboard/top_buttons.phtml'); 
                                                ?>
				
                                           </div>
                                    
                                           <div  class="col-sm-7 pull-right box-shadow clearfix"  style=""  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                               
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                               
                                                                                <div id="infobutton" class="infobutton">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                            <div id="" class="infodiv" >
                                                                                This chart shows the percentage of facilities reporting in the most recent 
                                                                                month that have at least one health worker trained in FP and provided at 
                                                                                least one FP commodity. This chart illustrates the percentage of 
                                                                                facilities that should be providing FP that are actually providing the 
                                                                                service.
                                                                            </div>
                                                                        </div>
                                                                             </div>  
                                                                </div>   
                                             
                                                     
									           <div id="chart11_div" style="width:100%; "></div>
                                         
				                           </div>                           
                                    </div>
                                    
                                    <div  class="row" style="margin-top:50px;margin-bottom:45px;">
                                         
                                           <div class="col-sm-7 box-shadow" style=""  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                 
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                                <div id="infobutton" class="infobutton">
                                                                                   <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                   <div id="" class="infodiv" >
                                                                                        This chart shows the percentage of facilities reporting in the most recent 
                                                                                        month that have at least one health worker trained in LARC and provided at 
                                                                                        least one implant or IUCD. This chart illustrates the percentage of 
                                                                                        facilities that should be providing LARC that are actually providing the 
                                                                                        service.  
                                                                                   </div>
                                                                                 </div>
                                                                             
                                                                               </div>   
	
				
                                           </div>
                                               
                                               <div id="chart12_div" style="width:100%; "></div>
                                               
                                           
                                               
                                           </div>
                                    </div>
                                    
                                
                                   
                                     
                                
                                   
                                </div>

		
		<div class="clear"></div>
                </div>
            
          
            
           
            
          
           
           </div><!-- content -->
           <br/><br/><br/>

		<script type="text/javascript">
		
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);

  $(function() {
	//  document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	drawChart12();
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;
		 
  });

  function drawChart11() {
       var FPData = <?= $this->fp_data; ?>;
       var locations = new Array(); var values = new Array();
       
       for(key in FPData){
            row = FPData[key];
            locations.push(row['location']);
            
            if(key == 0)
                values.push({y: row['percent'], color: '#000000'}); 
            else 
                values.push(row['percent']);
       }
            
        <?php if($this->freshVisit) { ?>
            var titleText = '<?php echo  "Percent of facilities with an FP-trained HW providing FP as of $this->date"; ?>';
        <?php } else { ?>
            var titleText = '<?php echo  "Percent of facilities with an FP-trained HW providing FP <br/>in selected geographies as of $this->date"; ?>';
        <?php } ?>
		                                                     	  

	  $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                },
                title: {
                    text: titleText,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                     title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: locations
                },
                yAxis: {
                    title: {
                       text: '% Facilities',
                       style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        var location = this.x;
                        index = -1;
                        for(key in FPData){
                            if(FPData[key]['location'].toUpperCase() === location.toUpperCase()){
                                index = key;
                                break;
                            }   
                        }
                        
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/>' + 
                                '<b>Numerator</b>:' + thousandSeparator(FPData[index]['numer'])+'<br/>' +
                                '<b>Denominator</b>:'+thousandSeparator(FPData[index]['denom']);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: values
                }]
            });
              
              
    }

 function drawChart12() {
       var LARCData = <?= $this->larc_data; ?>;
       var locations = new Array(); var values = new Array();
       
       for(key in LARCData){
            row = LARCData[key];
            locations.push(row['location']);
            
            if(key == 0)
                values.push({y: row['percent'], color: '#000000'}); 
            else 
                values.push(row['percent']);
       }

          <?php if($this->freshVisit) { ?>
            var titleText = '<?php echo  "Percent of facilities with an FP-trained HW providing LARC as of $this->date"; ?>';
        <?php } else { ?>
            var titleText = '<?php echo  "Percent of facilities with an FP-trained HW providing LARC <br/>in selected geographies as of $this->date"; ?>';
        <?php } ?>
	  
          $('#chart12_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart12_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                },
                title: {
                    text: titleText,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                     title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: locations
                },
                yAxis: {
                    title: {
                        text: '% Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        var location = this.x;
                        index = -1;
                        for(key in LARCData){
                            if(LARCData[key]['location'].toUpperCase() === location.toUpperCase()){
                                index = key;
                                break;
                            }   
                        }
                        
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/>' + 
                                '<b>Numerator</b>:' + thousandSeparator(LARCData[index]['numer'])+'<br/>' +
                                '<b>Denominator</b>:'+thousandSeparator(LARCData[index]['denom']);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: values
                }]
            });
    }

</script>
	

<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


</body>

</html>