<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

@media (max-width: 992px) {
    #topB {
      float: none !important;
    }
}
</style>

<!--<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">-->

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
    <!--<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />-->
<!--<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css">-->
    
    
<style>

    .infobutton {
        padding-right: 13px !important;
        padding-bottom : 6px;
    }

</style>    
    

<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" defer async></script>

<!--<script src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>-->
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />
<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css"></link>

<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>-->

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></link>
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="../bootstrap/js/bootstrap.min.js"></script>


<script>
    
  $(function() {
    $( "#accordion" ).accordion({header: "h3", collapsible: true,active: 0});
    
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
    
  });
  
  $(document).ready(function(){
       $( "#tabs" ).tabs({
        activate: function( event, ui ) {
            var selectedTab = $("#tabs").tabs('option', 'active');
            if(selectedTab == 1){
                //redrawChart(chart11Options, chart11Data, chart11Div); 
                $("#chart15_div").highcharts().reflow();
            }
        }
      });
//      
//      $('.infobutton').click(function(){
//        console.log("inside click");
//      });
  });
  
  $(document).ready(function() {
    $('#collapseOne').collapse('show');
});


  </script>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>


<div class="row sidebar" style="margin-top: 30px;">
			<!-------   /////////////////////////// make top buttons ////////////////////// -->
                        
<!--			<div class="row rightdiv " style="float: right;">
                            <div class="col-md-1" style="margin-top: 10px;" >
				<?php // require_once('views/scripts/dashboard/top_buttons.phtml');?>
                        </div>	
			</div>-->

			<!-------   /////////////////////////// make left buttons ////////////////////// -->

                                <div class="col-md-2">
			
				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    require_once('views/scripts/dashboard/left_buttonshome.phtml');
                                ?>
			</div>
                        <div class="col-md-4 pull-right" id="topB" >
                            <?php  require_once('views/scripts/dashboard/top_buttons.phtml');?>
                        </div>
			 <div class="col-md-6" style="margin-top: 10px;" >
			<!-------   /////////////////////////// load scripts ////////////////////// -->
           

			<!-------   /////////////////////////// charts ////////////////////// -->


		
                       

				
							<div class="row">
								<div class="col-md-12">
								
                                                                                <div id="infobutton" class="infobutton hidden">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                        The percentage of  facilities providing FP shows the proportion of facilities
                                                                                        reporting in the most recent month that provided any FP commodities in that 
                                                                                        month. It may be higher than the percentage of facilities with an FP trained 
                                                                                        health worker because some health workers may have learned to provide FP in 
                                                                                        their pre-service training, on the job, and/or were not reported as having 
                                                                                        received in-service training for other reasons.
                                                                                    </div>
                                                                                </div>
									<div id="chart11_div" style="width: 100%; height: 350px;"></div>
									
                                                                </div>
                                                                    
                                                            
                                                            <div class="col-md-12">
								
                                                                                <div id="infobutton" class="infobutton hidden">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                         The percentage of  facilities providing FP shows the proportion of facilities
                                                                                        reporting in the most recent month that provided any FP commodities in that 
                                                                                        month. It may be higher than the percentage of facilities with an FP trained 
                                                                                        health worker because some health workers may have learned to provide FP in 
                                                                                        their pre-service training, on the job, and/or were not reported as having 
                                                                                        received in-service training for other reasons.
                                                                                    </div>
                                                                                </div>
									<div id="chart15_div" style="width: 100%; height: 350px;"></div>
                                                                          
									
                                                                </div>
                                                                    
                                                                     
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                        <div class="col-md-12" >
                                                                                <div id="infobutton" class="infobutton hidden">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                        The percentage of  facilities providing LARC shows the proportion of facilities 
                                                                                        reporting in the most recent month that provided implants and/or IUDs in 
                                                                                        that month. It may be higher than the percentage of facilities with a LARC 
                                                                                        trained health worker because some health workers may have learned to 
                                                                                        provide LARC in their pre-service training, on the job, and/or were not 
                                                                                        reported as having received in-service training for other reasons.
                                                                                    </div>
                                                                                </div>
										<div id="chart12_div" style="width: 100%; height: 350px;"></div>
									</div>
								
							
								<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
					
						
								<div  class="col-md-12">
                                                                    
                                                                        <div id="infobutton" class="infobutton hidden">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                            <div id="" class="infodiv" >
                                                                                The percentage of  facilities providing injectables shows the proportion of 
                                                                                facilities reporting in the most recent month that provided injectables in 
                                                                                that month.
                                                                            </div>
                                                                        </div>
									<div id="chart13_div" style="width:100%; height: 350px; "></div>
									
									
								</div>
                                                        </div>
							<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
								
					
				</div>
		
	</div>
</div>
	
		
		<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->

		<!-------   /////////////////////////// main  ////////////////////// -->

                
                
                
                
             
		<script type="text/javascript">
		
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);

  $(function() {
	//document.getElementById("allCharts").style.marginLeft="130px";
	drawChart11();
	drawChart12();
	drawChart13();
        drawChart14('allfacs');
        drawChart14('fpfacs');
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;
		 
  });

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->

//TA:17:18 Coverage Fac Providing FP chart
  function drawChart11() {
       var jNumData = new Array();
       var jDenomData = new Array();
       
    <?php
        reset($this->fp_data); 
        $firstKey = key($this->fp_data); 
        $locationsString = ""; $valuesString = "";
	foreach ($this->fp_data as $key=>$row){ 
            $locationsString .= "'" . $row['location'] . "',";
            $location = $row['location'];
            
            $numerator = $this->fp_numerator[''.$location.''];
            $denominator = $this->fp_denominator[''.$location.''];
                    
            if($firstKey == $key)
                $valuesString .= "{y:" . round($row['percent']*100, 1) . ", color: '#000000'},"; 
            else
                $valuesString .= round($row['percent']*100, 1) . ",";  
            
            
             ?>
                   jNumData['<?php echo $row['location']; ?>']  = <?php echo $numerator; ?> ; 
                   jDenomData['<?php echo $row['location']; ?>']  = <?php echo $denominator; ?> ; 
        <?php
	}
        
        $locationsString = substr($locationsString, 0 , -1);
        $valuesString = substr($valuesString, 0 , -1);
    ?>
        
        var titleText = '<?php echo  "Percent of facilities providing at least 1 modern method as of $this->date"; ?>';
        var subtitleText = '(<?php echo  "as of $this->date"; ?>)';

	  <?php //echo  " var title_data = 'Percent of facilities providing FP, $this->date ' " ?>;
        $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 350
                },
                title: {
                    text: titleText,
                    x: -40,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                     title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: [<?php echo $locationsString; ?>]
                },
                yAxis: {
                    title: {
                        text: 'Percent Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.x]);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: [<?php echo $valuesString; ?>]
                }]
            });
         
    }
    
  //  TA:17:18 Coverage Fac Providing at least 3 commodities in
  /**
  * mode is allfacs or fpfacs. 
  * Selects the denominator we are working with
  */
  function drawChart14(mode) {
  
       var modernMethodsDataAll = <?php echo json_encode($this->modern_method_data); ?>;
       var modernMethodsData = modernMethodsDataAll[mode]; //select the mode
       
       //console.log(modernMethodsData);
   
        var locationsArray = []; var valuesArray = [];
        for(var location in modernMethodsData){ //var keyword important. A global with name location exists
            locationsArray.push(location);
            
            if(location === "National"){
                valuesArray.push({y:modernMethodsData[location]['percent'], color: '#000000'}); 
            }
            else{
                valuesArray.push(modernMethodsData[location]['percent']);
            }
        }
        
        var titleText = "Percent of FP facilities providing at least 3 modern methods as of " + '<?= $this->date; ?>';
        var subtitleText = "as of " + '<?= $this->date; ?>';
        divId = mode == 'allfacs' ? 'chart14_div' : 'chart15_div';
        
        $('#'+divId).highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#"+divId).siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 350
                },
                title: {
                    text: titleText,
                    x: -40,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                     title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: locationsArray
                },
                yAxis: {
                    title: {
                        text: 'Percent Facilities',
                        style: { "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + 
                                this.y + '%<br/>' +
                                '<b>Numerator</b>:' + thousandSeparator(modernMethodsData[this.x]['num']) +
                                '<br/><b>Denominator</b>:'+thousandSeparator(modernMethodsData[this.x]['denom']);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: valuesArray
                }]
            });
         
    }

//TA:17:18 Coverage Fac Providing LARC chart
 function drawChart12() {
 
       var jNumData = new Array();
       var jDenomData = new Array();
	                                                           
    <?php
        reset($this->larc_data); 
        $firstKey = key($this->larc_data); 
        $locationsString = ""; $valuesString = "";
	foreach ($this->larc_data as $key=>$row){ 
            $locationsString .= "'" . $row['location'] . "',";
            $location = $row['location'];
            
            $numerator = $this->larc_numerator[''.$location.''];
            $denominator = $this->larc_denominator[''.$location.''];
            
            if($firstKey == $key)
                $valuesString .= "{y:" . round($row['percent']*100, 1) . ", color: '#000000'},"; 
            else
                $valuesString .= round($row['percent']*100, 1) . ",";  
            
             ?>
                   jNumData['<?php echo $row['location']; ?>']  = <?php echo $numerator; ?> ; 
                   jDenomData['<?php echo $row['location']; ?>']  = <?php echo $denominator; ?> ; 
          <?php
            
        }
        
        $locationsString = substr($locationsString, 0 , -1);
        $valuesString = substr($valuesString, 0 , -1);
    ?>
        
        var titleText = '<?php echo  "Percent of FP facilities providing LARC as of $this->date"; ?>';
        var subtitleText = '(<?php echo  "as of $this->date"; ?>)';
        
	 $('#chart12_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart12_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 350
                },
                title: {
                    text: titleText,
                    x: -40,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                     title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: [<?php echo $locationsString; ?>]
                },
                yAxis: {
                    title: {
                        text: 'Percent Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.x]);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: [<?php echo $valuesString; ?>]
                }]
            });
      
 }

 function drawChart13() {
 
       var jNumData = new Array();
       var jDenomData = new Array();

    <?php
            reset($this->inj_data); 
            $firstKey = key($this->inj_data); 
            $locationsString = ""; $valuesString = "";
            foreach ($this->inj_data as $key=>$row){
                $locationsString .= "'" . $row['location'] . "',";
                $location = $row['location'];
                $numerator = $this->inj_numerator[''.$location.''];
                $denominator = $this->inj_denominator[''.$location.''];
                if($firstKey == $key)
                    $valuesString .= "{y:" . round($row['percent']*100, 1) . ", color: '#000000'},"; 
                else
                    $valuesString .= round($row['percent']*100, 1) . ",";  
                
                 
                     ?>
                   jNumData['<?php echo $row['location']; ?>']  = <?php echo $numerator; ?> ; 
                   jDenomData['<?php echo $row['location']; ?>']  = <?php echo $denominator; ?> ; 
                            <?php
            }
            
            $locationsString = substr($locationsString, 0 , -1);
            $valuesString = substr($valuesString, 0 , -1);
    ?>
	  
            var titleText = '<?php echo  "Percent of FP facilities providing injectables as of $this->date"; ?>';
            var subtitleText = '(<?php echo  "as of $this->date"; ?>)';
        
          $('#chart13_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 350
                },
                title: {
                    text: titleText,
                    x: -40,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                     title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: [<?php echo $locationsString; ?>]
                },
                yAxis: {
                    title: {
                       text: 'Percent Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.x]);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: [<?php echo $valuesString; ?>]
                }]
            });
 }

</script>


<script>
//  devsite.github.Link.convertAnchors();
//  window.prettyPrint();
</script>	

<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>
    
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
<script src="../js/tp/functions.js"></script>


</body>

</html>

