   <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'coverage';
                                        $variable = 'Simple';        
                                        require_once('views/scripts/template/template.phtml');
                                       
                                    ?>

                                     <div class="row">
                                         
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                      <?php require_once('views/scripts/dashboard/top_buttons.phtml');?>
				
                                           </div>
                                    
                                           <div  class="col-sm-7 pull-right box-shadow clearfix"  style="height:500px;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                              Percent of facilities providing at least 1 modern method as of <?php echo $this->date; ?>
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                                  <div id="infobutton" class="infobutton hidden">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                        The percentage of  facilities providing FP shows the proportion of facilities
                                                                                        reporting in the most recent month that provided any FP commodities in that 
                                                                                        month. It may be higher than the percentage of facilities with an FP trained 
                                                                                        health worker because some health workers may have learned to provide FP in 
                                                                                        their pre-service training, on the job, and/or were not reported as having 
                                                                                        received in-service training for other reasons.
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                             
                                                                          </div>   
                                             
                                               <div id="chart11_div" style="width:100%; height: 300px;"></div>
                                         
				                           </div>                           
                                    </div>
                                    
                                    <div class="row" style="margin-top:20px;padding-bottom:0px;">
                                         
                                           <div class="col-sm-7 box-shadow" style="height:500px;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                Percent of facilities providing LARC as of <?php echo $this->date; ?>
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                                  <div id="infobutton" class="infobutton hidden">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                        The percentage of  facilities providing LARC shows the proportion of facilities 
                                                                                        reporting in the most recent month that provided implants and/or IUDs in 
                                                                                        that month. It may be higher than the percentage of facilities with a LARC 
                                                                                        trained health worker because some health workers may have learned to 
                                                                                        provide LARC in their pre-service training, on the job, and/or were not 
                                                                                        reported as having received in-service training for other reasons.
                                                                                    </div>
                                                                                </div>
                                                                             
                                                                          </div>   
                                                   
                                              <div id="chart12_div" style="width:100%; height: 300px;"></div>
	
			      
				
                                           </div>
                                               
                                           <div class=" col-sm-6"  >
                                               
                                           </div>
                                               
                                           </div>
                                    </div>
                                    
                                     <div class="row" style="margin-top:20px;padding-bottom:0px;">
                                         
                                           <div class="col-sm-7 box-shadow" style="height:500px;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                              <?php echo  "Percent of facilities providing injectables as of $this->date"; ?>
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                                   <div id="infobutton" class="infobutton hidden">
                                                                                      <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                      <div id="" class="infodiv" >
                                                                                         The percentage of  facilities providing injectables shows the proportion of 
                                                                                         facilities reporting in the most recent month that provided injectables in 
                                                                                         that month.
                                                                                     </div>
                                                                                  </div>
                                                                             
                                                                            </div>   
                                                   
                                              <div id="chart13_div" style="width:100%; height: 300px;"></div>
	
			      
				
                                           </div>
                                               
                                           <div class=" col-sm-6"  >
                                               
                                           </div>
                                               
                                           </div>
                                    </div>
                                    
                                    <div class="row" style="margin-top:20px;padding-bottom:0px;">
                                         
                                           <div class="col-sm-7 box-shadow" style="height:500px;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                Percent of facilities providing at least 3 modern methods as of <?= $this->date; ?>
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                                <div id="infobutton" class="infobutton">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                        The percentage of  facilities providing injectables shows the proportion of 
                                                                                        facilities reporting in the most recent month that provided injectables in 
                                                                                        that month.
                                                                                    </div>
                                                                                </div>
                                                                             
                                                                            </div>   
                                                   
                                              <div id="chart14_div" style="width:100%; height: 300px;"></div>
	
			      
				
                                           </div>
                                               
                                           <div class=" col-sm-6"  >
                                               
                                           </div>
                                               
                                           </div>
                                    </div>
                                    
                                                                         

                                   
                                </div>

		
		<div class="clear"></div>
                </div>
            
          
            
           
            
          
           
           </div><!-- content -->
           <br/><br/><br/>
 

		<script type="text/javascript">
		
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);

  $(function() {
	//document.getElementById("allCharts").style.marginLeft="130px";
	drawChart11();
	drawChart12();
	drawChart13();
        drawChart14('allfacs');
        drawChart14('fpfacs');
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;
		 
  });

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->

//TA:17:18 Coverage Fac Providing FP chart
  function drawChart11() {
       var jNumData = new Array();
       var jDenomData = new Array();
       
    <?php
        reset($this->fp_data); 
        $firstKey = key($this->fp_data); 
        $locationsString = ""; $valuesString = "";
	foreach ($this->fp_data as $key=>$row){ 
            $locationsString .= "'" . $row['location'] . "',";
            $location = $row['location'];
            
            $numerator = $this->fp_numerator[''.$location.''];
            $denominator = $this->fp_denominator[''.$location.''];
                    
            if($firstKey == $key)
                $valuesString .= "{y:" . round($row['percent']*100, 1) . ", color: '#000000'},"; 
            else
                $valuesString .= round($row['percent']*100, 1) . ",";  
            
            
             ?>
                   jNumData['<?php echo $row['location']; ?>']  = <?php echo $numerator; ?> ; 
                   jDenomData['<?php echo $row['location']; ?>']  = <?php echo $denominator; ?> ; 
        <?php
	}
        
        $locationsString = substr($locationsString, 0 , -1);
        $valuesString = substr($valuesString, 0 , -1);
    ?>
        
        var titleText = '<?php // echo  "Percent of facilities providing at least 1 modern method as of $this->date"; ?>';
        var subtitleText = '(<?php echo  "as of $this->date"; ?>)';

	  <?php //echo  " var title_data = 'Percent of facilities providing FP, $this->date ' " ?>;
        $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 350
                },
                title: {
                    text: titleText,
                    x: -40,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                     title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: [<?php echo $locationsString; ?>]
                },
                yAxis: {
                    title: {
                        text: 'Percent Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.x]);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: [<?php echo $valuesString; ?>]
                }]
            });
         
    }
    
  //  TA:17:18 Coverage Fac Providing at least 3 commodities in
  /**
  * mode is allfacs or fpfacs. 
  * Selects the denominator we are working with
  */
  function drawChart14(mode) {
  
       var modernMethodsDataAll = <?php echo json_encode($this->modern_method_data); ?>;
       var modernMethodsData = modernMethodsDataAll[mode]; //select the mode
       
       //console.log(modernMethodsData);
   
        var locationsArray = []; var valuesArray = [];
        for(var location in modernMethodsData){ //var keyword important. A global with name location exists
            locationsArray.push(location);
            
            if(location === "National"){
                valuesArray.push({y:modernMethodsData[location]['percent'], color: '#000000'}); 
            }
            else{
                valuesArray.push(modernMethodsData[location]['percent']);
            }
        }
        
        var titleText = "";
        var subtitleText = "as of " + '<?= $this->date; ?>';
        divId = mode == 'allfacs' ? 'chart14_div' : 'chart15_div';
        
        $('#'+divId).highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 350
                },
                title: {
                    text: titleText,
                    x: -40,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                     title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: locationsArray
                },
                yAxis: {
                    title: {
                        text: 'Percent Facilities',
                        style: { "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + 
                                this.y + '%<br/>' +
                                '<b>Numerator</b>:' + thousandSeparator(modernMethodsData[this.x]['num']) +
                                '<br/><b>Denominator</b>:'+thousandSeparator(modernMethodsData[this.x]['denom']);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: valuesArray
                }]
            });
         
    }

//TA:17:18 Coverage Fac Providing LARC chart
 function drawChart12() {
 
       var jNumData = new Array();
       var jDenomData = new Array();
	                                                           
    <?php
        reset($this->larc_data); 
        $firstKey = key($this->larc_data); 
        $locationsString = ""; $valuesString = "";
	foreach ($this->larc_data as $key=>$row){ 
            $locationsString .= "'" . $row['location'] . "',";
            $location = $row['location'];
            
            $numerator = $this->larc_numerator[''.$location.''];
            $denominator = $this->larc_denominator[''.$location.''];
            
            if($firstKey == $key)
                $valuesString .= "{y:" . round($row['percent']*100, 1) . ", color: '#000000'},"; 
            else
                $valuesString .= round($row['percent']*100, 1) . ",";  
            
             ?>
                   jNumData['<?php echo $row['location']; ?>']  = <?php echo $numerator; ?> ; 
                   jDenomData['<?php echo $row['location']; ?>']  = <?php echo $denominator; ?> ; 
          <?php
            
        }
        
        $locationsString = substr($locationsString, 0 , -1);
        $valuesString = substr($valuesString, 0 , -1);
    ?>
        
        var titleText = '<?php // echo  "Percent of facilities providing LARC as of $this->date"; ?>';
        var subtitleText = '(<?php echo  "as of $this->date"; ?>)';
        
	 $('#chart12_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart12_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 350
                },
                title: {
                    text: titleText,
                    x: -40,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                     title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: [<?php echo $locationsString; ?>]
                },
                yAxis: {
                    title: {
                        text: 'Percent Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.x]);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: [<?php echo $valuesString; ?>]
                }]
            });
      
 }

 function drawChart13() {
 
       var jNumData = new Array();
       var jDenomData = new Array();

    <?php
            reset($this->inj_data); 
            $firstKey = key($this->inj_data); 
            $locationsString = ""; $valuesString = "";
            foreach ($this->inj_data as $key=>$row){
                $locationsString .= "'" . $row['location'] . "',";
                $location = $row['location'];
                $numerator = $this->inj_numerator[''.$location.''];
                $denominator = $this->inj_denominator[''.$location.''];
                if($firstKey == $key)
                    $valuesString .= "{y:" . round($row['percent']*100, 1) . ", color: '#000000'},"; 
                else
                    $valuesString .= round($row['percent']*100, 1) . ",";  
                
                 
                     ?>
                   jNumData['<?php echo $row['location']; ?>']  = <?php echo $numerator; ?> ; 
                   jDenomData['<?php echo $row['location']; ?>']  = <?php echo $denominator; ?> ; 
                            <?php
            }
            
            $locationsString = substr($locationsString, 0 , -1);
            $valuesString = substr($valuesString, 0 , -1);
    ?>
	  
            var titleText = '';
            var subtitleText = '(<?php echo  "as of $this->date"; ?>)';
        
          $('#chart13_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 350
                },
                title: {
                    text: titleText,
                    x: -40,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                     title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: [<?php echo $locationsString; ?>]
                },
                yAxis: {
                    title: {
                       text: 'Percent Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.x])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.x]);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: [<?php echo $valuesString; ?>]
                }]
            });
 }

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>
    
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
<script src="../js/tp/functions.js"></script>


</body>

</html>



<?php


?>

