   <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'coverage';
                                        $variable = 'Simple';        
                                        require_once('views/scripts/template/template.phtml');
                                       
                                    ?>
                                   
                                     <div class="row">
                                         
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                      <?php require_once('views/scripts/dashboard/top_buttons.phtml');?>
				
                                           </div>
                                    
                                           <div  class="col-sm-7 pull-right box-shadow clearfix"  style="height:auto;" >
                                               
                                               
                                                          <?php
                                                                       $chart_title = "";
                                                                       
                                                                       $info_text = "The percentage of all facilities with at least one health worker trained in FP demonstrates the current coverage of FP-trained health workers and the gaps in coverage. FP training includes Contraceptive Technology Update,  FP Technology, Injectable Contraceptives for CHEWs, LARC, and Post Partum IUCD in-service
      trainings. <br/><br/>  
                                                                                    Health workers who learned to provide FP through pre-service training, on-the-job 
                                                                                    training, or  other means may not be reflected here, though may indeed be competent and 
                                                                                    actively providing the service.";

                                                                       
                       
                                    
                                                                        include('views/scripts/template/chart_title.phtml');
                                                            
                                                           ?>
                                             
                                               <div id="chart11_div" style="width:100%; height:auto;"></div>
                                         
				                           </div>                           
                                    </div>
                                    
                                    <div  class="row" style="margin-top:50px;padding-bottom:45px;">
                                         
                                           <div class="col-sm-7 box-shadow" style="height:auto;"  >
                                               
                                                       <?php
                                                                       $chart_title = "";
                                                                       
                                                                       $info_text = "The percentage of all facilities with at least one health worker trained in FP demonstrates the current coverage of FP-trained health workers and the gaps in coverage. FP training includes Contraceptive Technology Update,  FP Technology, Injectable Contraceptives for CHEWs, LARC, and Post Partum IUCD in-service
      trainings. <br/><br/>  
                                                                                    Health workers who learned to provide FP through pre-service training, on-the-job 
                                                                                    training, or  other means may not be reflected here, though may indeed be competent and 
                                                                                    actively providing the service.";

                                                                       
                       
                                    
                                                                        include('views/scripts/template/chart_title.phtml');
                                                            
                                                           ?>
                                               
                                            <div id="chart12_div" style="width:100%; height:auto;"></div>
	
			      
                                               
                                           </div>
                                    </div>
                                   
                                </div>

		
		<div class="clear"></div>
                </div>
            
          
            
           
            
          
           
           </div><!-- content -->
           <br/><br/><br/>


		<script type="text/javascript">
		
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);

  $(function() {
	//  document.getElementById("allCharts").style.marginLeft="130px";
          
        
	drawChart11();
	drawChart12();
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;	 
    });
    
    function drawChart11() {               
       var FPData = <?= $this->fp_data; ?>;
       var locations = new Array(); var values = new Array();
       
       for(key in FPData){
            row = FPData[key];
            locations.push(row['location']);
            
            if(key == 0)
                values.push({y: row['percent'], color: '#000000'}); 
            else 
                values.push(row['percent']);
       }
            
        <?php if(!$this->freshVisit) { ?>
            var titleText = '<?php echo  "Percent of facilities with an FP-trained HW as of $this->date"; ?>';
        <?php } else { ?>
            var titleText = '<?php echo  "Percent of facilities with an FP-trained HW in selected geographies <br/>as of $this->date"; ?>';
        <?php } ?>
        
        $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                },
                title: {
                    text: titleText,
                    x: -40,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                    title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: locations
                },
                yAxis: {
                    title: {
                        text: '% Facilities',
                        style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        var location = this.x;
                        index = -1;
                        for(key in FPData){
                            if(FPData[key]['location'].toUpperCase() === location.toUpperCase()){
                                index = key;
                                break;
                            }   
                        }
                        
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/>' + 
                                '<b>Numerator</b>:' + thousandSeparator(FPData[index]['numer'])+'<br/>' +
                                '<b>Denominator</b>:'+thousandSeparator(FPData[index]['denom']);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: values
                }]
            });
    }
    
    
    function drawChart12() {               
       var LARCData = <?= $this->larc_data; ?>;
       var locations = new Array(); var values = new Array();
       
       for(key in LARCData){
            row = LARCData[key];
            locations.push(row['location']);
            
            if(key == 0)
                values.push({y: row['percent'], color: '#000000'}); 
            else 
                values.push(row['percent']);
       }
       
        <?php if(!$this->freshVisit) { ?>
            var titleText = '<?php echo  "Percent of facilities with a LARC-trained HW as of $this->date"; ?>';
        <?php } else { ?>
            var titleText = '<?php echo  "Percent of facilities with a LARC-trained HW in selected geographies <br/>as of $this->date"; ?>';
        <?php } ?>
        
        $('#chart12_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart12_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                },
                title: {
                    text: titleText,
                    x: -40,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                    title:{
                        text:'Geography',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: locations
                },
                yAxis: {
                    title: {
                         text: '% Facilities',
                         style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100
                },
                tooltip: {
                    formatter: function () {
                        var location = this.x;
                        index = -1;
                        for(key in LARCData){
                            if(LARCData[key]['location'].toUpperCase() === location.toUpperCase()){
                                index = key;
                                break;
                            }   
                        }
                        
                        return '<b>' + this.x + '</b>:' + this.y + '%<br/>' + 
                                '<b>Numerator</b>:' + thousandSeparator(LARCData[index]['numer'])+'<br/>' +
                                '<b>Denominator</b>:'+thousandSeparator(LARCData[index]['denom']);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true,
                            format: '{y}%'
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: values
                }]
            });
    }
    
  

</script>

<!--    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>-->
                
<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>                
    
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

</body>

</html>

