<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

@media (max-width: 992px) {
    #topB {
      float: none !important;
    }
}

</style>

<!--<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">-->

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


<!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
<!--<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />-->
<!--<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css">-->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />
      
<style>

    .infobutton {
        padding-right: 13px !important;
        padding-bottom : 6px;
    }
     
</style>    

    
<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>--> 

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script> 
<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" defer async></script>
<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css"></link>

<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>-->

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></link>
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="../bootstrap/js/bootstrap.min.js"></script>
<!--<script src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>-->
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>-->

<script>
  $(function() {
    $( "#accordion" ).accordion({header: "h3", collapsible: true,active: 0});
    
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  
  
  $(document).ready(function(){
       $( "#tabs" ).tabs({
        activate: function( event, ui ) {
            var selectedTab = $("#tabs").tabs('option', 'active');
            if(selectedTab == 1){
                //redrawChart(chart11Options, chart11Data, chart11Div); 
                $("#chart14_div").highcharts().reflow();
            }
        }
      });
//      
//      $('.infobutton').click(function(){
//        console.log("inside click");
//      });
  });
  
  $(document).ready(function() {
    $('#collapseOne').collapse('show');
});
  </script>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->
<div class="row sidebar" style="margin-top: 30px;">
			<!-------   /////////////////////////// make top buttons ////////////////////// -->
                        
<!--			<div class="row rightdiv " style="float: right;">
                            <div class="col-md-1" style="margin-top: 10px;" >
				<?php // require_once('views/scripts/dashboard/top_buttons.phtml');?>
                        </div>	
			</div>-->

			<!-------   /////////////////////////// make left buttons ////////////////////// -->

                                <div class="col-md-2">
			
				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    require_once('views/scripts/dashboard/left_buttonshome.phtml');
                                ?>
			</div>
                        <div class="col-md-4 pull-right" id="topB" >
                            <?php  require_once('views/scripts/dashboard/top_buttons.phtml');?>
                        </div>
			 <div class="col-md-6" style="margin-top: 10px;" >
			<!-------   /////////////////////////// load scripts ////////////////////// -->
           

			<!-------   /////////////////////////// charts ////////////////////// -->


		
                       

				
							<div class="row">
								<div class="col-md-12">
								
                                                                                <div id="infobutton" class="infobutton hidden">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                       This chart, which shows the percentage of reporting facilities that provided 
                                                                                at least one FP commodity over time, illustrates whether coverage of FP 
                                                                                services is improving over time.
                                                                                    </div>
                                                                                </div>
									<div id="chart11_div" style="width: 100%; height: 470px;"></div>
									
                                                                </div>
                                                            
                                                            <div class="col-md-12">
								
                                                                                <div id="infobutton" class="infobutton hidden">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                       This chart, which shows the percentage of reporting facilities that provided 
                                                                                at least one FP commodity over time, illustrates whether coverage of FP 
                                                                                services is improving over time.
                                                                                    </div>
                                                                                </div>
									<div id="chart14_div" style="width: 100%; height: 470px;"></div>
									
                                                                </div>
                                                                    
                                                                    
                                                                     
                                                                    
                                                                    
                                                                    
                                                                    
                                                                        <div class="col-md-12" >
                                                                                <div id="infobutton" class="infobutton hidden">
                                                                                    <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                    <div id="" class="infodiv" >
                                                                                       This chart, which shows the percentage of reporting facilities that provided 
                                                                                at least one implant or IUCD over time, illustrates whether coverage of 
                                                                                LARC services is improving over time.
                                                                                    </div>
                                                                                </div>
										<div id="chart13_div" style="width: 100%; height: 470px;"></div>
									</div>
								
							
								<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
					
						
                                                        </div>
							<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
								
					
				</div>
		
	</div>
                </div>
        </div>

		<script type="text/javascript">
		
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);
      
$(function() {
  
	//  document.getElementById("allCharts").style.marginLeft="130px";

	drawChartFPProviding();
        //drawChartProvidingAnyThreeModern('allfacs');
        drawChartProvidingAnyThreeModern('fpfacs');
	drawChartLARCProviding();
		
	//var currentLevel;
	//currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;

  });
  
    function drawChartFPProviding(){
        var FPOvertime = <?= $this->fp_overtime; ?>;
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = '<?= $this->start_date; ?>';
        
        dataArray = processOvertimeData(FPOvertime);
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        
        <?php
            if(empty($this->selectedDatemultiple)){
                $titleText = $this->end_date." to ".$this->start_date;
            }else{
                $titleText = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date(s)";
            }
        ?>
      
        //console.log(JSON.stringify(dataArray));
        var titleText = '<?php echo  "Percent of facilities providing FP, $titleText"; ?>';
        var subtitleText = '(<?php echo  "($titleText)"; ?>)';
        
        $('#chart11_div').highcharts({
            chart: {
                //type: 'line',
                height: 470,
                //spacingLeft: -20,
                events: {
                    load:function(){
                        $("text:contains(Highcharts.com)").css("display","none");
                        $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                    }
                }
            },
            title: {
                text: titleText,
                style: {
                    fontWeight: 'bold',
                    fontFamily: 'Arial',
                    fontSize: '16px'
                },
                x: -20 //center
            },
            xAxis: {
                title:{
                        text:'Months',
                        style:{ "fontWeight": "bold" }
                    },
                
                categories: monthNamesWithYears

            },
            yAxis: {
                title: {
                    text: 'Percent Facilities',
                    style:{ "fontWeight": "bold" }
                },
                labels: {
                    format: '{value}%'
                },
                //max:100,
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                formatter: function () {
                    var monthArray = (this.x).split(",");
                    var month = monthArray[0];
                    
                    return '<b>' + this.x + '</b><br/>' +
                        '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                        '<b>Numerator</b>: ' + thousandSeparator(FPOvertime[month][this.series.name]['numer']) + '<br/>' +
                        '<b>Denominator</b>: ' + thousandSeparator(FPOvertime[month][this.series.name]['denom']);
                }
            },
            plotOptions: {
                series: {
                    marker: {
                        enabled: true
                    }
                }
            },
            legend: {
                layout: 'horizontal',
                //verticalAlign: 'center',
                align: 'center',
                borderWidth: 1
                //shadow: true
            },
            series: dataArray
        }); 
 }
        
    
    function drawChartLARCProviding(){
        var LARCOvertime = <?= $this->larc_overtime; ?>;
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = '<?= $this->start_date; ?>';
        
        dataArray = processOvertimeData(LARCOvertime);
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        
       <?php
       if(empty($this->selectedDatemultiple)){
           $titleText = $this->end_date." to ".$this->start_date;
       }else{
           $titleText = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date(s)";
       }
       
       
       ?>
        var titleText = '<?php echo  "Percent of FP facilities providing LARC, $titleText"; ?>';
        var subtitleText = '(<?php echo  "($titleText)"; ?>)';
        
         
        $('#chart13_div').highcharts({
                chart: {
                    //type: 'line',
                    height: 470,
                    //spacingLeft: -20,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    }
                },
                title: {
                    text: titleText,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                    x: -20 //center
                },
                xAxis: {
                     title:{
                        text:'Months',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: monthNamesWithYears
                },
                yAxis: {
                    title: {
                       text: 'Percent Facilities',
                       style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100,
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        var monthArray = (this.x).split(",");
                        var month = monthArray[0];
                    
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                            '<b>Numerator</b>: ' + thousandSeparator(LARCOvertime[month][this.series.name]['numer']) + '<br/>' +
                            '<b>Denominator</b>: ' + thousandSeparator(LARCOvertime[month][this.series.name]['denom']);
                        }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    }
                },
                legend: {
                    layout: 'horizontal',
                    //verticalAlign: 'center',
                    align: 'center',
                    borderWidth: 1
                    //shadow: true
                },
                series: dataArray
            });

        
    }

    
    
    function drawChartProvidingAnyThreeModern(mode){
//        var modernMethodData = <?= $this->modern_method_data; ?>;
//        console.log(modernMethodData);
//
//          //declare the array in which to store data
//          var dataArray = new Array();
//          var modernMethodDataModed = modernMethodData[mode];
//          
//          //get month names for x axis: keys of the moded array
//          var monthNames = [];
//          for(month in modernMethodDataModed)
//              monthNames.push(month);
//              
//          //get the location names: keys for month. Locations for each month are same
//          var firstMonth = modernMethodDataModed[monthNames[0]];
//          var locationNames = [];
//          for(loc in firstMonth)
//              locationNames.push(loc);
//          
//          locationNames.sort();
//          for(loc in locationNames){
//              loopLocation = locationNames[loc];
//              obj = {name: loopLocation, data: []};
//              
//              for(month in monthNames){
//                  loopMonth = monthNames[month];
//                  obj.data.push(modernMethodDataModed[loopMonth][loopLocation]['percent']);
//              }
//              
//                if(loopLocation == 'National'){
//                    obj.marker = {enabled: true};
//                    obj.color = '#000000';
//                    obj.dashStyle = 'dot';
//                }
//              
//                dataArray.push(obj);
//          }
          
        var modernMethodData = <?= $this->modern_method_data; ?>;
        var modernMethodDataModed = modernMethodData[mode];
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = '<?= $this->start_date; ?>';
        
        dataArray = processOvertimeData(modernMethodDataModed);
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        
        console.log('dataArray: ', dataArray);
        console.log('monthNamesWithYears: ', monthNamesWithYears);
        
        <?php
            if(empty($this->selectedDatemultiple)){
                $titleText = $this->end_date." to ".$this->start_date;
            }else{
                $titleText = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date(s)";
            }
        ?>

         //console.log(JSON.stringify(dataArray));
         var titleText = '<?php echo  "Percent of FP facilities providing at least 3 FP commodities, $titleText"; ?>';
         var subtitleText = '(<?php echo  "($titleText)"; ?>)';
         var container = mode == 'allfacs' ? 'chart12_div' : 'chart14_div';
                 
         $('#'+container).highcharts({
             chart: {
                 type: 'line',
                 height: 470,
                 //spacingLeft: -20,
                 events: {
                     load:function(){
                         $("text:contains(Highcharts.com)").css("display","none");
                         $("#"+container).siblings("#infobutton").removeClass("hidden");
                     }
                 }
             },
             title: {
                 text: titleText,
                 style: {
                     fontWeight: 'bold',
                     fontFamily: 'Arial',
                     fontSize: '16px'
                 },
                 x: -20 //center
             },
             xAxis: {
                 title:{
                         text:'Months',
                         style:{ "fontWeight": "bold" }
                     },
                 //categories: monthNames
                 categories: monthNamesWithYears
             },
             yAxis: {
                 title: {
                     text: 'Percent Facilities',
                     style:{ "fontWeight": "bold" }
                 },
                 labels: {
                     format: '{value}%'
                 },
                 //max:100,
                 plotLines: [{
                     value: 0,
                     width: 1,
                     color: '#808080'
                 }]
             },
             tooltip: {
                 formatter: function () {
                     //console.log('modernMethodDataModed: ' + modernMethodDataModed[this.x][this.series.name]['numer']);
                     //console.log('modernMethodDataModed2: ' + modernMethodDataModed['July']['South South']['numer']);
                     //console.log('x: ' + this.x);
                         //console.log('series: ' + this.series.name);
                         //console.log('y: ' + this.y);
                     return '<b>' + this.x + '</b><br/>' +
                         '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                         '<b>Numerator</b>:' + thousandSeparator(modernMethodDataModed[this.x][this.series.name]['numer'])+'<br/>' +
                         '<b>Denominator</b>:'+thousandSeparator(modernMethodDataModed[this.x][this.series.name]['denom']);
                 }
             },
             plotOptions: {
                 series: {
                     marker: {
                         enabled: true
                     }
                 }
             },
             legend: {
                 layout: 'horizontal',
                 //verticalAlign: 'center',
                 align: 'center',
                 borderWidth: 1
                 //shadow: true
             },
             series: dataArray
         });

  }


</script>


<script>
  //devsite.github.Link.convertAnchors();
  //window.prettyPrint();
</script>	

<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
<script src="../js/tp/functions.js"></script>
<script src="../js/tp/overtime-ops.js"></script>

<script>
     
</script>

</body>

</html>

