   <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'coverage';
                                        $variable = 'Multiple';        
                                        require_once('views/scripts/template/template.phtml');
                                       
                                    ?>
                                     <div class="row">
                                         
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                      <?php require_once('views/scripts/dashboard/top_buttons.phtml');?>
				
                                           </div>
                                         
                                             <?php
                                                     if(empty($this->selectedDatemultiple)){
                                                               $titleText = $this->end_date." to ".$this->start_date;
                                                     }else{
                                                          $titleText = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date";
                                                     }
      
        
                                              ?>
                                    
                                           <div  class="col-sm-7 pull-right box-shadow clearfix"  style="height:auto;"  >
                                               
                                                 <?php
                                                                       $chart_title = "Percent of facilities providing FP, $titleText";
                                                                       
                                                                       $info_text = "This chart, which shows the percentage of reporting facilities that provided 
                                                                                at least one FP commodity over time, illustrates whether coverage of FP 
                                                                                services is improving over time.";

                                                                       
                       
                                    
                                                                        include('views/scripts/template/chart_title.phtml');
                                                            
                                                           ?>
                                               
                                    
                                                     
									           <div id="chart11_div" style="width:100%; height:auto;"></div>
                                         
				                           </div>                           
                                    </div>
                                    
                                    <div  class="row" style="margin-top:50px;">
                                         
                                           <div class="col-sm-7 box-shadow" style="height:auto;"  >
                                               
                                                                      <?php
                                                                       $chart_title = "Percent of facilities providing at least 3 FP commodities, $titleText";
                                                                       
                                                                       $info_text = " This chart, which shows the percentage of reporting facilities that provided 
                                                                                       at least one FP commodity over time, illustrates whether coverage of FP 
                                                                                       services is improving over time.";

                                                                       
                       
                                    
                                                                        include('views/scripts/template/chart_title.phtml');
                                                            
                                                           ?>
                                               
                                               
                                               <div id="chart12_div" style="width:100%;height:auto;"></div>
                                               
                                           
                                               
                                           </div>
                                    </div>
                                    
                                
                                    
                                     <div class="row" style="margin-top:50px;margin-bottom:45px;">
                                    
                                           <div  class="col-sm-7 box-shadow" style="height:auto;"   >
                                               
                                                         <?php
                                                                       $chart_title = "Percent of facilities providing LARC, $titleText";
                                                                       
                                                                       $info_text = "This chart, which shows the percentage of reporting facilities that provided 
                                                                                  at least one implant or IUCD over time, illustrates whether coverage of 
                                                                                 LARC services is improving over time.  ";

                                                                       
                       
                                    
                                                                        include('views/scripts/template/chart_title.phtml');
                                                            
                                                           ?>
                                               
                                               
                                                   <div id="chart13_div" style="width:100%;height:auto;"></div>
                                               
                                             
				                           </div>  
                                       
                                    </div>
                                    
                                    
                                    
                                     
                                
                                   
                                </div>

		
		<div class="clear"></div>
                </div>
            
          
            
           
            
          
           
           </div><!-- content -->
           <br/><br/><br/>
        

		<script type="text/javascript">
		
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);
      
$(function() {
  
	 // document.getElementById("allCharts").style.marginLeft="130px";

	drawChartFPProviding();
        drawChartProvidingAnyThreeModern('allfacs');
        drawChartProvidingAnyThreeModern('fpfacs');
	drawChartLARCProviding();
		
	//var currentLevel;
	//currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;

  });
  
    function drawChartFPProviding(){
        var jNumData = new Array();
       var jDenomData = new Array();
        <?php 
                //$locationNames = '';
                reset($this->fp_overtime);
                $locationArray = array(); $monthNames = array();
                $firstElement = current($this->fp_overtime);
                
            
                if(!empty($firstElement)){
                    $monthNames = array_keys($this->fp_overtime);
                    foreach($firstElement as $location => $consumption){                    
                            //$locationNames .= "'$location',{ role: 'tooltip', type: 'string', 'p': {'html': true} },";
                            $locationArray[] = $location;
                    }
                }
                
                 foreach($monthNames as $month){ 
                        
                ?>
                        jNumData['<?php echo $month; ?>'] = [];
                        jDenomData['<?php echo $month; ?>'] = [];
                        
                        <?php
             }
         ?>  
         
         //declare the array in which to store data
         var dataArray = new Array();
            
            <?php 
                if(!empty($this->fp_overtime)){
                    foreach($locationArray as $key=>$loc){
            ?>  
                        var obj = {name: '<?php echo $loc; ?>', data: []};
            
            <?php       foreach($monthNames as $month){ 
                         $numerator =  $this->fp_numerator[$month][$loc];
                         $denominator = $this->fp_denominator[$month][$loc];
                         
                ?>
                     
                   jNumData['<?php echo $month; ?>']['<?php echo $loc; ?>']  = <?php echo $numerator; ?>; 
                   jDenomData['<?php echo $month; ?>']['<?php echo $loc; ?>']  = <?php echo $denominator; ?>; 
                    
                                obj.data.push(<?php echo round($this->fp_overtime[$month][$loc],1); ?>);
            <?php
                        }//end month
                        
                        if($key == 0){
            ?>
                            obj.marker = {enabled: true};
                            obj.color = '#000000';
                            obj.dashStyle = 'dot';
                            //console.log(JSON.stringify(obj));
            <?php
                        }//key
            ?>
                        //add the object to the big array
                        dataArray.push(obj);
                        
            <?php   }//end location ?>
         <?php
       if(empty($this->selectedDatemultiple)){
           $titleText = $this->end_date." to ".$this->start_date;
       }else{
           $titleText = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date";
       }
      
       
       
       ?>
      
        //console.log(JSON.stringify(dataArray));
        var titleText = '';
        var subtitleText = '(<?php echo  "($titleText)"; ?>)';
                
        $('#chart11_div').highcharts({
            chart: {
                //type: 'line',
              //  height: 470,
                //spacingLeft: -20,
                events: {
                    load:function(){
                        $("text:contains(Highcharts.com)").css("display","none");
                        $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                    }
                }
            },
            title: {
                text: titleText,
                style: {
                    fontWeight: 'bold',
                    fontFamily: 'Arial',
                    fontSize: '16px'
                },
                x: -20 //center
            },
            xAxis: {
                title:{
                        text:'Months',
                        style:{ "fontWeight": "bold" }
                    },
                categories: <?php echo json_encode($monthNames); ?>
            },
            yAxis: {
                title: {
                    text: 'Percent Facilities',
                    style:{ "fontWeight": "bold" }
                },
                labels: {
                    format: '{value}%'
                },
                //max:100,
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                formatter: function () {
                    return '<b>' + this.x + '</b><br/>' +
                        '<b>' + this.series.name + '</b>: ' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.x][this.series.name])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.x][this.series.name]);
                }
            },
            plotOptions: {
                series: {
                    marker: {
                        enabled: true
                    }
                }
            },
            legend: {
                layout: 'horizontal',
                //verticalAlign: 'center',
                align: 'center',
                borderWidth: 1
                //shadow: true
            },
            series: dataArray
        });
        
        
     <?php }//end if !empty fp_overtime ?>
 
 }
    
    
     function drawChartLARCProviding(){
       var jNumData = new Array();
       var jDenomData = new Array();
        <?php 
                //$locationNames = '';
                reset($this->larc_overtime);
                $locationArray = array(); $monthNames = array();
                $firstElement = current($this->larc_overtime);
                
                if(!empty($firstElement)){
                  
                    $monthNames = array_keys($this->fp_overtime);
                   
                        foreach($firstElement as $location => $consumption){                    
                                //$locationNames .= "'$location',{ role: 'tooltip', type: 'string', 'p': {'html': true} },";
                                $locationArray[] = $location;
                        }            
                }
                
                 foreach($monthNames as $month){ 
                        
                ?>
                        jNumData['<?php echo $month; ?>'] = [];
                        jDenomData['<?php echo $month; ?>'] = [];
                        
                        <?php
             }
         ?>  
           // print_r($monthNames);
            
         
         //declare the array in which to store data
         var dataArray = new Array(); var obj = '';
         
        <?php 
                if(!empty($this->larc_overtime)){
                    foreach($locationArray as $key=>$loc){
            ?>  
                        var obj = {name: '<?php echo $loc; ?>', data: []};
            
            <?php       foreach($monthNames as $month){ 
                         $numerator =  $this->larc_numerator[$month][$loc];
                         $denominator = $this->larc_denominator[$month][$loc];
                ?>
                        
                          
                   jNumData['<?php echo $month; ?>']['<?php echo $loc; ?>']  = <?php echo $numerator; ?>; 
                   jDenomData['<?php echo $month; ?>']['<?php echo $loc; ?>']  = <?php echo $denominator; ?>;
                   
                                obj.data.push(<?php echo round($this->larc_overtime[$month][$loc],1); ?>);
                                
            <?php
                        }//end month
                        
                        if($key == 0){
            ?>
                            obj.marker = {enabled: true};
                            obj.color = '#000000';
                            obj.dashStyle = 'dot';
                            //console.log(JSON.stringify(obj));
            <?php
                        }//key
            ?>
                        //add the object to the big array
                        dataArray.push(obj);
                        
            <?php   }//end location ?>
        
        
        //console.log(JSON.stringify(dataArray));
       <?php
       if(empty($this->selectedDatemultiple)){
           $titleText = $this->end_date." to ".$this->start_date;
       }else{
           $titleText = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date";
       }
       
       
       ?>
        var titleText = '';
        var subtitleText = '(<?php echo  "($titleText)"; ?>)';
        
         
        $('#chart13_div').highcharts({
                chart: {
                    //type: 'line',
                    // height: 470,
                    //spacingLeft: -20,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    }
                },
                title: {
                    text: titleText,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                    x: -20 //center
                },
                xAxis: {
                     title:{
                        text:'Months',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: <?php echo json_encode($monthNames); ?>
                },
                yAxis: {
                    title: {
                       text: 'Percent Facilities',
                       style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100,
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + this.y + '%<br/><b>Numerator</b>:'+thousandSeparator(jNumData[this.x][this.series.name])+'<br/><b>Denominator</b>:'+thousandSeparator(jDenomData[this.x][this.series.name]);
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    }
                },
                legend: {
                    layout: 'horizontal',
                    //verticalAlign: 'center',
                    align: 'center',
                    borderWidth: 1
                    //shadow: true
                },
                series: dataArray
            });


         <?php }//end if !empty fp_overtime ?>
        
    }
    
    
    
    function drawChartProvidingAnyThreeModern(mode){
        var modernMethodData = <?= $this->modern_method_data; ?>;
        console.log(modernMethodData);

          //declare the array in which to store data
          var dataArray = new Array();
          var modernMethodDataModed = modernMethodData[mode];
          console.log(modernMethodDataModed);
          
          //get month names for x axis: keys of the moded array
          var monthNames = [];
          for(month in modernMethodDataModed)
              monthNames.push(month);
              
          //get the location names: keys for month. Locations for each month are same
          var firstMonth = modernMethodDataModed[monthNames[0]];
          var locationNames = [];
          for(loc in firstMonth)
              locationNames.push(loc);
          
          locationNames.sort();
          for(loc in locationNames){
              loopLocation = locationNames[loc];
              obj = {name: loopLocation, data: []};
              
              for(month in monthNames){
                  loopMonth = monthNames[month];
                  obj.data.push(modernMethodDataModed[loopMonth][loopLocation]['percent']);
              }
              
                if(loopLocation == 'National'){
                    obj.marker = {enabled: true};
                    obj.color = '#000000';
                    obj.dashStyle = 'dot';
                }
              
                dataArray.push(obj);
          }
          
             console.log(dataArray);
        <?php
            if(empty($this->selectedDatemultiple)){
                $titleText = $this->end_date." to ".$this->start_date;
            }else{
                $titleText = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date";
            }
        ?>

         //console.log(JSON.stringify(dataArray));
         var titleText = '';
         var subtitleText = '(<?php echo  "($titleText)"; ?>)';
         var container = mode == 'allfacs' ? 'chart12_div' : 'chart14_div';
                 
         $('#'+container).highcharts({
             chart: {
                 type: 'line',
                 // height: 470,
                 //spacingLeft: -20,
                 events: {
                     load:function(){
                         $("text:contains(Highcharts.com)").css("display","none");
                         $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                     }
                 }
             },
             title: {
                 text: titleText,
                 style: {
                     fontWeight: 'bold',
                     fontFamily: 'Arial',
                     fontSize: '16px'
                 },
                 x: -20 //center
             },
             xAxis: {
                 title:{
                         text:'Months',
                         style:{ "fontWeight": "bold" }
                     },
                 categories: monthNames
             },
             yAxis: {
                 title: {
                     text: 'Percent Facilities',
                     style:{ "fontWeight": "bold" }
                 },
                 labels: {
                     format: '{value}%'
                 },
                 //max:100,
                 plotLines: [{
                     value: 0,
                     width: 1,
                     color: '#808080'
                 }]
             },
             tooltip: {
                 formatter: function () {
                     //console.log('modernMethodDataModed: ' + modernMethodDataModed[this.x][this.series.name]['numer']);
                     //console.log('modernMethodDataModed2: ' + modernMethodDataModed['July']['South South']['numer']);
                     //console.log('x: ' + this.x);
                         //console.log('series: ' + this.series.name);
                         //console.log('y: ' + this.y);
                     return '<b>' + this.x + '</b><br/>' +
                         '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                         '<b>Numerator</b>:' + thousandSeparator(modernMethodDataModed[this.x][this.series.name]['numer'])+'<br/>' +
                         '<b>Denominator</b>:'+thousandSeparator(modernMethodDataModed[this.x][this.series.name]['denom']);
                 }
             },
             plotOptions: {
                 series: {
                     marker: {
                         enabled: true
                     }
                 }
             },
             legend: {
                 layout: 'horizontal',
                 //verticalAlign: 'center',
                 align: 'center',
                 borderWidth: 1
                 //shadow: true
             },
             series: dataArray
         });

  }


</script>


<script>
  //devsite.github.Link.convertAnchors();
  //window.prettyPrint();
</script>	

<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
<script src="../js/tp/functions.js"></script>

<script>
     
</script>

</body>

</html>



<?php


?>

