
     <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'coverage';
                                        $variable = 'Simple';        
                                        require_once('views/scripts/template/template.phtml');
                                       
                                    ?>
                                    
                                    
                                    
                                     <div class="row">
                                         
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                      <?php require_once('views/scripts/dashboard/top_buttons.phtml');?>
				
                                           </div>
                                         
                                             
                                    
                                           <div  class="col-sm-7 pull-right box-shadow clearfix"  style="height:auto;"  >
                                               <?php
                                                                       $chart_title = "";
                                                                       
                                                                       $info_text = "This chart, which shows the percentage of reporting facilities that provided 
                                                                                at least one FP commodity over time, illustrates whether coverage of FP 
                                                                                services is improving over time.";

                                                                       
                       
                                    
                                                                        include('views/scripts/template/chart_title.phtml');
                                                            
                                                           ?>
                                               
                                             
                                                     
									           <div id="chart11_div" style="width:100%;height:auto;"></div>
                                         
				                           </div>                           
                                    </div>
                                    
                                    <div  class="row" style="margin-top:50px;">
                                         
                                           <div class="col-sm-7 box-shadow" style="height:auto;"  >
                                               <?php
                                                                       $chart_title = "";
                                                                       
                                                                       $info_text = "This chart, which shows the percentage of reporting facilities that provided 
                                                                                       at least one FP commodity over time, illustrates whether coverage of FP 
                                                                                       services is improving over time.";

                                                                       
                       
                                    
                                                                        include('views/scripts/template/chart_title.phtml');
                                                            
                                                           ?>
                                               
                                               
                                               <div id="chart14_div" style="width:100%;height:auto;"></div>
                                               
                                           
                                               
                                           </div>
                                    </div>
                                    
                                
                                    
                                     <div class="row" style="margin-top:50px;margin-bottom:45px;">
                                    
                                           <div  class="col-sm-7 box-shadow" style="height:auto;"   >
                                               <?php
                                                                       $chart_title = "";
                                                                       
                                                                       $info_text = "This chart, which shows the percentage of reporting facilities that provided 
                                                                                  at least one implant or IUCD over time, illustrates whether coverage of 
                                                                                 LARC services is improving over time.  ";

                                                                       
                       
                                    
                                                                        include('views/scripts/template/chart_title.phtml');
                                                ?>
                                               
                                               <div id="chart13_div" style="width:100%;height:auto;"></div>
                                               
                                             
				                           </div>  
                                       
                                    </div>
                                    
                                    
                                    
                                     
                                
                                   
                                </div>

		
		<div class="clear"></div>
                </div>
            
          
            
           
            
          
           
           </div><!-- content -->
           <br/><br/><br/>
        

		<script type="text/javascript">
		
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);
      
$(function() {
  
        Highcharts.setOptions({
                    colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
                });
         

	drawChartFPProviding();
        drawChartProvidingAnyThreeModern('fpfacs');
	drawChartLARCProviding();
		
	//var currentLevel;
	//currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;

  });
  
    function drawChartFPProviding(){
        var FPOvertime = <?= $this->fp_overtime; ?>;
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = '<?= $this->start_date; ?>';
        
        var dataArray = processOvertimeData(FPOvertime);
        var monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        var dateLength = selectedDatemultiple.length;
        
        <?php
            if(empty($this->selectedDatemultiple)){
                $titleText = $this->end_date." to ".$this->start_date;
            }else{
                $titleText = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date(s)";
            }
        ?>

        var dateText = '<?= $this->end_date . " to " . $this->start_date ?>';
        if(dateLength > 0){
            dateText = dateLength === 1 ? 
                    monthNamesWithYears[0] : 
                    "across selected dates";
        }
        
        <?php if($this->freshVisit) { ?>
            var titleText = "Percent of facilities providing FP, <br/>" + dateText;
        <?php } else { ?>
            var titleText = "Percent of facilities providing FP in selected geographies, <br/>" + dateText;
        <?php } ?>
        
        $('#chart11_div').highcharts({
            chart: {
                type: dateLength == 1 ? 'column' : 'line',
                height: 470,
                //spacingLeft: -20,
                events: {
                    load:function(){
                        $("text:contains(Highcharts.com)").css("display","none");
                        $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                    }
                }
            },
            title: {
                text: titleText,
                style: {
                    fontWeight: 'bold',
                    fontFamily: 'Arial',
                    fontSize: '16px'
                },
                x: -20 //center
            },
            xAxis: {
                title:{
                        text:'Months',
                        style:{ "fontWeight": "bold" }
                    },
                
                categories: monthNamesWithYears

            },
            yAxis: {
                title: {
                    text: '% Facilities',
                    style:{ "fontWeight": "bold" }
                },
                labels: {
                    format: '{value}%'
                },
                //max:100,
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                formatter: function () {
                    var monthArray = (this.x).split(" ");
                    var month = monthArray[0];
                    
                    return '<b>' + this.x + '</b><br/>' +
                        '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                        '<b>Numerator</b>: ' + thousandSeparator(FPOvertime[month][this.series.name]['numer']) + '<br/>' +
                        '<b>Denominator</b>: ' + thousandSeparator(FPOvertime[month][this.series.name]['denom']);
                }
            },
            plotOptions: {
                series: {
                    marker: {
                        enabled: true
                    }
                },
                column: dateLength === 1  
                         ? {    
                            dataLabels: {
                                  enabled: true,
                                  format: '{y}%'
                              }
                          }
                          : {}  
            },
            legend: {
                layout: 'horizontal',
                //verticalAlign: 'center',
                align: 'center',
                borderWidth: 1
                //shadow: true
            },
            series: dataArray
        }); 
 }
        
    
    function drawChartLARCProviding(){
        var LARCOvertime = <?= $this->larc_overtime; ?>;
        
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = '<?= $this->start_date; ?>';
        
        var dataArray = processOvertimeData(LARCOvertime);
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        dateLength = selectedDatemultiple.length;

        var dateText = '<?= $this->end_date . " to " . $this->start_date ?>';
        if(dateLength > 0){
            dateText = dateLength === 1 ? 
                    monthNamesWithYears[0] : 
                    "across selected dates";
        }
        
        <?php if($this->freshVisit) { ?>
            var titleText = "Percent FP facilities providing LARC, <br/>" + dateText;
        <?php } else { ?>
            var titleText = "Percent FP facilities providing LARC in selected geographies, <br/>" + dateText;
        <?php } ?>
            
            
        
        
         
        $('#chart13_div').highcharts({
                chart: {
                    type: dateLength == 1 ? 'column' : 'line',
                    height: 470,
                    //spacingLeft: -20,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    }
                },
                title: {
                    text: titleText,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                    x: -20 //center
                },
                xAxis: {
                     title:{
                        text:'Months',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: monthNamesWithYears
                },
                yAxis: {
                    title: {
                       text: '% Facilities',
                       style:{ "fontWeight": "bold" }
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100,
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        var monthArray = (this.x).split(" ");
                        var month = monthArray[0];
                    
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                            '<b>Numerator</b>: ' + thousandSeparator(LARCOvertime[month][this.series.name]['numer']) + '<br/>' +
                            '<b>Denominator</b>: ' + thousandSeparator(LARCOvertime[month][this.series.name]['denom']);
                        }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    },
                    column: dateLength === 1  
                         ? {    
                            dataLabels: {
                                  enabled: true,
                                  format: '{y}%'
                              }
                          }
                          : {}  
                },
                legend: {
                    layout: 'horizontal',
                    //verticalAlign: 'center',
                    align: 'center',
                    borderWidth: 1
                    //shadow: true
                },
                series: dataArray
            });

        
    }

    
    
    function drawChartProvidingAnyThreeModern(mode){
          
        var modernMethodData = <?= $this->modern_method_data; ?>;
        var modernMethodDataModed = modernMethodData[mode];
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = '<?= $this->start_date; ?>';
        
        dataArray = processOvertimeData(modernMethodDataModed);
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        dateLength = selectedDatemultiple.length;
        
        <?php
//            if(empty($this->selectedDatemultiple)){
//                $titleText = $this->end_date." to ".$this->start_date;
//            }else{
//                $titleText = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date(s)";
//            }
        ?>

         //console.log(JSON.stringify(dataArray));
         //var titleText = '<?php //echo  "Percent of FP facilities providing at least 3 FP commodities, $titleText"; ?>';
         //var subtitleText = '(<?php //echo  "($titleText)"; ?>)';
         var container = mode === 'allfacs' ? 'chart12_div' : 'chart14_div';
        
        var dateText = '<?= $this->end_date . " to " . $this->start_date ?>';
        if(dateLength > 0){
            dateText = dateLength === 1 ? 
                    monthNamesWithYears[0] : 
                    "across selected dates";
        }
        
        <?php if($this->freshVisit) { ?>
            var titleText = "Percent of FP facilities providing at least 3 modern methods, <br/>" + dateText;
        <?php } else { ?>
            var titleText = "Percent of FP facilities providing at least 3 modern methods<br/> in selected geographies, " + dateText;
        <?php } ?>
            
         $('#'+container).highcharts({
             chart: {
                 type: dateLength === 1 ? 'column' : 'line',
                 height: 470,
                 //spacingLeft: -20,
                 events: {
                     load:function(){
                         $("text:contains(Highcharts.com)").css("display","none");
                         $("#"+container).siblings("#infobutton").removeClass("hidden");
                     }
                 }
             },
             title: {
                 text: titleText,
                 style: {
                     fontWeight: 'bold',
                     fontFamily: 'Arial',
                     fontSize: '16px'
                 },
                 x: -20 //center
             },
             xAxis: {
                 title:{
                         text:'Months',
                         style:{ "fontWeight": "bold" }
                     },
                 //categories: monthNames
                 categories: monthNamesWithYears
             },
             yAxis: {
                 title: {
                     text: '% Facilities',
                     style:{ "fontWeight": "bold" }
                 },
                 labels: {
                     format: '{value}%'
                 },
                 //max:100,
                 plotLines: [{
                     value: 0,
                     width: 1,
                     color: '#808080'
                 }]
             },
             tooltip: {
                 formatter: function () {
                     var monthArray = this.x.split(" ");
                     var month = monthArray[0];
                     
                     return '<b>' + this.x + '</b><br/>' +
                         '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                         '<b>Numerator</b>:' + thousandSeparator(modernMethodDataModed[month][this.series.name]['numer'])+'<br/>' +
                         '<b>Denominator</b>:'+thousandSeparator(modernMethodDataModed[month][this.series.name]['denom']);
                 }
             },
             plotOptions: {
                 series: {
                     marker: {
                         enabled: true
                     }
                 },
                 column: dateLength === 1  
                         ? {    
                            dataLabels: {
                                  enabled: true,
                                  format: '{y}%'
                              }
                          }
                          : {}    
                 
             },
             legend: {
                 layout: 'horizontal',
                 //verticalAlign: 'center',
                 align: 'center',
                 borderWidth: 1
                 //shadow: true
             },
             series: dataArray
         });

  }


</script>


<script>
  //devsite.github.Link.convertAnchors();
  //window.prettyPrint();
</script>	

<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
<script src="../js/tp/overtime-ops.js"></script>

<script>
     
</script>

</body>

</html>

