<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

</style>


<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!--<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css"></link>-->

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></link>

<script src="//code.jquery.com/jquery-1.10.2.js"></script>

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<style>

    .infobutton {
        padding-right: 13px !important;
        padding-bottom : 6px;
    }
    
    body {
        font: 13px/1.231 arial,helvetica,clean,sans-serif
    }
    
/*    .ui-accordion-header 
    {
        padding: 5px 10px !important;
        background: #008C00;
        color: #fff;
    }*/
    
    #wrapper {
        
        margin-top : 25px;
    }
    
    .well {
        padding: 19px 5px !important;
        width: 98%;
    }
    
    .row>.panel-default>.panel-heading {
        background-color: transparent !important;
    }
    
    
     
</style>    

    
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

<script>
  $(function() {
    $( "#accordion" ).accordion({header: "h3", collapsible: true,active: 0});
    
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  </script>

</head>
    
<body>
    
    <header>
            <div class="container-fluid" id="header">
                
                <?php require_once('views/scripts/header.phtml');?>
                
            </div>
    </header>
    
    <section id="wrapper" class="container-fluid">
        
        <div class="row">
            
            <!-- Accordion NAV Buttons LEFT Aligned -->
            
            <div class="col-md-2">
                
                <?php  
                    $fileInfo = pathinfo(__FILE__);
                    $fileID = $fileInfo['filename'];
                    require_once('views/scripts/dashboard/left_buttonshome.phtml');
                ?>
                
<!--                <style>
                    #accordion {
                        max-width: 100% !important;
                    }
                </style>-->
            </div>
            
            <!-- Main Chart Area centered Aligned -->
            
            <div class="col-md-10">
                
                <div class="row">
                    
                    <!-- Chart goes here -->
                    <div class="col-md-7" id="chartDisplayArea" style="display:none">
                        
                        
                        <div class="row">
                            <div class="panel panel-default container-fluid">
                                <div class="panel-heading row" >
                                    <div id="infobutton" class="infobutton">
                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                            <div id="" class="infodiv" >
                                                This chart, which shows the percentage of reporting facilities that provided 
                                                at least one FP commodity over time, illustrates whether coverage of FP 
                                                services is improving over time.
                                            </div>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <div id="chart11_div" ></div>
                                </div>
                            </div>
                            
                        </div>
                        
                        
                        <div class="row">
                            <div class="panel panel-default container-fluid">
                                <div class="panel-heading row" >
                                    <div id="infobutton" class="infobutton">
                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                            <div id="" class="infodiv" >
                                                This chart, which shows the percentage of reporting facilities that provided 
                                                at least one implant or IUCD over time, illustrates whether coverage of 
                                                LARC services is improving over time. 
                                            </div>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <div id="chart13_div" ></div>
                                </div>
                            </div>
                            
                        </div>
                        
                       
                        
                        
                    </div>
                    
                    <!-- Filter Box Right Aligned -->
            
                    <div class="col-md-5 ">
                        <div class="well">
                            <?php  require_once('views/scripts/dashboard/top_buttons.phtml');?>
                        </div>
                    </div>
                    
                </div>
                
            </div>
            
            
            
        </div>
        
    </section>
    
    
    
    
    
<!-- Javascript code for charts display goes here -->
    
<script type="text/javascript">
		

$(function() {

	drawChartFPProviding();
	drawChartLARCProviding();
	
        $("#chartDisplayArea").css("display","block");
        
	//var currentLevel;
	//currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;

  });
  
    function drawChartFPProviding(){
        
        <?php 
                //$locationNames = '';
                reset($this->fp_overtime);
                $locationArray = array(); $monthNames = array();
                $firstElement = current($this->fp_overtime);
                
                if(!empty($firstElement)){
                    $monthNames = array_keys($this->fp_overtime);
                    foreach($firstElement as $location => $consumption){                    
                            //$locationNames .= "'$location',{ role: 'tooltip', type: 'string', 'p': {'html': true} },";
                            $locationArray[] = $location;
                    }
                }
         ?>  
         
         //declare the array in which to store data
         var dataArray = new Array();
            
            <?php 
                if(!empty($this->fp_overtime)){
                    foreach($locationArray as $key=>$loc){
            ?>  
                        var obj = {name: '<?php echo $loc; ?>', data: []};
            
            <?php       foreach($monthNames as $month){ ?>
                                obj.data.push(<?php echo round($this->fp_overtime[$month][$loc],1); ?>);
            <?php
                        }//end month
                        
                        if($key == 0){
            ?>
                            obj.marker = {enabled: true};
                            obj.color = '#000000';
                            obj.dashStyle = 'dot';
                            //console.log(JSON.stringify(obj));
            <?php
                        }//key
            ?>
                        //add the object to the big array
                        dataArray.push(obj);
                        
            <?php   }//end location ?>
        
        
        //console.log(JSON.stringify(dataArray));
        var titleText = '<?php echo  "Percent of facilities providing FP, $this->end_date to $this->start_date"; ?>';
        var subtitleText = '(<?php echo  "($this->end_date to $this->start_date)"; ?>)';
                
        $('#chart11_div').highcharts({
            chart: {
                //type: 'line',
                height: 470,
                //spacingLeft: -20,
                events: {
                    load:function(){
                        $("text:contains(Highcharts.com)").css("display","none");
                        $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                    }
                }
            },
            title: {
                text: titleText,
                style: {
                    fontWeight: 'bold',
                    fontFamily: 'Arial',
                    fontSize: '16px'
                },
                x: -20 //center
            },
            xAxis: {
                categories: <?php echo json_encode($monthNames); ?>
            },
            yAxis: {
                title: {
                    text: null
                },
                labels: {
                    format: '{value}%'
                },
                //max:100,
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                formatter: function () {
                    return '<b>' + this.x + '</b><br/>' +
                        '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>';
                }
            },
            plotOptions: {
                series: {
                    marker: {
                        enabled: true
                    }
                }
            },
            legend: {
                layout: 'horizontal',
                //verticalAlign: 'center',
                align: 'center',
                borderWidth: 1
                //shadow: true
            },
            series: dataArray
        });
        
        
     <?php }//end if !empty fp_overtime ?>
 
 }
    
    
     function drawChartLARCProviding(){
        <?php 
                //$locationNames = '';
                reset($this->larc_overtime);
                $locationArray = array(); $monthNames = array();
                $firstElement = current($this->larc_overtime);
                
                if(!empty($firstElement)){
                    $monthNames = array_keys($this->fp_overtime);
                        foreach($firstElement as $location => $consumption){                    
                                //$locationNames .= "'$location',{ role: 'tooltip', type: 'string', 'p': {'html': true} },";
                                $locationArray[] = $location;
                        }            
                }                
         ?>        
         
         //declare the array in which to store data
         var dataArray = new Array(); var obj = '';
         
        <?php 
                if(!empty($this->larc_overtime)){
                    foreach($locationArray as $key=>$loc){
            ?>  
                        var obj = {name: '<?php echo $loc; ?>', data: []};
            
            <?php       foreach($monthNames as $month){ ?>
                                obj.data.push(<?php echo round($this->larc_overtime[$month][$loc],1); ?>);
            <?php
                        }//end month
                        
                        if($key == 0){
            ?>
                            obj.marker = {enabled: true};
                            obj.color = '#000000';
                            obj.dashStyle = 'dot';
                            //console.log(JSON.stringify(obj));
            <?php
                        }//key
            ?>
                        //add the object to the big array
                        dataArray.push(obj);
                        
            <?php   }//end location ?>
        
        
        //console.log(JSON.stringify(dataArray));
        var titleText = '<?php echo  "Percent of facilities providing LARC, $this->end_date to $this->start_date"; ?>';
        var subtitleText = '(<?php echo  "($this->end_date to $this->start_date)"; ?>)';
        
         
        $('#chart13_div').highcharts({
                chart: {
                    //type: 'line',
                    height: 470,
                    //spacingLeft: -20,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    }
                },
                title: {
                    text: titleText,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                    x: -20 //center
                },
                xAxis: {
                    categories: <?php echo json_encode($monthNames); ?>
                },
                yAxis: {
                    title: {
                        text: null
                    },
                    labels: {
                        format: '{value}%'
                    },
                    //max:100,
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>';
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    }
                },
                legend: {
                    layout: 'horizontal',
                    //verticalAlign: 'center',
                    align: 'center',
                    borderWidth: 1
                    //shadow: true
                },
                series: dataArray
            });


         <?php }//end if !empty fp_overtime ?>
        
    }
    
    
    


</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

  

</body>

</html>

