<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.mclass {
    max-width: 132px !important;
    overflow-wrap: break-word  !important;
    word-break: break-all !important;
}
</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script src="../bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="../bootstrap/js/bootstrap.min.js"></script>
<script src="../js/tp/functions.js"></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>



</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>


			<body class="docs slim framebox_body">
                            <div class="row">
                            <div class="col-md-2">
				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    $activationBar = "coverage";
                                    require_once('views/scripts/dashboard/left_buttonshome.phtml');
                                ?>
			</div>
                            
                           <div class="col-md-10">
                            <div class="row">
			<div class="col-md-5 col-md-push-7" style="text-align:right">
				<?php  require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>
                            <div class="col-md-7 col-md-pull-5">
                                          <div class="row">
			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			

								<div class="col-md-12">
                                                                        <div id="infobutton" class="infobutton hidden">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                            <div id="" class="infodiv" >
                                                                                This chart, which shows the percentage of reporting facilities that provided 
                                                                                at least one FP commodity over time, illustrates whether coverage of FP 
                                                                                services is improving over time.
                                                                            </div>
                                                                        </div>
									<div id="chart11_div" style=" height: 400px;"></div>
									</div>
									
								
								<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
					
								<div class="col-md-12">
                                                                        <div id="infobutton" class="infobutton hidden">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                            <div id="" class="infodiv" >
                                                                                This chart, which shows the percentage of reporting facilities that provided 
                                                                                at least one implant or IUCD over time, illustrates whether coverage of 
                                                                                LARC services is improving over time.  
                                                                            </div>
                                                                        </div>
									<div id="chart13_div" style=" height: 400px;"></div>
									</div>
									
								
								
                                            <!-------   /////////////////////////// chart 2,2 ////////////////////// -->
                                           
					</div>
                            </div>
                            </div>
                           </div>
                            </div>
                        </div>
				</div>
		
	</div>

		<div class="clear"></div>
		<div class="hrGrey"></div>
		<div class="clear"></div>
		
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>

		<!-------   /////////////////////////// main  ////////////////////// -->

		<script type="text/javascript">
		
  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.load('visualization', '1.1', {'packages':['bar']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  //document.getElementById("allCharts").style.marginLeft="130px";

	drawChartFPProviding();
	drawChartLARCProviding();
		
	//var currentLevel;
	//currentLevel = <?php echo '\'' . $this->location_data[0][name] . '\''; ?>;
		 
  }
  

    function drawChartFPProviding(){
        <?php 
                
                $locationNames = '';
                reset($this->fp_overtime);
                $locationArray = array();
                $firstElement = current($this->fp_overtime);
                
                if(!empty($firstElement)){
                    foreach($firstElement as $location => $consumption){                    
                            $locationNames .= "'$location',{ role: 'tooltip', type: 'string', 'p': {'html': true} },";
                            $locationArray[] = $location;
                    }
                      //print_r($locationArray);
                    $locationNames = substr($locationNames, 0, -1);
                    $legend = "'Month'," . "$locationNames";
                    //echo $legend;
                }
         ?>                        
         //console.log('legend: ' + <?php //echo $legend; ?>);
         
        var chartData = google.visualization.arrayToDataTable([
                            [<?php echo !empty($legend) ? $legend : ''; ?>],
            <?php 
                //$locationNamesArray = explode(',', $locationNames);
                
                if(!empty($this->fp_overtime)){
                    foreach ($this->fp_overtime as $month=>$locationValues){ 
                        $rowValues = '';
                        $count = 0;
                        foreach ($locationValues as $value){
                            $value = round($value, 1);
                              if($count>=12){
                                $count = 0;
                            }
                            $locationName = $locationArray[$count];
                            $toolTip = "<p style=\"padding:5px 7px;\"><b>$month</b><br/>$locationName:</b> " .$value. "\%</p>";
                            $rowValues .= "$value,'$toolTip',";
                            $count++;
                        }
                        $rowValues = substr($rowValues, 0, -1);
                        
            ?>
                    [<?php echo "'$month', $rowValues"; ?>],
                     
            <?php
                    }//end foreach
                } //end if
            ?>
       ]);
        
        
        <?php echo  " var title_data = 'Percent of facilities providing FP, $this->end_date to $this->start_date ' " ?>;
                
        var chartOptions = {
		      title: title_data,
		      titleTextStyle: { fontSize: 15 },
		      vAxis: {format: '#', minValue: 4},
		      legend: {fontSize: 14},
		      chartArea: {width: '65%', height: '70%', top: 55},
		      is3D:true,
                      animation:{ duration: 2000, easing: 'out',"startup": true },
                      tooltip : {isHtml : true },
                      series: {0:{color: 'black'}}
		};

          var chart = new google.visualization.LineChart(document.getElementById('chart11_div'));
          
          //show info icon
          google.visualization.events.addListener(chart, 'ready', function(){
                 $("#chart11_div").siblings('#infobutton').removeClass('hidden');
          }); 
          
	  chart.draw(chartData, chartOptions);
    }
    
    
    
    function drawChartLARCProviding(){
        <?php 
                
                $locationNames = '';
                $locationArray = array();
                reset($this->larc_overtime);
                $firstElement = current($this->larc_overtime);
                
                if(!empty($firstElement)){
                    foreach($firstElement as $location => $consumption){                    
                            $locationNames .= "'$location',{ role: 'tooltip', type: 'string', 'p': {'html': true} },";
                    $locationArray[] = $location;
                            
                    }

                    $locationNames = substr($locationNames, 0, -1);
                    $legend = "'Month'," . "$locationNames";
                    //echo $legend;
                }
         ?>                        
         //console.log('legend: ' + <?php //echo $legend; ?>);
         
        var chartData = google.visualization.arrayToDataTable([
                            [<?php echo !empty($legend) ? $legend : ''; ?>],
            <?php 
                //$locationNamesArray = explode(',', $locationNames);
                
                if(!empty($this->larc_overtime)){
                    foreach ($this->larc_overtime as $month=>$locationValues){ 
                        $rowValues = '';
                      $count = 0;
                        foreach ($locationValues as $value){
                            if($count>=12){
                                $count = 0;
                            }
                            $locationName = $locationArray[$count];
                            $value = round($value, 1);
                             
                            $toolTip = "<p style=\"padding:5px 7px;\"><b>$month</b><br/>$locationName:</b> " .$value. "\%</p>";
                           
                            $rowValues .= "$value,'$toolTip',";
                            $count++;
                        }
                        $rowValues = substr($rowValues, 0, -1);
                        
            ?>
                    [<?php echo "'$month', $rowValues"; ?>],
                     
            <?php
                    }//end foreach
                } //end if
            ?>
       ]);
        
        
        <?php echo  " var title_data = 'Percent of facilities providing LARC, $this->end_date to $this->start_date ' " ?>;
                
        var chartOptions = {
		      title: title_data,
		      titleTextStyle: { fontSize: 15 },
		      vAxis: {format: '#', minValue: 4},
		      legend: {fontSize: 14},
		      chartArea: {width: '65%', height: '70%', top: 55},
		      is3D:true,
                      animation:{ duration: 2000, easing: 'out',"startup": true },
                      tooltip : {isHtml : true },
                      series: {0:{color: 'black'}}
		};

          var chart = new google.visualization.LineChart(document.getElementById('chart13_div'));
          
          //show info icon
          google.visualization.events.addListener(chart, 'ready', function(){
                 $("#chart13_div").siblings('#infobutton').removeClass('hidden');
          }); 
          
	  chart.draw(chartData, chartOptions);
    }


</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>

