<?php require_once('views/helpers/Location.php');?>
<form id="addLocationForm"  action="<?php echo $this->base_url;?>/training/location-add/outputType/json" method="POST" <?php if($this->viewonly) echo 'disabled="disabled"'; ?>>

  <div class="row" style="">
        <div class="col-sm-6">
            <div class="form-group">
                  <input type="text" class="form-control" size="70" placeholder="<?php tp('Location name');?>" name="training_location_name" id="locationName" required value="<?php if(isset($this->rowLocation)) echo $this->rowLocation['training_location_name']; ?>" <?php echo $this->viewonly; ?>>
            </div>
        </div>
  </div>
<div class="row">
        <div class="col-sm-6">
            <div class="form-group">
               <?php 
                   if(isset($this->rowLocation)){
                        region_filters_dropdown_db($this, $this->locations, $this->rowLocation,false,false,false,'',true);
                    }else{
                        region_filters_dropdown_db($this, $this->locations, $this->locations,false,false,false,'',true);
                    }
               ?>
            </div>
        </div>
</div>
 

</form>

<div class="clear"></div>