<div id="footer-by-itech">
  <?php // tp("Developed and funded by I-TECH. For questions or help,"); ?>  
  <!-- <a href="http://www.trainingdata.org/" target="_blank"> -->
  <p> If you are experiencing technical problems with the Dashboard, have questions about the HR data or data upload, need a username and password, or have other questions, please contact the Dashboard administrator at <a href="mailto:support@fpdashboard.ng">support@fpdashboard.ng</a>.
  </p>
  <p>
      If you have questions specifically about the DHIS-2 data in the Dashboard, please contact Federal Ministry of Health (PRS Dept) by email at <a href="mailto:admin@dhis2nigeria.org.ng">admin@dhis2nigeria.org.ng</a> or by phone at 08036099676, 08033683677, 08065360433, or 08075795894.
</p> <?php  //tp('click here'); ?>
  <!--  </a>.  -->
</div>


<?php //require_once('views/scripts/status.phtml'); ?>

<?php
    //print 'myfooter: ' . $this->base_url; exit;
    //TP JS includes
   echo '<script src="'. $this->base_url . '/js/tp/functions.js" type="text/javascript"></script>';
?>

</div>
           		


</body>

</html>