<?php
/*
 * Created on Mar 7, 2008
 * 
 *  Built for itechweb  
 *  Fuse IQ -- todd@fuseiq.com
 *  
 */
?>

<div id="footer-by-itech">
  <?php // tp("Developed and funded by I-TECH. For questions or help,"); ?>  
  <!-- <a href="http://www.trainingdata.org/" target="_blank"> -->
  <?php // tp('click here'); ?>
  <!--  </a>.  -->
</div>


<?php require_once('views/scripts/status.phtml'); ?>

<?php
    //print 'myfooter: ' . $this->base_url; exit;
    //TP JS includes
    echo '<script src="'. $this->base_url . '/js/tp/functions.js" type="text/javascript"></script>';
?>