 <div class="row">                                 

<div class="title-bar border-hr col-xs-12 " style="" >
                                                           <div class="row">
                                                                <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                    <?php echo $chart_title; ?>
                                                                </div>
                                                                <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                    <div id="infobutton" class="infobutton infoButtonFirst" style="margin-bottom:-23px;">
                                                                        <span class="infowrap"><i class="fa fa-info-circle"></i>
                                                                        </span>
                                                                            <div id="" class="infodiv" >
                                                                            <?php  echo $info_text; ?>
                                                                                
                                                                            </div>
                                                                    </div>
                                                                </div>
                                                                             
                                                            </div>  
                                                    </div>
     
 </div>
                                             
		