<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0 transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}
    
 
.hometabs.ui-widget-header {
    background: #eeeeee !important;
    font-size: 12px;
    border-top: solid 2px; 
}
    
.small-tab{
    background-color:white;
    font-size:12px;
    padding:2px;
}
    
   

body {font-family: "Lato", sans-serif;}


    
    

</style>

 <?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
    
<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">



<!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css"></link>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />


<link rel="stylesheet" href="<?php echo $this->base_url; ?>bootstrap/css/bootstrap.min.css"></link>
<!--<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css"></link>-->
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></link>

<link rel="stylesheet" href="<?php echo $this->base_url; ?>css/cssfile.css"></link>

<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>-->
<!--<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" ></script>-->

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script src="<?php echo $this->base_url; ?>bootstrap/js/bootstrap.min.js"></script>

                



<script>
  $(function() {
    //$( "#accordion" ).accordion({header: "h3", collapsible: true, active: false, animated:200, animated:"slide"});
    $( "#tabs").tabs();
    
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  
  $(document).ready(function(){
       $( "#tabs" ).tabs({
        activate: function( event, ui ) {
            var selectedTab = $("#tabs").tabs('option', 'active');
            if(selectedTab == 1){
                //redrawChart(chart11Options, chart11Data, chart11Div); 
                $("#chart11_div").highcharts().reflow();
            }
        }
      });
//      
//      $('.infobutton').click(function(){
//        console.log("inside click");
//      });
  });
  
//  function redrawChart(chartOptions, chartData, chartDiv) {      
//    var chart = new google.visualization.ColumnChart(document.getElementById(chartDiv));
//     chart.draw(chartData, chartOptions);
//  }
  
  </script>

           

</head>
    
<body class="yui-skin-sam" style="background-color:#EEEEEE;overflow-x:hidden;" >
    <?php
        
        //var_dump(array_keys($this->national_consumption_by_method)); exit;
    ?>
	<div id="pageHolder" style="margin:0px;background-color:#EEEEEE;">

		<div id="header"><?php require_once('views/scripts/headerhome.phtml');?></div>
		<div id="content" style="padding:0px;background-color:white;">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  //require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>
			
			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->

			<!--<body class="docs slim framebox_body">-->
                            
                            
    <?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>                       
                                
                                
                                
				
                            <div class="row sidebar" style="background-color:#EEEEEE;margin-top:20px;height:100%;">
                                <div class="col-md-2">
	
                                    <?php  
                                    
                                        require_once('views/scripts/dashboard/left_buttonshome.phtml');
                                    ?>				
        
                                </div>
                                
                               <div class="col-sm-10" style="background-color:white;height:100%;padding-top:10px;">
                                
                                
                               