<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0 transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}
    
 
.hometabs.ui-widget-header {
    background: #eeeeee !important;
    font-size: 12px;
    border-top: solid 2px; 
}
    
.small-tab{
    background-color:white;
    font-size:12px;
    padding:2px;
}
    
   

body {font-family: "Lato", sans-serif;}


    
    

</style>

    
<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css"></link>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />

<link rel="stylesheet" href="<?php echo $this->base_url; ?>/bootstrap/css/bootstrap.min.css"></link>

</head>

<?php

require_once('views/helpers/Location.php');
require_once('views/helpers/ScriptContainer.php');
?>
    

<?php
require_once('views/helpers/TrainingViewHelper.php');
require_once('views/helpers/FormHelper.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
   

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></link>

<script src="//code.jquery.com/jquery-1.10.2.js"></script>

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<link rel="stylesheet" href="http://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"></link>

<script src="http://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></link>

<script src="<?php echo $this->base_url; ?>/bootstrap/js/bootstrap.min.js"></script>
   
    <script>
  $(function() {
      
      $('#myTable').DataTable();
   
  });
 
  </script>  

    <style>
        
        legend {
     display:block; 
    width: 15%; 
    padding:0;
    /* padding: 0; */
    /* margin-bottom: 20px; */
     font-size: 14px;
    /* line-height: inherit; */
    /* color: #333; */
      border: 0; 

}



        
    </style>
    
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php print t('Add').' '.t('Training').' '.t('Location'); ?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

  
</head>
<body class="yui-skin-sam" <?php if ( $this->setting['display_region_b'] && !$this->viewonly) { ?>onload="filterSubTypeOptions('select_location_province','select_location_district');hideRegion_c_id();" <?php }else{ ?>onload="hideRegion_c_id();"<?php } ?>>
<div id="pageHolder">
  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">
                            
                      
                                
		