

  <script type="text/javascript">
  function hideRegion_c_id(){
                    document.getElementById("region_c_id").style.display = "none";
                    document.getElementById("region_c_id").style.visibility = "hidden";
                    
                    document.getElementById("region_c_lbl").style.display = "none";
                    document.getElementById("region_c_lbl").style.visibility = "hidden";
                    
                    document.getElementById("showregionc_id").style.display = "none";
                    document.getElementById("showregionc_id").style.visibility = "hidden";
                    
                    
                    }
  
  </script>
  <?php
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        require_once('views/scripts/template/template2.phtml');
                                    ?>

  <div style="background-color:#f4f0ec;padding:5px;">
		<h1><?php print t('Add').' '.t('Training').' '.t('Location'); ?></h1>

    <p><?php print t('Please enter').' '.t('Training').' '.t('location information'); ?>:</p>
    <br>

		<?php  require_once('views/scripts/training/training_template_locationform.phtml'); ?>

    <?php if ($this->hasACL('import_training_location')) : ?>
    <!-- import location button -->
     
    <span id="importlocation" class="yui-button yui-push-button" style="float:right;">
      <span class="first-child">
        <button onclick="location.href='<?php echo $this->base_url; ?>/facility/importLocation';return false;" type="button" tabindex=1 id="locationImportBtn" class="yui-button yui-push-button"><?php tp('Import location from Excel');?></button>
      </span>
    </span>
    <?php endif; ?>  
    <button type="button" id="submitLocation" style="float:right;margin-right:700px;" ><?php print t('Add Location'); ?></button>
    <br/><br/>
      
    <div class="actionBtn" >
				
		<script type="text/javascript">
			addAjaxSubmit('submitLocation','addLocationForm','<?php echo $this->base_url;?>/training/location-add/info/extra/outputType/json');
		</script>


  </div>
 </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>

</body>
</html>