
  <script type="text/javascript">
  function hideRegion_c_id(){
                    document.getElementById("region_c_id").style.display = "none";
                    document.getElementById("region_c_id").style.visibility = "hidden";
                    
                    document.getElementById("region_c_lbl").style.display = "none";
                    document.getElementById("region_c_lbl").style.visibility = "hidden";
                    
                    document.getElementById("showregionc_id").style.display = "none";
                    document.getElementById("showregionc_id").style.visibility = "hidden";
                    
                    
                    }
  
  </script>
  <?php
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        require_once('views/scripts/template/template2.phtml');
                                    ?>

    <h1><?php echo t('Search for').' '.t('Training').' '.t('Location');?></h1>
	   <form action="" method="get">
   <fieldset><legend><?php tp('Select Criteria');?></legend>
       
        <div class="row">
            <div class="col-sm-3"><div class="fieldLabel"><?php echo t('Training').' '.t('Location Name');?></div></div>
            <div class="col-sm-6">
                <div class="form-group">
	              
	                <div class="fieldInput"><select id="training_location_name" name="training_location_name" class="form-control">
		              <option value="">--<?php tp('All');?>--</option>
		             <?php
			      foreach ( $this->location_names as $vals ) {
				if(trim($vals['training_location_name']) == '')
					continue;
				echo '<option value="'.htmlspecialchars($vals['training_location_name']).'" '.((@$this->criteria['training_location_name']) == $vals['training_location_name']? 'SELECTED':'').' >'.$vals['training_location_name'].'</option>';
		}
		?>
	</select></div>
                      
            </div>
        </div>  
        </div>
       
        <div class="row text-center" >
                       <div class="col-sm-12" >
                          <div class="form-group">
		             <?php region_filters_dropdown_db($this, $this->locations, $this->criteria, true, true); ?>
                          </div>                      
                        </div>
        </div>
   
	
	<div class="clear"></div>
	<input type="hidden" name="limit" id="limit" value="1" />
    <input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
   </fieldset>
   </form>
<?php if ( $this->criteria['go'] ) { ?>
		    <div class="hrGrey"></div>
		    <div class="fieldIndentNoMargin" style="background-color:#90EE90;"><?php echo t('Training').' '.t('locations');?> <span class="total"><?php echo $this->count;?>  <?php tp('Results');?></span><?php echo $this->printAndExport();?></div>
			<a href="<?php echo $this->base_url;?>/facility/add-location"><?php echo t('Add new').' '.t('Training').' '.t('location');?></a><br/><br/>
		    <div id="locations"></div>
            <div style="margin-bottom:40px;">  
                        <table id="myTable" class="display"  >
                        
                           <thead>

                             <tr>

                                <th>ID</th>

                                <th>Location Name</th>
            
                                <th>Geopolitical Zone</th>
            
                                <th>State</th>
            

                             </tr>

                            </thead>  
                            
                            <tbody>
                  
         <?php
		       $cnt = 0;
		 	$isFirstRow = true;
			foreach($this->results as $row) {
                    
                echo '

            

                     <tr>

                         <td>
                      
                            
                               '. $row['id'].'
                            
                         
                        </td>

                        <td>
            
                            
                           '.$row['training_location_name'].'
                            
                        
                        </td>
            
                        <td>
                 
                            
                            '. $row['province_name'] .'
                            
                        
                        </td>
            
                        <td>
                        
                            
                         '. ($this->setting['display_region_b']?$row['district_name']:'') .'
                            
                          
                        </td>
            
                       
            

                    </tr>

                ';
                
                        }
                
                ?>
                
                </tbody>
                   
                </table>
                        
            </div>
<?php } ?>
  </div>
  
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>

</body>
</html>