  <?php
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        require_once('views/scripts/template/template2.phtml');
                                    ?>

 <div class="row">
    <div align="center">
	<h1><?php echo t('Search').space.t('Facilities');?></h1>
           
            <form action="" method="get"   >
		<fieldset  class="width" ><legend><?php tp('Select Criteria');?></legend>
                    
                <div class="row">
                    <div class="col-sm-6">

		       <div class="form-group">
                           <input type="text" class="form-control" id="facility_name" name="facility_name" placeholder="<?php echo t('Facility').space.t('Name');?>" >
                        </div>
                        
                    </div>
                </div>
                    <div class="row">
                       <div class="col-sm-12">
                          <div class="form-group">
		             <?php region_filters_dropdown_db($this, $this->locations, $this->criteria, true, true); ?>
                          </div>                      
                        </div>
                    </div>
		
		
		

		
		 <!-- TA:17: 09/04/2014 START-->
<?php if($this->setting['display_facility_type']){?>
		<div class="fieldLabel" id="type_id_lbl"><?php echo t('Facility').space.t('Type');?></div>
		<div class="fieldInput">
		<select id="type_id" name="type_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
		foreach ( $this->facility_types as $vals ) {
						echo '<option value="'.$vals['id'].'" '.((@$this->criteria['type_id']) == $vals['id']? 'SELECTED':'').' >'.$vals['facility_type_phrase'].'</option>';
		}
		?>
		</select></div>
		<?php }?>
		<!-- TA:17:20 fix bug -->
		<?php if($this->setting['display_facility_sponsor']){?>
		<div class="fieldLabel" id="sponsor_id_lbl"><?php echo t('Facility').space.t('Sponsor');?></div>
		<div class="fieldInput">
		<select id="sponsor_id" name="sponsor_id" >
				<option value="">--<?php tp('All');?>--</option>
				<?php
					foreach ( $this->facility_sponsors as $vals ) {
						echo '<option value="'.$vals['id'].'" '.((@$this->criteria['sponsor_id']) == $vals['id']? 'SELECTED':'').' >'.$vals['facility_sponsor_phrase'].'</option>';
				}
				?>
		</select></div>
		<?php }?>

		<div class="clear"></div>
		<input type="hidden" name="limit" id="limit" value="1" />
		<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
	</fieldset>
	</form>
    </div>

               
 
	

<?php if ( $this->criteria['go'] ) { ?>
		    <div class="hrGrey"></div>
		    <div class="fieldIndentNoMargin" style="background-color:#90EE90;"><?php tp('Facilities');?> <span class="total"><?php echo $this->count;?>  <?php tp('Results');?></span><?php echo $this->printAndExport();?></div>
                    <div style="margin-bottom:40px;">  
                        <table id="myTable" class="table-responsive"  >
                        
                           <thead>

                             <tr>

                                <th>ID</th>

                                <th>Facility Name</th>
            
                                <th>Geopolitical Zone</th>
            
                                <th>State</th>
            
                                <th>Local Government Area</th>
          

                             </tr>

                            </thead>  
                            
                            <tbody>
                  
         <?php
		       $cnt = 0;
		 	$isFirstRow = true;
			foreach($this->results as $row) {
                    
                echo '

            

                     <tr>

                         <td>
                      
                            
                               '. $row['id'].'
                            
                         
                        </td>

                        <td>
            
                            
                           '.$row['facility_name'].'
                            
                        
                        </td>
            
                        <td>
                 
                            
                            '. $row['province_name'] .'
                            
                        
                        </td>
            
                        <td>
                        
                            
                         '. ($this->setting['display_region_b']?$row['district_name']:'') .'
                            
                          
                        </td>
            
                        <td>
                          
                            
                           '. ($this->setting['display_region_c']?$row['region_c_name']:'') .'
                            
                        
                        </td>
            

                    </tr>

                ';
                
                        }
                
                ?>
                
                </tbody>
                   
                </table>
                        
            </div>
                    
     
		
<?php } ?>

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>
</div>

</body>
</html>