
      <style type="text/css">
  
          #region_c_id, #region_c_lbl, #showregionc_id{
              display: none;
              visibility: hidden;
          }
                    
                    
                    
  
  </style>
<?php
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        require_once('views/scripts/template/template2.phtml');
                                    ?>
  
 <div style="background-color:#f4f0ec;padding:5px;">


		<h1><?php echo t('View').' '.t('Training').' '.t('Location');?></h1>

		<div class="fieldInput">

    <?php
			$jsnippet = "window.location = '$this->base_url/facility/view-location/id/' + this.value;";
			training_location_dropdown( $this->tlocations, $this->id, 'name="training_location_id" id="select_training_location" onchange="'.$jsnippet.'"'.space.$this->viewonly);
    ?>
  </div>

    <?php if($this->id) : ?>


  		<?php require_once('views/scripts/training/training_template_locationform.phtml'); ?>

  		<?php if(!$this->viewonly): ?>

   		<button type="button" id="submitLocation"><?php tp('Save Changes');?></button>
 		<div style="float:right;">&nbsp;</div><?php if (@$this->okToDelete) { ?><input type="button" id="deleteLocation" name="deleteLocation" value="Delete" class="submitNoArrow"  onclick="doDelete();" /><?php } ?>
  		<script type="text/javascript">
  			addAjaxSubmit('submitLocation','addLocationForm','<?php echo $this->base_url;?>/training/location-add/update/<?php echo $this->id; ?>/info/extra/outputType/json');
  		</script>
    <br/><br/>

      <?php endif; ?>

    <?php endif; ?>
    
 </div>


    <div class="clear"></div>

  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>
<script language="JavaScript">
function doDelete() {
	if(confirm("<?php tp('Are you sure you wish to delete this location?');?>")) {
		window.location = '<?php echo $this->base_url;?>/facility/deleteLocation/id/<?php echo $this->id;?>';
		return false;
	}
}
</script>

</body>
</html>