<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php tp('Person Search');?></title>
		<?php
		require_once('views/helpers/Location.php');
		require_once('views/helpers/ScriptContainer.php');
		print ScriptContainer::$instance->renderCSSHead();
		print ScriptContainer::$instance->renderJSHead();
                
                echo '<link rel="stylesheet" href="http://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" type="text/css">';
		?>
        
                <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
                <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E=" crossorigin="anonymous"></script>
                <script src="http://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
	</head>
    <style>
        .grey {
            background-color: grey !important;
        }
        .grey td.sorting_1 {
            background-color: inherit !important;
        }
    </style>
    <script type="text/javascript">
    
    dataTableObj = null;
    
    $(document).ready(function()
    {
        //This is a dataTable API for filtering rows based on content of the active field
        $.fn.dataTable.ext.search.push(
        function( settings, data, dataIndex ) {
       
        // Get the value of the user status search value set by onchange of the status select element
        var filter = document.getElementById("activeStatusText").value;
        
        var active = data[8]  || 7 ; // use data for the age column
        
        var myRowClasses = settings.aoData[dataIndex].nTr.className.split(" ");
        console.log(myRowClasses);
        
        //alert(filter);
        if(filter == active || filter == "" || filter == "all")
        {
            return true;
        }
        
        
        return false;
     }
    );
        
    })
    
    
    
    function makeJqueryTable(rows, cols)
    {
        //Populate Table Header
        
        var tr = '<tr>';
        
         for(var key in cols)
         {
             var td = "<td>";
             td += cols[key].label;
             td += "</td>";
             
             tr += td;
         }
         
         tr += '</tr>';
         
       $("#peopleTableDiv table thead").append(tr);
       // End of populating Table Header
       
       //Populate Table body
       
       
       
       for(var key in rows)
       {
        var tr = '<tr>';
        var count = 0;
           for(var key2 in rows[key])
           {
               
               var td = '<td>';
               
               if(count == 0)
               {
                   td += "<a href='<?php echo $this->base_url;?>/person/view/id/" + rows[key][key2] + "' >" + rows[key][key2] + "</a>";
               }
               else
               {
                   td += rows[key][key2]
               }
             
             
              td += '</td>';
              
              tr += td;
              
              count++;
           }
           
         tr += '</tr>';
         
         $("#peopleTableDiv table tbody").append(tr);
       }
       
       dataTableObj = $("#peopleTable").DataTable({
        fnRowCallback: function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
     
            if(aData[8].toString().toLowerCase().trim() !== "active" && aData[8].toString().toLowerCase().trim() !== "active provider" && aData[8].toString().toLowerCase().trim()!== "")
            {
               
                $(nRow).addClass('grey')
            }
        }    
       });
    }
    
    function filterByActiveStatus()
    {
        var sel = document.getElementById("activeStatus");
        
        var activeStatus = document.getElementById("activeStatus").options[sel.selectedIndex].value;
        
        console.log("Status  = " + activeStatus);
        document.getElementById("activeStatusText").value = activeStatus;
        
        dataTableObj.draw();
        
        
    }
    
    function changeLimitSubmit(){
        document.getElementById("limit").value = 0;
        document.getElementById("preview").click();
    }
    
    </script>
	<body class="yui-skin-sam" >

		<div id="pageHolder">

			<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
			<div id="content">
				<h1><?php tp('People Search');?></h1>
				<form action="" method="get" name="searchForm" id="personSearchForm">
					<fieldset><legend><?php tp('Select Criteria');?></legend>

                                        <input type="hidden" value="" id="activeStatusText" name="activeStatusText" />
                                            
					<?php region_filters_dropdown($this, $this->locations, $this->criteria, true, false); ?>

					<div class="fieldLabel"  id="facilityInput_lbl"><?php tp('Facility');?></div><div class="fieldInput">

					<?php echo renderFacilityDropDown($this->facilities, $this->criteria['facilityInput'],false); ?></div>

					<div class="clear"></div>

					<!-- course taken -->
					<div class="fieldLabel" id="training_title_option_id_lbl"><?php echo (@$this->translation['Training Name']); ?></div>
					<div class="fieldInput">
						<select id="training_title_option_id" name="training_title_option_id" >
							<option value="">--<?php tp('All');?>--</option>
							<?php
							foreach ( $this->courses as $vals ) {
								echo '<option value="'.$vals['id'].'" '.((@$this->criteria['training_title_option_id']) == $vals['id']? 'SELECTED':'').' >'.$this->truncate($vals['training_title_phrase']).'</option>';
							}
							?>
						</select></div>
						<div class="clear"></div>

						<div class="fieldLabel" id="qualification_id_lbl"><?php tp('Cadre');?></div>
						<div class="fieldInput"><select id="qualification_id" name="qualification_id">
							<option value="">--<?php tp('All');?>--</option>
							<?php
							$lastParent = null;
							foreach ( $this->qualifications as $vals ) {
								if ( !$vals['id'] ) {
									$lastParent = $vals['parent_phrase'];
									echo '<option value="'.$vals['parent_id'].'" '.((@$this->criteria['qualification_id']) == $vals['parent_id']?'SELECTED':'').'>'.htmlspecialchars($vals['parent_phrase']).'</option>';
								} else {
									echo '<option value="'.$vals['id'].'" '.((@$this->criteria['qualification_id']) == $vals['id']?'SELECTED':'').'>&nbsp;&nbsp;'. htmlspecialchars($vals['qualification_phrase']).'</option>';
								}
							}
							?>
						</select></div>
						<div  id="firstAutoComplete">
							<div class="fieldLabel"><?php echo (@$this->translation['First Name']); ?></div><div class="fieldInput"><input id="first_name" type="text" name="first_name" value="<?php echo $this->criteria['first_name'];?>" /><div class="clear"></div><div id="firstContainer" class="autoComplete"></div></div>
						</div>
						<script type="text/javascript">
							var firstAuto = makeAutocomplete('first_name', 'firstContainer', '<?php echo $this->base_url;?>/person/firstList/outputType/text/' );
						</script>
						<div id="lastAutoComplete">
							<div class="fieldLabel"><?php echo (@$this->translation['Last Name']); ?></div><div class="fieldInput"><input id="last_name" type="text" name="last_name" value="<?php echo $this->criteria['last_name'];?>" /><div class="clear"></div><div id="lastContainer" class="autoComplete"></div></div>
						</div>
						<script type="text/javascript">
							var lastAuto = makeAutocomplete('last_name', 'lastContainer', '<?php echo $this->base_url;?>/person/lastList/outputType/text/' );
						</script>
						<div class="clear"></div>
                                                <div class="fieldLabel"></div><div class="fieldInput" style="font-size:11px; font-weight:bold; color: #696969;"><input type="radio" id="is_trainer" value="is_trainer" name="person_type" <?php if ( $this->criteria['person_type'] == 'is_trainer') echo 'CHECKED'; ?> /><label for="is_trainer"><?php echo t('Trainers').' '.t('only');?></label></div>
                                                <div class="fieldLabel"></div><div class="fieldInput" style="font-size:11px; font-weight:bold; color: #696969;"><input type="radio" id="is_participant" value="is_participant" name="person_type" <?php if ( $this->criteria['person_type'] == 'is_participant' ) echo 'CHECKED'; ?> /><label for="is_participant"><?php echo t('Participants').' '.t('only');?></label></div>
                                                <div class="fieldLabel"></div><div class="fieldInput" style="font-size:11px; font-weight:bold; color: #696969;"><input type="radio" id="is_unattached_person" value="is_unattached_person" name="person_type" <?php if ( $this->criteria['person_type'] == 'is_unattached_person' ) echo 'CHECKED'; ?> /><label for="is_unattached_person"><?php tp('Untrained Only');?></label></div>
                                                <div class="fieldLabel"></div><div class="fieldInput" style="font-size:11px; font-weight:bold; color: #696969;"><input type="radio" id="is_everyone" value="is_everyone" name="person_type" <?php if ( $this->criteria['person_type'] == 'is_everyone' ) echo 'CHECKED'; ?> /><label for="is_everyone"><?php tp('Everyone');?></label></div>
<?php
	if (isset($this->setting['display_mod_skillsmart']) && ($this->setting['display_mod_skillsmart'] == 1)){
?>
						<div class="fieldLabel"></div><div class="fieldInput" style="font-size:11px; font-weight:bold; color: #696969;"><input type="checkbox" id="is_complete" value="is_complete" name="is_complete" <?php if ( $this->criteria['is_complete'] == 'is_complete' ) echo 'CHECKED'; ?> /><?php tp('Incomplete competence');?></div>
<?php
	}
?>
						<input type="hidden" name="limit" id="limit" value="1" />
						<input type="submit" class="submitNoArrow" id="preview" name="go" value="<?php tp('Preview');?>" />
					</fieldset>
				</form>
				<?php if ( $this->criteria['go'] ) { ?>

<?php
#	foreach($this->results as $row) {
#		var_dump ($row);
#	}
?>

				<div class="hrGrey"></div>
				<div class="fieldIndentNoMargin"><?php tp('People');?> <span class="total"><?php echo $this->count;?>  <?php tp('Results');?></span><?php echo $this->printAndExport();?></div>
					<a href="<?php echo $this->base_url;?>/person/add"><?php tp('Add New Person');?></a><br/><br/>
                                        <div style="width:310px !important; float:left !important">
                                        <span style="font-size: 11px;font-weight: bold; color:#696969;font-family: Arial, Helvetica, sans-serif;">Filter By Active status</span> 
                                        <select id="activeStatus" onchange="filterByActiveStatus()">
                                            
                                            <option value="all">All</option>
                                            
                                            
                                            <?php 
                                            //print_r($this->person_status);
                                          
                                            foreach($this->person_status as $pstatus){
                                                $titleShow = $pstatus['title'];
                                                $titleValue = strtolower(trim($pstatus['title']));
                                                echo '<option value="'.$titleShow.'">'.$titleShow.'</option>';
                                                if($pstatus['id']==1){
                                                  //  echo '<option value="inactive">All Inactive Providers</option>';
                                                }
                                            }
                                            ?>
                                        </select>
                                        </div>
                                        <div id="infobutton" class="infobutton" style="width:70px !important; float: left;">
            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
            <div id="" class="infodiv" >
               “Active Status” refers to health workers marked as Active Providers that are currently actively providing clinical services in a health facility. These health workers are counted towards the total health workforce need for family planning Nigeria.
<br/><br/>
“Inactive Status” refers to designations including Retired Provider, National Official, State Official, LGA Official or Deceased status indicates that the health worker is not actively providing clinical services in a health facility. These health workers are not counted towards the total health workforce need although they may serve other important functions such as supervision and training of trainers.

            </div>
 </div>
                                        <br /><br />
                                        
                                        <div id="peopleTableDiv">
                                            
                                            <table id="peopleTable" class="display">
                                                
                                                <thead>
                                                    
                                                </thead>
                                                
                                                <tbody>
                                                    
                                                </tbody>
                                                
                                            </table>
                                            
                                        </div> <br /><br />
                                        
					<div id="people"></div>
                                        
                                        
                                        
                                       
                                        
                                       
					<script type="text/javascript">
                                                  
						var peopleData = [
                                                    
						<?php
                                                
						$cnt = 0;
						$isFirstRow = true;

						foreach($this->results as $row) {
							$showperson = true;

							$required = isset ($row['comps']['required']) ? $row['comps']['required'] : 0;
                                                        
                                                        
							$answered = isset($row['comps']['answers'])?count($row['comps']['answers']):0;
                                                        
                                                        if(isset($this->criteria['is_complete'])) {
                                                            if ($this->criteria['is_complete'] == 'is_complete')
                                                            {
                                                                    if ($required <= $answered){
                                                                            $showperson = false;
                                                                    }
                                                            }
                                                        }

							if ($showperson){
								if ( (isset($_REQUEST['limit']) AND !$_REQUEST['limit'])  or ($cnt < 100) ) {
									if (!$isFirstRow )
									echo ',';
									$isFirstRow = false;

									$thisrow = array();
									$thisrow[] = $row['id'];
									$thisrow[] = addslashes($row['first_name']);


									if ( $this->setting['display_middle_name'] &&  !$this->setting['display_middle_name_last'] ) {
										$thisrow[] = addslashes($row['middle_name']);
									}
									
                                                                        $thisrow[] = addslashes($row['last_name']);
									
                                                                        if ( $this->setting['display_middle_name'] && $this->setting['display_middle_name_last'] ) {
										$thisrow[] = 'M'; //addslashes($row['middle_name']);
									}
                                                                        
									// Some results do not contain province_name
									if (! array_key_exists('province_name', $row)) {
										$row['province_name'] = '(no region)';
									}
									if (isset($this->setting['display_mod_skillsmart']) && ($this->setting['display_mod_skillsmart'] == 1)){
										// ALSO DISPLAY SKILLSMART SPECIFIC COLUMNS
										
                                                                                $thisrow[] = addslashes($row['district_name']);
                                                                                $thisrow[] = addslashes($row['region_c_name']);
										$thisrow[] = addslashes($row['facility_name']);
                                                                               
										$thisrow[] = addslashes($row['qualification_phrase']);
                                                                                
										$thisrow[] = addslashes($row['province_name']);
                                                                             
                                                                                $thisrow[] = addslashes($row['phone_mobile']);
                                                                                
                                                                                $thisrow[] = (string) addslashes($row['active']);


										if($row['res']=="0"){
											$showred=' style=\"color:Red\"';
										} else {
											$showred="";
										}

                                                                                        // New database driven
                                                                                   if(isset($row['comps'])) {
                                                                                        if (count ($row['comps']) > 0){
                                                                                                if ($required > $answered){
                                                                                                        // INCOMPLETE
                                                                                                        $thisrow[] = '<a href=\\\''.$this->base_url.'/person/editcompetency/id/'.$row['id'].'\\\'>Enter data</a>';
                                                                                                        $thisrow[] = "";
                                                                                                } else {
                                                                                                        // COMPLETE
                                                                                                        $thisrow[] = '<a href=\\\''.$this->base_url.'/person/editcompetency/id/'.$row['id'].'\\\'>Enter data</a>';
                                                                                                        $thisrow[] = '<a href=\\\'' . $this->base_url . '/person/viewcompetency/id/' . $row['id'] . '\\\'>View</a>';
                                                                                                }
                                                                                        } else {
                                                                                                $thisrow[] = '';
                                                                                                $thisrow[] = '';
                                                                                        }
                                                                                   }
                                                                                   else {
                                                                                                $thisrow[] = '';
                                                                                                $thisrow[] = '';
                                                                                        }
									} else {
										// ONLY DISPLAY NON-SKILLSMART COLUMNS
										
										$thisrow[] = addslashes($row['district_name']);
                                                                                $thisrow[] = addslashes($row['region_c_name']);
                                                                                $thisrow[] = addslashes($row['facility_name']);
                                                                                
										$thisrow[] = trim(addslashes($row['qualification_phrase'])); // bugfix.
                                                                                $thisrow[] = addslashes($row['active']);
                                                                              // $thisrow[] = addslashes($row['email']);
                                                                                //$thisrow[] = addslashes($row['phone_mobile']);
										}

									echo "['" . implode("','", $thisrow) . "']\n";
									$cnt++;
								}
							}
						}
						?>];
                                                
                                                
                                                    
						var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
							if ( (sData == null) || (sData.length == 0) )
							sData = '&nbsp;&nbsp;&nbsp;';
							elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/person/view/id/" + oRecord.getData("id") + "' >" + sData + "</a>";
						}

						var peopleColumnDefs = [
						{key:"id", label: "ID", sortable:true, resizable:true,
						formatter: formatViewUrl},
						{key:"first_name", label: "<?php echo addslashes((@$this->translation['First Name'])); ?>", sortable:true, resizeable:true},
						<?php if ( $this->setting['display_middle_name'] && !$this->setting['display_middle_name_last'] ) { ?>
							{key:"middle_name", label: "<?php echo addslashes((@$this->translation['Middle Name'])); ?>", sortable:true, resizeable:true},
						<?php }?>
						{key:"last_name", label: "<?php echo addslashes((@$this->translation['Last Name'])); ?>", sortable:true, resizeable:true},
						<?php if ( $this->setting['display_middle_name'] && $this->setting['display_middle_name_last'] ) { ?>
							{key:"middle_name", label: "<?php echo (@$this->translation['Middle Name']); ?>", sortable:true, resizeable:true},
						<?php }?>
						
                                                    {key:"district_name", label: "<?php echo 'State' ;?>", sortable:true, resizeable:true},
                                                    {key:"region_c_name", label: "<?php echo 'LGA';?>", sortable:true, resizeable:true},
                                                    {key:"facility_name", label: "<?php echo 'Facility Name';?>", sortable:true, resizeable:true},
                                                    
						{key:"qualification_phrase", label: "<?php tp('Cadre');?>", sortable:true, resizeable:true},
                                                {key:"active", label: "Status", sortable:true, resizable:true},
                                                    <?php ?> //TA:17: 09/09/2014
						
						
						
                                                <?php 	if (isset($this->setting['display_mod_skillsmart']) && ($this->setting['display_mod_skillsmart'] == 1)){ ?>
						,{key:"comp", label: "<?php tp('Competence');?>", sortable:false, resizeable:false},
			{key:"rpt", label: "<?php tp('Report');?>", sortable:false, resizeable:false}
                                <?php	} 	?>
						];
                                                
                                                 makeJqueryTable(peopleData,peopleColumnDefs);
						//makeDataTable("people", null, peopleData, peopleColumnDefs);
					</script>                
					<?php if ($cnt < count($this->results)) { ?>
					[<?php tp('Limited to 100 rows');?>]  <a href="#"  onclick="changeLimitSubmit();"> Full Results </a>
                                     <?php } } ?>
				</div>
				<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
                                 <!--<script type="text/javascript" src="../js/tp/functions.js"></script>-->
			</div>
		</body>
	</html>