<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	position: relative;
}

#homecontent-mid {
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px; 
}

.sliderdiv {
	float: left;
}

.main-search {
	float: left;
	overflow: hidden;
}

.nav-buttons {
	float: left;
	overflow: hidden;
}


</style>

<!--<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">-->

<?php
    require_once('views/helpers/ScriptContainer.php');
    print ScriptContainer::$instance->renderCSSHead();
    print ScriptContainer::$instance->renderJSHead();
?>


      <!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
       <!--<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />-->
    <!--<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css">-->


<style>
    
    .infobutton {
        padding-right: 13px;
    }
    
    <?php if(isset($this->consumption_bsm) && !empty($this->consumption_bsm) || (isset($this->consumption_bmmandlocation) && !empty($this->consumption_bmmandlocation))) { ?>
    
        .infoButtonFirst {
            padding-right: 0px;
            margin-right: -86px;
        }
    
    <?php } ?>
    
</style>    

    

<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" defer async></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />

<!--<script src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>-->
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>-->

<script src="../js/tp/functions.js"></script>

<script>
    function checkCommoditySelection(){
//        console.log(combo.options);
//        console.log(combo.options[combo.selectedIndex]);
//        console.log(combo.options[combo.selectedIndex].value);

        //var combo = document.getElementById("comm_id");
        //var selectedValue = combo.options[combo.selectedIndex].value;
        //alert('submitting: ' + selectedValue); 
        
        //if(selectedValue != 0) return true;
                
        //return false;
    }
</script>

<script>
  $(function() {
    $( "#accordion" ).accordion({active: 1});
  });
  </script>
</head>
<body class="yui-skin-sam">
    
    <?php   
            //echo 'high<br/><br/>' ;
            //var_dump($this->consumption_by_method); 
            //var_dump($this->consumption_bsmandlocation_first); 
    ?>
    
	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>
				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>
			</div>

			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
                                <?php require_once('views/scripts/consumption/top_buttons.phtml');?>
			</div>
			<div class="hrNav"></div>

			<!-------   /////////////////////////// make left buttons ////////////////////// -->
			<div class="nav-buttons">
				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    require_once('views/scripts/dashboard/left_buttons.phtml');
                                ?>
			</div>
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>
			
			<!-------   /////////////////////////// charts ////////////////////// -->

			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">
				
				<div class="hrNav" id="hrr"></div>
				<div class="hrNav"></div>
				
				
				    <div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv" style="margin-left: 20px;">
                                                                    <div id="infobutton" class="infobutton infoButtonFirst  hidden" style="margin-bottom:-23px;">
                                                                        <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                        <div id="" class="infodiv" >
                                                                            ...
                                                                        </div>
                                                                    </div>
								    <div class="hrNav"></div>
									<div id="chart11_div" style="width: 550px; height: 400px; margin-left:20px;"></div>
									</div>
									
								</div>
							</div>
						</div>			
					</div>
					
					<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
					
					<div id="bottomrow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv" style="margin-left: 20px; margin-top: 0px;">
                                                                            <div id="infobutton" class="infobutton hidden" style="margin-bottom:-23px;">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    ...
                                                                                </div>
                                                                            </div>
                                                                        <div class="hrNav"></div>
    									<div id="chart13_div" style="width: 550px; height: 450px;margin-left:20px;"></div>
									</div>
									
								</div>
							</div>
						</div>
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
                                                <div class="main-search"></div>
					</div>
					
				</div>
				
				
	</div>

		<div class="hrNav"></div>
		<div class="clear"></div>
		
		<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->

		<!-------   /////////////////////////// main gnr ////////////////////// -->


<script type="text/javascript">
    //console.log(<?php //echo json_encode($this->consumption_by_method); ?>);
    //set high charts global color scheme for all high charts instances on this page
    $(function () {
        Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
    });
    
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);
  $(function () {
	  document.getElementById("allCharts").style.marginLeft="130px";

        //drawTest();
	<?php if(isset($this->consumption_by_method) && !empty($this->consumption_by_method)) { ?>
                console.log("koko 5");
                drawChart11();
        <?php } ?>
            
        <?php if(isset($this->consumption_overtime) && !empty($this->consumption_overtime)) { ?>
            console.log("koko 1");
            drawChart13();
        <?php } ?>
            
        <?php if(isset($this->cons_all_BSL_overtime) && !empty($this->cons_all_BSL_overtime)) { ?>
            console.log("koko 2");
            drawChartAllConsumptionByLocationOvertime();
        <?php } ?>
            
        <?php if(isset($this->consumption_bsm) && !empty($this->consumption_bsm)) { ?>
                console.log("koko 3");
                drawChartConsumptionBSM_First();
                drawChartConsumptionBSM();
        <?php } ?>
            
        <?php if(isset($this->consumption_bmmandlocation) && !empty($this->consumption_bmmandlocation)) { ?>
                console.log("koko 4");
                drawChartConsumption_BMMAndLocation_First();
                <?php if(isset($this->showlinechart) && $this->showlinechart==TRUE){ ?>
                    drawChartConsumption_BSMAndLocation();
                <?php } else if (isset($this->commlinechart) && $this->commlinechart==TRUE){
                          //$this->cons_all_BSL_overtime = $this->consumption_bmmandlocation;
                ?>
                            drawChartMMSLOvertime();
                <?php } else { ?>
                    $('#chart13_div').html('<div style="font-weight:bold; padding:5px;background: #eeeeee;border:1px solid #cccccc;">The consumption chart for the last 12 months will not be displayed when multiple locations and multiple commodities are selected. Please either select a single commodity and multiple locations, or multiple commodities and a single location to display this chart.</div>');
        <?php   } 
            }
        ?>
            
        
	//var currentLevel;
	//currentLevel = <?php //echo '\'' . $this->location_data[0][name] . '\''; ?>;
		 
  });
  
  
  
  
function drawChart11() {
       var consumptionData = <?= 
                                isset($this->consumption_by_method) ?
                                $this->consumption_by_method :
                                '{}'  //empty json object
                             ?>;
       var methods = new Array(); var values = new Array();
       for(key in consumptionData){
            row = consumptionData[key];
            methods.push(row['method']);
            
            if(key == 1)
                 values.push(Math.round(row['consumption']/10));
            else 
                values.push(parseInt(row['consumption']));
       }
          
          var title_data = '';
          <?php if(empty($this->cons_all_BSL_overtime)){ ?>
              title_data = <?php echo "'Consumption by method, $this->date'"; ?>; 
              subtitleText = <?php echo "'($this->date)'"; ?>
          <?php } else { ?>
              title_data = <?php echo "'Consumption by method in selected geographies, $this->date'"; ?>;
              subtitleText = <?php echo "'($this->date)'"; ?>
          <?php } ?>
              
	
        $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart11_div")
                           .siblings('.infobutton')
                           .find('.infodiv')
                           .html('This chart shows consumption of each FP commodity in the ' +
                                    'most recent month or selected date(s) for the selected geography. ' +
                                    'Given the different scale of male condom consumption, consumption ' +
                                    'is reflected in units of 10 male condoms, while all other commodities ' +
                                    'are reflected as a single commodity.'
                                 );
                           $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 450
                },
                title: {
                    text: title_data,
                    style:{
                        "fontSize": "16px",
                        "fontWeight": "bold",
                        "fontFamily":"Arial"
                    },
                    align: 'center',
                    x: -20
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                    title:{
                        text:'FP Commodity',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: methods
                },
                yAxis: {
                    title: {
                        text: '#  Commodities Consumed',
                        style:{ "fontWeight": "bold" }
                    }
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>: ' + thousandSeparator(this.y);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: values
                }]
            });
}



function drawChart13() {
        var consumptionOvertime = <?= 
                        isset($this->consumption_overtime) ?
                        $this->consumption_overtime :
                        '{}'  //empty json object
          ?>;
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = '<?= $this->end_date; ?>';
        
        dataArray = processConsumptionOvertimeData(consumptionOvertime);
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
                        
                <?php 
                if(!empty($this->selectedDatemultiple)){

                    $titleText = (sizeof($this->selectedDatemultiple)>1) ?"across selected dates" : "across selected date(s)";
                }else{
                   $titleText = $this->start_date." to ".$this->end_date;
                }
                ?>
                        
                        
                        var title_data = <?php echo "'Consumption of FP commodities, $titleText'"; ?>; 
                        var subtitleText = <?php echo "'($titleText)'"; ?>
                            
                        $('#chart13_div').highcharts({
                            chart: {
                                //type: 'column',
                                reflow: true,
                                plotBackgroundColor: null,
                                plotBorderWidth: null,
                                plotShadow: false,
                                events: {
                                    load:function(){
                                        $("text:contains(Highcharts.com)").css("display","none");
                                        $("#chart13_div")
                                       .siblings('.infobutton')
                                       .find('.infodiv')
                                       .html('This chart shows consumption of each FP commodity for each of ' +
                                             'the last 12 months or selected date(s) for the selected geography.');
                                       $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                                    }
                                },
                                height: 450
                            },
                            title: {
                                text: title_data,
                                style:{
                                    "fontSize": "16px",
                                    "fontWeight": "bold",
                                    "fontFamily":"Arial"
                                },
                                x: -20
                            },
                            legend: {
                                layout: 'horizontal',
                                align: 'center',
                                borderWidth: 1
                            },
                            xAxis: {
                                title:{
                                    text:'Month',
                                    style:{ "fontWeight": "bold" }
                                },
                                categories: monthNamesWithYears
                            },
                            yAxis: {
                                title: {
                                     text: '#  Commodities Consumed',
                                     style:{ "fontWeight": "bold" }
                                },
                                plotLines: [{
                                    value: 0,
                                    width: 1,
                                    color: '#808080'
                                }]
                            },
                            tooltip: {
                                formatter: function () {
                                    return '<b>' + this.x + '</b><br/>' +
                                        '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y);
                                }
                            },
                            plotOptions: {
                                series: {
                                    marker: {
                                        enabled: true
                                    }
                                }
                            },
                            credits: {enabled: false},
                            series: dataArray                       
                        });         
         
    }//end drawchart13
    
    
    
    
    function drawChartAllConsumptionByLocationOvertime() {
        var consumptionOvertime = <?= 
                        isset($this->cons_all_BSL_overtime) ?
                        $this->cons_all_BSL_overtime :
                        '{}'  //empty json object
          ?>;
        
        dataArray = processConsumptionOvertimeData(consumptionOvertime);
        selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        startDate = <?php echo json_encode($this->end_date); ?>;
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        
        
           <?php 
               if(!empty($this->selectedDatemultiple)){
                   
                   $titleText = (sizeof($this->selectedDatemultiple)>1) ?"across selected dates" : "across selected date";
               }else{
                  $titleText = $this->start_date." to ".$this->end_date;
               }
               ?>
        
         var title_data = '';
          <?php if(isset($this->single_location)){ ?>
              title_data = <?php echo "'Consumption of FP commodities in selected geographies, $titleText'"; ?>; 
              subtitleText = <?php echo "'($titleText)'"; ?>
          <?php } ?>
              
          
        
        $('#chart13_div').highcharts({
                chart: {
                    //type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div")
                           .siblings('.infobutton')
                           .find('.infodiv')
                           .html('This chart displays the consumption of each FP commodity for the last 12 months or selected date(s) in the selected geography.');
                           $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 450
                },
                title: {
                    text: title_data,
                    style:{
                        "fontSize": "16px",
                        "fontWeight": "bold",
                        "fontFamily":"Arial"
                    },
                    x: -20
                },
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    borderWidth: 1
                },
                xAxis: {
                    title:{
                      text:'Month',
                      style:{ "fontWeight": "bold" }
                       },
                    categories: monthNamesWithYears
                },
                yAxis: {
                    title: {
                       text: '#  Commodities Consumed',
                       style:{ "fontWeight": "bold" }
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y);
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    }
                },
                credits: {enabled: false},
                series: dataArray
                
            });
     
    }
    
    
    function drawChartConsumption_BMMAndLocation_First(){
       
            var consumptionOvertime = <?= 
                    isset($this->consumption_bmmandlocation_first) ?
                    $this->consumption_bmmandlocation_first :
                    '{}'  //empty json object
                ?>;
                
              var consumptionDataObject = consumptionOvertime['consumption'];
              var selectedCommoditites = Object.values(consumptionOvertime['methods']);
              var seriesObjectsArray = new Array(); 
              
              for(selectedLocation in consumptionDataObject){
                  var seriesObject = {};  //one row/object in the series
                  seriesObject.name = selectedLocation;
                  seriesObject.data = new Array();
                  
                    for(var key in selectedCommoditites){
                        commodity = selectedCommoditites[key];
                        consumption =  commodity.toLowerCase() == "male condoms" ?
                                       consumption = Math.round(consumptionDataObject[selectedLocation][commodity] / 10) :
                                       parseInt(consumptionDataObject[selectedLocation][commodity]);

                        seriesObject.data.push(consumption);
                    }

                    seriesObjectsArray.push(seriesObject);
                }
            
            
            //display highcharts
            $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    width: 650,
                    height: 350,
                  events: {
                      load:function(){
                          $("text:contains(Highcharts.com)").css("display","none");
                          $("#chart11_div").siblings('#infobutton').removeClass('hidden');
                          $("#chart11_div")
                            .siblings('.infobutton')
                            .find('.infodiv')
                            .html('This chart shows consumption of each FP commodity in the ' +
                                     'most recent month or selected date(s) for the selected geography. ' +
                                     'Given the different scale of male condom consumption, consumption ' +
                                     'is reflected in units of 10 male condoms, while all other commodities ' +
                                     'are reflected as a single commodity.'
                            );
                      }
                  }
                },
                title: { 
                    text: 'Consumption by method <br/>for selected commodities and geographies in <?php echo date("F Y",strtotime($this->selectedDate)); ?>' ,  
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                    x: -70,
                },
                tooltip: {
                    useHtml: true,
                    formatter: function (){
                        return '<b>'+ (this.key.toLowerCase() == "male condoms" ? this.key + "(unit x10)" : this.key) +'</b><br>' + 
                               '<b>' + this.series.name + ': </b>' + thousandSeparator(this.y);
                    },
//                    pointFormat: '{point.x},{point.y}',
//                    pointFormatter:function(){
//                        console.log('pf: ' + this.x, this.y);
//                    }
                },
                xAxis: { 
                    categories: selectedCommoditites,  //array of x-axis categories
                    title:{
                        text:'FP Commodity',
                        style:{ "fontWeight": "bold" }
                    },
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: 'Commodities Consumed',
                        style:{ "fontWeight": "bold" },
                        align: 'high'
                    },
                    labels: {
                        overflow: 'justify'
                        //format: '{value}'
//                        formatter: function () {                           
//                            return thousandSeparator(this.value);
//                        }
                    }
                },
                plotOptions: {
                    column: {
                        dataLabels: {
                            enabled: true,
                        },
//                        formatter: function(){
//                            return thousandSeparator(10000);
//                        }
                    },
                    series: {
                        pointWidth: 50,
                        stacking: 'normal',
                        point: {
                            events: {
                                mouseOver: function (e) {
                                    //console.log(this.x, this.y)
                                }
                            }
                        }
                    }
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    //reversed: true,
                    verticalAlign: 'top',
                    x:-10,
                    y: 80,
//                    floating: true,
                    //borderWidth: 1,
                    //borderRadius: 5,
//                  backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                    shadow: true
                },
                credits: { enabled: false },
                series: seriesObjectsArray
                
            });

}
    
    
    function drawChartConsumption_BSMAndLocation(){
        var consumptionOvertime = <?= 
                        isset($this->consumption_bmmandlocation) ?
                        $this->consumption_bmmandlocation :
                        '{}'  //empty json object
          ?>;
                  
        console.log('consumptionOvertime', consumptionOvertime);
        var methodObject = <?= json_encode($this->methods); ?>;
        var commodityName = methodObject[Object.keys(methodObject)[0]];
        dataArray = processMethodConsumptionOvertimeData(consumptionOvertime, commodityName);        
        selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        startDate = <?php echo json_encode($this->end_date); ?>;
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        console.log('monthNamesWithYears', monthNamesWithYears);
        console.log('dataArray', dataArray);
                                   
            var titleText = 'Consumption by method <br/>for selected commodities and geographies, ' +
                            '<?php echo  "$this->start_date to $this->end_date"; ?>';
            

            $('#chart13_div').highcharts({
                chart: {
                    //type: 'line',
                    height: 470,
                    //spacingLeft: -20,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                            $("#chart13_div")
                            .siblings('.infobutton')
                            .find('.infodiv')
                            .text("This chart displays the consumption of " + commodityName + 
                                  " for each of the last 12 months or selected date(s) in the selected geography");
                        }
                    }
                },
                title: {
                    text: titleText,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                    x: -20 //center
                },
                xAxis: {
                    title:{
                    text:'Month',
                    style:{ "fontWeight": "bold" }
                },
                    categories: monthNamesWithYears
                },
                yAxis: {
                     title: {
                     text: '#  Commodities Consumed',
                     style:{ "fontWeight": "bold" }
                      },
//                                    labels: {
//                                        format: '{value}%'
//                                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y) + '<br/>';
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    }
                },
                legend: {
                    layout: 'horizontal',
                    //verticalAlign: 'center',
                    align: 'center',
                    borderWidth: 1
                    //shadow: true
                },
                series: dataArray
            });
         
    }
    
    
    function drawChartMMSLOvertime() {
        var consumptionOvertime = <?= 
                        isset($this->consumption_bmmandlocation) ?
                        $this->consumption_bmmandlocation :
                        '{}'  //empty json object
          ?>;

        dataArray = processConsumptionAndLocationOvertimeData(consumptionOvertime);        
        selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        startDate = <?php echo json_encode($this->end_date); ?>;
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        
               <?php 
               if(!empty($this->selectedDatemultiple)){
                   
                   $titleText = (sizeof($this->selectedDatemultiple)>1) ?"across selected dates" : "across selected date";
               }else{
                  $titleText = $this->start_date." to ".$this->end_date;
               }
               ?>
                
              var title_data = <?php echo "'Consumption of FP commodities in selected geographies, $titleText'"; ?>;
              var subtitleText = <?php echo "'($titleText)'"; ?>
        
        $('#chart13_div').highcharts({
                chart: {
                    //type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div")
                           .siblings('.infobutton')
                           .find('.infodiv')
                           .html('This chart displays the consumption of each of the selected FP commodity for the last 12 months or selected date(s) in the selected geography.');
                           $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 450
                },
                title: {
                    text: title_data,
                    style:{
                        "fontSize": "16px",
                        "fontWeight": "bold",
                        "fontFamily":"Arial"
                    },
                    x: -20
                },
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    borderWidth: 1
                },
                xAxis: {
                    title:{
                     text:'Month',
                     style:{ "fontWeight": "bold" }
                                },
                    categories: monthNamesWithYears
                },
                yAxis: {
                    title: {
                      text: 'Commodities Consumed',
                      style:{ "fontWeight": "bold" }
                                },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y);
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    }
                },
                credits: {enabled: false},
                series: dataArray
                
            });
      
    <?php // }//end if isset($this->cons_all_BSL_overtime) ?>


    }//end function 
    
</script>


<script>
  //devsite.github.Link.convertAnchors();
  //window.prettyPrint();
</script>	
                
        <script src="../js/highcharts/highcharts.js"></script>
        <script src="../js/highcharts/modules/exporting.js"></script>   
                
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
<script src="../js/tp/functions.js"></script>
<script src="../js/tp/overtime-ops.js"></script>


</body>

</html>