<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0 transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}
    
 
.hometabs.ui-widget-header {
    background: #eeeeee !important;
    font-size: 12px;
    border-top: solid 2px; 
}
    
.small-tab{
    background-color:white;
    font-size:12px;
    padding:2px;
}
    
   

body {font-family: "Lato", sans-serif;}


    
    

</style>

 <?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
    
<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">



<!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css"></link>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />


<link rel="stylesheet" href="<?php echo $this->base_url; ?>bootstrap/css/bootstrap.min.css"></link>
<!--<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css"></link>-->
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></link>

<link rel="stylesheet" href="<?php echo $this->base_url; ?>css/cssfile.css"></link>

<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>-->
<!--<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" ></script>-->

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script src="<?php echo $this->base_url; ?>bootstrap/js/bootstrap.min.js"></script>

                



<script>
  $(function() {
    //$( "#accordion" ).accordion({header: "h3", collapsible: true, active: false, animated:200, animated:"slide"});
    $( "#tabs").tabs();
    
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  
  $(document).ready(function(){
       $( "#tabs" ).tabs({
        activate: function( event, ui ) {
            var selectedTab = $("#tabs").tabs('option', 'active');
            if(selectedTab == 1){
                //redrawChart(chart11Options, chart11Data, chart11Div); 
                $("#chart11_div").highcharts().reflow();
            }
        }
      });
//      
//      $('.infobutton').click(function(){
//        console.log("inside click");
//      });
  });
  
//  function redrawChart(chartOptions, chartData, chartDiv) {      
//    var chart = new google.visualization.ColumnChart(document.getElementById(chartDiv));
//     chart.draw(chartData, chartOptions);
//  }
  
  </script>

           

</head>

<?php
    

require_once('views/helpers/Location.php');
//require_once('views/helpers/ConsumptionLocation.php');
require_once('views/helpers/ScriptContainer.php');

//$current_view = '/'.$path[1].'/'. $path[2]; 
?>

<?php  //file_put_contents('c:\wamp\logs\php_debug.log', 'top_buttons 1 >'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();   
       //var_dump("current_view=", $current_view, "END");
       //$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX); 

?>

    
<body class="yui-skin-sam" style="background-color:#EEEEEE;overflow-x:hidden;" >
    <?php
        
        //var_dump(array_keys($this->national_consumption_by_method)); exit;
    ?>
	<div id="pageHolder" style="margin:0px;background-color:#EEEEEE;padding-bottom:0px;">

		<div id="header"><?php require_once('views/scripts/headerhome.phtml');?></div>
		<div id="content" style="padding:0px;background-color:#EEEEEE;">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  //require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>
			
			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->

			<!--<body class="docs slim framebox_body">-->
                            
                            
                          
                                
                                
                                
				
                            <div class="row sidebar" style="background-color:#EEEEEE;margin-top:20px;height:100%;">
                                <div class="col-sm-2" style="height:100%;">
		
                                    
                                     <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'consumption';
                                        require_once('views/scripts/dashboard/left_buttonshome.phtml');
                                    ?>	
        
                                </div>
                                <div class="col-sm-10 " style="background-color:white;height:100%;padding-top:10px;">
                                    
                                    <form name="dashboardForm" id="consumptionForm" method="post" onsubmit="return checkCommoditySelection();"> 
                                    
                                     <div class="row">
                                           
                                           <div class="col-sm-7">
                                         
                                              <div class="row">
                                                 <div  class="col-sm-12 pull-right  clearfix"  style="height:500px;"  >
                                                    <div class="col-sm-10 box-shadow"  style="height:500px;">
                                               
                                                       <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                <?php echo "Consumption by method, $this->date"; ?>
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                                   <div id="infobutton" class="infobutton infoButtonFirst" style="margin-bottom:-23px;">
                                                                                      <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                     <div id="" class="infodiv" >
                                                                            ...
                                                                                    </div>
                                                                            </div>
                                                                            </div>
                                                                             
                                                                          </div>   
                                             
                                                       <div id="chart11_div" style="width:100%; height:400px;"></div>
                                                    </div>
                                                     
                                                    <div class="col-sm-2">
                                                        
                                                           <?php 
                                                                  if(isset($this->monthDate)){
                                                           ?>
                                                              <select name="lastPullDate" id="lastPullDate" style="margin-bottom:5px !important">
                                                               <?php 
                                                                   for($i=0;$i<sizeof($this->monthDate); $i++){
                                                                          $selected = ($this->monthDate[$i]==$this->selectedDate)?"selected":"";
                                                                          echo "<option value='".$this->monthDate[$i]."' $selected>".$this->monthName[$i]."</option>";
                                                                    }
                                                                      
                                                                  }
                                                               ?>
                                                             </select><br/>
                                                    
                                                     </div>
                                         
				                              </div> 
                                               
                                                 <div class="col-sm-12 " style="height:500px;margin-top:20px;margin-bottom:20px;"  >
                                                     
                                                     <div class="col-sm-10 box-shadow" style="height:500px;">
                                               
                                                       <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                                
                                                                                 <?php 
                                                                                
                                                                                       if(!empty($this->selectedDatemultiple)){
                   
                                                                                          $titleText = (sizeof($this->selectedDatemultiple)>1) ?"across selected dates" : "across selected date";
                                                                                       }else{
                                                                                            $titleText = $this->start_date." to ".$this->end_date;
                                                                                       }
                                                                                 ?>
                                                                                
                                                                                 <?php
                                                                                
                                                                                      echo "Consumption of FP commodities, $titleText"; 
                                                                                
                                                                                 ?>
                       
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                              <div id="infobutton" class="infobutton hidden" style="margin-bottom:-23px;">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    ...
                                                                                </div>
                                                                            </div>
                                                                          </div>  
                                                     </div>
                                                         
                                                        <div id="chart13_div" style="width:100%; height:400px;"></div>
                                                         
                                                     </div>
                                                         
                                                     <div class="col-sm-2">
                                                          
                                                          <?php  
                                                                 if(isset($this->monthDatemultiple)){
                                                          ?>
                                                            <select name="lastPullDatemultiple[]" id="lastPullDatemultiple" multiple="true" szize="5" style="margin-bottom:5px !important">
                                                         <?php 
                                                             for($i=0;$i<sizeof($this->monthDatemultiple); $i++){
                                                                        $selected = (in_array($this->monthDatemultiple[$i],$this->selectedDatemultiple))?"selected":"";
                                                                 echo "<option value='".$this->monthDatemultiple[$i]."' $selected>".$this->monthNamemultiple[$i]."</option>";
                                                                 }
                                                           ?>
                                                           </select>
   
                                                          <?php 
                                                             }
    
                                                          ?>
                                                         
                                                     </div>
	
				
                                           </div>
                                               
                                          
                                               
                                                </div>
                                               
                                              
                                          </div>
                                       
                                           <div class="col-sm-5">
                                                 <br/>
    
    <div>
        <?php region_filters_dropdown_db($this, $this->locations, $this->criteria, true, true); ?>
        <p>
            <strong>Maximum of six (6) locations allowed per filter</strong><br/>
            <!--<strong>Only one (1) location allowed when filtering ALL commodities</strong>-->
        </p>
    </div>
    
    <br/>
    <input type="submit" value="Preview" class="dbbutton dbbutton_leftmenu" onclick="return checkSelection();">
    
                                           </div>
                                    </div>
                                        
                                    </form>
                           
                                   
                                </div>

		
		<div class="clear"></div>
                </div>
          
           </div><!-- content -->
           <br/><br/><br/>

<script type="text/javascript">
    //console.log(<?php //echo json_encode($this->consumption_by_method); ?>);
    //set high charts global color scheme for all high charts instances on this page
    $(function () {
        Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
    });
    
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);
  $(function () {
	//  document.getElementById("allCharts").style.marginLeft="130px";

        //drawTest();
	<?php if(isset($this->consumption_by_method) && !empty($this->consumption_by_method)) { ?>
                drawChart11();
        <?php } ?>
            
        <?php if(isset($this->consumption_overtime) && !empty($this->consumption_overtime)) { ?>
            console.log("koko 1");
            drawChart13();
        <?php } ?>
            
        <?php if(isset($this->cons_all_BSL_overtime) && !empty($this->cons_all_BSL_overtime)) { ?>
            console.log("koko 2");
            drawChartAllConsumptionByLocationOvertime();
        <?php } ?>
            
        <?php if(isset($this->consumption_bsm) && !empty($this->consumption_bsm)) { ?>
                console.log("koko 3");
                drawChartConsumptionBSM_First();
                drawChartConsumptionBSM();
        <?php } ?>
            
        <?php if(isset($this->consumption_bmmandlocation) && !empty($this->consumption_bmmandlocation)) { ?>
                console.log("koko 4");
                drawChartConsumption_BMMAndLocation_First();
                <?php if(isset($this->showlinechart) && $this->showlinechart==TRUE){ ?>
                    drawChartConsumption_BSMAndLocation();
                <?php } else if (isset($this->commlinechart) && $this->commlinechart==TRUE){
                          //$this->cons_all_BSL_overtime = $this->consumption_bmmandlocation;
                ?>
                            drawChartMMSLOvertime();
                <?php } else { ?>
                    $('#chart13_div').html('<div style="font-weight:bold; padding:5px;background: #eeeeee;border:1px solid #cccccc;">The consumption chart for the last 12 months will not be displayed when multiple locations and multiple commodities are selected. Please either select a single commodity and multiple locations, or multiple commodities and a single location to display this chart.</div>');
        <?php   } 
            }
        ?>
            
        
	//var currentLevel;
	//currentLevel = <?php //echo '\'' . $this->location_data[0][name] . '\''; ?>;
		 
  });
  
  
  
  
function drawChart11() {

    <?php
        if(isset($this->consumption_by_method) && !empty($this->consumption_by_method)) {
            $methodString = ""; $consumptionString = "";
            foreach ($this->consumption_by_method as $key=>$row){
                       if($key == 1){
                           $methodString .= "'" . $row['method'] . '(unit x10)' . "',";
                           $consumptionString .= (int)round($row['consumption']/10) . ",";
                       }
                       else{
                           $methodString .= "'" . $row['method'] . "',";
                           $consumptionString .= $row['consumption'] . ",";
                       }
            }

            $methodString = substr($methodString, 0, strlen($methodString)-1);
            $consumptionString = substr($consumptionString, 0, strlen($consumptionString)-1);
    ?>


	  <?php //echo  " var title_date = 'Monthly Consumption by Method$this->title_date ' " ?>;
          
          var title_data = '';
          <?php if(empty($this->cons_all_BSL_overtime)){ ?>
              title_data = ''; 
              subtitleText = <?php echo "'($this->date)'"; ?>
          <?php } else { ?>
              title_data = '';
              subtitleText = <?php echo "'($this->date)'"; ?>
          <?php } ?>
              
	
        $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart11_div")
                           .siblings('.infobutton')
                           .find('.infodiv')
                           .html('This chart shows consumption of each FP commodity in the ' +
                                    'most recent month for the selected geography. ' +
                                    'Given the different scale of male condom consumption, consumption ' +
                                    'is reflected in units of 10 male condoms, while all other commodities ' +
                                    'are reflected as a single commodity.'
                                 );
                           $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 450
                },
                title: {
                    text: title_data,
                    style:{
                        "fontSize": "16px",
                        "fontWeight": "bold",
                        "fontFamily":"Arial"
                    },
                    align: 'center',
                    x: -20
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                    title:{
                        text:'FP Commodity',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: [<?php echo $methodString; ?>]
                },
                yAxis: {
                    title: {
                        text: 'Number of Commodities Consumed',
                        style:{ "fontWeight": "bold" }
                    }
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>: ' + thousandSeparator(this.y);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: [<?php echo $consumptionString; ?>]
                }]
            });
            
            
    <?php }//end if isset($this->consumption_by_method ?>

}



function drawChart13() {
        //console.log('inside 13');
        <?php 
                if(isset($this->consumption_overtime) && !empty($this->consumption_overtime)) {
                    //return;
                    
                    //first get all the commodtiy names from the first element/month
                    $commNames = ''; $monthNames = "";
                    reset($this->consumption_overtime);
                    $firstElement = current($this->consumption_overtime);

                    if(!empty($firstElement)){
                        foreach($firstElement as $key=>$commodity){                    
                            $commNames[] = $key;
                        }
                        $monthNames = array_keys($this->consumption_overtime);
                    }
        ?>      
                
                var dataArray = new Array();
                
                <?php 
                    //if(!empty($this->consumption_overtime)){
                        foreach($commNames as $comm){
                            $name =''; $consumption = 0; 
                            if($comm == "Male Condoms"){
                                $name = "$comm (unit x10)";
                            } 
                            else{
                                $name = "$comm";
                            }
                ?>
                        var obj = {name: '<?php echo $name; ?>', data: []};

                <?php 
                        foreach($monthNames as $monthName){ 
                            if($comm == "Male Condoms" && $this->consumption_overtime[$monthName][$comm] != null){
                                $consumption = round($this->consumption_overtime[$monthName][$comm] / 10);
                            }
                            else if($this->consumption_overtime[$monthName][$comm] != null){
                                $consumption = $this->consumption_overtime[$monthName][$comm];
                            }
                            else{
                                $consumption = 0;
                            }
                ?>
                        
                                obj.data.push(<?php echo $consumption; ?>);

                <?php
                            }//end month
                ?>
                            //JS
                            dataArray.push(obj);
                            
                <?php
                        }//end commodity
                ?>
                        
                        <?php 
               if(!empty($this->selectedDatemultiple)){
                   
                   $titleText = (sizeof($this->selectedDatemultiple)>1) ?"across selected dates" : "across selected date";
               }else{
                  $titleText = $this->start_date." to ".$this->end_date;
               }
               ?>
                       
                        var title_data = ''; 
                        var subtitleText = <?php echo "'($titleText)'"; ?>
                            
                        $('#chart13_div').highcharts({
                            chart: {
                                //type: 'column',
                                reflow: true,
                                plotBackgroundColor: null,
                                plotBorderWidth: null,
                                plotShadow: false,
                                events: {
                                    load:function(){
                                        $("text:contains(Highcharts.com)").css("display","none");
                                        $("#chart13_div")
                                       .siblings('.infobutton')
                                       .find('.infodiv')
                                       .html('This chart shows consumption of each FP commodity for each of ' +
                                             'the last 12 months for the selected geography.');
                                       $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                                    }
                                },
                                height: 450
                            },
                            title: {
                                text: title_data,
                                style:{
                                    "fontSize": "16px",
                                    "fontWeight": "bold",
                                    "fontFamily":"Arial"
                                },
                                x: -20
                            },
                            legend: {
                                layout: 'horizontal',
                                align: 'center',
                                borderWidth: 1
                            },
                            xAxis: {
                                title:{
                                    text:'Month',
                                    style:{ "fontWeight": "bold" }
                                },
                                categories: <?php echo json_encode($monthNames); ?>
                            },
                            yAxis: {
                                title: {
                                     text: 'Number of Commodities Consumed',
                                     style:{ "fontWeight": "bold" }
                                },
                                plotLines: [{
                                    value: 0,
                                    width: 1,
                                    color: '#808080'
                                }]
                            },
                            tooltip: {
                                formatter: function () {
                                    return '<b>' + this.x + '</b><br/>' +
                                        '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y);
                                }
                            },
                            plotOptions: {
                                series: {
                                    marker: {
                                        enabled: true
                                    }
                                }
                            },
                            credits: {enabled: false},
                            series: dataArray                       
                        });
                    
        <?php
                }//end big if 
         ?>                        
                 
         
    }//end drawchart13
    
    
    
    
    function drawChartAllConsumptionByLocationOvertime() {
        <?php 
            if(isset($this->cons_all_BSL_overtime) && !empty($this->cons_all_BSL_overtime)){
                //first get all the commodtiy names from the first element/month
                $commNames = ''; $monthNames = "";
                reset($this->cons_all_BSL_overtime);
                $firstElement = current($this->cons_all_BSL_overtime);
                
                if(!empty($firstElement)){
                    foreach($firstElement as $key=>$commodity){                    
                        $commNames[] = $key;
                    }
                    $monthNames = array_keys($this->cons_all_BSL_overtime);
                }
         ?>                        

            var dataArray = new Array();
            <?php 
                        foreach($commNames as $comm){
                            $name =''; $consumption = 0; 
                            if($comm == "Male Condoms"){
                                $name = "$comm (unit x10)";
                            } 
                            else{
                                $name = "$comm";
                            }
                ?>
                        var obj = {name: '<?php echo $name; ?>', data: []};

                <?php 
                        foreach($monthNames as $monthName){ 
                            if($comm == "Male Condoms" && $this->cons_all_BSL_overtime[$monthName][$comm] != null){
                                $consumption = round($this->cons_all_BSL_overtime[$monthName][$comm] / 10);
                            }
                            else if($this->cons_all_BSL_overtime[$monthName][$comm] != null){
                                $consumption = $this->cons_all_BSL_overtime[$monthName][$comm];
                            }
                            else{
                                $consumption = 0;
                            }
                ?>
                        
                                obj.data.push(<?php echo $consumption; ?>);

                <?php
                            }//end month
                ?>
                            //JS
                            dataArray.push(obj);
                            
                <?php
                        }//end commodity
                ?>
           <?php 
               if(!empty($this->selectedDatemultiple)){
                   
                   $titleText = (sizeof($this->selectedDatemultiple)>1) ?"across selected dates" : "across selected date";
               }else{
                  $titleText = $this->start_date." to ".$this->end_date;
               }
               ?>
        
         var title_data = '';
          <?php if(isset($this->single_location)){ ?>
              title_data = <?php echo "'Consumption of FP commodities in selected geographies, $titleText'"; ?>; 
              subtitleText = <?php echo "'($titleText)'"; ?>
          <?php } ?>
        
        $('#chart13_div').highcharts({
                chart: {
                    //type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div")
                           .siblings('.infobutton')
                           .find('.infodiv')
                           .html('This chart displays the consumption of each FP commodity for the last 12 months in the selected geography.');
                           $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 450
                },
                title: {
                    text: title_data,
                    style:{
                        "fontSize": "16px",
                        "fontWeight": "bold",
                        "fontFamily":"Arial"
                    },
                    x: -20
                },
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    borderWidth: 1
                },
                xAxis: {
                    title:{
                      text:'Month',
                      style:{ "fontWeight": "bold" }
                       },
                    categories: <?php echo json_encode($monthNames); ?>
                },
                yAxis: {
                    title: {
                       text: 'Number of Commodities Consumed',
                       style:{ "fontWeight": "bold" }
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y);
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    }
                },
                credits: {enabled: false},
                series: dataArray
                
            });
      
    <?php }//end if isset($this->cons_all_BSL_overtime) ?>


    }
    
    
    
    function drawChartConsumptionBSM_First(){
        //console.log('drawChartConsumptionBSM_First');
        // Create and populate the data table.
          //,{ role: 'style' }
//	var chart11Data = google.visualization.arrayToDataTable([
//            ['', ''],
//        <?php
                $method = $this->consumption_bsm_first_element['method'];
                $consumption = $this->consumption_bsm_first_element['consumption'];
                
                ?>//
//                        [<?php //echo  "'$method', $consumption"; ?>],
//        ]);
//
//                  <?php //echo  " var title_date = 'Monthly Consumption by Method$this->title_date ' " ?>;
//
//                  var title_data = <?php //echo "'Consumption of $this->method, $this->date'"; ?>;
//
//                  var chart11Options = {  
//                              title: title_data,
//                              titleTextStyle: { fontSize: 16 },
//                              is3D:true,
//                              legend: 'none',
//                              groupWidth : 10,
//                              hAxis : {textStyle: {fontSize: 12}},
//                              chartArea: {width: '70%', height: '70%', top: 55}
//                        };
//
//                  var formatter = new google.visualization.NumberFormat({ 
//                                groupingSymbol:',',
//                                pattern:'###,###,##0'
//                            }
//                           );
//                    formatter.format(chart11Data, 1);
//
//                  var chart11 = new google.visualization.ColumnChart(document.getElementById('chart11_div'));
//                  
//                  //show info icon
//                    var info = <?php //echo "'This chart shows consumption of $this->method in the most recent month at the national level. '"; ?>;
//                    google.visualization.events.addListener(chart11, 'ready', function(){
//                           $("#chart11_div").siblings('#infobutton').removeClass('hidden');
//                           $("#chart11_div")
//                                .siblings('.infobutton')
//                                .find('.infodiv')
//                                .text(info);
//
//                    }); 
//                    
//                  chart11.draw(chart11Data, chart11Options);
    }
  
    function drawChartConsumptionBSM(){
//         console.log('drawChartConsumptionBSM');
//        var chart13Data = google.visualization.arrayToDataTable([
//                            ['Month', 'National'],
//            <?php 
//                if(!empty($this->consumption_bsm)){
//                    foreach ($this->consumption_bsm as $month=>$consumption){ 
            ?>//
//                    [<?php // echo "'$month', $consumption"; ?>],
//                     
//            <?php
//                    }//emd foreach
//                } //end if
            ?>//
//       ]);
//        
//        <?php // echo  "var title_data = 'Consumption of $this->method, $this->start_date to $this->end_date ' " ?>;
//                
//        var chart13Options = {
//		      title: title_data,
//		      titleTextStyle: { fontSize: 15 },
//		      vAxis: {format: '#', minValue: 4},
//		      legend: {fontSize: 14},
//		      chartArea: {width: '65%', height: '70%', top: 55},
//		      is3D:true
//		};
//
//          var chart13 = new google.visualization.LineChart(document.getElementById('chart13_div'));
//          
//          var formatter = new google.visualization.NumberFormat({ 
//                                groupingSymbol:',',
//                                pattern:'###,###,##0'
//                            }
//                           );
//          formatter.format(chart13Data, 1);
//                
//                
//            //show info icon
//            var info = <?php // echo "'This chart displays the consumption of $this->method for each of the last 12 months at the national level.'"; ?>;
//            google.visualization.events.addListener(chart13, 'ready', function(){
//                   $("#chart13_div").siblings('#infobutton').removeClass('hidden');
//                   $("#chart13_div")
//                        .siblings('.infobutton')
//                        .find('.infodiv')
//                        .text(info);
//
//            }); 
//	  chart13.draw(chart13Data, chart13Options);
      
    }
    
    
    function drawChartConsumption_BMMAndLocation_First(){
      <?php 
            if(isset($this->consumption_bmmandlocation_first['consumption'])){
                $firstConsumption = $this->consumption_bmmandlocation_first['consumption']; 
                $methods = $this->consumption_bmmandlocation_first['methods']; 
                $methodsString = "";
                foreach($methods as $method)
                    $methodsString .= "'$method',";
                $methodsString = substr($methodsString, 0, strlen($methodsString)-1);
        ?>
                
                
              //var selectedCommoditites = JSON.parse('<?php //echo $methods; ?>');
              var selectedCommoditites = [<?php echo $methodsString; ?>];
              var seriesObjectsArray = new Array(); 
              var consumptionData = '<?php echo $firstConsumption; ?>';
              consumptionDataObject = JSON.parse(consumptionData);
              console.log("selectedCommoditites: " + selectedCommoditites);
                  
              for(selectedLocation in consumptionDataObject){
                  var seriesObject = {};  //one row/object in the series
                  seriesObject.name = selectedLocation;
                  seriesObject.data = new Array();
                  
                  commoditiesObject = consumptionDataObject[selectedLocation];
                  //console.log(commoditiesObject);
                  
                for(var key in selectedCommoditites){
                    for(dbMethod in commoditiesObject){
                        console.log("key: " + key + selectedCommoditites[key]);
                        console.log("dbm: " + dbMethod);
                        
                        if(selectedCommoditites[key] == dbMethod){
                             //$consumption = round($consumption/10,0);  
                             //$method = $row['method'] . '(unit x10)';
                             consumption = commoditiesObject[dbMethod];
                             if(selectedCommoditites[key].toLowerCase() == "male condoms")
                                 consumption = Math.round(consumption/10);
                            seriesObject.data.push(parseInt(consumption));
                        }
                    }
                }
                
                seriesObjectsArray.push(seriesObject);
            }
            
            //console.log(JSON.stringify(seriesObjectsArray));
            
            //display highcharts
            $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    width: 650,
                    height: 350,
                  events: {
                      load:function(){
                          $("text:contains(Highcharts.com)").css("display","none");
                          $("#chart11_div").siblings('#infobutton').removeClass('hidden');
                          $("#chart11_div")
                            .siblings('.infobutton')
                            .find('.infodiv')
                            .html('This chart shows consumption of each FP commodity in the ' +
                                     'most recent month for the selected geography. ' +
                                     'Given the different scale of male condom consumption, consumption ' +
                                     'is reflected in units of 10 male condoms, while all other commodities ' +
                                     'are reflected as a single commodity.'
                            );
                      }
                  }
                },
                title: { 
                    text: 'Consumption by method <br/>for selected commodities and geographies in <?php echo date("F Y",strtotime($this->selectedDate)); ?>' ,  
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                    x: -70,
                },
                tooltip: {
                    useHtml: true,
                    formatter: function (){
                        return '<b>'+ (this.key.toLowerCase() == "male condoms" ? this.key + "(unit x10)" : this.key) +'</b><br>' + 
                               '<b>' + this.series.name + ': </b>' + thousandSeparator(this.y);
                    },
//                    pointFormat: '{point.x},{point.y}',
//                    pointFormatter:function(){
//                        console.log('pf: ' + this.x, this.y);
//                    }
                },
                xAxis: { categories: selectedCommoditites,  //array of x-axis categories
                    title:{
                        text:'FP Commodity',
                        style:{ "fontWeight": "bold" }
                    },
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: 'Number of Commodities Consumed',
                        style:{ "fontWeight": "bold" },
                        align: 'high'
                    },
                    labels: {
                        overflow: 'justify'
                        //format: '{value}'
//                        formatter: function () {                           
//                            return thousandSeparator(this.value);
//                        }
                    }
                },
                plotOptions: {
                    column: {
                        dataLabels: {
                            enabled: true,
                        },
//                        formatter: function(){
//                            return thousandSeparator(10000);
//                        }
                    },
                    series: {
                        pointWidth: 50,
                        stacking: 'normal',
                        point: {
                            events: {
                                mouseOver: function (e) {
                                    //console.log(this.x, this.y)
                                }
                            }
                        }
                    }
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    //reversed: true,
                    verticalAlign: 'top',
                    x:-10,
                    y: 80,
//                    floating: true,
                    //borderWidth: 1,
                    //borderRadius: 5,
//                  backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                    shadow: true
                },
                credits: { enabled: false },
                series: seriesObjectsArray
                
            });
      <?php
            }
      ?>

}
    
    
    function drawChartConsumption_BSMAndLocation(){
        console.log('drawChartConsumption_BSMAndLocation');
                 
        var dataArray = new Array();
        <?php 
                

                if(isset($this->consumption_bmmandlocation)){
                    $locationArray = array(); $monthNames = array();
                    reset($this->consumption_bmmandlocation);
                    $firstElement = current($this->consumption_bmmandlocation);
                    
                    //get the month names to use for categories 
                    $monthNames = array_keys($this->consumption_bmmandlocation);
                    $commodityName = '';
                    
                    if(!empty($firstElement)){
                        foreach($firstElement as $location => $consumption){                    
                                $locationArray[] = $location;
                                $commodityName = key($consumption);
                        }
                    }
                ?>
                        console.log("Locastion: " + '<?php echo json_encode($locationArray); ?>'); 
                    <?php
                    //start looping the arrays
                                foreach($locationArray as $key=>$loc){
                        ?>  
                                    var obj = {name: '<?php echo $loc; ?>', data: []};

                        <?php       foreach($monthNames as $month){ ?>
                                            obj.data.push(<?php echo $this->consumption_bmmandlocation[$month][$loc][$commodityName]; ?>);
                        <?php
                                    }//end month
                        ?>
                                    //add the object to the big array
                                    dataArray.push(obj);

                        <?php   }//end location ?>
                            
                           
                           //console.log(JSON.stringify(dataArray));
                            //var titleText = '<?php echo  "Consumption of  $commodityName in selected geographies"; ?>';
                            var titleText = 'Consumption by method <br/>for selected commodities and geographies, <?php echo  "$this->end_date to $this->start_date"; ?>';
                            var subtitleText = '(<?php echo  "$this->end_date to $this->start_date"; ?>)';

                            $('#chart13_div').highcharts({
                                chart: {
                                    //type: 'line',
                                    height: 470,
                                    //spacingLeft: -20,
                                    events: {
                                        load:function(){
                                            $("text:contains(Highcharts.com)").css("display","none");
                                            $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                                            $("#chart13_div")
                                            .siblings('.infobutton')
                                            .find('.infodiv')
                                            .text("This chart displays the consumption of <?php echo $commodityName; ?>  for each of the last 12 months in the selected geography");
                                        }
                                    }
                                },
                                title: {
                                    text: titleText,
                                    style: {
                                        fontWeight: 'bold',
                                        fontFamily: 'Arial',
                                        fontSize: '16px'
                                    },
                                    x: -20 //center
                                },
                                xAxis: {
                                    title:{
                                    text:'Month',
                                    style:{ "fontWeight": "bold" }
                                },
                                    categories: <?php echo json_encode($monthNames); ?>
                                },
                                yAxis: {
                                     title: {
                                     text: 'Number of Commodities Consumed',
                                     style:{ "fontWeight": "bold" }
                                      },
//                                    labels: {
//                                        format: '{value}%'
//                                    },
                                    plotLines: [{
                                        value: 0,
                                        width: 1,
                                        color: '#808080'
                                    }]
                                },
                                tooltip: {
                                    formatter: function () {
                                        return '<b>' + this.x + '</b><br/>' +
                                            '<b>' + this.series.name + '</b>: ' + this.y + '<br/>';
                                    }
                                },
                                plotOptions: {
                                    series: {
                                        marker: {
                                            enabled: true
                                        }
                                    }
                                },
                                legend: {
                                    layout: 'horizontal',
                                    //verticalAlign: 'center',
                                    align: 'center',
                                    borderWidth: 1
                                    //shadow: true
                                },
                                series: dataArray
                            });
         <?php   
                }//end if
         ?>                        
                
        
    }
    
    
    function drawChartMMSLOvertime() {
        <?php 
            if(isset($this->consumption_bmmandlocation) && !empty($this->consumption_bmmandlocation)){
                //first get all the commodtiy names from the first element/month
                $commNames = array(); $monthNames = "";
                reset($this->consumption_bmmandlocation);
                $firstElement = current($this->consumption_bmmandlocation);
                
                if(!empty($firstElement)){
                    foreach($firstElement as $key=>$selectedCommNames){
                        $locationName = $key;
                        $commNames = $selectedCommNames;
                    }
                    $monthNames = array_keys($this->consumption_bmmandlocation);
                }
         ?>                        

            //console.log(<?php //echo json_encode($commNames); ?>);
            //console.log(<?php //echo json_encode($locationName); ?>);
            
            var dataArray = new Array();
            <?php 
                        foreach($commNames as $methodName=>$consumptionValue){
                            $name =''; $consumption = 0;
                            if($methodName == "Male Condoms"){
                                $name = "$methodName (unit x10)";
                            }
                            else{
                                $name = $methodName;
                            }
                ?>
                       var obj = {name: '<?php echo $name; ?>', data: []};

                <?php 
                        foreach($monthNames as $monthName){
                            if($methodName == "Male Condoms" && $this->consumption_bmmandlocation[$monthName][$locationName][$methodName] != null){
                                $consumption = round($this->consumption_bmmandlocation[$monthName][$locationName][$methodName] / 10);
                            }
                            else if($this->consumption_bmmandlocation[$monthName][$locationName][$methodName] != null){
                                $consumption = $this->consumption_bmmandlocation[$monthName][$locationName][$methodName];
                            }
                            else{
                                $consumption = 0;
                            }
                ?>
                        
                                obj.data.push(<?php echo $consumption; ?>);

                <?php
                            }//end month
                ?>
                            //JS
                            dataArray.push(obj);
                            
                <?php
                        }//end commodity
                ?>
        
                //console.log(dataArray);
               <?php 
               if(!empty($this->selectedDatemultiple)){
                   
                   $titleText = (sizeof($this->selectedDatemultiple)>1) ?"across selected dates" : "across selected date";
               }else{
                  $titleText = $this->start_date." to ".$this->end_date;
               }
               ?>
                
              var title_data = <?php echo "'Consumption of FP commodities in selected geographies, $titleText'"; ?>;
              var subtitleText = <?php echo "'($titleText)'"; ?>
        
        $('#chart13_div').highcharts({
                chart: {
                    //type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div")
                           .siblings('.infobutton')
                           .find('.infodiv')
                           .html('This chart displays the consumption of each of the selected FP commodity for the last 12 months in the selected geography.');
                           $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    height: 450
                },
                title: {
                    text: title_data,
                    style:{
                        "fontSize": "16px",
                        "fontWeight": "bold",
                        "fontFamily":"Arial"
                    },
                    x: -20
                },
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    borderWidth: 1
                },
                xAxis: {
                    title:{
                     text:'Month',
                     style:{ "fontWeight": "bold" }
                                },
                    categories: <?php echo json_encode($monthNames); ?>
                },
                yAxis: {
                    title: {
                      text: 'Number of Commodities Consumed',
                      style:{ "fontWeight": "bold" }
                                },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y);
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    }
                },
                credits: {enabled: false},
                series: dataArray
                
            });
      
    <?php }//end if isset($this->cons_all_BSL_overtime) ?>


    }//end function 
    
</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	
                
        <script src="../js/highcharts/highcharts.js"></script>
        <script src="../js/highcharts/modules/exporting.js"></script>   
                
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
<script src="../js/tp/functions.js"></script>


</body>

</html>

<?php


?>
