     <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'consumption';
                                       // $variable = 'Simple';        
                                        require_once('views/scripts/template/template.phtml');
                                       
                                    ?> 
                         <form name="dashboardForm" id="consumptionForm" method="post" onsubmit="return checkCommoditySelection();"> 
                                    
                                       <div class="row">
                                         
                                           <div class="col-sm-5 pull-right" style="margin-bottom:20px;">
                                               
			         	       <?php require_once('views/scripts/consumption/top_buttons.phtml');?>
                                                     
                                           </div>
                                           
                                           
                                           <div class="col-sm-7" >
                                         
                                              <div class="row">
                                                 <!--<div  class="col-sm-12 pull-right  clearfix"  style="height:auto;margin-bottom:50px;"  >-->
                                                    
                                                     <div class="col-sm-9 box-shadow "  style="height:auto">
                                               
                                                     
                                                          <?php
                                                                       $chart_title = "";
                                                                        $info_text =  "";
                                                                        include('views/scripts/template/chart_title.phtml');
                                                            
                                                           ?>
                                                         
                                                        
                                                           <div id="chart11_div" style="width:100%; height:auto;"></div>
                                                       
                                                    </div>
                                                     
                                                     <div class="col-sm-3" style="margin-bottom:50px;">
                                                        
                                                             <?php require_once('views/scripts/consumption/top_buttons1.phtml');?>
                                                    
                                                     </div>
                                              </div>
                                               
                                           </div>  
                                           
                                           
                                       </div>
                             
                                        
                                       <div class="row" style="margin-top: 20px;">
                                               
                                                 <div class="col-sm-7 " style="height:auto;"  >
                                                     <div class="row">
                                                        <div class="col-sm-3 pull-right pull-left-sm" id="lastd" style="margin-bottom:70px;">

                                                           <?php require_once('views/scripts/consumption/top_buttons11.phtml');?>

                                                         </div>
                                                     
                                                        <div class="col-sm-9 box-shadow"  id="chart2" style="height:auto;">

                                                           
                                                                                  <?php
                                                                                          $chart_title = "";
                                                                                          $info_text =  "";
                                                                                          include('views/scripts/template/chart_title.phtml');
                                                                                          //echo 6;

                                                                                  ?>

                                                           <div id="chart13_div" style="width:100%; height:auto;"></div>

                                                        </div>
                                                     </div>
                                               
                                           </div>
                                               
                                          
                                               
                                                </div>
                                            <br/><br/>
                                        
                                    </form>
          
                                   
                                </div>

		
		<div class="clear"></div>
                </div>
            
          
            
           
            
          
           
           </div><!-- content -->
           <br/><br/><br/>
           

<script type="text/javascript">
    //console.log(<?php //echo json_encode($this->consumption_by_method); ?>);
    //set high charts global color scheme for all high charts instances on this page
    $(function () {
        Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
    });
    
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);
  $(function () {
	//  document.getElementById("allCharts").style.marginLeft="130px";

        //drawTest();
	<?php if(isset($this->consumption_by_method) && !empty($this->consumption_by_method)) { ?>
                drawChart11();
        <?php } ?>
            
        <?php if(isset($this->consumption_overtime) && !empty($this->consumption_overtime)) { ?>
            console.log("koko 1");
            drawChart13();
        <?php } ?>
            
        <?php if(isset($this->cons_all_BSL_overtime) && !empty($this->cons_all_BSL_overtime)) { ?>
            console.log("koko 2");
            drawChartAllConsumptionByLocationOvertime();
        <?php } ?>
            
        <?php if(isset($this->consumption_bsm) && !empty($this->consumption_bsm)) { ?>
                console.log("koko 3");
                drawChartConsumptionBSM_First();
                drawChartConsumptionBSM();
        <?php } ?>
            
        <?php if(isset($this->consumption_bmmandlocation) && !empty($this->consumption_bmmandlocation)) { ?>
                console.log("koko 4");
                drawChartConsumption_BMMAndLocation_First();
                <?php if(isset($this->showlinechart) && $this->showlinechart==TRUE){ ?>
                    drawChartConsumption_BSMAndLocation();
                <?php } else if (isset($this->commlinechart) && $this->commlinechart==TRUE){
                          //$this->cons_all_BSL_overtime = $this->consumption_bmmandlocation;
                ?>
                            drawChartMMSLOvertime();
                <?php } else { ?>
                    $('#chart13_div').html('<div style="font-weight:bold; padding:5px;background: #eeeeee;border:1px solid #cccccc;">The consumption chart for the last 12 months will not be displayed when multiple locations and multiple commodities are selected. Please either select a single commodity and multiple locations, or multiple commodities and a single location to display this chart.</div>');
        <?php   } 
            }
        ?>
            
        
	//var currentLevel;
	//currentLevel = <?php //echo '\'' . $this->location_data[0][name] . '\''; ?>;
		 
  });
  
  
  
  
function drawChart11() {
       var consumptionData = <?= 
                                isset($this->consumption_by_method) ?
                                $this->consumption_by_method :
                                '{}'  //empty json object
                             ?>;
       var methods = new Array(); var values = new Array();
       for(key in consumptionData){
            row = consumptionData[key];
            
            //if(key == 1){
            if(row['method'].toLowerCase() == "male condoms"){
                 values.push(Math.round(row['consumption']/10));
                 methods.push(row['method'] + '(unit x10)');
             } else {
                values.push(parseInt(row['consumption']));
                methods.push(row['method']);
            }
       }
          
        var overtimeData = <?= 
                              isset($this->cons_all_BSL_overtime) ?
                              $this->cons_all_BSL_overtime :
                              '{}'  //empty json object
                           ?>;
        <?php if($this->freshVisit) { ?>
            var titleText = '<?php echo  "Consumption by method, $this->date"; ?>';
        <?php } else { ?>
            var titleText = '<?php echo  "Consumption by method in selected geographies as of $this->date"; ?>';
        <?php } ?>
            
   
        $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart11_div")
                            .siblings('.row')
                            .find('.infodiv')
                           .html('This chart shows consumption of each FP commodity in the ' +
                                    'most recent month or selected date(s) for the selected geography. ' +
                                    'Given the different scale of male condom consumption, consumption ' +
                                    'is reflected in units of 10 male condoms, while all other commodities ' +
                                    'are reflected as a single commodity.'
                                 );
                           $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    //height: 450
                },
                title: {
                    text: titleText,
                    style:{
                        "fontSize": "16px",
                        "fontWeight": "bold",
                        "fontFamily":"Arial"
                    },
                    align: 'center',
                    x: -20
                },
                legend: {
                    enabled: false
                },
                xAxis: {
                    title:{
                        text:'FP Commodity',
                        style:{ "fontWeight": "bold" }
                    },
                    categories: methods
                },
                yAxis: {
                    title: {
                        text: '#  Commodities Consumed',
                        style:{ "fontWeight": "bold" }
                    }
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b>: ' + thousandSeparator(this.y);
                    }
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true
                    },
                    column: {
                        dataLabels: {
                            enabled: true
                        }
                    }
                },
                credits: {enabled: false},
                series: [{
                    data: values
                }]
            });
}



function drawChart13() {
        var consumptionOvertime = <?= 
                        isset($this->consumption_overtime) ?
                        $this->consumption_overtime :
                        '{}'  //empty json object
          ?>;
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = '<?= $this->end_date; ?>';
        
        var dataArray = processConsumptionOvertimeData(consumptionOvertime);
        var monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        var dateLength = selectedDatemultiple.length;         
        
        <?php 
        if(!empty($this->selectedDatemultiple)){
            $titleText = (sizeof($this->selectedDatemultiple)>1) ?"across selected dates" : "across selected date(s)";
        }else{
           $titleText = $this->start_date." to ".$this->end_date;
        }
        ?>

        var dateText = '<?= $this->start_date . " to " . $this->end_date ?>';
        if(dateLength > 0){
            dateText = dateLength === 1 ? 
                    monthNamesWithYears[0] : 
                    "across selected dates";
        } 

        <?php if($this->freshVisit) { ?>
            var titleText = "Consumption of FP commodities, <br/>" + dateText;
        <?php } else { ?>
            var titleText = "Consumption of FP commodities in selected geographies, <br/>" + dateText;
        <?php } ?>
        
                //var title_data = <?php //echo "'Consumption of FP commodities, $titleText'"; ?>; 
                //var subtitleText = <?php //echo "'($titleText)'"; ?>

                            
                        $('#chart13_div').highcharts({
                            chart: {
                                type: dateLength == 1 ? 'column' : 'line',
                                reflow: true,
                                plotBackgroundColor: null,
                                plotBorderWidth: null,
                                plotShadow: false,
                                events: {
                                    load:function(){
                                        $("text:contains(Highcharts.com)").css("display","none");
                                        $("#chart13_div")
                                       .siblings('.row')
                                       .find('.infodiv')
                                       .html('This chart shows consumption of each FP commodity for each of ' +
                                             'the last 12 months or selected date(s) for the selected geography.');
                                       $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                                    }
                                }
                            },
                            title: {
                                text: titleText,
                                style:{
                                    "fontSize": "16px",
                                    "fontWeight": "bold",
                                    "fontFamily":"Arial"
                                },
                                x: -20
                            },
                            legend: {
                                layout: 'horizontal',
                                align: 'center',
                                borderWidth: 1
                            },
                            xAxis: {
                                title:{
                                    text:'Month',
                                    style:{ "fontWeight": "bold" }
                                },
                                categories: monthNamesWithYears
                            },
                            yAxis: {
                                title: {
                                     text: '#  Commodities Consumed',
                                     style:{ "fontWeight": "bold" }
                                },
                                plotLines: [{
                                    value: 0,
                                    width: 1,
                                    color: '#808080'
                                }]
                            },
                            tooltip: {
                                formatter: function () {
                                    return '<b>' + this.x + '</b><br/>' +
                                        '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y);
                                }
                            },
                            plotOptions: {
                                series: {
                                    marker: {
                                        enabled: true
                                    }
                                },
                                column: dateLength === 1  
                                        ? {    
                                           dataLabels: {
                                                 enabled: true,
                                             }
                                         }
                                         : {}  
                            },
                            credits: {enabled: false},
                            series: dataArray                       
                        });         
         
    }//end drawchart13
    
    
    
    
    function drawChartAllConsumptionByLocationOvertime() {
        var consumptionOvertime = <?= 
                        isset($this->cons_all_BSL_overtime) ?
                        $this->cons_all_BSL_overtime :
                        '{}'  //empty json object
          ?>;
        
        var dataArray = processConsumptionOvertimeData(consumptionOvertime);
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = <?php echo json_encode($this->end_date); ?>;
        var monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        var dateLength = selectedDatemultiple.length;
        
           <?php 
               if(!empty($this->selectedDatemultiple)){
                   
                   $titleText = (sizeof($this->selectedDatemultiple)>1) ?"across selected dates" : "across selected date";
               }else{
                  $titleText = $this->start_date." to ".$this->end_date;
               }
               ?>
        
         //var title_data = '';
          <?php 
//            if(isset($this->single_location)){ ?>
              //title_data = //<?php //echo "'Consumption of FP commodities in selected geographies, $titleText'"; ?>; 
              //subtitleText = //<?php //echo "'($titleText)'"; ?>
          <?php //} ?>
              
           var dateText = '<?= $this->start_date . " to " . $this->end_date ?>';
            if(dateLength > 0){
                dateText = dateLength === 1 ? 
                        monthNamesWithYears[0] : 
                        "across selected dates";
            } 

            <?php if($this->freshVisit) { ?>
                var titleText = "Consumption of FP commodities, <br/>" + dateText;
            <?php } else { ?>
                var titleText = "Consumption of FP commodities in selected geographies, <br/>" + dateText;
            <?php } ?>
            
        $('#chart13_div').highcharts({
                chart: {
                    type: dateLength == 1 ? 'column' : 'line',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div")
                           .siblings('.row')
                           .find('.infodiv')
                           .html('This chart displays the consumption of each FP commodity for the last 12 months or selected date(s) in the selected geography.');
                           $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    //height: 450
                },
                title: {
                    text: titleText,
                    style:{
                        "fontSize": "16px",
                        "fontWeight": "bold",
                        "fontFamily":"Arial"
                    },
                    x: -20
                },
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    borderWidth: 1
                },
                xAxis: {
                    title:{
                      text:'Month',
                      style:{ "fontWeight": "bold" }
                       },
                    categories: monthNamesWithYears
                },
                yAxis: {
                    title: {
                       text: '#  Commodities Consumed',
                       style:{ "fontWeight": "bold" }
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y);
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    },
                    column: dateLength === 1  
                         ? {    
                            dataLabels: {
                                  enabled: true,
                              }
                          }
                          : {}  
                },
                credits: {enabled: false},
                series: dataArray
                
            });
     
    }
    
    
    function drawChartConsumption_BMMAndLocation_First(){
       
            var consumptionOvertime = <?= 
                isset($this->consumption_bmmandlocation_first) ?
                $this->consumption_bmmandlocation_first :
                '{}'  //empty json object
            ?>;
            console.log('consumptionOvertime', consumptionOvertime);
              var consumptionDataObject = consumptionOvertime['consumption'];
              var selectedCommoditites = Object.values(consumptionOvertime['methods']);
              var seriesObjectsArray = new Array(); 
              
              for(selectedLocation in consumptionDataObject){
                  var seriesObject = {};  //one row/object in the series
                  seriesObject.name = selectedLocation;
                  seriesObject.data = new Array();
                  
                    for(var key in selectedCommoditites){
                        commodity = selectedCommoditites[key];
                        consumption =  0;
                        
                        if(commodity.toLowerCase() == "male condoms"){
                            consumption = Math.round(consumptionDataObject[selectedLocation][commodity] / 10);
                            selectedCommoditites[key] = selectedCommoditites[key] + '(unit x10)';
                        } else {
                            consumption = parseInt(consumptionDataObject[selectedLocation][commodity]);
                        }

                        seriesObject.data.push(consumption);
                    }

                    seriesObjectsArray.push(seriesObject);
                }
                
            var titleText = 'Consumption by method for selected commodities and geographies, <?php echo date("F Y",strtotime($this->selectedDate)); ?>';            
            
            //display highcharts
            $('#chart11_div').highcharts({
                chart: {
                    type: 'column',
                    //width: 650,
                    //height: 350,
                  events: {
                      load:function(){
                          $("text:contains(Highcharts.com)").css("display","none");
                          $("#chart11_div").siblings('#infobutton').removeClass('hidden');
                          $("#chart11_div")
                            .siblings('.row')
                            .find('.infodiv')
                            .html('This chart shows consumption of each FP commodity in the ' +
                                     'most recent month or selected date(s) for the selected geography. ' +
                                     'Given the different scale of male condom consumption, consumption ' +
                                     'is reflected in units of 10 male condoms, while all other commodities ' +
                                     'are reflected as a single commodity.'
                            );
                      }
                  }
                },
                title: { 
                    text: titleText,  
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                },
                tooltip: {
                    useHtml: true,
                    formatter: function (){
                        return '<b>'+ (this.key.toLowerCase() == "male condoms" ? this.key + "(unit x10)" : this.key) +'</b><br>' + 
                               '<b>' + this.series.name + ': </b>' + thousandSeparator(this.y);
                    },
//                    pointFormat: '{point.x},{point.y}',
//                    pointFormatter:function(){
//                        console.log('pf: ' + this.x, this.y);
//                    }
                },
                xAxis: { 
                    categories: selectedCommoditites,  //array of x-axis categories
                    title:{
                        text:'FP Commodity',
                        style:{ "fontWeight": "bold" }
                    },
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: 'Commodities Consumed',
                        style:{ "fontWeight": "bold" },
                        align: 'high'
                    },
                    labels: {
                        overflow: 'justify'
                        //format: '{value}'
//                        formatter: function () {                           
//                            return thousandSeparator(this.value);
//                        }
                    }
                },
                plotOptions: {
                    column: {
                        dataLabels: {
                            enabled: true,
                        },
//                        formatter: function(){
//                            return thousandSeparator(10000);
//                        }
                    },
                    series: {
                        pointWidth: 50,
                        stacking: 'normal',
                        point: {
                            events: {
                                mouseOver: function (e) {
                                    //console.log(this.x, this.y)
                                }
                            }
                        }
                    }
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    //reversed: true,
                    verticalAlign: 'top',
                    x:-10,
                    y: 80,
//                    floating: true,
                    //borderWidth: 1,
                    //borderRadius: 5,
//                  backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                    shadow: true
                },
                credits: { enabled: false },
                series: seriesObjectsArray
                
            });

}
    
    
    function drawChartConsumption_BSMAndLocation(){
        var consumptionOvertime = <?= 
                        isset($this->consumption_bmmandlocation) ?
                        $this->consumption_bmmandlocation :
                        '{}'  //empty json object
          ?>;
                  
        var methodObject = <?= json_encode($this->methods); ?>;
        var commodityName = methodObject[Object.keys(methodObject)[0]];
        var dataArray = processMethodConsumptionOvertimeData(consumptionOvertime, commodityName);        
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = <?php echo json_encode($this->end_date); ?>;
        var monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        var dateLength = selectedDatemultiple.length;
                         
        var dateText = '<?= $this->start_date . " to " . $this->end_date ?>';
            if(dateLength > 0){
                dateText = dateLength === 1 ? 
                        monthNamesWithYears[0] : 
                        "across selected dates";
            } 
        var titleText = 'Consumption by method <br/>for selected commodities and geographies, ' + dateText;
            
            
            $('#chart13_div').highcharts({
                chart: {
                    type: dateLength == 1 ? 'column' : 'line',
                    //height: 470,
                    //spacingLeft: -20,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                            $("#chart13_div")
                            .siblings('.row')
                            .find('.infodiv')
                            .text("This chart displays the consumption of " + commodityName + 
                                  " for each of the last 12 months or selected date(s) in the selected geography");
                        }
                    }
                },
                title: {
                    text: titleText,
                    style: {
                        fontWeight: 'bold',
                        fontFamily: 'Arial',
                        fontSize: '16px'
                    },
                    x: -20 //center
                },
                xAxis: {
                    title:{
                    text:'Month',
                    style:{ "fontWeight": "bold" }
                },
                    categories: monthNamesWithYears
                },
                yAxis: {
                     title: {
                     text: '#  Commodities Consumed',
                     style:{ "fontWeight": "bold" }
                      },
//                                    labels: {
//                                        format: '{value}%'
//                                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y) + '<br/>';
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    },
                    column: dateLength === 1  
                         ? {    
                            dataLabels: {
                                  enabled: true,
                              }
                          }
                          : {}  
                },
                legend: {
                    layout: 'horizontal',
                    //verticalAlign: 'center',
                    align: 'center',
                    borderWidth: 1
                    //shadow: true
                },
                series: dataArray
            });
         
    }
    
    
    function drawChartMMSLOvertime() {
        var consumptionOvertime = <?= 
                        isset($this->consumption_bmmandlocation) ?
                        $this->consumption_bmmandlocation :
                        '{}'  //empty json object
          ?>;

        var dataArray = processConsumptionAndLocationOvertimeData(consumptionOvertime);        
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = <?php echo json_encode($this->end_date); ?>;
        var monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        var dateLength = selectedDatemultiple.length;
            
            var dateText = '<?= $this->start_date . " to " . $this->end_date ?>';
            if(dateLength > 0){
                dateText = dateLength === 1 ? 
                        monthNamesWithYears[0] : 
                        "across selected dates";
            } 
                
           var title_data = 'Consumption of FP commodities in selected geographies, ' + dateText;
                      
        $('#chart13_div').highcharts({
                chart: {
                    type: dateLength == 1 ? 'column' : 'line',
                    reflow: true,
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    events: {
                        load:function(){
                            $("text:contains(Highcharts.com)").css("display","none");
                            $("#chart13_div")
                           .siblings('.row')
                           .find('.infodiv')
                           .html('This chart displays the consumption of each of the selected FP commodity for the last 12 months or selected date(s) in the selected geography.');
                           $("#chart13_div").siblings("#infobutton").removeClass("hidden");
                        }
                    },
                    //height: 450
                },
                title: {
                    text: title_data,
                    style:{
                        "fontSize": "16px",
                        "fontWeight": "bold",
                        "fontFamily":"Arial"
                    },
                    x: -20
                },
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    borderWidth: 1
                },
                xAxis: {
                    title:{
                     text:'Month',
                     style:{ "fontWeight": "bold" }
                                },
                    categories: monthNamesWithYears
                },
                yAxis: {
                    title: {
                      text: 'Commodities Consumed',
                      style:{ "fontWeight": "bold" }
                                },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y);
                    }
                },
                plotOptions: {
                    series: {
                        marker: {
                            enabled: true
                        }
                    },
                    column: dateLength === 1  
                         ? {    
                            dataLabels: {
                                  enabled: true,
                              }
                          }
                          : {}  
                },
                credits: {enabled: false},
                series: dataArray
                
            });
      
    <?php // }//end if isset($this->cons_all_BSL_overtime) ?>


    }//end function 
    
</script>

  
        <script src="../js/highcharts/highcharts.js"></script>
        <script src="../js/highcharts/modules/exporting.js"></script>   
                
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
<script src="../js/tp/overtime-ops.js"></script>

</body>

</html>