<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	position: relative;
}

#homecontent-mid {
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px; 
}

.sliderdiv {
	float: left;
}

.main-search {
	float: left;
	overflow: hidden;
}

.nav-buttons {
	float: left;
	overflow: hidden;
}


</style>

<!--<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">-->

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
       <!--<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />-->
    <!--<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css">-->

    
<style>
    
    .infobutton {
        padding-right: 13px;
    }
    
</style>        
    
    
<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" defer async></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />

<!--<script src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>-->
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>-->

<script>
    function checkCommoditySelection(){
//        console.log(combo.options);
//        console.log(combo.options[combo.selectedIndex]);
//        console.log(combo.options[combo.selectedIndex].value);

        //var combo = document.getElementById("comm_id");
        //var selectedValue = combo.options[combo.selectedIndex].value;
        //alert('submitting: ' + selectedValue); 
        
        //if(selectedValue != 0) return true;
                
        //return false;
    }
</script>

<script>
  $(function() {
    $( "#accordion" ).accordion({active: 1});
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  </script>
</head>
<body class="yui-skin-sam">
    
    <?php   
            //echo 'high<br/><br/>' ;
            //var_dump($this->consumption_by_method); 
            //var_dump($this->consumption_bsmandlocation_first); 
    ?>
    
	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>
				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>
			</div>

			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
                                <?php require_once('views/scripts/consumption/top_buttons2.phtml');?>
			</div>
			<div class="hrNav"></div>

			<!-------   /////////////////////////// make left buttons ////////////////////// -->
			<div class="nav-buttons">
				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    require_once('views/scripts/dashboard/left_buttons.phtml');
                                ?>
			</div>
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');
                             // print_r($this->consumptionArray);
                                ?>
			</div>
			
			<!-------   /////////////////////////// charts ////////////////////// -->

			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">
				
				<div class="hrNav" id="hrr"></div>
				<div class="hrNav"></div>
				
				
				    <div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
                                                                    <div id="infobutton" class="infobutton hidden"">
                                                                        <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                        <div id="" class="infodiv" >
                                                                            ...
                                                                        </div>
                                                                    </div>
								    <div class="hrNav"></div>
									<div id="chart11_div" style="width: 630px; height: 460px;"></div>
									</div>
									
								</div>
							</div>
						</div>			
					</div>
					
					<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
					
					<div id="bottomrow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
                                                                            <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    ...
                                                                                </div>
                                                                            </div>
                                                                        <div class="hrNav"></div>
    									<div id="chart13_div" style="width: 630px; height: 370px;"></div>
									</div>
									
								</div>
							</div>
						</div>
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
                                                <div class="main-search"></div>
					</div>
					
				</div>
				
				
	</div>

		<div class="hrNav"></div>
		<div class="clear"></div>
		
                
		<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->

		<!-------   /////////////////////////// main gnr ////////////////////// -->


<script type="text/javascript">
    
  var newFPCurrentMonth = "This chart shows number of clients who accepted a modern family planning method for the first time in their lives in the most recent month for the selected geography.";
  var newFPOvertime = "This chart shows the number of clients who accepted a modern family planning method for the first time in their lives over a period of 12 months for the selected geography.";
  var currentFPCurrentMonth = "This chart shows the number of clients who have ever used an FP method at any point before returning to receive any family planning method in the most recent month for the selected geography.";
  var currentFPOvertime = "This chart, which shows the number of clients who have ever used an FP method at any point before returning to receive any family planning method, illustrates use over a period of 12 months for the selected geography.";
  
  var currentMonthText ="";
  var overtimeText = "";
  var selectedCommodityAlias = "";
  
  //check if only one commodity selected and get which commodity it is
  <?php if(count($this->commodityObjectsArray)== 1) { ?>
      selectedCommodityAlias = '<?php echo $this->commodityObjectsArray[0]['commodity_alias']; ?>';
  <?php } ?>
      
      console.log('selectedCommodityAlias: ' + selectedCommodityAlias);
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);
  
    $(function() {
	  document.getElementById("allCharts").style.marginLeft="130px";

          
        //drawTest();
	<?php if(isset($this->default_option)) { ?>
                console.log("DEFAULT");
                currentMonthText = '<u>New FP Acceptors</u><br>' + newFPCurrentMonth + "<br/><br/>" + '<u>Current FP Users</u><br>' + currentFPCurrentMonth;
                overtimeText = '<u>New FP Acceptors</u><br>' + newFPOvertime + "<br/><br/>" + '<u>Current FP Users</u><br>' + currentFPOvertime;
                
                drawBarChart();
                <?php if(!isset($this->geoListSelectionMade)) { //line chart only available if no geo selection made?>
                    drawDefaultLineChart();
                <?php } else { ?>
                    $('#chart13_div').html('<div style="font-weight:bold; padding:5px;background: #eeeeee;border:1px solid #cccccc;">The consumption chart for the last 12 months will not be displayed when multiple locations are selected. Please either select a single commodity and multiple locations or single commodity and single location to display this chart.</div>');
                <?php } ?>
        <?php } else if(isset($this->commodityOnly)) { ?>
                console.log("commodityOnly");
                //set the info text with the tenary operator check
                currentMonthText = selectedCommodityAlias == 'new_acceptors' ? newFPCurrentMonth : currentFPCurrentMonth;
                overtimeText = selectedCommodityAlias == 'new_acceptors' ? newFPOvertime : currentFPOvertime;
                
                drawLocationBarChart();
                drawCommodityOvertimeChart();
        <?php } else if(isset($this->commodityAndLocation)) { ?>
                console.log("commodityAndLocation");
                //set the info text with the tenary operator check
                currentMonthText = selectedCommodityAlias == 'new_acceptors' ? newFPCurrentMonth : currentFPCurrentMonth;
                overtimeText = selectedCommodityAlias == 'new_acceptors' ? newFPOvertime : currentFPOvertime;
                
                drawLocationBarChart();
                drawCommodityAndLocationLineChart();
        <?php } ?>        
		 
  });
  

 function drawBarChart() {
     var dataArray = new Array();
<?php
    if(isset($this->default_option) && !empty($this->default_option)) { 
        
        
        $commNames = array('new_acceptors'=>'New FP acceptors', 'current_users'=>'Current FP Users');
     
       
        $consumptionArray = end($this->consumptionArrays);
       // print_r($consumptionArray);
        if(!empty($this->selectedDate)){
         $fKey = date('F',strtotime($this->selectedDate));
         $consumptionArray = $this->consumptionArrays[$fKey];
        }
       // echo '<br/><br/>';
       // print_r($consumptionArray);exit;
        $locationNames = array_keys($consumptionArray);
        
        

        foreach($commNames as $alias=>$commName){
            //if(substr($commName, 0, 6) == 'Female') $commName = 'Current FP Users';
            //if(substr($commName, 0, 3) == 'New') $commName = 'New FP acceptors';
?>
            var obj = {name: '<?php echo $commName; ?>', data: []};
            
<?php   foreach($locationNames as $location){ ?>
                obj.data.push(<?php echo $consumptionArray[$location][$alias]; ?>);
<?php                
            }//end location
?>
        //JS
        dataArray.push(obj);
<?php        
        }//end commodity
        
        if(!empty($this->selectedDate)){
              $this->date = date('F Y',strtotime($this->selectedDate));
          }
?>
          
          var title_data = '';
          <?php if(isset($this->default_option) && !empty($this->default_option)) { ?>
              title_data = <?php echo "'Current FP users and New FP acceptors, $this->date'"; ?>;
              subtitleText = <?php echo "'($this->date)'"; ?>;
          <?php } else { ?>
              title_data = <?php echo "'Consumption by method, $this->single_location, $this->date'"; ?>;
              subtitleText = <?php echo "'($this->single_location, $this->date)'"; ?>;
          <?php } ?>
              
              
          $("#chart11_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#chart11_div").siblings('#infobutton').removeClass('hidden');
                                    $("#chart11_div")
                                            .siblings('.infobutton')
                                            .find('.infodiv')
                                            .html(currentMonthText);
                                }
                            },
                    },
                    title: {
                        text: title_data,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontSize: '16px',
                            fontFamily: 'Arial',
                        },
                    },
                    xAxis: {
                         title: {
                      text: 'Geography',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: <?php echo json_encode($locationNames); ?>
                    },
                    yAxis: {
                        title: {
                      text: '#Users',
                      style:{ "fontWeight": "bold" }
                      }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'horizontal',
                        align: 'center',
                        //x: 40,
                        //y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        //shadow: true
                    },
                    credits: {enabled: false},
                    series:dataArray

              });
              
    <?php }//end big if ?>              
              
}//end drawbarchart


function drawLocationBarChart() {
       
      <?php 
                $allow = isset($this->commodityAndLocation) || isset($this->commodityOnly) ? true : false;
                $commodityName = '';
                
                if($allow) {
                    $commodityName = $this->commodityObject['commodity_name']; 
                    if(substr($commodityName, 0, 6) == 'Female') $commodityName = 'Current FP Users';
                    if(substr($commodityName, 0, 3) == 'New') $commodityName = 'New FP acceptors';
                }
        ?>
                //console.log(<?php //echo json_encode($this->consumptionArray);?>);
<?php
      if($allow){
        $commNames = array('new_acceptors'=>'New family planning acceptors', 'current_users'=>'Female 15-49 years using modern contraceptives');
        
       
        $consumptionArray = end($this->consumptionArrays);
         if(!empty($this->selectedDate)){
         $fKey = date('F',strtotime($this->selectedDate));
         $consumptionArray = $this->consumptionArrays[$fKey];
        }
        $locationNames = array_keys($consumptionArray);
        reset($consumptionArray); 
        $firstKey = key($consumptionArray);  
        
        
        //echo $firstKey;exit;
        $color = ''; $consumptionString = "";
        foreach ($consumptionArray as $location=>$indicators){ 
            $consumptionString .= $location == $firstKey ?
                                  "{y:" . $indicators[$this->commodityObject['commodity_alias']] . ", color: '#000000'},":
                                  $indicators[$this->commodityObject['commodity_alias']] . ",";
        }
        $consumptionString = substr($consumptionString, 0, -1);
       
?>    
	  <?php //echo  " var title_date = 'Monthly Consumption by Method$this->title_date ' " ?>;
          
          var title_data = '';
          
          <?php //if(isset($this->commodityAndLocation) && !empty($this->commodityAndLocation)) { ?>
          <?php //if($allow) {
          if(!empty($this->selectedDate)){
              $this->date = date('F Y',strtotime($this->selectedDate));
          }
          ?>
              title_data = <?php echo "'$commodityName, $this->date'"; ?>;
              subtitleText = <?php echo "'($this->date)'"; ?>;
          <?php //} ?>
              
          $("#chart11_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#chart11_div").siblings('#infobutton').removeClass('hidden');
                                    $("#chart11_div")
                                            .siblings('.infobutton')
                                            .find('.infodiv')
                                            .html(currentMonthText);
                                }
                            },
                    },
                    title: {
                        text: title_data,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px',
                        },
                    },
                    xAxis: {
                        title: {
                      text: 'Geography',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: <?php echo json_encode($locationNames); ?>
                    },
                    yAxis: {
                        title: {
                      text: '#Users',
                      style:{ "fontWeight": "bold" }
                      }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b>' + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        enabled: false,
                        useHTML: true,
                        layout: 'horizontal',
                        align: 'center',
                        //x: 40,
                        //y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        //shadow: true
                    },
                    credits: {enabled: false},
                    series: [{
                        data: [<?php echo $consumptionString; ?>]
                    }]
                    

              });
          
    <?php
        }
    ?>
}


function drawDefaultLineChart() {
  
        var dataArray = new Array();
        
            <?php 
                if(isset($this->default_option) && !empty($this->default_option)) { 
                    //$commNames = array('new_acceptors'=>'New family planning acceptors', 'current_users'=>'Female 15-49 years using modern contraceptives');
                    $commNames = array('new_acceptors'=>'New FP acceptors', 'current_users'=>'Current FP Users');
                    $monthNames = array_keys($this->consumptionArray);
                    
                    foreach($commNames as $alias=>$commName){
            ?>
                        //JS
                        var obj = {name: '<?php echo $commName; ?>', data: []};
            <?php
                        foreach($this->consumptionArray as $monthName=>$locationData){
                            $monthTotal = 0;
                            foreach($locationData as $indicators){
                                $monthTotal += (int)$indicators[$alias];
                            }
            ?>
                            //push the value for the current month in the loop
                            obj.data.push(<?php echo $monthTotal; ?>);
            <?php
                        }
            ?>
                        dataArray.push(obj);
            <?php
                    }
            ?>
                    


        <?php 
        if(isset($this->selectedDatemultiple) && !empty($this->selectedDatemultiple)){
         $textTitle = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date";
        }else{
         $textTitle = $this->start_date.' to '.$this->end_date;    
        }
        $textHook = $this->geoListSelectionMade ? 'in selected geographies' : ''; ?>
        
        var title_data = <?php echo "'Current FP users and New FP Acceptors $textHook, $textTitle'"; ?>;
        var subtitleText = <?php echo "'($textTitle)'"; ?>;
        
                $('#chart13_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 470,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart13_div").siblings('#infobutton').removeClass('hidden');
                                $("#chart13_div")
                                     .siblings('.infobutton')
                                     .find('.infodiv')
                                     .html(overtimeText);
                            }
                        }
                    },
                    title: {
                        text: title_data,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                         title: {
                      text: 'Month',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: <?php echo json_encode($monthNames); ?>
                    },
                    yAxis: {
                        title: {
                      text: '#Users',
                      style:{ "fontWeight": "bold" }
                      },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        series: {
                            marker: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        //verticalAlign: 'center',
                        align: 'center',
                        borderWidth: 1
                        //shadow: true
                    },
                    series: dataArray
                });
                
    <?php }//end big if ?>

    }//end drawDefaultLineChart
    
    
    
    function drawCommodityOvertimeChart() {
        <?php 
                $commodityName = '';
                if(isset($this->commodityOnly)) {
                    $commodityName = $this->commodityObject['commodity_name']; 
                    if(substr($commodityName, 0, 6) == 'Female') $commodityName = 'Current FP Users';
                    if(substr($commodityName, 0, 3) == 'New') $commodityName = 'New FP acceptors';
                }
        ?>
                
        var dataArray = new Array();
        var obj = {name: '<?php echo $commodityName; ?>', data: []};
            <?php 
                $consumptionArray = array();
                if(isset($this->commodityOnly) && !empty($this->commodityOnly)) { 
                 $monthNames = array_keys($this->consumptionArray);
                 
                 foreach($this->consumptionArray as $monthName=>$monthArray){                     
                     $totalCommoditySum = 0;
                     
                     foreach($monthArray as $location=>$indicators){
                         $totalCommoditySum += (int)$indicators[$this->commodityObject['commodity_alias']];
                     }
            ?>
                    obj.data.push(<?php echo $totalCommoditySum; ?>);
                     
            <?php
                    }//end foreach
                    
                      if(isset($this->selectedDatemultiple) && !empty($this->selectedDatemultiple)){
         $textTitle = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date";
        }else{
         $textTitle = $this->start_date.' to '.$this->end_date;    
        }
            ?>

        dataArray.push(obj); 
        
        
          var title_data = <?php echo "'$commodityName, $textTitle'"; ?>;
          var subtitleText = <?php echo "'($textTitle)'"; ?>;
        
          
                
            
                
                $('#chart13_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 470,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart13_div").siblings('#infobutton').removeClass('hidden');
                                $("#chart13_div")
                                     .siblings('.infobutton')
                                     .find('.infodiv')
                                     .text(overtimeText);
                            }
                        }
                    },
                    title: {
                        text: title_data,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                        : {
                         title: {
                      text: 'Month',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: <?php echo json_encode($monthNames); ?>
                    },
                    yAxis: {
                         title: {
                      text: '#Users',
                      style:{ "fontWeight": "bold" }
                      },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        series: {
                            marker: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        //verticalAlign: 'center',
                        align: 'center',
                        borderWidth: 1
                        //shadow: true
                    },
                    series: dataArray
                });
                
     <?php
                
                } //end if
     ?>     

    }
    


    function drawCommodityAndLocationLineChart() {
        //console.log("Highest");
        //console.log(<?php //echo json_encode($this->consumptionArray);?>);
        //console.log(<?php //echo json_encode($this->consumptionArray); ?>);
        
         ///$mmg = array_keys($this->consumptionArray); 
        //console.log("Location count: " + '<?php //echo json_encode($mmg);?>');
        
        var dataArray = new Array();
        
            <?php 
                $commodityName = ''; $commodityAlias="";
                if(isset($this->commodityAndLocation)) {
                    $commodityName = $this->commodityObject['commodity_name']; 
                    if(substr($commodityName, 0, 6) == 'Female') $commodityName = 'Current FP Users';
                    if(substr($commodityName, 0, 3) == 'New') $commodityName = 'New FP acceptors';
                    $commodityAlias = $this->commodityObject['commodity_alias']; 
                }
            
                if(isset($this->commodityAndLocation) && !empty($this->commodityAndLocation)) { 
                    $monthNames = array_keys($this->consumptionArray);
                    $firstLocation = '';
                    
                    $locationNames = array();
                    if(isset($this->geoLocations)) {
                        reset($this->consumptionArray);
                        $firstElement = current($this->consumptionArray);
                        $locationNames = array_keys($firstElement);
                        //$firstLocation = $locationNames[0];
                    }
                    
                    foreach($locationNames as $key=>$location){
            ?>
                        //JS
                        //console.log('The arraty');
                        //console.log(<?php //echo json_encode($locationNames); ?>);
                        //return;
                        //console.log(<?php //echo json_encode($this->consumptionArray); ?>);
                        var obj = {name: '<?php echo $location; ?>', data: []};
            
           <?php       foreach($monthNames as $monthName){ ?>
                
                            obj.data.push(<?php echo $this->consumptionArray[$monthName][$location][$commodityAlias]; ?>);                            
                            
            <?php
                        }
                        if($key == 0){
            ?>
                            obj.color = '#000000';
                            obj.dashStyle = 'dot';
                            obj.marker = {enabled: true};
            <?php
                        }
            ?>
                        dataArray.push(obj);
            <?php
                    }
                    
                    if(isset($this->selectedDatemultiple) && !empty($this->selectedDatemultiple)){
         $textTitle = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date";
        }else{
         $textTitle = $this->start_date.' to '.$this->end_date;    
        }
            ?>
            
            var title_data = <?php echo "'$commodityName in selected geographies, $textTitle'"; ?>;
            var subtitleText = <?php echo "'($textTitle)'"; ?>;

            $('#chart13_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 470,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart13_div").siblings('#infobutton').removeClass('hidden');
                                $("#chart13_div")
                                     .siblings('.infobutton')
                                     .find('.infodiv')
                                     .text(overtimeText);
                            }
                        }
                    },
                    title: {
                        text: title_data,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                        title: {
                      text: 'Month',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: <?php echo json_encode($monthNames); ?>
                    },
                    yAxis: {
                        title: {
                      text: '#Users',
                      style:{ "fontWeight": "bold" }
                      },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                   '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        series: {
                            marker: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        //verticalAlign: 'center',
                        align: 'center',
                        borderWidth: 1
                        //shadow: true
                    },
                    series: dataArray
                });
                
    <?php } ?>


    }
    
</script>



                
      <script src="../js/highcharts/highcharts.js"></script>
        <script src="../js/highcharts/modules/exporting.js"></script>   

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

<script src="../js/tp/functions.js"></script>

</body>

</html>