     <?php  
                                        $fileInfo = pathinfo(__FILE__);
                                        $fileID = $fileInfo['filename'];
                                        $activationBar = 'consumption';
                                       // $variable = 'Simple';        
                                        require_once('views/scripts/template/template.phtml');
                                       
                                    ?> 
                         <form name="dashboardForm" id="consumptionForm" method="post" onsubmit="return checkCommoditySelection();"> 
                                    
                                       <div class="row">
                                         
                                           <div class="col-sm-5  pull-right " style="margin-bottom:20px;">
                                               
			         	                      <?php require_once('views/scripts/consumption/top_buttons.phtml');?>
    
                                           </div>
                                           
                                           <div class="col-sm-7 pull-right " >
                                         
                                              <div class="row">
                                                 <!--<div  class="col-sm-12 pull-right  clearfix"  style="height:auto;margin-bottom:50px;"  >-->
                                                    
                                                    <div class="col-sm-3 pull-right" style="margin-bottom:50px;">
                                                        
                                                             <?php require_once('views/scripts/consumption/top_buttons1.phtml');?>
                                                    
                                                     </div>
                                                     <div class="col-sm-9 box-shadow pull-right"  style="height:auto">
                                               
                                                     
                                                          <?php
                                                                       $chart_title = "";
                                                                        $info_text =  "";
                                                                        include('views/scripts/template/chart_title.phtml');
                                                            
                                                           ?>
                                                         
                                                        
                                                           <div id="chart11_div" style="width:100%; height:auto;"></div>
                                                       
                                                    </div>
                                                     
                                              </div>
                                           </div>
                                       </div>
                                                     
                                        
                                        <div class="row" style="margin-top:20px;margin-bottom:20px;">
				                              <!--</div>--> 
                                               
                                                 <div class="col-sm-7 " style="height:auto;"  >
                                                     
                                                     <div class="row">
                                                        <div class="col-sm-3 pull-right pull-left-sm" id="lastd" style="margin-bottom:70px;">

                                                           <?php require_once('views/scripts/consumption/top_buttons11.phtml');?>

                                                         </div>
                                                     
                                                            <div class="col-sm-9 box-shadow"  id="chart2" style="height:auto;">

                                                                                                 <?php 
                                                                                            if(isset($this->selectedDatemultiple) && !empty($this->selectedDatemultiple)){
                                                                                                     $textTitle = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date";
                                                                                            }else{
                                                                                                  $textTitle = $this->start_date.' to '.$this->end_date;    
                                                                                                }
                                                                                            $textHook = $this->geoListSelectionMade ? 'in selected geographies' : ''; ?>


                                                                                      <?php
                                                                                              $chart_title = "";
                                                                                              $info_text =  "";
                                                                                              include('views/scripts/template/chart_title.phtml');
                                                                                              //echo 6;

                                                                                      ?>

                                                               <div id="chart13_div" style="width:100%; height:auto;"></div>

                                                            </div>
                                                     </div>
                                               
                                                </div>
                                               
                                          
                                               
                                                </div>
                                               
                                              
                                          
                                       
                                         
                                        
                                        
                                    </form>
          
                                   
                                </div>

		
		<div class="clear"></div>
                </div>
            
          
            
           
            
          
           
           </div><!-- content -->
           <br/><br/><br/>



<script type="text/javascript">
    
  var newFPCurrentMonth = "This chart shows number of clients who accepted a modern family planning method for the first time in their lives in the most recent month for the selected geography.";
  var newFPOvertime = "This chart shows the number of clients who accepted a modern family planning method for the first time in their lives over a period of 12 months for the selected geography.";
  var currentFPCurrentMonth = "This chart shows the number of clients who have ever used an FP method at any point before returning to receive any family planning method in the most recent month for the selected geography.";
  var currentFPOvertime = "This chart, which shows the number of clients who have ever used an FP method at any point before returning to receive any family planning method, illustrates use over a period of 12 months for the selected geography.";
  
  var currentMonthText ="";
  var overtimeText = "";
  var selectedCommodityAlias = "";
  
  //check if only one commodity selected and get which commodity it is
  <?php if(count($this->commodityObjectsArray)== 1) { ?>
      selectedCommodityAlias = '<?php echo $this->commodityObjectsArray[0]['commodity_alias']; ?>';
  <?php } ?>
      
      console.log('selectedCommodityAlias: ' + selectedCommodityAlias);
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);
  
    $(function() {
        
	 // document.getElementById("allCharts").style.marginLeft="130px";

          
        //drawTest();
	<?php if(isset($this->default_option)) { ?>
                console.log("DEFAULT");
                currentMonthText = '<u>New FP Acceptors</u><br>' + newFPCurrentMonth + "<br/><br/>" + '<u>Current FP Users</u><br>' + currentFPCurrentMonth;
                overtimeText = '<u>New FP Acceptors</u><br>' + newFPOvertime + "<br/><br/>" + '<u>Current FP Users</u><br>' + currentFPOvertime;
                
                drawBarChart();
                <?php if(!isset($this->geoListSelectionMade)) { //line chart only available if no geo selection made?>
                    drawDefaultLineChart();
                <?php } else { ?>
                    $('#chart2').html('<div style="font-weight:bold; padding:5px;background: #eeeeee;border:1px solid #cccccc;">The consumption chart for the last 12 months will not be displayed when multiple locations are selected. Please either select a single commodity and multiple locations or single commodity and single location to display this chart.</div>');
                    $('#lastd select').hide();
                <?php } ?>
        <?php } else if(isset($this->commodityOnly)) { ?>
                console.log("commodityOnly");
                //set the info text with the tenary operator check
                currentMonthText = selectedCommodityAlias == 'new_acceptors' ? newFPCurrentMonth : currentFPCurrentMonth;
                overtimeText = selectedCommodityAlias == 'new_acceptors' ? newFPOvertime : currentFPOvertime;
                
                drawLocationBarChart();
                drawCommodityOvertimeChart();
        <?php } else if(isset($this->commodityAndLocation)) { ?>
                console.log("commodityAndLocation");
                //set the info text with the tenary operator check
                currentMonthText = selectedCommodityAlias == 'new_acceptors' ? newFPCurrentMonth : currentFPCurrentMonth;
                overtimeText = selectedCommodityAlias == 'new_acceptors' ? newFPOvertime : currentFPOvertime;
                
                drawLocationBarChart();
                drawCommodityAndLocationLineChart();
        <?php } ?>        
		 
  });
  

 function drawBarChart() {
        var dataArray = new Array();
        var consumptionData = <?= 
                                isset($this->default_option) ?
                                $this->currentMonthConsumptionArray :
                                '{}'  //empty json object
                             ?>;
        
        commodityNames = {'new_acceptors': 'New FP acceptors', 'current_users':'Current FP Users'};
        locationNames = Object.keys(consumptionData);
        
        for(alias in commodityNames){
            var obj = {name: commodityNames[alias], data: []};
            
            for(loc in locationNames){
                loopLocation = locationNames[loc];
                obj.data.push(parseInt(consumptionData[loopLocation][alias]));
            }
            dataArray.push(obj);
        }
          
            <?php if($this->freshVisit) { ?>
                var titleText = '<?php echo  "Current FP users and New FP acceptors, <br/>$this->date"; ?>';
            <?php } else { ?>
                var titleText = '<?php echo  "Current FP users and New FP acceptors <br/>in selected geographie, $this->date"; ?>';
            <?php } ?>
              
          $("#chart11_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#chart11_div").siblings('#infobutton').removeClass('hidden');
                                    $("#chart11_div")
                                            .siblings('.row')
                                            .find('.infodiv')
                                            .html(currentMonthText);
                                }
                            },
                    },
                    title: {
                        text: titleText,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontSize: '16px',
                            fontFamily: 'Arial',
                        },
                    },
                    xAxis: {
                         title: {
                      text: 'Geography',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: locationNames
                    },
                    yAxis: {
                        title: {
                      text: '#  Users',
                      style:{ "fontWeight": "bold" }
                      }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'horizontal',
                        align: 'center',
                        //x: 40,
                        //y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        //shadow: true
                    },
                    credits: {enabled: false},
                    series:dataArray

              });
                            
}//end drawbarchart


function drawLocationBarChart() {
        var values = new Array();
        var allow = false;
        
        <?php if(isset($this->commodityAndLocation) || isset($this->commodityOnly)) { ?>
                allow = true
        <?php } ?>
            
        var consumptionData = allow === true ? <?= $this->currentMonthConsumptionArray; ?> : {};
        var commodityName = allow === true ? '<?= $this->commodityObject['commodity_name']; ?>' : '';
        var commodityAlias = allow === true ? '<?= $this->commodityObject['commodity_alias']; ?>' : '';
        commodityNames = {'new_acceptors': 'New FP acceptors', 'current_users':'Current FP Users'};
        locationNames = Object.keys(consumptionData);
                
        for(loc in consumptionData){
            consumption = consumptionData[loc];
            var value = loc.toUpperCase() === 'National'.toUpperCase() ?
                                  {y: parseInt(consumption[commodityAlias]), color: '#000000'} :
                                  parseInt(consumption[commodityAlias]);
            
            values.push(value);
        }
        
                         
          <?php 
            if(!empty($this->selectedDate)){
                $this->date = date('F Y',strtotime($this->selectedDate));
            }
          ?>
                    
          <?php if($this->freshVisit) { ?>
                var titleText = commodityName + ', <?= $this->date; ?>';
            <?php } else { ?>
                var titleText =  commodityName + ' in selected geographies, ' + '<?= $this->date; ?>';
            <?php } ?>
              
          $("#chart11_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#chart11_div").siblings('#infobutton').removeClass('hidden');
                                    $("#chart11_div")
                                            .siblings('.row')
                                            .find('.infodiv')
                                            .html(currentMonthText);
                                }
                            },
                    },
                    title: {
                        text: titleText,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px',
                        },
                    },
                    xAxis: {
                        title: {
                      text: 'Geography',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: locationNames
                    },
                    yAxis: {
                        title: {
                      text: '#  Users',
                      style:{ "fontWeight": "bold" }
                      }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b>' + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        enabled: false,
                        useHTML: true,
                        layout: 'horizontal',
                        align: 'center',
                        //x: 40,
                        //y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        //shadow: true
                    },
                    credits: {enabled: false},
                    series: [{
                        data: values
                    }]
                    

              });
          
}


function drawDefaultLineChart() {
                    
        var dataArray = new Array();
        var consumptionData = <?= isset($this->default_option) ? $this->consumptionArray : '{}'  //empty json object ?>;
        var commodityNames = {'new_acceptors': 'New FP acceptors', 'current_users':'Current FP Users'};
        
        for(alias in commodityNames){
            var obj = {name: commodityNames[alias], data: []};
                
                for(month in consumptionData){
                    monthTotal = 0;
                    locationNames = Object.keys(consumptionData[month]);
                    
                    for(loc in locationNames){
                        loopLocation = locationNames[loc];
                        monthTotal += parseInt(consumptionData[month][loopLocation][alias]);
                    }
                    
                    obj.data.push(monthTotal);
                }
            
            dataArray.push(obj);
        }
        
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = <?php echo json_encode($this->end_date); ?>;
        var monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        var dateLength = selectedDatemultiple.length;
        
        var dateText = '<?= $this->start_date . " to " . $this->end_date ?>';
        if(dateLength > 0){
            dateText = dateLength === 1 ? 
                    monthNamesWithYears[0] : 
                    "across selected dates";
        } 

        <?php if($this->freshVisit) { ?>
            var titleText = "Current FP users and New FP Acceptors, <br/>" + dateText;
        <?php } else { ?>
            var titleText = "Current FP users and New FP Acceptors in selected geographies, <br/>" + dateText;
        <?php } ?>
            
        
                $('#chart13_div').highcharts({
                    chart: {
                        type: dateLength == 1 ? 'column' : 'line',
                        height: 470,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart13_div").siblings('#infobutton').removeClass('hidden');
                                $("#chart13_div")
                                     .siblings('.row')
                                     .find('.infodiv')
                                     .html(overtimeText);
                            }
                        }
                    },
                    title: {
                        text: titleText,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                         title: {
                      text: 'Month',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: monthNamesWithYears
                    },
                    yAxis: {
                        title: {
                      text: '#  Users',
                      style:{ "fontWeight": "bold" }
                      },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        series: {
                            marker: {
                                enabled: true
                            }
                        },
                        column: dateLength === 1  
                                ? {    
                                   dataLabels: {
                                         enabled: true,
                                     }
                                 }
                                 : {}  
                    },
                    legend: {
                        layout: 'horizontal',
                        //verticalAlign: 'center',
                        align: 'center',
                        borderWidth: 1
                        //shadow: true
                    },
                    series: dataArray
                });
                
    <?php //}//end big if ?>

}//end drawDefaultLineChart



function drawCommodityOvertimeChart() {
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = <?php echo json_encode($this->end_date); ?>;
        var monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        var dateLength = selectedDatemultiple.length;
        
        var dataArray = new Array();
        var allow = false;
        <?php if(isset($this->commodityAndLocation) || isset($this->commodityOnly)) { ?>
                allow = true
        <?php } ?>
        
        var consumptionData = allow === true ? <?= $this->consumptionArray; ?> : {};
        var commodityName = allow === true ? '<?= $this->commodityObject['commodity_name']; ?>' : '';
        var commodityAlias = allow === true ? '<?= $this->commodityObject['commodity_alias']; ?>' : '';
        
        commodityNames = {'new_acceptors': 'New FP acceptors', 'current_users':'Current FP Users'};
        locationNames = Object.keys(consumptionData);
        console.log('consumptionData', consumptionData, 'locationNames', locationNames);
        var obj = {name: commodityName, data: []};
        
        for(month in consumptionData){
            monthData = consumptionData[month];
            totalCommoditySum = 0;
            
            for(loc in monthData){
                locationData = monthData[loc];
                totalCommoditySum += parseInt(locationData[commodityAlias]);
            }
            obj.data.push(totalCommoditySum);
        }
        
        dataArray.push(obj); 
        console.log('dataArray', dataArray);
        
          var title_data = commodityName + ', <?= $textTitle; ?>';
          var subtitleText = <?php echo "'($textTitle)'"; ?>;
          
          var dateText = '<?= $this->start_date . " to " . $this->end_date ?>';
            if(dateLength > 0){
                dateText = dateLength === 1 ? 
                        monthNamesWithYears[0] : 
                        "across selected dates";
            } 

            <?php if($this->freshVisit) { ?>
                var titleText = commodityName +', ' + dateText;
            <?php } else { ?>
                var titleText = commodityName + " in selected geographies, <br/>" + dateText;
            <?php } ?>
        
                $('#chart13_div').highcharts({
                    chart: {
                        type: dateLength == 1 ? 'column' : 'line',
                        height: 470,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart13_div").siblings('#infobutton').removeClass('hidden');
                                $("#chart13_div")
                                     .siblings('.row')
                                     .find('.infodiv')
                                     .text(overtimeText);
                            }
                        }
                    },
                    title: {
                        text: titleText,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                      title: {
                        text: 'Month',
                        style:{ "fontWeight": "bold" }
                      },
                        categories: monthNamesWithYears
                    },
                    yAxis: {
                         title: {
                      text: '#  Users',
                      style:{ "fontWeight": "bold" }
                      },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        series: {
                            marker: {
                                enabled: true
                            }
                        },
                        column: dateLength === 1  
                         ? {    
                            dataLabels: {
                                  enabled: true,
                              }
                          }
                          : {}  
                    },
                    legend: {
                        layout: 'horizontal',
                        //verticalAlign: 'center',
                        align: 'center',
                        borderWidth: 1
                        //shadow: true
                    },
                    series: dataArray
                });

}
    
    
    

function drawCommodityAndLocationLineChart() {
        var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        var startDate = <?php echo json_encode($this->end_date); ?>;
        var monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        var dateLength = selectedDatemultiple.length;
        
        var dataArray = new Array();
        var consumptionData = <?= isset($this->commodityAndLocation) ? $this->consumptionArray : '{}'  //empty json object ?>;
        var commodityName = '<?= isset($this->commodityAndLocation) ? $this->commodityObject['commodity_name'] : ''; ?>';
        var commodityAlias = '<?= isset($this->commodityAndLocation) ? $this->commodityObject['commodity_alias'] : ''; ?>';
        commodityNames = {'new_acceptors': 'New FP acceptors', 'current_users':'Current FP Users'};
        
        var monthNames = Object.keys(consumptionData);
        var locationNames = Object.keys(consumptionData[monthNames[0]]);
        
        for(loc in locationNames){
            loopLocation = locationNames[loc];
            console.log('loopLocation', loopLocation);
            var obj = {name: loopLocation, data: []};
                
                for(month in monthNames){
                    loopMonth = monthNames[month];
                    obj.data.push(parseInt(consumptionData[loopMonth][loopLocation][commodityAlias]));
                    if(loopLocation.toUpperCase() === 'National'.toUpperCase()){
                        obj.color = '#000000';
                        obj.dashStyle = 'dot';
                        obj.marker = {enabled: true};
                    }
                }
            
            dataArray.push(obj);
        }
        
            
            var dateText = '<?= $this->start_date . " to " . $this->end_date ?>';
            if(dateLength > 0){
                dateText = dateLength === 1 ? 
                        monthNamesWithYears[0] : 
                        "across selected dates";
            } 
            var titleText = commodityName + ' in selected geographies,  <br/>' + dateText;
            

            $('#chart13_div').highcharts({
                    chart: {
                        type: dateLength == 1 ? 'column' : 'line',
                        height: 470,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart13_div").siblings('#infobutton').removeClass('hidden');
                                $("#chart13_div")
                                     .siblings('.row')
                                     .find('.infodiv')
                                     .text(overtimeText);
                            }
                        }
                    },
                    title: {
                        text: titleText,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                        title: {
                      text: 'Month',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: monthNamesWithYears
                    },
                    yAxis: {
                        title: {
                      text: '#  Users',
                      style:{ "fontWeight": "bold" }
                      },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                   '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        series: {
                            marker: {
                                enabled: true
                            }
                        },
                        column: dateLength === 1  
                         ? {    
                            dataLabels: {
                                  enabled: true,
                              }
                          }
                          : {}  
                    },
                    legend: {
                        layout: 'horizontal',
                        //verticalAlign: 'center',
                        align: 'center',
                        borderWidth: 1
                        //shadow: true
                    },
                    series: dataArray
                });
    }
    
</script>



                
      <script src="../js/highcharts/highcharts.js"></script>
        <script src="../js/highcharts/modules/exporting.js"></script>   

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

<!--<script src="../js/tp/functions.js"></script>-->
<script src="../js/tp/overtime-ops.js"></script>
</body>

</html>