<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	position: relative;
}

#homecontent-mid {
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px; 
}

.sliderdiv {
	float: left;
}

.main-search {
	float: left;
	overflow: hidden;
}

.nav-buttons {
	float: left;
	overflow: hidden;
}


</style>

<!--<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">-->

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
       <!--<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />-->
    <!--<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css">-->

    
<style>
    
    .infobutton {
        padding-right: 13px;
    }
    
</style>        
    
    
<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" defer async></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />

<!--<script src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>-->
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>-->

<script>
    function checkCommoditySelection(){
//        console.log(combo.options);
//        console.log(combo.options[combo.selectedIndex]);
//        console.log(combo.options[combo.selectedIndex].value);

        //var combo = document.getElementById("comm_id");
        //var selectedValue = combo.options[combo.selectedIndex].value;
        //alert('submitting: ' + selectedValue); 
        
        //if(selectedValue != 0) return true;
                
        //return false;
    }
</script>

<script>
  $(function() {
    $( "#accordion" ).accordion({active: 1});
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  </script>
</head>
<body class="yui-skin-sam">
    
    <?php   
            //echo 'high<br/><br/>' ;
            //var_dump($this->consumption_by_method); 
            //var_dump($this->consumption_bsmandlocation_first); 
    ?>
    
	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>
				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>
			</div>

			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
                                <?php require_once('views/scripts/consumption/top_buttons2.phtml');?>
			</div>
			<div class="hrNav"></div>

			<!-------   /////////////////////////// make left buttons ////////////////////// -->
			<div class="nav-buttons">
				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    require_once('views/scripts/dashboard/left_buttons.phtml');
                                ?>
			</div>
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');
                             // print_r($this->consumptionArray);
                                ?>
			</div>
			
			<!-------   /////////////////////////// charts ////////////////////// -->

			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">
				
				<div class="hrNav" id="hrr"></div>
				<div class="hrNav"></div>
				
				
				    <div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
                                                                    <div id="infobutton" class="infobutton hidden"">
                                                                        <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                        <div id="" class="infodiv" >
                                                                            ...
                                                                        </div>
                                                                    </div>
								    <div class="hrNav"></div>
									<div id="chart11_div" style="width: 630px; height: 460px;"></div>
									</div>
									
								</div>
							</div>
						</div>			
					</div>
					
					<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
					
					<div id="bottomrow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
                                                                            <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    ...
                                                                                </div>
                                                                            </div>
                                                                        <div class="hrNav"></div>
    									<div id="chart13_div" style="width: 630px; height: 370px;"></div>
									</div>
									
								</div>
							</div>
						</div>
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
                                                <div class="main-search"></div>
					</div>
					
				</div>
				
				
	</div>

		<div class="hrNav"></div>
		<div class="clear"></div>
		
                
		<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->

		<!-------   /////////////////////////// main gnr ////////////////////// -->


<script type="text/javascript">
    
  var newFPCurrentMonth = "This chart shows number of clients who accepted a modern family planning method for the first time in their lives in the most recent month or selected date(s) for the selected geography.";
  var newFPOvertime = "This chart shows the number of clients who accepted a modern family planning method for the first time in their lives over a period of 12 months or selected date(s) for the selected geography.";
  var currentFPCurrentMonth = "This chart shows the number of clients who have ever used an FP method at any point before returning to receive any family planning method in the most recent month or selected date(s) for the selected geography.";
  var currentFPOvertime = "This chart, which shows the number of clients who have ever used an FP method at any point before returning to receive any family planning method, illustrates use over a period of 12 months or selected date(s) for the selected geography.";
  
  var currentMonthText ="";
  var overtimeText = "";
  var selectedCommodityAlias = "";
  
  //check if only one commodity selected and get which commodity it is
  <?php if(count($this->commodityObjectsArray)== 1) { ?>
      selectedCommodityAlias = '<?php echo $this->commodityObjectsArray[0]['commodity_alias']; ?>';
  <?php } ?>
      
      console.log('selectedCommodityAlias: ' + selectedCommodityAlias);
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);
  
    $(function() {
	  document.getElementById("allCharts").style.marginLeft="130px";

          
        //drawTest();
	<?php if(isset($this->default_option)) { ?>
                console.log("DEFAULT");
                currentMonthText = '<u>New FP Acceptors</u><br>' + newFPCurrentMonth + "<br/><br/>" + '<u>Current FP Users</u><br>' + currentFPCurrentMonth;
                overtimeText = '<u>New FP Acceptors</u><br>' + newFPOvertime + "<br/><br/>" + '<u>Current FP Users</u><br>' + currentFPOvertime;
                
                drawBarChart();
                <?php if(!isset($this->geoListSelectionMade)) { //line chart only available if no geo selection made?>
                    drawDefaultLineChart(); 
                <?php } else { ?>
                    $('#chart13_div').html('<div style="font-weight:bold; padding:5px;background: #eeeeee;border:1px solid #cccccc;">' +
                            'The consumption chart for the last 12 months will not be displayed when multiple locations are selected. ' +
                            'Please either select a single user type and multiple locations or single user type and single location to ' +
                            'display this chart.</div>');
                <?php } ?>
        <?php } else if(isset($this->commodityOnly)) { ?>
                console.log("commodityOnly");
                //set the info text with the tenary operator check
                currentMonthText = selectedCommodityAlias == 'new_acceptors' ? newFPCurrentMonth : currentFPCurrentMonth;
                overtimeText = selectedCommodityAlias == 'new_acceptors' ? newFPOvertime : currentFPOvertime;
                
                drawLocationBarChart();
                drawCommodityOvertimeChart();
        <?php } else if(isset($this->commodityAndLocation)) { ?>
                console.log("commodityAndLocation");
                //set the info text with the tenary operator check
                currentMonthText = selectedCommodityAlias == 'new_acceptors' ? newFPCurrentMonth : currentFPCurrentMonth;
                overtimeText = selectedCommodityAlias == 'new_acceptors' ? newFPOvertime : currentFPOvertime;
                
                drawLocationBarChart();
                drawCommodityAndLocationLineChart();
        <?php } ?>        
		 
  });
  

 function drawBarChart() {
        var dataArray = new Array();
        var consumptionData = <?= 
                                isset($this->default_option) ?
                                $this->currentMonthConsumptionArray :
                                '{}'  //empty json object
                             ?>;
        
        commodityNames = {'new_acceptors': 'New FP acceptors', 'current_users':'Current FP Users'};
        locationNames = Object.keys(consumptionData);
        
        for(alias in commodityNames){
            var obj = {name: commodityNames[alias], data: []};
            
            for(loc in locationNames){
                loopLocation = locationNames[loc];
                obj.data.push(parseInt(consumptionData[loopLocation][alias]));
            }
            dataArray.push(obj);
        }
          
          var title_data = '';
          <?php if(isset($this->default_option) && !empty($this->default_option)) { ?>
              title_data = <?php echo "'Current FP users and New FP acceptors, $this->date'"; ?>;
              subtitleText = <?php echo "'($this->date)'"; ?>;
          <?php } else { ?>
              title_data = <?php echo "'Consumption by method, $this->single_location, $this->date'"; ?>;
              subtitleText = <?php echo "'($this->single_location, $this->date)'"; ?>;
          <?php } ?>
          
          //$('#bar-title').text(title_data);
              
          $("#chart11_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#chart11_div").siblings('#infobutton').removeClass('hidden');
                                    $("#chart11_div")
                                            .siblings('.infobutton')
                                            .find('.infodiv')
                                            .html(currentMonthText);
                                }
                            },
                    },
                    title: {
                        text: title_data,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontSize: '16px',
                            fontFamily: 'Arial',
                        },
                    },
                    xAxis: {
                         title: {
                      text: 'Geography',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: locationNames
                    },
                    yAxis: {
                        title: {
                      text: '#  Users',
                      style:{ "fontWeight": "bold" }
                      }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        useHTML: true,
                        layout: 'horizontal',
                        align: 'center',
                        //x: 40,
                        //y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        //shadow: true
                    },
                    credits: {enabled: false},
                    series:dataArray

              });
                            
}//end drawbarchart


function drawLocationBarChart() {
        var values = new Array();
        var allow = <?= isset($this->commodityAndLocation) || isset($this->commodityOnly) ?> ? true : false;
        var consumptionData = allow === true ? <?= $this->currentMonthConsumptionArray; ?> : {};
        var commodityName = allow === true ? '<?= $this->commodityObject['commodity_name']; ?>' : '';
        var commodityAlias = allow === true ? '<?= $this->commodityObject['commodity_alias']; ?>' : '';
        commodityNames = {'new_acceptors': 'New FP acceptors', 'current_users':'Current FP Users'};
        locationNames = Object.keys(consumptionData);
                
        for(loc in consumptionData){
            consumption = consumptionData[loc];
            var value = loc.toUpperCase() === 'National'.toUpperCase() ?
                                  {y: parseInt(consumption[commodityAlias]), color: '#000000'} :
                                  parseInt(consumption[commodityAlias]);
            
            values.push(value);
        }
        
               
          var title_data = '';
          
          <?php 
            if(!empty($this->selectedDate)){
                $this->date = date('F Y',strtotime($this->selectedDate));
            }
          ?>
          
          title_data = commodityName + ', <?= $this->date; ?>';
          
              
          $("#chart11_div").highcharts({
                    chart: {
                        type: 'column',
                        spacingLeft: 20,
                        events: {
                                load:function(){
                                    $("text:contains(Highcharts.com)").css("display","none");
                                    $("#chart11_div").siblings('#infobutton').removeClass('hidden');
                                    $("#chart11_div")
                                            .siblings('.infobutton')
                                            .find('.infodiv')
                                            .html(currentMonthText);
                                }
                            },
                    },
                    title: {
                        text: title_data,
                        x: -40,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px',
                        },
                    },
                    xAxis: {
                        title: {
                      text: 'Geography',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: locationNames
                    },
                    yAxis: {
                        title: {
                      text: '#  Users',
                      style:{ "fontWeight": "bold" }
                      }
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b>' + ': ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        column: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        enabled: false,
                        useHTML: true,
                        layout: 'horizontal',
                        align: 'center',
                        //x: 40,
                        //y: 60,
                        borderWidth: 1,
                        backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                        //shadow: true
                    },
                    credits: {enabled: false},
                    series: [{
                        data: values
                    }]
                    

              });
          
}


function drawDefaultLineChart() {
                    
        var dataArray = new Array();
        var consumptionData = <?= isset($this->default_option) ? $this->consumptionArray : '{}'  //empty json object ?>;
        commodityNames = {'new_acceptors': 'New FP acceptors', 'current_users':'Current FP Users'};
        
        for(alias in commodityNames){
            var obj = {name: commodityNames[alias], data: []};
                
                for(month in consumptionData){
                    monthTotal = 0;
                    locationNames = Object.keys(consumptionData[month]);
                    
                    for(loc in locationNames){
                        loopLocation = locationNames[loc];
                        monthTotal += parseInt(consumptionData[month][loopLocation][alias]);
                    }
                    
                    obj.data.push(monthTotal);
                }
            
            dataArray.push(obj);
        }
        
        selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        startDate = <?php echo json_encode($this->end_date); ?>;
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);


        <?php 
        if(isset($this->selectedDatemultiple) && !empty($this->selectedDatemultiple)){
         $textTitle = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date";
        }else{
         $textTitle = $this->start_date.' to '.$this->end_date;    
        }
        $textHook = $this->geoListSelectionMade ? 'in selected geographies' : ''; ?>
        
        var title_data = <?php echo "'Current FP users and New FP Acceptors $textHook, $textTitle'"; ?>;
        var subtitleText = <?php echo "'($textTitle)'"; ?>;
        
                $('#chart13_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 470,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart13_div").siblings('#infobutton').removeClass('hidden');
                                $("#chart13_div")
                                     .siblings('.infobutton')
                                     .find('.infodiv')
                                     .html(overtimeText);
                            }
                        }
                    },
                    title: {
                        text: title_data,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                         title: {
                      text: 'Month',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: monthNamesWithYears
                    },
                    yAxis: {
                        title: {
                      text: '#  Users',
                      style:{ "fontWeight": "bold" }
                      },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        series: {
                            marker: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        //verticalAlign: 'center',
                        align: 'center',
                        borderWidth: 1
                        //shadow: true
                    },
                    series: dataArray
                });
                
    <?php //}//end big if ?>

}//end drawDefaultLineChart



function drawCommodityOvertimeChart() {
        selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        startDate = <?php echo json_encode($this->end_date); ?>;
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        
        var dataArray = new Array();
        var allow = <?= isset($this->commodityAndLocation) || isset($this->commodityOnly) ?> ? true : false;
        var consumptionData = allow === true ? <?= $this->consumptionArray; ?> : {};
        var commodityName = allow === true ? '<?= $this->commodityObject['commodity_name']; ?>' : '';
        var commodityAlias = allow === true ? '<?= $this->commodityObject['commodity_alias']; ?>' : '';
        
        commodityNames = {'new_acceptors': 'New FP acceptors', 'current_users':'Current FP Users'};
        locationNames = Object.keys(consumptionData);
        console.log('consumptionData', consumptionData, 'locationNames', locationNames);
        var obj = {name: commodityName, data: []};
        
        for(month in consumptionData){
            monthData = consumptionData[month];
            totalCommoditySum = 0;
            
            for(loc in monthData){
                locationData = monthData[loc];
                totalCommoditySum += parseInt(locationData[commodityAlias]);
            }
            obj.data.push(totalCommoditySum);
        }
        
        dataArray.push(obj); 
        console.log('dataArray', dataArray);
        
          var title_data = commodityName + ', <?= $textTitle; ?>';
          var subtitleText = <?php echo "'($textTitle)'"; ?>;
        
                $('#chart13_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 470,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart13_div").siblings('#infobutton').removeClass('hidden');
                                $("#chart13_div")
                                     .siblings('.infobutton')
                                     .find('.infodiv')
                                     .text(overtimeText);
                            }
                        }
                    },
                    title: {
                        text: title_data,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                      title: {
                        text: 'Month',
                        style:{ "fontWeight": "bold" }
                      },
                        categories: monthNamesWithYears
                    },
                    yAxis: {
                         title: {
                      text: '#  Users',
                      style:{ "fontWeight": "bold" }
                      },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        series: {
                            marker: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        //verticalAlign: 'center',
                        align: 'center',
                        borderWidth: 1
                        //shadow: true
                    },
                    series: dataArray
                });

}
    
    
    

function drawCommodityAndLocationLineChart() {
        selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
        startDate = <?php echo json_encode($this->end_date); ?>;
        monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
        
        var dataArray = new Array();
        var consumptionData = <?= isset($this->commodityAndLocation) ? $this->consumptionArray : '{}'  //empty json object ?>;
        var commodityName = '<?= isset($this->commodityAndLocation) ? $this->commodityObject['commodity_name'] : ''; ?>';
        var commodityAlias = '<?= isset($this->commodityAndLocation) ? $this->commodityObject['commodity_alias'] : ''; ?>';
        commodityNames = {'new_acceptors': 'New FP acceptors', 'current_users':'Current FP Users'};
        monthNames = Object.keys(consumptionData);
        locationNames = Object.keys(consumptionData[monthNames[0]]);
        
        for(loc in locationNames){
            loopLocation = locationNames[loc];
            console.log('loopLocation', loopLocation);
            var obj = {name: loopLocation, data: []};
                
                for(month in monthNames){
                    loopMonth = monthNames[month];
                    obj.data.push(parseInt(consumptionData[loopMonth][loopLocation][commodityAlias]));
                    if(loopLocation.toUpperCase() === 'National'.toUpperCase()){
                        obj.color = '#000000';
                        obj.dashStyle = 'dot';
                        obj.marker = {enabled: true};
                    }
                }
            
            dataArray.push(obj);
        }
        
            
            <?php   
                    if(isset($this->selectedDatemultiple) && !empty($this->selectedDatemultiple)){
         $textTitle = (sizeof($this->selectedDatemultiple)>1)?"across selected dates":"across selected date";
        }else{
         $textTitle = $this->start_date.' to '.$this->end_date;    
        }
            ?>
            
            var title_data = commodityName + ' in selected geographies, ' + '<?= $textTitle; ?>';
            var subtitleText = <?php echo "'($textTitle)'"; ?>;

            $('#chart13_div').highcharts({
                    chart: {
                        //type: 'line',
                        height: 470,
                        //spacingLeft: -20,
                        events: {
                            load:function(){
                                $("text:contains(Highcharts.com)").css("display","none");
                                $("#chart13_div").siblings('#infobutton').removeClass('hidden');
                                $("#chart13_div")
                                     .siblings('.infobutton')
                                     .find('.infodiv')
                                     .text(overtimeText);
                            }
                        }
                    },
                    title: {
                        text: title_data,
                        style: {
                            fontWeight: 'bold',
                            fontFamily: 'Arial',
                            fontSize: '16px'
                        },
                        //x: -20 //center
                    },
                    xAxis: {
                        title: {
                      text: 'Month',
                      style:{ "fontWeight": "bold" }
                      },
                        categories: monthNamesWithYears
                    },
                    yAxis: {
                        title: {
                      text: '#  Users',
                      style:{ "fontWeight": "bold" }
                      },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        formatter: function () {
                            return '<b>' + this.x + '</b><br/>' +
                                   '<b>' + this.series.name + '</b>: ' + thousandSeparator(this.y) + '<br/>';
                        }
                    },
                    plotOptions: {
                        series: {
                            marker: {
                                enabled: true
                            }
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        //verticalAlign: 'center',
                        align: 'center',
                        borderWidth: 1
                        //shadow: true
                    },
                    series: dataArray
                });
    }
    
</script>



                
      <script src="../js/highcharts/highcharts.js"></script>
        <script src="../js/highcharts/modules/exporting.js"></script>   

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

<script src="../js/tp/functions.js"></script>
<script src="../js/tp/overtime-ops.js"></script>

</body>

</html>