<script>
    function checkSelection(){
        /*************************/
        //return;
        /*************************/
        //alert('filter');
        
            var regionBox = document.getElementById("region_c_id"); //lga
            var districtBox = document.getElementById("district_id"); //state
            var provinceBox = document.getElementById("province_id"); //zone
            var commodityBox = document.getElementById('comm_id');;
            
            var regionValues = getSelectedValues(regionBox);
            var districtValues = getSelectedValues(districtBox);
            var provinceValues = getSelectedValues(provinceBox);
            var commodityValues = getSelectedValues(commodityBox);
            
            if(regionValues.length > 0 || districtValues.length > 0 || provinceValues.length > 0){
                if(commodityValues.length > 1){
                    console.log('commodityValues.length: ' + commodityValues.length);
                    alert ('Only one commodity allowed when filtering location(s)');
                    return false;
                }
            }
        
        
        return true;
    }
    
    function getSelectedValues(multipleSelectBox){
        var selected = new Array();
        for (var i = 0; i < multipleSelectBox.options.length; i++) {
             if(multipleSelectBox.options[i].selected){
                //alert(multipleSelectBox.options[i].value);
                selected.push(multipleSelectBox.options[i].value);
            }
        }
        return selected;
    }
</script>

<?php //require_once('../../html/js/singlelocationselect.js');?>

<form name="dashboardForm" id="consumptionForm" method="post" onsubmit="return checkCommoditySelection();"> 

<?php 
require_once('views/helpers/Location.php');
//require_once('views/helpers/ConsumptionLocation.php');
require_once('views/helpers/ScriptContainer.php');

$current_view = '/'.$path[1].'/'. $path[2]; 
?>

<?php  //file_put_contents('c:\wamp\logs\php_debug.log', 'top_buttons 1 >'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();   
       //var_dump("current_view=", $current_view, "END");
       //$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX); 

?>

<p3>
    <div>
        <?php         
            $commsHtml = '';
            $selected = '';
            foreach($this->comms as $comm){
                if(in_array($comm['id'],$this->methods)){
                    $selected = 'selected="selected"';
                }
                //if(substr($comm['commodity_name'], 0, 6) == 'Female') $comm['commodity_name'] = 'Current FP Users';
                //if(substr($comm['commodity_name'], 0, 3) == 'New') $comm['commodity_name'] = 'New FP acceptors';
                
                $commsHtml .= '<option value="'. $comm['id'] . '" ' . $selected . '>' . $comm['commodity_name'] . '</option>';
                $selected = '';
            }
        ?>
        <label><?php echo ($this->chart_module == 'newfpacceptors')?'User Type: ':'Commodity: '; ?></label>
      
        <select id="comm_id" name="comm_id[]" multiple="multiple">
                <!--<option value="0">--Choose--</option>-->
                <!--<option value="0">ALL</option>-->
                <?php echo $commsHtml; ?>
        </select>
    </div>
    <br/>
    
    <div>
        <?php region_filters_dropdown_db($this, $this->locations, $this->criteria, true, true); ?>
        <p>
            <strong>Maximum of six (6) locations allowed per filter</strong><br/>
            <?php 
            if($this->chart_module == "newfpacceptors"){
                echo '<strong>Only one user type allowed when filtering location(s)</strong';
            }else{
            echo '<strong>Only one commodity allowed when filtering location(s)</strong>';
            }
            ?>
        </p>
    </div>
    
    <br/>
    <input type="submit" value="Filter" class="dbbutton dbbutton_leftmenu" onclick="return checkSelection();">
    
</p3>


 </form>


					



