<script>
    function checkSelection1(){
        /*************************/
        return;
        /*************************/
        //alert('filter');
        var commodityIndex = document.getElementById('comm_id').selectedIndex;
        
        if(commodityIndex == 0){
            var regionBox = document.getElementById("region_c_id"); //lga
            var districtBox = document.getElementById("district_id"); //state
            var provinceBox = document.getElementById("province_id"); //zone
            
            var regionValues = getSelectedValues(regionBox);
            var districtValues = getSelectedValues(districtBox);
            var provinceValues = getSelectedValues(provinceBox);
            
            if(regionValues.length > 1 || districtValues.length > 1 || provinceValues.length > 1){
                alert ('Only one (1) location allowed when filtering ALL commodities');
                return false;
            }
        }
        
        return true;
    }
    
    function checkSelection(){
        var LGASelections = $('#region_c_id').val();
        var stateSelections = $('#district_id').val();
        var zoneSelections = $('#province_id').val();
        var selectionMade = false;
        console.log('zoneSelections: ' + stateSelections, stateSelections.length);
        //return false;
        
//        if(LGASelections == null && stateSelections == null && zoneSelections == null){
//            alert("Please select one or more locations to filter");
//            return false;
//        }
//        else
        if(LGASelections != null){
            console.log('inside lga');
               if(LGASelections.length <= 6)
                   return true;
               else {
                    alert("Maximum of six (6) locations allowed per filter");
                    return false;
               }
        }
        else if(stateSelections != null){
            console.log('inside state');
               if(stateSelections.length <= 6) 
                   return true; 
               else {
                    alert("Maximum of six (6) locations allowed per filter");
                    return false;
               }
        }
        else if(zoneSelections != null){
            console.log('inside zone');
           if(zoneSelections.length <= 6) 
                   return true; 
           else {
                alert("Maximum of six (6) locations allowed per filter");
                return false;
           }
        }
//        else{
//            alert("Maximum of six (6) locations allowed per filter");
//            return false;
//        }
        console.log('inside nada');
        
        return true;
    }
    
    function getSelectedValues(multipleSelectBox){
        var selected = new Array();
        for (var i = 0; i < multipleSelectBox.options.length; i++) {
             if(multipleSelectBox.options[i].selected){
                //alert(multipleSelectBox.options[i].value);
                selected.push(multipleSelectBox.options[i].value);
            }
        }
        return selected;
    }
</script>


<?php
    

require_once('views/helpers/Location.php');
//require_once('views/helpers/ConsumptionLocation.php');
require_once('views/helpers/ScriptContainer.php');

$current_view = '/'.$path[1].'/'. $path[2]; 
?>


<?php 
  
        
            $commsHtml = '';
            $selected = '';
            foreach($this->comms as $comm){
                if(array_key_exists($comm['id'],$this->methods)){
                    $selected = 'selected="selected"';
                }                
                $commsHtml .= '<option value="'. $comm['id'] . '" ' . $selected . '>' . ucfirst(strtolower($comm['commodity_name'])) . '</option>';
                $selected = '';
            }
        ?>
        <label>Commodity: </label>
        <select id="comm_id" name="comm_id[]" multiple="multiple">
                <!--<option value="0">--Choose--</option>-->
                <!--<option value="0">ALL</option>-->
                <?php echo $commsHtml; ?>
        </select>
        
     
    <br/>
 
        <?php region_filters_dropdown_db($this, $this->locations, $this->criteria, true, true); ?>
        <p>
            <strong>Maximum of six (6) locations allowed per filter</strong><br/>
            <!--<strong>Only one (1) location allowed when filtering ALL commodities</strong>-->
        </p>
    
    
    <br/>
    <input type="submit" value="Preview" class="dbbutton dbbutton_leftmenu" onclick="return checkSelection();">
 