<?php

echo 

'<p>Dear Administrator of the Family Planning Dashboard,</p>
A request has been made for new user registration. 
Please visit <a href="'.Settings::$COUNTRY_BASE_URL.'/user/requestaccess">Requests</a> to approve or deny this user request. 

<br>Family Planning Dashboard <a href="'.Settings::$COUNTRY_BASE_URL.'">FP DashBoard</a>

<p>
Sincerely, <br>
Director of Family Health Division, FMOH
</p>
';




?>