<?php
	if (isset ($_POST['csv'])){

		$data = array();
		
		$_row = array();
                $data[] = array("","Facility Summary of ".$this->criteria['details_facility']['facility_name']."","");
                $data[] = array("Geo Zone","".$this->criteria['details_facility']['geo_zone']."");
                $data[] = array("State","".$this->criteria['details_facility']['state']."");
                $data[] = array("Local Government","".$this->criteria['details_facility']['lga']."");
                $data[] = array("");
                $data[]  = array("","HR Summary: Total number of health workers trained","");
                $data[] = array("");
                  foreach ($this->heading as $key=>$value){
			$_row[] = $value;
		}
		$data[] = $_row;
		
		foreach ($this->outdetails as $row){
			$_row = array();
			foreach ($row as $key=>$value){
				$_row[] = $value;
			}
			$data[] = $_row;
		}
		//print_r($this->summary);echo '<br/><br/>';
               // print_r($this->summary_details);exit;
 $sizer = sizeof($this->summary_details);
 $data[] = "";
                                    for($u=0;$u<$sizer;$u++){
                                        $titles = $this->summary[$u];
                                        $values = $this->summary_details[$u];
                                    $data[] =  array("Health Workers trained in ".$titles.": ".$values,"");  
                                    //array_push($data,$hw_summary);
                                    }
                
                $data[] = array("");
                $data[] = array("","Commodity Summary: Monthly consumption by method for last 12 months","");
                $data[] = array("");
                $_row = array();
              foreach ($this->headers as $key=>$value){
			$_row[] = $value;
		}
		$data[] = $_row;
		
		foreach ($this->output as $row){
			$_row = array();
			foreach ($row as $key=>$value){
				$_row[] = $value;
			}
			$data[] = $_row;
		}
                
                $data[] = array("");
                $data[] = array("","Clients","");
                $data[] = array("");
                $_row = array();
              foreach ($this->clientHeaders as $key=>$value){
			$_row[] = $value;
		}
		$data[] = $_row;
		
		foreach ($this->clientData as $row){
			$_row = array();
			foreach ($row as $key=>$value){
				$_row[] = $value;
			}
			$data[] = $_row;
		}
                
                
                $data[] = array("");
                $data[] = array("","Stock Out Summary: Stock outs over last 12 months","");
                $data[] = array("");
                $_row = array();
                foreach ($this->headers as $key=>$value){
			$_row[] = $value;
		}
		$data[] = $_row;
		
		foreach ($this->outputs as $row){
			$_row = array();
			foreach ($row as $key=>$value){
				$_row[] = $value;
			}
			$data[] = $_row;
		}
		
               // print_r($data);exit;
		$delimiter = ',';
		$enclosure = '"';
		$encloseAll = false;
		$nullToMysqlNull = false;
	
		$delimiter_esc = preg_quote($delimiter, '/');
		$enclosure_esc = preg_quote($enclosure, '/');
	
		$output = array();

		foreach ($data as $row){
			$outputrow = array();
			foreach ($row as $field){
				if ($field === null && $nullToMysqlNull) {
					$outputrow[] = 'NULL';
					continue;
				}
		
				// Enclose fields containing $delimiter, $enclosure or whitespace
				if ( $encloseAll || preg_match( "/(?:${delimiter_esc}|${enclosure_esc}|\s)/", $field ) ) {
					$outputrow[] = $enclosure . str_replace($enclosure, $enclosure . $enclosure, $field) . $enclosure;
				}
				else {
					$outputrow[] = $field;
				}
			}
                        
                        
                        
			$output[] = implode($delimiter,$outputrow);
		}
		$output = implode("\n", $output);

		header("Content-type: text/csv");
		header("Content-Disposition: attachment; filename=facility-summary::Commodity-Summary:Monthly-consumption-by-method-for-last-12-months" . date("d.m.Y.H.m.s") . ".csv");
		header("Pragma: no-cache");
		header("Expires: 0");
		echo $output;
		exit;
	}
        
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php tp('Facility Summary Report');?></title>
		<?php
		require_once('views/helpers/Location.php');
		require_once('views/helpers/ScriptContainer.php');
		print ScriptContainer::$instance->renderCSSHead();
		print ScriptContainer::$instance->renderJSHead();

		?>
 


    <style>
.numeric {
    text-align: right;
}
</style>


<script src="../bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css" />
<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css" />

		<script type="text/javascript" charset="utf-8">
                   
			$(document).ready(function() {
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
                              // $('#message').hide();  
                               
                                      
                                 dialogs = $( "#dialog-certification-message" ).dialog({
                                  autoOpen: false,
                                  modal: true,
                                  draggable: false,
                                  resizable: false,
                                 
                                      }); 

			} );
		</script>
        
	</head>
    <style type="text/css">
        #content {
    
  
    margin: 0 auto;
}
.ui-state-default, .ui-widget-content .ui-state-default, .ui-widget-header .ui-state-default {
    color: #FFF;
    background: #71AE70 none repeat-x scroll 50% 50%;
    font-weight: normal;
}
        .col-md-11 {

    margin-left: 60px !important;
}
select, input[type="text"] {
    color: black !important;
}
        h4,h3,h2, .row{
            font-size: 13px !important;
            text-align:left;
        }
        
#pageHolder{
    min-width:0px !important;
}
#facility_id{
    min-width:75% !important;
}
h2{
    height:5px !important;
}
div#dialog-certification-message {
    min-height: 50px !important;
}
#dialog-certification-message{
    display:none;
   }
        </style>
        
         <script>
           
        
	
        
	
  </script>
    <input type="hidden" name="tableheading" id="thidden" />
        <script>
 function submitForm(){
     
     document.getElementById("facilitysummaryForm").submit();
     return true;
 }
 
 
  function errorAlert(error){
     document.getElementById("data").innerHTML = "<div id='statusBox' style='color:red;'><p align='center'>"+error+"</p></div>";
                  dialogCert = $( "#dialog-certification-message" ).dialog({
                      autoOpen: false,
                                  modal: true,
                                  draggable: false,
                                  resizable: false,
                                 
                                  buttons: [
                                    {
                                      text: "Close",
                                      icons: {
                                        primary: "ui-icon-close"
                                      },
                                      click: function() {
                                        $( this ).dialog( "close" );
                                      }
                                    }
                                        ]
                  });
                  
                 
                  $('#dialog-certification-message').dialog('open');
 }
 
$(function() {


$('#submitFacilitySummary').click(function() {
    
        $.ajax({
            type: "POST",
            url: "<?php echo $this->base_url;?>/reports/summaryresult",
            data: $("#facilitysummaryForm").serialize(),
            beforeSend: function() {
//                $(".ui-dialog").show();
//                document.getElementById("dialog-certification-message").style.display = "block";
//               
//                
//                 $('.ui-dialog-titlebar').hide();
//               dialogCert = $( "#dialog-certification-message" ).dialog();
//               $('#dialog-certification-message').dialog('open');
startLoading();
               },
            success: function(data) {
             //alert("successful");
             var responseData =   jQuery.parseJSON(data);
            
           //alert(responseData);
             var error = responseData.error;
            // alert(responseData.error);
             if(error!=""){
                 errorAlert(error);
//                 document.getElementById("message").innerHTML = "<div id='statusBox' style='color:red;'><p align='center'>* "+error+"</p></div>";
//                 $('#message').show().fadeIn('slow');    
         }else{
            // document.getElementById("data").innerHTML = "Populating...";
             //var table1 = "resultTable1";
             //var table2 = "resultTable2";
             //var table3 = "resultTable3";
             //var headingTable1 = "";
            // alert("Hello this is the work 1");
             var heading = $.map(responseData.heading, function(el) { return el });
             // alert("Hello this is the work 2");
             var headers = $.map(responseData.headers, function(el) { return el });
             // alert("Hello this is the work 3");
           //  alert(data.outdetails)
             var outdetailsArray = jQuery.parseJSON(responseData.outdetails);
             // alert("Hello this is the work 4");
             var summaryArray = jQuery.parseJSON(responseData.summary_details);
            //  alert("Hello this is the work 5");
             var summary = jQuery.parseJSON(responseData.summary);
             // alert("Hello this is the work 6");
             var outputdetailsArray = jQuery.parseJSON(responseData.output);
             // alert("Hello this is the work 7");
             var outputsdetailsArray = jQuery.parseJSON(responseData.outputs);
             // alert("Hello this is the work 8");
             var detailsFacilityArray = jQuery.parseJSON(responseData.details_facility);
             
             var clientHeaders = $.map(responseData.clientHeaders, function(el) { return el });
             var clientData =  jQuery.parseJSON(responseData.clientData);
             // alert("Hello this is the work 9");
             heading = heading.toString();
             headers = headers.toString();
             var headingArray = heading.split(",");
             var headersArray = headers.split(",");
               //alert(headingArray);
               
             var responseTable1  = '<h2><b>HR Summary: Total number of health workers trained </b></h2>';
                 responseTable1 += '<table cellpadding="0" cellspacing="0" border="0" class="display tablegrids" id="" style="width:100%">\n\n\
                                    <thead>\n<tr>\n';

    jQuery.each( headingArray, function( key, value ) {
       responseTable1 += '<th>'+value+'</th>';
});
    responseTable1 += '\n</tr>\n</thead>\n<tbody>\n';
     jQuery.each( outdetailsArray, function( key, value ) {
      
      var individualResponseTable1Data = value.toString();
      var individualResponseTable1DataArray = individualResponseTable1Data.split(",");
      responseTable1  += '<tr>\n';
      jQuery.each( individualResponseTable1DataArray, function( key, result ) {
          result = result.replace("@", ",");
          responseTable1  += '<td>'+result+'</td>\n';
      })
      responseTable1  += '</tr>';
});
    responseTable1 += '</tbody>\n</table>\n';
		responseTable1 +='\n\n';
                
                jQuery.each( summaryArray, function( key, value ) {
             
              
              responseTable1 +='<h2><b>'+summary[key]+': '+value+'</b></h2>';
          });
               
               
               //Sencond table-----------------------------------------------------------------------------------------
                var responseTable2  = '<br><h2><b>Commodity Summary: Monthly consumption by method for last 12 months</b></h2>';
                 responseTable2 += '<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid2" id="" style="width:100%">\n\n\
                                    <thead>\n<tr>\n';

    jQuery.each( headersArray, function( key, value ) {
        if(key>0){
        var startString = value.substring(0,3);
          var endString = value.substring(3);
          value = startString+', '+endString;
      }
       responseTable2 += '<th>'+value+'</th>';
});
    responseTable2 += '\n</tr>\n</thead>\n<tbody>\n';
     jQuery.each( outputdetailsArray, function( key, value ) {
      
      var individualResponseTable2Data = value.toString();
      var individualResponseTable2DataArray = individualResponseTable2Data.split(",");
      responseTable2  += '<tr>\n';
      jQuery.each( individualResponseTable2DataArray, function( key, result ) {
                   responseTable2  += '<td>'+result+'</td>\n';
      })
      responseTable2  += '</tr>';
});
    responseTable2 += '</tbody>\n</table>\n';
    
     //Sencond table-----------------------------------------------------------------------------------------
                var responseTable3  = '<br><h2><b>Clients</b></h2>';
                 responseTable3 += '<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid3" id="" style="width:100%">\n\n\
                                    <thead>\n<tr>\n';

    jQuery.each( clientHeaders, function( key, value ) {
        if(key>0){
        var startString = value.substring(0,3);
          var endString = value.substring(3);
          value = startString+', '+endString;
      }
       responseTable3 += '<th>'+value+'</th>';
});
    responseTable3 += '\n</tr>\n</thead>\n<tbody>\n';
     jQuery.each( clientData, function( key, value ) {
      
      var individualResponseTable3Data = value.toString();
      var individualResponseTable3DataArray = individualResponseTable3Data.split(",");
      responseTable3  += '<tr>\n';
      jQuery.each( individualResponseTable3DataArray, function( key, result ) {
                   responseTable3  += '<td>'+result+'</td>\n';
      })
      responseTable3  += '</tr>';
});
    responseTable3 += '</tbody>\n</table>\n';
    
    
     
     
     //--------------------------------------------------------------thirdtable-------------------------------
       var responseTable4  = '<br><h2><b>Stock Out Summary: Stock outs over last 12 months</b></h2>';
                 responseTable4 += '<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid4" id="" style="width:100%">\n\n\
                                    <thead>\n<tr>\n';

    jQuery.each( headersArray, function( key, value ) {
         if(key>0){
        var startString = value.substring(0,3);
          var endString = value.substring(3);
          value = startString+', '+endString;
      }
       responseTable4 += '<th>'+value+'</th>';
});
    responseTable4 += '\n</tr>\n</thead>\n<tbody>\n';
     jQuery.each( outputsdetailsArray, function( key, value ) {
      
      var individualResponseTable4Data = value.toString();
      var individualResponseTable4DataArray = individualResponseTable4Data.split(",");
      responseTable4  += '<tr>\n';
      jQuery.each( individualResponseTable4DataArray, function( key, result ) {
                 responseTable4  += '<td>'+result+'</td>\n';
      })
      responseTable4  += '</tr>';
});
    responseTable4 += '</tbody>\n</table>\n';
         document.getElementById("resultTable1").innerHTML = "";
         document.getElementById("resultTable1").innerHTML =responseTable1;
         document.getElementById("resultTable2").innerHTML = "";
         document.getElementById("resultTable2").innerHTML =responseTable2;
         document.getElementById("resultTable3").innerHTML = "";
         document.getElementById("resultTable3").innerHTML =responseTable3;
         document.getElementById("resultTable4").innerHTML = "";
         document.getElementById("resultTable4").innerHTML =responseTable4;
         document.getElementById("downloadLink").innerHTML = '<input type="hidden" name="csv" value="1" /><span style="float:right !important;"><button type="submit" class="btn-link"  id="submitfinally" name="download" onClick="return submitForm();">Download</button></span><br/>';      
         document.getElementById("csvdownload").innerHTML = '<input type="hidden" name="csv" value="1" />'; 
         document.getElementById("facilityDetails").innerHTML = "Facility Summary of "+detailsFacilityArray['facility_name'];      
        oTable = $('.tablegrids').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
        oTable = $('.tablegrid2').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
        oTable = $('.tablegrid3').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
                                
        oTable = $('.tablegrid4').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
                                
                               // alert(responseTable1)
            
            
               
             
//             document.getElementById("message").innerHTML = "";
//                 $('#message').hide().fadeOut('slow'); 
         }
//          dialogCert = $( "#dialog-certification-message" ).dialog();
//               $('#dialog-certification-message').dialog('close');
//             $('.ui-dialog-titlebar').show();
//              document.getElementById("data").innerHTML = "Fetching data...";
            stopLoading();
            },
            error: function(jqXHR, textStatus, errorThrown){
              console.log(" The following error occured: "+ textStatus, errorThrown );
              alert(" The following error occured: "+ textStatus+" "+ errorThrown);
//              dialogCert = $( "#dialog-certification-message" ).dialog();
//               $('#dialog-certification-message').dialog('close');
//             $('.ui-dialog-titlebar').show();
//              document.getElementById("data").innerHTML = "Fetching data...";
            stopLoading();
            }

        })
    })
});

</script>
    
   
        <div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
              
            
			<div id="content">
                            
	<body class="yui-skin-sam" >
            <div id="dialog-certification-message" title="" >
 
           <p style="text-align:center;v-align:middle;padding:10px !important" id="data">Fetching data...</p>
          </div>
		
				<div id="subcontent">
                                    <div class="row">
                                        
                                    <div class="row">
                                    <div class="col-md-11">
					<div id="contentheader">
						<h2><?php tp('Facility Summary Query');?></h2><br>
                                                    <div id="facilityDetails">
                                                   <?php if(!empty($this->criteria['details_facility']['facility_name']) && isset($this->criteria['details_facility']['facility_name'])){
                                                   ?><h3><?php tp('Facility Summary of '.$this->criteria['details_facility']['facility_name'].'');?></h3>
                                                   <?php }?>
                                                    </div>
                                                   <br/>
					</div>
                                    
                                    </div>
                                     <div class="col-md-11">
                                         <div id="certMessage">
    
                                         </div>
                                     <?php 
                                                    // print_r($this->criteria['error']);
                                     if(isset($_POST['go'])){
                                                     foreach($this->criteria['error'] as $error){
                                                         echo '<h3 align="center" style="color:red;"><b>* '.$error.'</b></h3>';
                                                     }
                                     }
                                     
                                                     ?>
                                         <div id="message" style="width:100% !important;padding-top:10px;"></div>
                                     </div>
                                        
                                    </div>
                                    <div class="row">
                                        <div class="col-md-11" style="border:1px solid black;">
                                            <div class="row">
					<form  action="" method="post" id="facilitysummaryForm" >
						
					<input type="hidden" name="process" id="process" value="1">
					

							<div class="col-md-2">

							<p align="center"><span class="required">*</span> Zone</p>
							
							<p align="center"><?php renderFilter($this->locations, 1, 'province_id', $this->criteria['province_id'], 'district_id', false,false,"10"); ?></p>
                                                        </div>
							<div class="col-md-2">
	
							<p align="center"><span class="required">*</span> State</p>
							
							<p align="center"><?php renderFilter($this->locations, 2, 'district_id', $this->criteria['district_id'], 'region_c_id', false,false,"10"); ?></p>
                                                        </div>
							<div class="col-md-2">
	
							<p align="center"><span class="required">*</span> LGA</p>
							
							<p align="center"><?php renderFilter($this->locations, 3, 'region_c_id', $this->criteria['region_c_id'],'facility_id', false, false,"10"); ?></p>
                                                        </div>
                                            <div id="csvdownload"></div>
							

							<!-- TA:17: 09/04/2014 START-->
<div class="col-md-6">
                                                        <p align="center"><span class="required">*</span> Facility</p>
							<p align="center">
<?php renderFilter($this->locations, 4, 'facility_id', $this->criteria['facility_id'],'', false, false,'10'); ?></p>
</div>
                                                        </div>
                                        </div></div>
                                    <div class="row">

							<div class="col-md-11">
							<div class="mainformholder" style="height:35px !important;width:100%;">
							
                                                        
                                                           
                                                            <div  style="width:50px !important;margin: 0 auto;">
								<input type="submit" name="go" id="submitFacilitySummary" value="<?php tp('Preview');?>" class="submitNoArrow" onclick="return false;" />
							</div>
                                                            </div>
                                                            <div style="width:100% !important;float:right !important;">
                                                             <div id="downloadLink" style="float:right;">
                                                                <?php 
if (count ($this->outputs) > 0){
    $_POST['csv'] = 1;
$url = $_SERVER['REQUEST_URI'] . "&csv=1";
    ?>
    <input type="hidden" name="csv" value="1" />
    <span style="float:right !important;">
        <button type="submit" class="btn-link"  name="download" id="submitfinally" onClick="return submitForm();" ><?php tp('Download');?></button></span><br/>
 <?php   
}
?>
                                                            </div>
                                                        </div>
                                                        </div>
						</div>
						
<br/>

<div class="row">
    
<div class="col-md-11" id="resultTable1">
   
                                        <?php
 //print_r($this->tocktack);

if (isset($this->outdetails)) {
	if (count ($this->outdetails) == 0){
           echo ' 
                                    <h2><b>HR Summary: Total number of health workers trained</b></h2>';
            
		echo "				<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"display tablegrid\" id=\"\" style=\"width:100%\">\n";
		echo "					<thead>\n";
		echo "						<tr>\n";
		echo "							<th>".t('Output')."</th>\n";
		echo "						</tr>\n";
		echo "					</thead>\n";
		echo "					<tbody>\n";
		echo "						<tr>\n";
		echo "							<td>".t("Your search criteria returned no results")."</td>\n";
		echo "						</tr>\n";
		echo "					</tbody>\n";
		echo "				</table>\n";
	} else {
?>
<br>
                                    <h2><b>HR Summary: Total number of health workers trained</b></h2>
				
                                    <table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
					<thead>
						<tr>
<?php
		foreach ($this->heading as $key=>$value){
			echo "							<th>" . $value . "</th>\n";
		}
?>
						</tr>
					</thead>
					<tbody>
<?php
		foreach ($this->outdetails as $row){
			echo "						<tr style=\"cursor : pointer;\" class=\"GradeA\">\n";
			foreach ($row as $key=>$value){
				echo "				   			<td>" . $value . "</td>\n";
			}
			echo "						</tr>\n";
		}
?>
					</tbody>
				</table>
                                    <?php 
                                    $size = sizeof($this->summary_details);
                                    for($r=0;$r<$size;$r++){
                                        $title = $this->summary[$r];
                                        $value = $this->summary_details[$r];
                                     echo  '<h2><b>Health Workers trained in '.$title.': '.$value.'</b></h2>';  
                                    }
                                    ?>
                              <br/><br/>     
                                    
                                    
				
<?php
	}
}
?>
                                        
</div>                   
                                        
                                        
            <div class="col-md-11" id="resultTable2">                       
<?php
 //print_r($this->tocktack);

if (isset($this->output)) {
	if (count ($this->output) == 0){
           echo '  <br/><h2><b>Commodity Summary: Monthly consumption by method for last 12 months</b></h2>';
		echo "				<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"display tablegrid\" id=\"\" style=\"width:100%\">\n";
		echo "					<thead>\n";
		echo "						<tr>\n";
		echo "							<th>".t('Output')."</th>\n";
		echo "						</tr>\n";
		echo "					</thead>\n";
		echo "					<tbody>\n";
		echo "						<tr>\n";
		echo "							<td>".t("Your search criteria returned no results")."</td>\n";
		echo "						</tr>\n";
		echo "					</tbody>\n";
		echo "				</table>\n";
	} else {
?>

				<br>
                                    <h2><b>Commodity Summary: Monthly consumption by method for last 12 months</b></h2>
                                    <table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
					<thead>
						<tr>
<?php
		foreach ($this->headers as $key=>$value){
			echo "							<th>" . $value . "</th>\n";
		}
?>
						</tr>
					</thead>
					<tbody>
<?php
		foreach ($this->output as $row){
			echo "						<tr style=\"cursor : pointer;\" class=\"GradeA\">\n";
			foreach ($row as $key=>$value){
				echo "				   			<td>" . $value . "</td>\n";
			}
			echo "						</tr>\n";
		}
?>
					</tbody>
				</table>
				
<?php
	}
}
?>
                                    
                                    
                                    </div>
    
      <div class="col-md-11" id="resultTable3">                       
<?php
 //print_r($this->tocktack);

if (isset($this->clientData)) {
	if (count ($this->clientData) == 0){
           echo '  <br/><h2><b>Clients</b></h2>';
		echo "				<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"display tablegrid\" id=\"\" style=\"width:100%\">\n";
		echo "					<thead>\n";
		echo "						<tr>\n";
		echo "							<th>".t('Output')."</th>\n";
		echo "						</tr>\n";
		echo "					</thead>\n";
		echo "					<tbody>\n";
		echo "						<tr>\n";
		echo "							<td>".t("Your search criteria returned no results")."</td>\n";
		echo "						</tr>\n";
		echo "					</tbody>\n";
		echo "				</table>\n";
	} else {
?>

				<br>
                                    <h2><b>Clients</b></h2>
                                    <table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
					<thead>
						<tr>
<?php
		foreach ($this->clientHeaders as $key=>$value){
			echo "							<th>" . $value . "</th>\n";
		}
?>
						</tr>
					</thead>
					<tbody>
<?php
		foreach ($this->clientData as $row){
			echo "						<tr style=\"cursor : pointer;\" class=\"GradeA\">\n";
			foreach ($row as $key=>$value){
				echo "				   			<td>" . $value . "</td>\n";
			}
			echo "						</tr>\n";
		}
?>
					</tbody>
				</table>
				
<?php
	}
}
?>
                                    
                                    
                                    </div>
                                   
                                    <div class="col-md-11" id="resultTable4">
                                        
                                        <?php
 //print_r($this->tocktack);

if (isset($this->outputs)) {
	if (count ($this->outputs) == 0){
            echo 
            '<br/>
            <h2><b>Stock Out Summary: Stock outs over last 12 months</b></h2>';
		echo "				<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"display tablegrid\" id=\"\" style=\"width:100%\">\n";
		echo "					<thead>\n";
		echo "						<tr>\n";
		echo "							<th>".t('Output')."</th>\n";
		echo "						</tr>\n";
		echo "					</thead>\n";
		echo "					<tbody>\n";
		echo "						<tr>\n";
		echo "							<td>".t("Your search criteria returned no results")."</td>\n";
		echo "						</tr>\n";
		echo "					</tbody>\n";
		echo "				</table>\n";
	} else {
?>

				<br>
                                    <h2><b>Stock Out Summary: Stock outs over last 12 months</b></h2>
                                    <table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
					<thead>
						<tr>
<?php
		foreach ($this->headers as $key=>$value){
			echo "							<th>" . $value . "</th>\n";
		}
?>
						</tr>
					</thead>
					<tbody>
<?php
		foreach ($this->outputs as $row){
			echo "						<tr style=\"cursor : pointer;\" class=\"GradeA\">\n";
			foreach ($row as $key=>$value){
				echo "				   			<td>" . $value . "</td>\n";
			}
			echo "						</tr>\n";
		}
?>
					</tbody>
				
 <?php   
	}
}
?>
                                        
                                        </form>
                                    </div>
                                    </div>
					
				</div>
                                            </div>
				
			</div>  
        		
				
			<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
			</div>
		
	</body>
</html>






