<?php
//echo $_POST['download'];exit;
	if (isset ($_POST['csv'])&& $_POST['csv']=="1"){

		$data = array();
		
		$_row = array();
		foreach ($this->headers as $key=>$value){
			$_row[] = $value;
		}
		$data[] = $_row;
		
		foreach ($this->output as $row){
			$_row = array();
			foreach ($row as $key=>$value){
				$_row[] = $value;
			}
			$data[] = $_row;
		}
		


		$delimiter = ',';
		$enclosure = '"';
		$encloseAll = false;
		$nullToMysqlNull = false;
	
		$delimiter_esc = preg_quote($delimiter, '/');
		$enclosure_esc = preg_quote($enclosure, '/');
	
		$output = array();
if($this->criteria['aggregate_method'] == "view_part_names" || $this->criteria['aggregate_method'] == "view_aggregate_part"){
                                    $output[] = "Total Participants: ".$this->criteria['total_participants']."";
                                }  else if($this->criteria['aggregate_method'] == "view_aggregate_train" || $this->criteria['aggregate_method'] == "view_individual_train") {
                                    $output[] = "Total Trainings: ".$this->criteria['total_training']."";
                                } 
		foreach ($data as $row){
			$outputrow = array();
			foreach ($row as $field){
				if ($field === null && $nullToMysqlNull) {
					$outputrow[] = 'NULL';
					continue;
				}
		
				// Enclose fields containing $delimiter, $enclosure or whitespace
				if ( $encloseAll || preg_match( "/(?:${delimiter_esc}|${enclosure_esc}|\s)/", $field ) ) {
					$outputrow[] = $enclosure . str_replace($enclosure, $enclosure . $enclosure, $field) . $enclosure;
				}
				else {
					$outputrow[] = $field;
				}
			}
                        //$output[] = "Total Participants: ".$this->criteria['total_participants']."";
                      
                              
			$output[] = implode($delimiter,$outputrow);
		}
		$output = implode("\n", $output);

		header("Content-type: text/csv");
		header("Content-Disposition: attachment; filename=training-data-" . date("d.m.Y.H.m.s") . ".csv");
		header("Pragma: no-cache");
		header("Expires: 0");
		echo $output;
		exit;
	}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php tp('Training Reports');?></title>
		<link href="../js/datepicker/jquery.datepick.css" rel="stylesheet"/>
                <?php
		require_once('views/helpers/Location.php');
		require_once('views/helpers/ScriptContainer.php');
		print ScriptContainer::$instance->renderCSSHead();
		print ScriptContainer::$instance->renderJSHead();

		?>
     



<script src="../js/datepicker/jquery.plugin.js"></script>
<script src="../js/datepicker/jquery.datepick.js"></script>

<script src="../bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css" />
<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css" />

<?php 
if( $this->criteria['aggregate_method']=="view_part_names"){
    ?>
    <script type="text/javascript" charset="utf-8">
                    
			$(document).ready(function() {
                      
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers",
                                         "order": [[ 0, "asc" ]],
                                         "aaSorting": [[0, 'asc']]
				});
                                
                               dialogs = $( "#dialog-certification-message" ).dialog({
                                  autoOpen: false,
                                  modal: true,
                                  draggable: false,
                                  resizable: false,
                                 
                                      });
                                
			} );
                        
                       
		</script>
<?php 
}else{
    

?>
		<script type="text/javascript" charset="utf-8">
                    
			$(document).ready(function() {
                      
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers",
                                         "order": [[ 0, "desc" ]],
                                         "aaSorting": [[0, 'desc']]
				});
                                
                               dialogs = $( "#dialog-certification-message" ).dialog({
                                  autoOpen: false,
                                  modal: true,
                                  draggable: false,
                                  resizable: false,
                                 
                                      });
                                
                                $("#region_c_id").on('change', function (event) {
                     check_buttons();
                 });
                 $("#province_id").on('change', function (event) {
                     check_buttons();
                 });
                
                $("#district_id").on('change', function (event) {
                    check_buttons();
                });
                
                $("#aggreg_region_c_id").on('change', function (event) {
                     check_buttons();
                 });
                 $("#aggreg_province_id").on('change', function (event) {
                     check_buttons();
                 });
                
                $("#aggreg_district_id").on('change', function (event) {
                    check_buttons();
                });
               
			} );
                        
                       
		</script>
<?php } ?>
<script>
 $(function() {
	$('#trainingEndDateStart').datepick({
             dateFormat: "dd/mm/yyyy"
        });
        $('#trainingEndDateEnd').datepick({
             dateFormat: "dd/mm/yyyy"
        });
        
        $('#dobStart').datepick({
             dateFormat: "dd/mm/yyyy"
        });
        $('#dobEnd').datepick({
             dateFormat: "dd/mm/yyyy"
        });
	
});


</script>
	</head>
    <style type="text/css">
        h4,h3, .row{
            font-size: 13px !important;
        }
        .datepicker{
            width:45% !important;
        }
        .col-md-11 {

    margin-left: 60px !important;
}
.ui-state-default, .ui-widget-content .ui-state-default, .ui-widget-header .ui-state-default {
    color: #FFF;
    background: #71AE70 none repeat-x scroll 50% 50%;
    font-weight: normal;
}


#pageHolder{
    min-width:0px !important;
}

        #trainingtype{
            max-width:190px !important;
        }
        #facility_id, #aggreg_facility_id{
            max-width:200px !important;
            min-width:200px !important;
        }
        
        .mclass{
    min-height:100px;
   
    
}
select, input[type="text"] {
    color: black !important;
}

.datepick select{
    color:white !important;
} 
.datepick-ctrl a{
    text-decoration:none !important;
    color:#fff;
}
div#dialog-certification-message {
    min-height: 50px !important;
}
#dialog-certification-message{
    display:none;
   }
        </style>
        <script type="text/javascript">
            function check_verify(id){
                
                var val = document.getElementById(id).value;
               changeLocationBars(val);
                //alert('This is the value '+val);
                if(val=="view_individual_train" || val=="view_aggregate_train"){
                    document.getElementById("province_id").disabled=false;
                    document.getElementById("district_id").disabled=false;
                    document.getElementById("region_c_id").disabled=true;
                    document.getElementById("facility_id").disabled = true;
                    
                    document.getElementById("aggreg_province_id").disabled=false;
                    document.getElementById("aggreg_district_id").disabled=false;
                    document.getElementById("aggreg_region_c_id").disabled=true;
                    document.getElementById("aggreg_facility_id").disabled = true;
                    
                    document.getElementById("cadre").disabled = true;
                    document.getElementById("gender").disabled = true;
                    document.getElementById("certification").disabled = true;
                    document.getElementById("dob-start-day").disabled = true;
                    document.getElementById("dob-start-month").disabled = true;
                    document.getElementById("dob-start-year").disabled = true;
                    document.getElementById("dob-end-day").disabled = true;
                    document.getElementById("dob-end-month").disabled = true;
                    document.getElementById("dob-end-year").disabled = true;
                }else{
                    replaceGeoGraphy(id);
                    document.getElementById("province_id").disabled=false;
                    document.getElementById("district_id").disabled=false;
                    document.getElementById("region_c_id").disabled=false;
                    document.getElementById("facility_id").disabled = false;
                    
                    document.getElementById("aggreg_province_id").disabled=false;
                    document.getElementById("aggreg_district_id").disabled=false;
                    document.getElementById("aggreg_region_c_id").disabled=false;
                    document.getElementById("aggreg_facility_id").disabled = false;
                    
                    document.getElementById("cadre").disabled = false;
                    document.getElementById("gender").disabled = false;
                    document.getElementById("certification").disabled = false;
                    document.getElementById("dob-start-day").disabled = false;
                    document.getElementById("dob-start-month").disabled = false;
                    document.getElementById("dob-start-year").disabled = false;
                    document.getElementById("dob-end-day").disabled = false;
                    document.getElementById("dob-end-month").disabled = false;
                    document.getElementById("dob-end-year").disabled = false;
                }
                
            }
            function check_buttons(){
               var val =   forms.aggregate_method.value;
               changeLocationBars(val);
                if(val=="view_individual_train" || val=="view_aggregate_train"){
       
       
                    document.getElementById("province_id").disabled=false;
                    document.getElementById("district_id").disabled=false;
                    document.getElementById("region_c_id").disabled=true;
                    document.getElementById("facility_id").disabled = true;
                    
                    document.getElementById("aggreg_province_id").disabled=false;
                    document.getElementById("aggreg_district_id").disabled=false;
                    document.getElementById("aggreg_region_c_id").disabled=true;
                    document.getElementById("aggreg_facility_id").disabled = true;
                    
                    
                    document.getElementById("cadre").disabled = true;
                    document.getElementById("gender").disabled = true;
                    document.getElementById("certification").disabled = true;
                    document.getElementById("dob-start-day").disabled = true;
                    document.getElementById("dob-start-month").disabled = true;
                    document.getElementById("dob-start-year").disabled = true;
                    document.getElementById("dob-end-day").disabled = true;
                    document.getElementById("dob-end-month").disabled = true;
                    document.getElementById("dob-end-year").disabled = true;
                    
       
                }else{
                    //alert(val);
                    
                        
                    document.getElementById("province_id").disabled=false;
                    document.getElementById("district_id").disabled=false;
                    document.getElementById("region_c_id").disabled=false;
                    document.getElementById("facility_id").disabled = false;
                    
                    document.getElementById("aggreg_province_id").disabled=false;
                    document.getElementById("aggreg_district_id").disabled=false;
                    document.getElementById("aggreg_region_c_id").disabled=false;
                    document.getElementById("aggreg_facility_id").disabled = false;
                    
                    document.getElementById("cadre").disabled = false;
                    document.getElementById("gender").disabled = false;
                    document.getElementById("certification").disabled = false;
                    document.getElementById("dob-start-day").disabled = false;
                    document.getElementById("dob-start-month").disabled = false;
                    document.getElementById("dob-start-year").disabled = false;
                    document.getElementById("dob-end-day").disabled = false;
                    document.getElementById("dob-end-month").disabled = false;
                    document.getElementById("dob-end-year").disabled = false;
                }
            }
            function changeLocationBars(val){
                if(val=="view_part_names"){
       document.getElementById("geoSelectionMenu").style.display = 'block';
       document.getElementById("geoSelectionMenu").style.visibile = 'show';
       
       document.getElementById("geoSelectionMenuAggregate").style.display = 'none';
       document.getElementById("geoSelectionMenuAggregate").style.visibile = 'hidden';
       
      }else{
       document.getElementById("geoSelectionMenu").style.display = 'none';
       document.getElementById("geoSelectionMenu").style.visibile = 'hidden';
       
       document.getElementById("geoSelectionMenuAggregate").style.display = 'block';
       document.getElementById("geoSelectionMenuAggregate").style.visibile = 'show';
 }
            }
            </script>
           <style type="text/css">

        .grey {
            background-color: grey !important;
        }
        .grey td.sorting_1 {
            background-color: inherit !important;
        }
   

/* HTML5 Boilerplate accessible hidden styles */
[type="radio"] {
  border: 0; 
  clip: rect(0 0 0 0); 
  height: 1px; margin: -1px; 
  overflow: hidden; 
  padding: 0; 
  position: absolute; 
  width: 1px;
}

/* One radio button per line */
label {
  
  cursor: pointer;
  line-height: 2.5;
  font-size: 0.99em;
}

[type="radio"] + span {
  /*display: block;*/
}

/* the basic, unchecked style */
[type="radio"] + span:before {
  content: '';
  display: inline-block;
  width: 0.9em;
  height: 0.9em;
  vertical-align: -0.25em;
  border-radius: 1em;
  border: 0.125em solid #fff;
  box-shadow: 0 0 0 0.15em #000;
  margin-right: 0.75em;
  transition: 0.5s ease all;
}

/* the checked style using the :checked pseudo class */
[type="radio"]:checked + span:before {
  background: green;
  box-shadow: 0 0 0 0.45em #000;
}

/* never forget focus styling */
[type="radio"]:focus + span:after {
  
}
#geoSelectionMenuAggregate{
    display:none;
    visibility:none;
}

#content{
   
    margin: 0 auto;
}

         </style>
    <script>
 function submitForm(){
     
     document.getElementById("trainingDataForm").submit();
     return true;
 }    
 
 String.prototype.replaceAll = function(target, replacement) {
  return this.split(target).join(replacement);
};
 
   function errorAlert(error){
     document.getElementById("data").innerHTML = "<div id='statusBox' style='color:red;'><p align='center'>"+error+"</p></div>";
                  dialogCert = $( "#dialog-certification-message" ).dialog({
                      autoOpen: false,
                                  modal: true,
                                  draggable: false,
                                  resizable: false,
                                 
                                  buttons: [
                                    {
                                      text: "Close",
                                      icons: {
                                        primary: "ui-icon-close"
                                      },
                                      click: function() {
                                        $( this ).dialog( "close" );
                                      }
                                    }
                                        ]
                  });
                  
                 
                  $('#dialog-certification-message').dialog('open');
 }
 
 
 
 $(function() {
$('#submitTrainingData').click(function() {
    $.ajax({
            type: "POST",
            url: "<?php echo $this->base_url;?>/reports/trainingresult",
            data: $("#trainingDataForm").serialize(),
            beforeSend: function() {
             //alert("before");
//             $(".ui-dialog").show();
//               document.getElementById("dialog-certification-message").style.display = "block";
//               
//              
//                 
//             $('.ui-dialog-titlebar').hide();
//               dialogCert = $( "#dialog-certification-message" ).dialog();
//               $('#dialog-certification-message').dialog('open');
                    startLoading();
               },
            success: function(data) {
             //alert("successful");
//          stopLoading();
//        alert(data);
          
             var responseData =   jQuery.parseJSON(data);
             var locationName = responseData['locationName'];
             
          // alert(responseData);
             
            // document.getElementById("data").innerHTML = "Populating...";
             var  headers = $.map(responseData.headers, function(el) { return el });
             
             
          
      
             var aggregate_method = responseData['aggregate_method'];
             var totalTraining = responseData['total_training'];
             var alertMessage = responseData['alert'];
             
             var locationTotal = responseData['locationNumber'];
             
             var totalParticipants = responseData['total_participants'];
             //var perLocations = perLocation['perLocation'];
             //var agreggate_participants = perLocation['agreggate_participants'];
             //alert(locationName);
            //lert(agreggate_participants);
             var dataMessage = "";
             var checkActiveStatus = false;

           if(aggregate_method=="view_aggregate_part" || aggregate_method=="view_part_names")
           {
                if(aggregate_method=="view_part_names"){
                    if(locationName=="all geography"){
                        dataMessage = "<h3 align='left'><b><i>Total Participants :  "+totalParticipants+"</i></b></h3><h4 align='left'><i>"+alertMessage+"</i></h4>";
                    }else{
                        dataMessage = "<h3 align='left'><b><i>Total Participants :  "+locationTotal+"</i></b></h3><h4 align='left'><i>"+alertMessage+"</i></h4>";
                    }
                }else{
                    dataMessage = "<h3 align='left'><b><i>Total Participants :  "+totalParticipants+"</i></b></h3>";
                }
                checkActiveStatus = true;
             }
             
else{
               dataMessage = "<h3 align='left'><b><i>Total Trainings :  "+totalTraining+"</i></b></h3>";
             }
             
             
             headers = headers.toString();
             var headersArray = headers.split(",");
             var outputArray = jQuery.parseJSON(responseData.output);
         
          var responseTable  = dataMessage;
              responseTable += '<table cellpadding="0" cellspacing="0" border="0" class="display tablegrids" id="" style="width:100%">\n\n\
                                    <thead>\n<tr>\n';

    jQuery.each( headersArray, function( key, value ) {
       responseTable += '<th>'+value+'</th>';
});
    responseTable += '\n</tr>\n</thead>\n<tbody>\n';
   var classCSS = "";
     jQuery.each( outputArray, function( key, value ) {
      
      var individualResponseTableData = value.toString();
     
      var individualResponseTableDataArray = individualResponseTableData.split(","); 
      if(checkActiveStatus){
      var lengthStatus = individualResponseTableDataArray.length;
      var tempPlacHolder = individualResponseTableDataArray[lengthStatus-1];
      var activateStatus = tempPlacHolder.toString();
      console.log("THis is the active status "+activateStatus.length+" the length "+lengthStatus+" another one "+activateStatus[14]+" dfdfdf"+activateStatus.toString());
      if(activateStatus.toString() != "Active Provider" && activateStatus.toString()  !="" ){
          classCSS = "grey";
      }else{
        classCSS = "";
      }
        }

      responseTable  += '<tr class="'+classCSS+'">\n';
      jQuery.each( individualResponseTableDataArray, function( key, result ) {
          result = result.replaceAll("@", ",");
          responseTable  += '<td>'+result+'</td>\n';
      })
      responseTable  += '</tr>';
});

    responseTable += '</tbody>\n</table>\n';
    document.getElementById("resultTable").innerHTML = "";
    document.getElementById("resultTable").innerHTML = responseTable;
    document.getElementById("downloadLink").innerHTML = '<input type="hidden" name="csv" value="1" /><span style="float:right !important;"><button type="submit" class="btn-link"  id="submitfinally" name="download" onClick="return submitForm();">Download</button></span><br/>';      
    document.getElementById("csvdownload").innerHTML = '<input type="hidden" name="csv" value="1" />'; 
    document.getElementById("csvid").value = 1;
                oTable = $('.tablegrids').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
               
//                 dialogCert = $( "#dialog-certification-message" ).dialog();
//               $('#dialog-certification-message').dialog('close');
//             $('.ui-dialog-titlebar').show();
//             document.getElementById("data").innerHTML = "Fetching data...";
stopLoading();
     
   },
            error: function(jqXHR, textStatus, errorThrown){
              console.log(" The following error occured: "+ textStatus, errorThrown );
              alert(" The following error occured: "+ textStatus+" "+ errorThrown);
//               dialogCert = $( "#dialog-certification-message" ).dialog();
//               $('#dialog-certification-message').dialog('close');
//             $('.ui-dialog-titlebar').show();
//             document.getElementById("data").innerHTML = "Fetching data...";
stopLoading();
            }

        })
    
      
});
 });
</script>
         <div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
                
                        <div id="content">
	<body class="yui-skin-sam" onload="check_buttons()" >
		<div id="dialog-certification-message" title="" >
 
           <p style="text-align:center;v-align:middle;padding:10px !important" id="data">Fetching data...</p>
          </div>
                        <div clas="row">
				<div id="subcontent">
                                    <div class="row">
					<div id="contentheader">
						<h2><?php tp('Training Reports');?></h2><br>
					</div>
                                    </div>
					
                                        <div class="row">
                                         <?php 
                                                    // print_r($this->criteria['error']);
                                                     foreach($this->criteria['error'] as $error){
                                                         echo '<h3 align="center" style="color:red;"><b>* '.$error.'</b></h3>';
                                                     }
                                                     ?>
					<form  action="" method="post" name="forms" id="trainingDataForm" >
						
					<input type="hidden" name="process" id="process" value="1">
					

</div>
                                        <div class="row">	
                                                <div  class="col-md-11 ">
                                                 
                                                    <?php
                                                    if(!isset($this->criteria['aggregate_method']) || $this->criteria['aggregate_method']==""){
                                                        $this->criteria['aggregate_method'] = "view_part_names";
                                                    }
                                                     ////echo 'This is the thing you dnt do in school '.$this->criteria['aggregate_method']; ?>
                                                    <label for="view_part_names"><input type="radio" name="aggregate_method" onClick="check_verify('view_part_names');" value="view_part_names" id="view_part_names" <?php if($this->criteria['aggregate_method']=="view_part_names"){ echo "checked='checked'";} ?>/>  <span>View Participant Names&nbsp;</span></label>  &nbsp;&nbsp;&nbsp;
                                                    <label for="view_aggregate_part"> <input type="radio" name="aggregate_method" onclick="check_verify('view_aggregate_part');" id="view_aggregate_part" value="view_aggregate_part" <?php if($this->criteria['aggregate_method']=="view_aggregate_part"){ echo "checked='checked'";} ?>/><span> View Aggregate Participants</span></label>&nbsp; &nbsp;&nbsp;  
                                                    <label for="view_aggregate_train"> <input type="radio" name="aggregate_method" onclick="check_verify('view_aggregate_train')" value="view_aggregate_train"  id="view_aggregate_train" <?php if($this->criteria['aggregate_method']=="view_aggregate_train"){ echo "checked='checked'";} ?>/><span> View Aggregate Trainings&nbsp;</span></label>      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                    <label for="view_individual_train"> <input type="radio" name="aggregate_method" onclick="check_verify('view_individual_train')" value="view_individual_train" id="view_individual_train" <?php if($this->criteria['aggregate_method']=="view_individual_train"){ echo "checked='checked'";} ?>/><span> View Individual Trainings </span>&nbsp;</label>     
                                                
                                                 
                                                </div>
                                                       </div> 
                                        <div class="row">
                                            <div  class="col-md-11" style="border:1px solid black; border-bottom: 0px !important;margin:0 auto;padding-bottom:3px;padding-left:10px; ">
                                                <div class="row">
                                                    <div id="geoSelectionMenu">
<div class="col-md-2" >
							<p align="center">Zone</p>
							
						<p align="center">	<?php renderFilter($this->locationsPerGeo, 1, 'province_id', $this->criteria['province_id'], 'district_id', true,false,'10'); ?></p>
</div>
							<div class="col-md-2" >
	
							<p align="center">State</p>
							
							<p align="center"><?php renderFilter($this->locationsPerGeo, 2, 'district_id', $this->criteria['district_id'], 'region_c_id', true,false,'10'); ?></p>
                                                        </div>
							<div class="col-md-3" >
	
							<p align="center">LGA</p>
							
							<p align="center"><?php renderFilter($this->locationsPerGeo, 3, 'region_c_id', $this->criteria['region_c_id'],'facility_id', true, false,'10'); ?></p>
							
                                                        </div>

							<!-- TA:17: 09/04/2014 START-->
<?php ?><div class="col-md-5" >
                                                        <p align="center">Facility</p>
							<p align="center">
<?php renderFilter($this->locationsPerGeo, 4, 'facility_id', $this->criteria['facility_id'],'', true, false,'10'); ?></p>
</div></div>
                                                    
                                                    <div id="geoSelectionMenuAggregate">
<div class="col-md-2" >
							<p align="center">Zone</p>
							
							<p align="center"><?php renderFilter($this->locations, 1, 'aggreg_province_id', $this->criteria['province_id'], 'aggreg_district_id', true,false,'10'); ?></p>
</div>
							<div class="col-md-2" >
	
							<p align="center">State</p>
							
							<p align="center"><?php renderFilter($this->locations, 2, 'aggreg_district_id', $this->criteria['district_id'], 'aggreg_region_c_id', true,false,'10'); ?></p>
                                                        </div>
							<div class="col-md-3" >
	
							<p align="center">LGA</p>
							
							<p align="center"><?php renderFilter($this->locations, 3, 'aggreg_region_c_id', $this->criteria['region_c_id'],'aggreg_facility_id', true, false,'10'); ?></p>
							
                                                        </div>

							<!-- TA:17: 09/04/2014 START-->
<?php ?><div class="col-md-5" >
                                                        <p align="center">Facility</p>
							<p align="center">
<?php renderFilter($this->locations, 4, 'aggreg_facility_id', $this->criteria['facility_id'],'', true, false,'10'); ?></p>
</div></div>
							
                                       
                                            </div>
                                        </div>
                                        
                                       
                                        
                                            <div class="col-md-11" style="border:1px solid black;margin:0 auto;padding-bottom: 3px;">
                                                <div class="row" style="padding-top: 9px !important">	
                                                    <div class="col-md-3" >
							<p align="center"><?php echo t('Training Type'); ?></p>
							
							<p align="center"><select name="training_type[]" id="trainingtype" multiple size="10" >
<?php
echo "<option value=''  >--choose--</option>";
	foreach ($this->trainingtypes as $item){
            if(isset($this->criteria['training_type']) && is_array($this->criteria['training_type']) && in_array($item['id'],$this->criteria['training_type'])){
                $selected = "selected='selected'";
            }else{
                $selected = "";
            }
		echo "<option value=\"" . $item['id'] . "\" ".$selected." title='".$item['training_title_phrase']."'>" . $item['training_title_phrase'] . "</option>\n";
	}
?>
							</select></p></div>
							<div class="col-md-4" >

							<p align="center"><?php echo 'Training Organizer'; ?></p>
							
							<p align="center">
                               <select name="trainingorganizer[]" id="trainingorganizer"  multiple size="10" style="width:100%;">
	<?php
         echo "<option value='' >--choose--</option>";
		foreach ($this->trainingorganizer as $item){
                   if(isset($this->criteria['trainingorganizer']) && is_array($this->criteria['trainingorganizer']) && in_array($item['id'],$this->criteria['trainingorganizer'])){
                $selected = "selected='selected'";
            }else{
                $selected = "";
            }
			echo "<option value=\"" . $item['id'] . "\" ".$selected." title='".$item['training_organizer_phrase']."'>" . $item['training_organizer_phrase'] . "</option>\n";
		}
	?>
							</select></p></div>
                                                        
                                                        <div class="col-md-2" >
							<p align="center"><?php echo t('Professional Qualification'); ?></p>
							
							<p align="center"><select name="cadre[]" style="width:95%;" id="cadre" multiple/>
	<?php
       
        echo "<option value=''  ".$disbaled.">--choose--</option>";
		foreach ($this->qualifications as $item){
                    if($item['id']== $this->criteria['cadre']){
                        $selected = "selected='selected'";
                    }else{
                        $selected = "";
                    }
			echo "<option value=\"" . $item['id'] . "\" ".$selected." title='".$item['qualification_phrase']."'>" . $item['qualification_phrase'] . "</option>\n";
		}
	?>
							</select></p>
                                                         <p align="center">Gender</p>
							
							   <p align="center"><select name="gender" style="max-height:25px;" id="gender"> 
                                                                <option value="" >--choose--</option>
                                                                <option value="male" <?php if($this->criteria['gender']=="male") echo 'selected="selected"';?>>Male</option>
                                                                <option value="female" <?php if($this->criteria['gender']=="female") echo 'selected="selected"';?>>Female</option>
                                                            </select>    
                                                           </p>  
                                                     
                                                       <input type="hidden" name="csv" value="0"  id="csvid"/>
                                                        </div>
                                                        <div class="col-md-3" >
                                                            <div id="csvdownload"></div>
                                                            <div class="row">
                                                            <div class="col-md-1">
                                                               <div id="infobutton" class="infobutton" style="">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                   Active Provider status indicates that the health worker is currently actively providing clinical services in a health facility. These health workers are counted towards the total health workforce need for family planning Nigeria.<br/><br/>

All other designations including Retired Provider, National Official, State Official, LGA Official or Deceased status indicates that the health worker is not actively providing clinical services in a health facility. These health workers are not counted towards the total health workforce need although they may serve other important functions such as supervision and training of trainers.

                                                                                </div>
                                                    </div>
                                                            </div>
                                                             <div class="col-md-9">
                                                            <p align="center">


                                                              Active Provider Status</p>
                                                            <p align="center"> <select name="person_status_id[]" id="person_status_id" multiple  size="10">
                                                <?php 
                                                if(empty($this->criteria['person_status_id'])){
                                                    $this->criteria['person_status_id'][] = 1;
                                                }
                                                echo "<option value=''  >--choose--</option>";
                                            //print_r($this->person_status);
                                          
                                            foreach($this->person_status as $pstatus){
                                                $titleShow = $pstatus['title'];
                                                $id = $pstatus['id'];
                                                //$id = ($id==0 || $id=="")?1:$id;
                                                $selected = (in_array($id, $this->criteria['person_status_id']))? 'selected' : '';
                                              // $selected = (!empty($this->criteria['person_status_id']) && $this->criteria['person_status_id'] == $id)? 'selected':'';
                                               ?>
                                              <option value="<?php echo $id; ?>" <?php echo $selected; ?>><?php echo $titleShow; ?></option> 
  
  
                                            <?php
                                            }
                                            ?>
                                                                </select></p>
                                                        
	                                                          
                                                                                
                                                              </div>
                                                              </div>                  
                                                                                     
														   
                                                        </div>
													

                                                        </div>
                                                <div class="row">
                                                    <div class="col-md-4 col-md-push-1" >
							
	<p align="center"><?php echo t('Trained End Date Range'); ?></p>
							<p align="center"><input type="text" id="trainingEndDateStart"  value="<?php echo $this->criteria['trainingEndDateStart']; ?>" name="trainingEndDateStart" style="width:30% !important"/>
							
                                                             
                                                            &nbsp;&nbsp; to &nbsp;&nbsp;     
                                                         <input type="text" id="trainingEndDateEnd"  value="<?php echo $this->criteria['trainingEndDateEnd'];  ?>" name="trainingEndDateEnd"  style="width:30% !important"/></p>                  
                                                                                
                                                                                
                                                                                     
															
                                                      
                                                       

						</div>
                                                    <div class="col-md-2">
                                                          <p align="center">Certification</p>
							
							<p align="center"><select name="certification" style="max-height:25px; " id="certification"> 
                                                                <option value="" >--choose</option>
                                                                <option value="Y" <?php if($this->criteria['certification']=="Yes") echo 'selected="selected"';?>>Yes</option>
                                                                <option value="N" <?php if($this->criteria['certification']=="No") echo 'selected="selected"';?>>No</option>
                                                            </select>    </p>    
                                                    </div>
                                                    
                                                    <div class="col-md-4">
                                                         <p align="center"><?php echo t('Date of Birth'); ?></p>

							
                                                           <p align="center"><input type="text" id="dobStart"  value="<?php echo $this->criteria['dobStart']; ?>" name="dobStart" style="width:30% !important" placeholder="mm/dd/yyyy"/>
							 &nbsp;&nbsp;to &nbsp;&nbsp;    
                                                           <input type="text" id="dobEnd"  value="<?php echo $this->criteria['dobEnd'];  ?>" name="dobEnd"  style="width:30% !important" placeholder="mm/dd/yyyy"/></p>                  
                                                                        
                                                                        
                                                    </div>
                                                   
                                                </div>
                                                            
                                            </div>
                                        </div>
                                            </div>
						
						<div class="row" style="height : 50px;">
                                                    <div class="col-md-11">
							<div  style="float : right;" >
								<input type="submit" name="go" id="submitTrainingData" value="<?php tp('Preview');?>" class="submitNoArrow" onclick="return false;"/>
							</div>
                                                    </div>
                                                     
						</div>
						
					
                                       <div class="row">  
    <div class="col-md-11">
 <div id="downloadLink" style="float:right;">
                                                               <?php 
                                                               //echo count($this->outputs);exit;
if (count ($this->output) > 0){
    $_POST['csv'] = 1;
$url = $_SERVER['REQUEST_URI'] . "&csv=1";
    ?>
    <input type="hidden" name="csv" value="1" />
    <span style="float:right !important;">
        <button type="submit" class="btn-link"  name="download" id="submitfinally" onClick="return submitForm();" ><?php tp('Download');?></button></span><br/>
 <?php   
}
?>
                                                            </div>

<div id="resultTable">
<?php
if (isset($this->output)) {
	if (count ($this->output) == 0){
            
           
                                    
		echo "				<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"display tablegrid\" id=\"\" style=\"width:100%\">\n";
		echo "					<thead>\n";
		echo "						<tr>\n";
		echo "							<th>".t('Output')."</th>\n";
		echo "						</tr>\n";
		echo "					</thead>\n";
		echo "					<tbody>\n";
              
		echo "						<tr>\n";
		echo "							<td>".t("Your search criteria returned no results")."</td>\n";
		echo "						</tr>\n";
                
		echo "					</tbody>\n";
		echo "				</table>\n";
	} else {
?>

				<br>
                                    <?php if(isset($this->criteria['total_participants'])){
                                        
                                                 if(!$this->perLocation['agreggate_participants']){
                                            if($this->perLocation['locationName']=="all geography"){
                                                 echo "<h3 align='left'><b><i>Total Participants :  ".$this->criteria['total_participants']."</i></b></h3>";
                                    echo "<h4 align='left'><i>".$this->alert."</i></h4>";
                                            } else {
                                     echo "<h3 align='left'><b><i>Total Participants :  ".$this->perLocation['perLocation']."</i></b></h3>";
                                    echo "<h4 align='left'><i>".$this->alert."</i></h4>";
                                    
                                                 }
                                    
                                }
                                else{
                                  echo "<h3 align='left'><b><i>Total Participants :  ".$this->criteria['total_participants']."</i></b></h3>";
                                                   
                                }
                                } else if(isset($this->criteria['total_training'])) {
                                    echo "<h3 align='left'><b><i>Total Trainings:  ".$this->criteria['total_training']."</i></b></h3>";
                                } 
                                ?>
                                <table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
					<thead>
						<tr>
<?php
		foreach ($this->headers as $key=>$value){
			echo "							<th>" . $value . "</th>\n";
		}
?>
						</tr>
					</thead>
					<tbody>
<?php
		foreach ($this->output as $row){
			echo "						<tr style=\"cursor : pointer;\" class=\"GradeA\">\n";
			foreach ($row as $key=>$value){
				echo "				   			<td>" . $value . "</td>\n";
			}
			echo "						</tr>\n";
		}
?>
					</tbody>
				</table>
                                    <br/>
                                    <?php
$url = $_SERVER['REQUEST_URI'] . "&csv=1";
    ?>
    <span style="float:right !important;"><button type="submit" class="btn-link"  name="download"><?php tp('Download');?></button></span>
<?php
	}
        ?>
</div>
    <?php
}
?>
		</form>			
				
                                        </div>
                                        </div>
			</div>   
                </div>
                        <div class="clear" style="height : 100px;"></div>
			
               		
	
			<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

			</div>
		
	</body>
  <script src="../js/tp/functions.js"></script>
    <script type="text/javascript">
   function replaceGeoGraphy(aggregateValue){
      
      if(aggregateValue=="view_part_names"){
       document.getElementById("geoSelectionMenu").style.display = 'block';
       document.getElementById("geoSelectionMenu").style.visibile = 'show';
       
       document.getElementById("geoSelectionMenuAggregate").style.display = 'none';
       document.getElementById("geoSelectionMenuAggregate").style.visibile = 'hidden';
       //alert("heelo");
      }else{
       document.getElementById("geoSelectionMenuAggregate").style.display = 'block';
       document.getElementById("geoSelectionMenuAggregate").style.visibile = 'show';
       
       document.getElementById("geoSelectionMenu").style.display = 'none';
       document.getElementById("geoSelectionMenu").style.visibile = 'hidden';
       //alert("hello");
       
 }
}
   
    </script>
</html>






