<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0 transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}
    
 
.hometabs.ui-widget-header {
    background: #eeeeee !important;
    font-size: 12px;
    border-top: solid 2px; 
}
    
.small-tab{
    background-color:white;
    font-size:12px;
    padding:2px;
}
    
   

body {font-family: "Lato", sans-serif;}


    
    

</style>

 <?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
    
<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">



<!--<link rel="stylesheet" type="text/css" href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />-->
<link rel="stylesheet" href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400" type="text/css"></link>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />


<link rel="stylesheet" href="<?php echo $this->base_url; ?>bootstrap/css/bootstrap.min.css"></link>
<!--<link rel="stylesheet" href="../bootstrap/css/bootstrap-theme.min.css"></link>-->
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"></link>

<link rel="stylesheet" href="<?php echo $this->base_url; ?>css/cssfile.css"></link>

<!--<script src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>-->

<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>-->
<!--<script id="jqueryui" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" ></script>-->

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script src="<?php echo $this->base_url; ?>bootstrap/js/bootstrap.min.js"></script>

                



<script>
  $(function() {
    //$( "#accordion" ).accordion({header: "h3", collapsible: true, active: false, animated:200, animated:"slide"});
    $( "#tabs").tabs();
    
    //set high charts global color scheme for all high charts instances on this page
    Highcharts.setOptions({
            colors: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099', '#0099C6', '#DD4477', '#AAAA11', '#B77322']
        });
  });
  
  $(document).ready(function(){
       $( "#tabs" ).tabs({
        activate: function( event, ui ) {
            var selectedTab = $("#tabs").tabs('option', 'active');
            if(selectedTab == 1){
                //redrawChart(chart11Options, chart11Data, chart11Div); 
                $("#chart11_div").highcharts().reflow();
            }
        }
      });
//      
//      $('.infobutton').click(function(){
//        console.log("inside click");
//      });
  });
  
//  function redrawChart(chartOptions, chartData, chartDiv) {      
//    var chart = new google.visualization.ColumnChart(document.getElementById(chartDiv));
//     chart.draw(chartData, chartOptions);
//  }
  
  </script>

           

</head>
    
<body class="yui-skin-sam" style="background-color:#EEEEEE;overflow-x:hidden;" >
    <?php
        
        //var_dump(array_keys($this->national_consumption_by_method)); exit;
    ?>
	<div id="pageHolder" style="margin:0px;background-color:#EEEEEE;">

		<div id="header"><?php require_once('views/scripts/headerhome.phtml');?></div>
		<div id="content" style="padding:0px;background-color:white;">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  //require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>
			
			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->

			<!--<body class="docs slim framebox_body">-->
                            
                            
    <?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>      
                        
                               <div class="row" style=" margin-top:30px;">
                                         
                                           <div class=" col-sm-5 pull-right"  >
	
			         	                      <?php
                                                              
                                                              $variable = 'Multiple'; 
                                                              
                                                              require_once('views/scripts/dashboard/top_buttons.phtml');
                                                              
                                                             
                                                            
                                                              ?>
                                               
                                           </div>
				
                                           <div  class="col-sm-7 pull-right  clearfix"  style="height:510px;"  >
                                               
                                               

                                               <div class="row">
                                                   <div  class="col-sm-2">&nbsp;</div>
                                                   
                                                   <div  class="col-sm-10 pull-right box-shadow clearfix"  style="height:510px;"  >
                                                        <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                             
                                                            </div>
                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                <div id="infobutton" class="infobutton">
                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                            <div id="" class="infodiv" >
                                                                ...
                                                            </div>
                                                        </div>
                                                            </div>

                                                          </div>   
                                               
                                                            <div id="chart11_div" style="width:100%; height: 470px;"></div>
                                                   </div>
                                               </div>
				           </div>                           
                                </div>
                        
                               <div  class="row" style="margin-top:70px;margin-left:100px;">
                                         
                                           <div class="col-sm-7 box-shadow" style="height:510px;"  >
                                               
                                               <div class="title-bar border-hr col-xs-12 " style="padding:0px;" >
                                                                            <div class="col-xs-11 text-left small-tab title-bar-font" >
                                                                            </div>
                                                                            <div  class="col-xs-1 title-bar-info-btn " style="min-height:20px;" >
                                                                               <div id="infobutton" class="infobutton ">
                                                                            <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                            <div id="" class="infodiv" >
                                                                                ...
                                                                            </div>
                                                                        </div>
                                                                             
                                                                          </div>   
                                                   
                                                   </div>
	
			         	       <div id="chart12_div" style="width:100%; height: 470px;"></div>
				
                                               
                                           </div>
                                    </div>
                        
                        <br><br>
                                    
				
				</div>
		
	</div>

		<div class="clear"></div>
		<div class="hrGrey"></div>
		<div class="clear"></div>
		
		<!--<script type="text/javascript" src="https://www.google.com/jsapi"></script>-->

		<!-------   /////////////////////////// main  ////////////////////// -->

		<script type="text/javascript">
		
//  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
//  google.load('visualization', '1.1', {'packages':['bar']});
//  google.setOnLoadCallback(apiLoaded);
      
$(function() {
  
//	document.getElementById("allCharts").style.marginLeft="130px";

        drawChartPercentFRR('allfacs');
        drawChartPercentFRR('fpfacs');
		
	//currentLevel = <?php //echo '\'' . $this->location_data[0]['name'] . '\''; ?>;

  });
    
    
    function drawChartPercentFRR(mode){
        var percentFRRData = <?= $this->frr_data; ?>;
        console.log(percentFRRData);

          //declare the array in which to store data
          var dataArray = new Array();
          var percentFRRDataModed = percentFRRData[mode];
          console.log(percentFRRDataModed);
          
          var selectedDatemultiple = <?php echo json_encode($this->selectedDatemultiple); ?>;
         var startDate = '<?= $this->start_date; ?>';
        
            monthNamesWithYears = processMonthNamesWithYears(selectedDatemultiple, startDate);
            dateLength = selectedDatemultiple.length;
          
          //get month names for x axis: keys of the moded array
          var monthNames = [];
          for(month in percentFRRDataModed)
              monthNames.push(month);
              
          //get the location names: keys for month. Locations for each month are same
          var firstMonth = percentFRRDataModed[monthNames[0]];
          var locationNames = [];
          for(loc in firstMonth)
              locationNames.push(loc);
          
          locationNames.sort();
          for(loc in locationNames){
              loopLocation = locationNames[loc];
              obj = {name: loopLocation, data: []};
              
              for(month in monthNames){
                  loopMonth = monthNames[month];
                  obj.data.push(percentFRRDataModed[loopMonth][loopLocation]['percent']);
              }
              
                if(loopLocation == 'National'){
                    obj.marker = {enabled: true};
                    obj.color = '#000000';
                    obj.dashStyle = 'dot';
                }
              
                dataArray.push(obj);
          }
          
             console.log(dataArray);
             
             if(dateLength > 0){
                dateText = dateLength === 1 ? 
                        monthNamesWithYears[0] : 
                        "across selected dates";
            }
            <?php if($this->freshVisit) { ?>
                var titleText = "Facilities Reporting Rates Percentages, <br/>" + dateText;
            <?php } else { ?>
                var titleText = "Facilities Reporting Rates Percentages <br/>in selected geographies, " + dateText;
            <?php } ?>

            var container = mode == 'allfacs' ? 'chart11_div' : 'chart12_div';
                 
         $('#'+container).highcharts({
             chart: {
                 type: dateLength == 1 ? 'column' : 'line',
                 height: 470,
                 //spacingLeft: -20,
                 events: {
                     load:function(){
                         $("text:contains(Highcharts.com)").css("display","none");
                         $("#chart11_div").siblings("#infobutton").removeClass("hidden");
                     }
                 }
             },
             title: {
                 text: titleText,
                 style: {
                     fontWeight: 'bold',
                     fontFamily: 'Arial',
                     fontSize: '16px'
                 },
                 x: -20 //center
             },
             xAxis: {
                 title:{
                         text:'Months',
                         style:{ "fontWeight": "bold" }
                     },
                 categories: monthNamesWithYears
             },
             yAxis: {
                 title: {
                     text: 'Percent Facilities',
                     style:{ "fontWeight": "bold" }
                 },
                 labels: {
                     format: '{value}%'
                 },
                 //max:100,
                 plotLines: [{
                     value: 0,
                     width: 1,
                     color: '#808080'
                 }]
             },
             tooltip: {
                 formatter: function () {
                     var monthArray = this.x.split(" ");
                     var month = monthArray[0];
                     
                     return '<b>' + this.x + '</b><br/>' +
                         '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
                         '<b>Numerator</b>:' + thousandSeparator(percentFRRDataModed[month][this.series.name]['numer'])+'<br/>' +
                         '<b>Denominator</b>:'+thousandSeparator(percentFRRDataModed[month][this.series.name]['denom']);
                 
//                     return '<b>' + this.x + '</b><br/>' +
//                         '<b>' + this.series.name + '</b>: ' + this.y + '%<br/>' +
//                         '<b>Numerator</b>:' + thousandSeparator(percentFRRDataModed[this.x][this.series.name]['numer'])+'<br/>' +
//                         '<b>Denominator</b>:'+thousandSeparator(percentFRRDataModed[this.x][this.series.name]['denom']);
                 }
             },
             plotOptions: {
                 series: {
                     marker: {
                         enabled: true
                     }
                 },
                 column: dateLength === 1  
                         ? {    
                            dataLabels: {
                                  enabled: true,
                                  format: '{y}%'
                              }
                          }
                          : {}
             },
             legend: {
                 layout: 'horizontal',
                 //verticalAlign: 'center',
                 align: 'center',
                 borderWidth: 1
                 //shadow: true
             },
             series: dataArray
         });

  }


</script>

<script src="../js/highcharts/highcharts.js"></script>
<script src="../js/highcharts/modules/exporting.js"></script>

<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
<script src="../js/tp/overtime-ops.js"></script>

</body>

</html>