<div class="bs-example">
    <div class="panel-group p-group" id="accordion">
        <div class="panel panel-default p p-default">
            <div class="panel-heading p-heading">
                
                <h4 class="panel-title p-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Coverage</a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse <?php echo (isset($activationBar) && $activationBar =='coverage')?'in':'';?>">
                <div class="panel-body p-body">
                 <div>
      <ul>
          <li id='trained_hws' >
              <a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/coverage/cummhwtrained'; ?>" 
         id="cummhwtrained"
         class="<?php echo $fileID == 'cummhwtrained' || $fileID == 'cummhwtraineddemo' ? 'active': ''?>">
          Trained HWs
      </a>
          </li>
          
          <li id='fptrained_hws'>
      <a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/coverage/percentfacswithtrainedhw'; ?>"
         id="percentfacswithtrainedhw"
         class="<?php echo $fileID == 'percentfacswithtrainedhw' ? 'active': ''?>">
          Facilities with Trained HWs
      </a></li>
      <li id='fp'>
      <a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/coverage/percentfacsproviding'; ?>"
         id="percentfacsproviding"
         class="<?php echo $fileID == 'percentfacsproviding' ? 'active': ''?>">
          Facilities Providing FP
      </a>
      </li>
      <li id='fp_OverTime'>
      <a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/coverage/providingovertime'; ?>"
         id="providingovertime"
         class="<?php echo $fileID == 'providingovertime' || $fileID == 'providingovertimedemo' ? 'active': ''?>">
          Facilities Providing FP Over Time
      </a>
      </li>
      <li id='fptrained_hws_pfp'>
      <a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/coverage/facswithhwproviding'; ?>"
         id="facswithhwproviding"
         class="<?php echo $fileID == 'facswithhwproviding' ? 'active': ''?>">
          Facilities with Trained HWs Providing FP
      </a>
      </li>
      <li id='fptrained_hws_pfp_overtime'>
      
      <a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/coverage/coverageovertime'; ?>"
         id="coverageovertime"
         class="<?php echo $fileID == 'coverageovertime' ? 'active': ''?>">
          Facilities with Trained HWs Providing FP Over Time
      </a>
      </li>
      </ul>
  </div>    
                </div>
            </div>
        </div>
        <div class="panel panel-default p p-default">
            <div class="panel-heading p-heading">
                <h4 class="panel-title p-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Consumption</a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse <?php echo (isset($activationBar) && $activationBar =='consumption')?'in':'';?>">
                <div class="panel-body p-body">
                     <div>
      <ul>
          <li id='fptrained_hws_pfp_overtime'>
              <a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/consumption/consumption'; ?>"
         id="consumption"
         class="<?php echo $fileID == 'consumption' || $fileID == 'consumptiondemo' ? 'active': ''?>">
              Commodity Consumption
      </a>
          </li>
            <li><a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/consumption/newandcurrentfpusers'; ?>"
               id="newandcurrentfpusers"
               class="<?php echo $fileID == 'newandcurrentfpusers' ? 'active': ''?>">
                    New FP Acceptors and Current FP Users
            </a></li>
      </ul>
  </div>
  
                </div>
            </div>
        </div>
        <div class="panel panel-default p p-default">
            <div class="panel-heading p-heading">
                <h4 class="panel-title p-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">Stock Outs</a>
                </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse <?php echo (isset($activationBar) && $activationBar =='stockout')?'in':'';?>"">
                <div class="panel-body p-body">
                    <div>
      <ul>
          <li><a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/stockout/percentstockoutwithtrainedhw'; ?>"
         id="percentstockoutwithtrainedhw"
         class="<?php echo $fileID == 'percentstockoutwithtrainedhw' ? 'active': ''?>">
          Stock Outs at Facilities with Trained HWs
      </a></li>
      
      <li> <a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/stockout/percentfacsprovidingbutstockedout'; ?>"
         id="percentfacsprovidingbutstockedout"
         class="<?php echo $fileID == 'percentfacsprovidingbutstockedout' ? 'active': ''?>">
          Stock Outs at Facilities Providing FP
      </a></li>
      
      <li><a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/stockout/stockouts'; ?>"
         id="stockouts"
         class="<?php echo $fileID == 'stockouts' ? 'active': ''?>">
          Stock Outs at Facilities Providing FP Over Time
      </a></li>
      </ul>
  </div>
  
                </div>
            </div>
        </div>
    </div>
</div>

                               
                                        
<style> 
    .active{
        background: #eeeeee; text-decoration: none;
    }
    .p-title h4:active{
        text-decoration:none !important;
    }
    #accordion{width:100% !important;}

    .p-title h4{
        width:100% !important;
    }
    
    .p-title h4 a{
        width:100% !important;
    }
    
    .p-title h4:hover{
        cursor:pointer !important;
    }
    
    .p-title a {
        text-decoration: none;
    }
    .p-title a:hover {
        text-decoration: none;
    }
    .p .p-default,.p-heading{
        /*padding: 5px 10px !important;*/
        background: #008C00 !important;
        color:#fff !important;
         /*font: 16px/1.231 arial,helvetica,clean,sans-serif !important;*/
        
    }
    .p{
        /*margin-bottom:-4px !important;*/
    }
    .p-body ul{
        margin:0 !important;
         font-size: 13px !important;
           font: 13px/1.231 arial,helvetica,clean,sans-serif !important;
    }
    .p-body ul li{
          font:  arial,helvetica,clean,sans-serif !important;
       border-bottom: 1px dotted white;
        
    }
    .p-body ul li a{
         color:black !important;
         text-align: left;
        
    }
    .p-body ul li a:hover{
         color:#fff !important;
        
    }
    .p-body a{
        display: block; 
        padding-bottom:5px;
        padding:1px 5px 1px 10px !important;
        text-decoration: none;
        padding-bottom: 5px !important;
        padding-top:5px !important;
        
        /*border-bottom: 1px solid #222222;*/
    }
    .p-body a:hover{
        color:#fff !important;  background: #2AA92A; text-decoration: none;
        
    }
    .p-title .ui-accordion-header .ui-helper-reset .ui-state-default .ui-corner-all .ui-accordion-icons{display: none !important;}
    
    .p-title .ui-accordion-header .ui-helper-reset .ui-state-default .ui-corner-all .ui-accordion-icons :hover{display: none !important;}
    .p-body {
        padding: 1em 0 !important; 
        border: 0 !important; 
        height: 100% !important;
        background:#fed636;
    }
    .ui-widget-content a:hover{
        color:#fff;  background: #2AA92A; text-decoration: none;
        
    }
    .ui-accordion-header-icon{display: none;}
    .ui-accordion-content {
        padding: 1em 0 !important; 
        border: 0 !important; 
        height: 100% !important;
        background:#fed636;
    }
    .p-title .ui-accordion-header .ui-helper-reset .ui-state-default .ui-corner-all .ui-accordion-icons{display: none;}
    
</style>


<?php


?>