<?php

$fullname = $this->title . ' '. $this->first_name . ' ' . $this->last_name;

echo 
'Dear '. trim($fullname) .',
Your request to register as a user for the Family Planning Dashboard has been received and is currently in 
process. You will receive further notification by email when processing is completed. 

For further assistance with the Family Planning Dashboard '. Settings::$COUNTRY_BASE_URL .', 
please contact: support@fpdashboard.ng.


Sincerely,
Director of Family Health Division, FMOH
';


?>