<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<style>

#homecontent {

	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;

	position: relative;

}



#homecontent-mid {

	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;

	min-height: 100%;

	outline: medium none;

	top: -40px;

}



#homebanner {

	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0

		transparent;

	padding-right: 20px;

	position: relative;

}



.rounded {

	border-radius: 10px 10px 10px 10px;

}





.sliderdiv {

	background: none repeat scroll 0 0 FFFFFF;

	float: left;

}



.main-search {

	background: none repeat scroll 0 0 #FFFFFF;

	float: left;

	overflow: hidden;

}



.nav-buttons {

	background: none repeat scroll 0 0 #FFFFFF;

	float: left;

	overflow: hidden;

}





</style>



<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"

	rel="stylesheet" type="text/css">



<?php

require_once('views/helpers/ScriptContainer.php');

print ScriptContainer::$instance->renderCSSHead();

print ScriptContainer::$instance->renderJSHead();

?>





      <link rel="stylesheet" type="text/css"

	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />

<link rel="stylesheet"

	href="//www.google.com/cse/style/look/default.css" type="text/css" />

<link rel="stylesheet"

	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"

	type="text/css">

<script

	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>



<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>

<script id="jqueryui"	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"

	defer async></script>

<script

	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>

<!--[if lt IE 9]>

    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>

    <![endif]-->

<script

	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>





<script type="text/javascript" src="http://canvg.googlecode.com/svn/trunk/rgbcolor.js"></script> 

<script type="text/javascript" src="http://canvg.googlecode.com/svn/trunk/canvg.js"></script>

    



<script>

    

        var textChecker = '';

    

        $(document).ready(function(){           

            textChecker = setInterval(function(){ 

                console.log('timer fired');

                var elArray = document.forms["pdfForm"].getElementsByTagName('input');

                

                var found = false;

                for(var i=0; i<elArray.length; i++){

                    var el = elArray[i];

                    if(el.type == 'text'  && el.value == ''){

                        console.log(elArray[i]);

                        found = true;

                        

                    }

                }

                

                if(found == false){

                    //alert("It is still loading here");

                    console.log('clearing');

                    clear();

                    //call ajax handler

                   

                  sendChartsData();

                      //alert("We are here");

                }

            },1000);

        });

        

        function clear(){

            clearInterval(textChecker);

        }

    

        function sendChartsData(){

            

            var url = './createpdfLga';

            

            

            var state_name = document.getElementById('state_name').value;

            

           // var lga_name  = document.getElementbyId('lga_name').value;

          

            var report_hidden = document.getElementById('report_id').value;

            

            var facilitysum_hidden = document.getElementById("facilitysum_hidden").value;

            var chart13_hidden = document.getElementById("chart13_hidden").value;

            var folder_name = document.getElementById("folder_name").value; 

            var lga_name_hidden = document.getElementById("lga_name_hidden").value;

            var facilities_list_fp_prov_hidden = document.getElementById("facilities_list_fp_prov_hidden").value;

            var facilities_list_larc_prov_hidden = document.getElementById('facilities_list_larc_prov_hidden').value;

            var percent_facilities_list_fp_prov_hidden = document.getElementById('percent_facilities_list_fp_prov_hidden').value;

            var percent_facilities_larc_prov = document.getElementById('percent_facilities_larctrained').value;

            var facilities_stocked_out_fp_seven_days_hidden = document.getElementById('facilities_stocked_out_fp_seven_days_hidden').value;

            var percent_lga_stock_out_fp_seven_days_hidden = document.getElementById('percent_lga_stock_out_fp_seven_days_hidden').value;

            var percent_lga_stock_out_larc_hidden = document.getElementById('percent_lga_stock_out_larc_hidden').value;

            var facilities_stocked_out_larc_hidden = document.getElementById("facilities_stocked_out_larc_hidden").value;
            
            var report_rate = document.getElementById("report_rate").value;
           

           //alert(lga_name+report_hidden+facilitysum_hidden+chart13_hidden+folder_name);

            //alert('hello who is here');

            $.ajax({

                type: 'POST',

                url: url,

                data: {generate:true,state_name:state_name,report_hidden:report_hidden,facilitysum_hidden:facilitysum_hidden,chart13_hidden:chart13_hidden,

                folder_name:folder_name,lga_name_hidden:lga_name_hidden,report_rate:report_rate,facilities_list_fp_prov_hidden:facilities_list_fp_prov_hidden,percent_facilities_list_fp_prov_hidden:percent_facilities_list_fp_prov_hidden,

            percent_facilities_larc_prov:percent_facilities_larc_prov,facilities_list_larc_prov_hidden:facilities_list_larc_prov_hidden,

            facilities_stocked_out_fp_seven_days_hidden:facilities_stocked_out_fp_seven_days_hidden,percent_lga_stock_out_fp_seven_days_hidden:percent_lga_stock_out_fp_seven_days_hidden,

            percent_lga_stock_out_larc_hidden:percent_lga_stock_out_larc_hidden,facilities_stocked_out_larc_hidden:facilities_stocked_out_larc_hidden

        },

                success: function(response){

                    //reload the page

                   //alert(response);

                    console.log('ajax success: ' + response);

                },

                error: function(e){

                    

                },

                complete: function(response, status){

                    console.log('ajax complete');

                  location.reload(); 

                }

                

            });

             

        }

        

        

      function getImgData(chartContainer) {

        //var chartArea = chartContainer.getElementsByTagName('iframe')[0].

          //contentDocument.getElementById('chartArea');

          

        var chartArea =

           chartContainer.getElementsByTagName('svg')[0].parentNode;

        var svg = chartArea.innerHTML;        

        var doc = chartContainer.ownerDocument;

        var canvas = doc.createElement('canvas');

        canvas.setAttribute('width', chartArea.offsetWidth);

        canvas.setAttribute('height', chartArea.offsetHeight);

                

        canvas.setAttribute(

            'style',

            'position: absolute; ' +

            'top: ' + (-chartArea.offsetHeight * 2) + 'px;' +

            'left: ' + (-chartArea.offsetWidth * 2) + 'px;');

        doc.body.appendChild(canvas);

        canvg(canvas, svg);

        var imgData = canvas.toDataURL("image/png");

        canvas.parentNode.removeChild(canvas);

        return imgData;

      }

      

      function tableChartReadyHandler(){

          setImgData("table_hidden", document.getElementById('table_div'));

      }

      function saveAsImg(chartContainer) {

        var imgData = getImgData(chartContainer);

        

        // Replacing the mime-type will force the browser to trigger a download

        // rather than displaying the image in the browser window.

        window.location = imgData.replace("image/png", "image/octet-stream");

      }

      

      function toImg(chartContainer, imgContainer) { 

            var doc = chartContainer.ownerDocument;

            var img = doc.createElement('img');

            img.src = imgData = getImgData(chartContainer);

            document.getElementById("chart_html").value = imgData;

            while (imgContainer.firstChild) {

              imgContainer.removeChild(imgContainer.firstChild);

            }

            imgContainer.appendChild(img);

      }





      function setImgData(hiddenField, chartContainer) { 

        var doc = chartContainer.ownerDocument;

        var imgData = getImgData(chartContainer);

        document.getElementById(hiddenField).value = imgData;

      }





      



    </script>













</head>

<body class="yui-skin-sam">



	<div id="pageHolder">



		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>

		<div id="content">

                    <?php 

                    $data = $this->fp_percent_facprov;

                    //echo print_r($data[])

                    $state_name = $this->state_name;

                    $lga_name = $this->lga_name;

                    $folder_name = $this->folder_name;
                    
                    $report_rate = $this->report_rate;

                    $percent_facilities_with_fphw_not_prov_fp = $this->percent_fp_trained_not_providing_for_this_LGA;

                    $facilities_with_fp_trained_hw_not_provfp = $this->facilities_with_fp_trained_hw_not_provfp;

                    $facilities_fplist_implode = implode(',',$facilities_with_fp_trained_hw_not_provfp);

                    

                    $percent_larc_trained_not_providing_for_this_lga_value = $this->percent_larc_trained_not_providing;

                    $facilities_larctrained_not_providing = $this->facilities_larctrained_not_providing;

                    $facilities_larclist_implode = implode(',',$facilities_larctrained_not_providing);

                    

                    $percent_lga_stock_out_fp_seven_days = $this->percent_lga_stock_out_fp;

                    $facilities_stocked_out_fp_seven_days = implode(",",$this->facilities_stocked_out_fp_seven_days);

                   

                    

                    $facilities_stocked_out_larc = implode(',',$this->facilities_stocked_out_larc);

                    $percent_lga_stock_out_larc = $this->percent_lga_stock_out_larc;

                   //  print_r($facilities_larclist_implode);exit;

                     

                    

                     //print_r($this->consumption_overtime_lga);exit;

                    $report_id = $this->report_id;
                    $table_array = "";
                    
                    if(is_array($this->table_array)){
                    $table_array = implode(",",$this->table_array);
                    }

                    //print_r($this->fp_trained_lgas);echo '<br/><br/>';

          // print_r($this->larc_trained_lgas);echo '<br/><br/>';

          // print_r($this->fp_prov_lgas);echo '<br/><br/>';

          // print_r($this->larc_prov_lgas);echo '<br/><br/>';

                    

                  //  echo 'THis is the data we want to have here';

              //print_r($this->consumption_overtime);exit;

                    ?>



			<!-------   /////////////////////////// get data ////////////////////// -->



			<div>

			

			<!-------   /////////////////////////// load scripts ////////////////////// -->

                        <div class="nav-buttons">

				<?php require_once('views/scripts/dashboard/displayScripts.phtml');?>

			</div>



			<!-------   /////////////////////////// charts ////////////////////// -->





			<body class="docs slim framebox_body">

                            <form name="pdfForm" id="pdfForm" method="post" action="./createpdfState"> 

				<div id="allCharts" class="container">

                                    <input type="hidden" id="state_name" value="<?php echo $state_name; ?>" name="state_name"/>
                                    
                                    <input type="hidden" id="report_rate" value="<?php echo $report_rate; ?>" name="report_rate" />
                                    <input type="hidden" id="lga_name" value="<?php echo $lga_name; ?>" name="lga_name"/>

                                    <input type="hidden" id="lga_name_hidden" value="<?php echo $lga_name; ?>" name="lga_name_hidden"/>

                                    <input type="hidden" id="facilities_list_fp_prov_hidden" value="<?php echo $facilities_fplist_implode; ?>" name="facilities_list_fp_prov" />

				    <input type="hidden" id="percent_facilities_list_fp_prov_hidden" value="<?php echo $percent_facilities_with_fphw_not_prov_fp; ?>" name="percent_facilities_list_fp_prov" />

                                    

                                    <input type="hidden" id="percent_facilities_larc_prov_hidden" value="<?php echo $percent_larc_trained_not_providing_for_this_lga_value; ?>" name="percent_facilities_list_larc_prov" />

                                    

                                    <input type="hidden" id="percent_facilities_larctrained" value="<?php echo $percent_larc_trained_not_providing_for_this_lga_value; ?>" name="percent_facilities_larctrained" />

                                    

                                    <input type="hidden" id="percent_lga_stock_out_fp_seven_days_hidden" value="<?php echo $percent_lga_stock_out_fp_seven_days; ?>" name="percent_lga_stock_out_fp_seven_days_hidden" />

                                    <input type="hidden" id="facilities_stocked_out_fp_seven_days_hidden" value="<?php echo $facilities_stocked_out_fp_seven_days; ?>" name="facilities_stocked_out_fp_seven_days_hidden" />

                                    

                                    <input type="hidden" id="percent_lga_stock_out_larc_hidden" value="<?php echo $percent_lga_stock_out_larc; ?>" name="percent_lga_stock_out_larc_hidden" />

                                    <input type="hidden" id="facilities_stocked_out_larc_hidden" value="<?php echo $facilities_stocked_out_larc; ?>" name="facilities_stocked_out_larc_hidden" />

                                    

                                    

                                    <input type="hidden" id="facilities_list_larc_prov_hidden" value="<?php echo $facilities_larclist_implode; ?>" name="facilities_list_larc_prov" />

                                    <input type="hidden" id="folder_name" value="<?php echo $folder_name; ?>" name="folder_name" />

                                    

                                    <input type="hidden" id="report_id" value="<?php echo $report_id; ?>" name="report_id" />

                                    <div id="toprow" class="container">

						<div id="homecontent" class="container">

							<div id="homecontent-mid" class="row rounded">

								<div id="homebanner" class="rounded">

                                                                    

                                                                        <!--1 $ 2-->

                                                                        <div class="sliderdiv">

                                                                        <input type="text" name="facilitysum_hidden" id="facilitysum_hidden" value="" />

    									<div id="facilitysum_div"></div>

									</div>

                                                                        

                                                                    <div class="sliderdiv">

                                                                        <input type="text" name="chart13_hidden" id="chart13_hidden" value="" />

    									<div id="chart13_div"></div>

									</div>

                                                                      

                                                                    

                                                                        

                                                                      

                                                                        

                                                                        <input type="submit" name="generate" value="GENERATE" />

                                                                        

								</div>

							</div>

						</div>			

					</div>



				<div class="clear"></div>

				<div class="hrGrey"></div>

				<div class="clear"></div>



				

				</div>

                            </form>



                        </div>



		<div class="clear"></div>

		<div class="hrGrey"></div>

		<div class="clear"></div>

		

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <script type="text/javascript">

		

        google.load("visualization", "1", {packages:["corechart", "treemap", "geochart","table"]});

        google.setOnLoadCallback(drawCharts);



      function drawCharts(){

       

        

       

        drawChart13();

        drawFPANDLARCProviding();

        //drawTable();

        //ConvertToImage();

        //fpstock_hidden

      }



   

   function drawFPANDLARCProviding() {

      //alert('This is from drwChart');

      //console.log('This is from drwChart'); 

      //var trainedHw = new Array();

      

      <?php //for($i=0; $i < $this->cumm_data; $i++) {?>

        

              //trainedHW.push(<?php //echo $this->data[$i]['tp_fp'], $this->data[$i]['tp_larc']; ?>);

      <?php //} ?>

 var state_name = document.getElementById("state_name").value;

 var lga_name = document.getElementById("lga_name").value;

      var chartData = google.visualization.arrayToDataTable([

         

        [' ',lga_name , state_name],

        //[' ', 'Total FP Trained', 'Total LARC Trained'],

        <?php

        $percentageData = $this->facility_providing_lga_state;

        
        $stateData = (isset($percentageData[0]['percent'])?$percentageData[0]['percent']:0);
        $lgaData = (isset($percentageData[1]['percent'])?$percentageData[1]['percent']:0);
        
        $statepercent = round($stateData,1);
        $fp_prov_lga = round($lgaData,1);

       

        $category = "Provided FP";

//         $annotation = $nationalpercent . '%';

                   

                        echo "['" . $category . "', " . $fp_prov_lga . ", " . $statepercent . " ],";

                        

       $percentageData_stock_out = $this->fp_stock_out_for_seven_days;
       
       
       

        $statepercent = round((isset($percentageData_stock_out[0]))?$percentageData_stock_out[0]:0,1);

        $stocked_out_of_fp_data = round((isset($percentageData_stock_out[1]))?$percentageData_stock_out[1]:0,1);

        //$state_name = "Abia";

        $category = "Stocked out of FP";

//         $annotation = $nationalpercent . '%';

                   

                        echo "['" . $category . "', " . $stocked_out_of_fp_data  . ", " . $statepercent . " ],";

                        

              $percentageData_trained_hw = $this->facility_with_hw_trained_in_fp;

        $stateData = (isset($percentageData_trained_hw[0]['percent'])?$percentageData_trained_hw[0]['percent']:0);
        $lgaData = (isset($percentageData_trained_hw[1]['percent'])?$percentageData_trained_hw[1]['percent']:0);
        
        $statepercent = round($stateData,1);

        $fp_trained_hw = round($lgaData,1);

        //$state_name = "Abia";

        $category = "FP trained HW";

//         $annotation = $nationalpercent . '%';

                   

                        echo "['" . $category . "', " . $fp_trained_hw  . ", " . $statepercent . " ],";

                                

                        

                     

        ?>                                        

      ]);



 var view = new google.visualization.DataView(chartData);

    

    view.setColumns([0, 

                    1,{ calc: function(dt, row){

                            var percent1 = dt.getValue(row, 1)+"%";

                            return percent1;

                    },

                         sourceColumn: 1,

                         type: "string",

                         role: "annotation" },

                      

                    2,{ calc: function(dt, row){

                            var percent2 = dt.getValue(row, 2)+"%";

                            return percent2;

                    },

                         sourceColumn: 2,

                         type: "string",

                         role: "annotation" },

                   ]);

             

//              var national_title = <?php //echo "'$national_title'"; ?>;

              

              

      var chartOptions = {

                width: 600,

                height: 400,

                fontSize:16,

                bar: { width: '50%' },

                titleTextStyle: { fontSize: 16 },

                 annotations: {

     

    alwaysOutside: true

  },

                series: {2: {type: "line", color: 'red'}},

               vAxis: {format: '#\'%\'', minValue: 4},

                legend:{position:"bottom"}

                //seriesType: "bars",



              //  series: {2: {type: "line", color: 'red'}},

                //chartArea: {width: '50%', left: 80}//new       

                //tooltip: {'text' : 'both', isHtml : true}

      };



     var chart = new google.visualization.ColumnChart(document.getElementById('facilitysum_div'));

      google.visualization.events.addListener(chart, 'ready', function(){

            document.getElementById("facilitysum_hidden").value = chart.getImageURI();

     });

     chart.draw(view, chartOptions);

      //sendChartsData();

      

    }

   

   function drawChart13() {

        var data = google.visualization.arrayToDataTable([

          ['Year', 'Injectables',{role:'annotation'}, 'Implants',{role:'annotation'}],

          <?php

          $consumption_overtime = $this->consumption_overtime_lga;

          foreach($consumption_overtime as $key=>$cummValues){

              $injectables = $cummValues['Injectables'];

              if($cummValues['Injectables']==""){

                  $injectables = 0;

              }

              $implants = $cummValues['Implants'];

              if($cummValues['Implants']==""){

                  $implants = 0;

              }

              echo "['".$key."',".$injectables.",".$injectables.",".$implants.",".$implants."],";

          }

          ?>

         

        ]);



        var options = {

       

        pointSize:10,

         width: 900,

         fontSize:16,

         height: 400

          

        };



        var chart = new google.visualization.LineChart(document.getElementById('chart13_div'));

        

        google.visualization.events.addListener(chart, 'ready', function(){

            document.getElementById("chart13_hidden").value = chart.getImageURI();

     });

     

       var formatter = new google.visualization.NumberFormat(

  {groupingSymbol:','});

     var formating = new google.visualization.NumberFormat(

  {pattern:'###,###,##0'});



formatter.format(data, 1);

formating.format(data, 1);



formatter.format(data, 2);

formating.format(data, 2);





formatter.format(data, 3);

formating.format(data, 3);



formatter.format(data, 4);

formating.format(data, 4);

        chart.draw(data, options);

      }

      

    
    </script>





<script>

  devsite.github.Link.convertAnchors();

  window.prettyPrint();

</script>	



  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>







</body>



</html>