<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}


</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>


<script type="text/javascript" src="http://canvg.googlecode.com/svn/trunk/rgbcolor.js"></script> 
<script type="text/javascript" src="http://canvg.googlecode.com/svn/trunk/canvg.js"></script>
    

<script>
    
        var textChecker = '';
    
        $(document).ready(function(){           
            textChecker = setInterval(function(){ 
                console.log('timer fired');
                var elArray = document.forms["pdfForm"].getElementsByTagName('input');
                
                var found = false;
                for(var i=0; i<elArray.length; i++){
                    var el = elArray[i];
                    if(el.type == 'text'  && el.value == ''){
                        console.log(elArray[i]);
                        found = true;
                        
                    }
                }
                
                if(found == false){
                    //alert("It is still loading here");
                    console.log('clearing');
                    clear();
                    //call ajax handler
                    
                    sendChartsData();
                      //alert("We are here");
                }
            },1000);
        });
        
        function clear(){
            clearInterval(textChecker);
        }
    
        function sendChartsData(){
           
            var url = './createpdfState';
            var fcs_hidden = document.getElementById('fcs_hidden').value;
            var folder_name = document.getElementById("folder_name").value; 
            var state_hidden = document.getElementById('state_name').value;
            var report_hidden = document.getElementById('report_id').value;
            var fac_hw_hidden = document.getElementById('fac_hw_hidden').value;
            var chart13_hidden = document.getElementById('chart13_hidden').value;
            var larcprov_hidden = document.getElementById('larcprov_hidden').value;
            var fpprov_hidden = document.getElementById('fpprov_hidden').value;
            var fpstock_hidden = document.getElementById('fpstock_hidden').value;
            var larc_stock_out_hidden = document.getElementById('larc_stock_out_hidden').value;
            var table_hidden = document.getElementById('table_hidden').value;
            var report_rate = document.getElementById('report_rate').value;
           
            $.ajax({
                type: 'POST',
                url: url,
                data: {generate:true,fcs_hidden:fcs_hidden,report_rate:report_rate,state_hidden:state_hidden,report_hidden:report_hidden,fac_hw_hidden:fac_hw_hidden,
                    chart13_hidden:chart13_hidden,larcprov_hidden:larcprov_hidden,fpprov_hidden:fpprov_hidden,fpstock_hidden:fpstock_hidden,
                    larc_stock_out_hidden:larc_stock_out_hidden,table_hidden:table_hidden,folder_name:folder_name},
                success: function(response){
                    //reload the page
                     alert(response);
                    console.log('ajax success: ' + response);
                },
                error: function(e){
                    
                },
                complete: function(response, status){
                    console.log('ajax complete');
                  location.reload(); 
                }
                
            });
             
        }
        
        
      function getImgData(chartContainer) {
        //var chartArea = chartContainer.getElementsByTagName('iframe')[0].
          //contentDocument.getElementById('chartArea');
          
        var chartArea =
           chartContainer.getElementsByTagName('svg')[0].parentNode;
        var svg = chartArea.innerHTML;        
        var doc = chartContainer.ownerDocument;
        var canvas = doc.createElement('canvas');
        canvas.setAttribute('width', chartArea.offsetWidth);
        canvas.setAttribute('height', chartArea.offsetHeight);
                
        canvas.setAttribute(
            'style',
            'position: absolute; ' +
            'top: ' + (-chartArea.offsetHeight * 2) + 'px;' +
            'left: ' + (-chartArea.offsetWidth * 2) + 'px;');
        doc.body.appendChild(canvas);
        canvg(canvas, svg);
        var imgData = canvas.toDataURL("image/png");
        canvas.parentNode.removeChild(canvas);
        return imgData;
      }
      
      function tableChartReadyHandler(){
          setImgData("table_hidden", document.getElementById('table_div'));
      }
      function saveAsImg(chartContainer) {
        var imgData = getImgData(chartContainer);
        
        // Replacing the mime-type will force the browser to trigger a download
        // rather than displaying the image in the browser window.
        window.location = imgData.replace("image/png", "image/octet-stream");
      }
      
      function toImg(chartContainer, imgContainer) { 
            var doc = chartContainer.ownerDocument;
            var img = doc.createElement('img');
            img.src = imgData = getImgData(chartContainer);
            document.getElementById("chart_html").value = imgData;
            while (imgContainer.firstChild) {
              imgContainer.removeChild(imgContainer.firstChild);
            }
            imgContainer.appendChild(img);
      }


      function setImgData(hiddenField, chartContainer) { 
        var doc = chartContainer.ownerDocument;
        var imgData = getImgData(chartContainer);
        document.getElementById(hiddenField).value = imgData;
      }


      

    </script>






</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">
                    <?php 
                    $data = $this->fp_percent_facprov;
                    $report_rate = $this-->report_rate;
                    //echo print_r($data[])
                    $state_name = $data[1]['location'];
                    if(strtolower($state_name)!="federal capital territory"){
                    $state_name .=" State"; 
                    }
                    $folder_name = $this->folder_name;
                    $report_id = $this->report_id;
                    if(is_array($this->table_array)){
			$table_array = implode(",",$this->table_array);
                    }else{
                        $table_array = "";
                    }
                    
                  // echo $table_array;exit;
          // print_r($this->fp_prov_lgas);echo '<br/>';
           //print_r($this->larc_prov_lgas);echo '<br/>';
           //exit;
                    //print_r($this->fp_trained_lgas);echo '<br/><br/>';
          // print_r($this->larc_trained_lgas);echo '<br/><br/>';
          // print_r($this->fp_prov_lgas);echo '<br/><br/>';
          // print_r($this->larc_prov_lgas);echo '<br/><br/>';
                    
                  //  echo 'THis is the data we want to have here';
              //print_r($this->consumption_overtime);exit;
                    ?>

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
                        <div class="nav-buttons">
				<?php require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->


			<body class="docs slim framebox_body">
                            <form name="pdfForm" id="pdfForm" method="post" action="./createpdfState"> 
				<div id="allCharts" class="container">
                                    <input type="hidden" id="folder_name" value="<?php echo $folder_name; ?>" name="folder_name" />
                                    
                                    <input type="hidden" id="state_name" value="<?php echo $state_name; ?>" name="state_name"/>
				<input type="hidden" id="report_id" value="<?php echo $report_id; ?>" name="report_id" />
                                <input type="hidden" id="report_rate" value="<?php echo $report_rate; ?>" name="report_rate"  />
                                     <div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
                                                                    
                                                                        <!--1 $ 2-->
                                                                        <div class="sliderdiv">
                                                                                <!--1-->
                                                                                <!--<div id="chart11_div" style="width: 700px; height: 300px;"></div>-->
                                                                                <input type="text" name="fcs_hidden" id="fcs_hidden" value="" />
                                                                                <div id="fcs_div"></div>
                                                                                
                                                                                <br/><br/>
                                                                             <input type="text" name="fac_hw_hidden" id="fac_hw_hidden" value="" />
                                                                             <div id="fac_hw_div"></div> 
                                                                            
                                                                        </div>
                                                                    
                                                                       <div class="sliderdiv">
                                                                        <input type="text" name="chart13_hidden" id="chart13_hidden" value="" />
    									<div id="chart13_div"></div>
									</div>
                                                                        
                                                                        <div class="sliderdiv">
                                                                        <input type="text" name="table_hidden[]" id="table_hidden" value="<?php echo $table_array; ?>" />
    									<div id="table_div"></div>
									</div>
                                                                        
                                                                    <div class="sliderdiv">
                                                                        <input type="text" name="larcprov_hidden" id="larcprov_hidden" value="" />
    									<div id="larcprov_div"></div>
									</div>
                                                                        <div class="sliderdiv">
                                                                        <input type="text" name="fpprov_hidden" id="fpprov_hidden" value="" />
    									<div id="fpprov_div"></div>
									</div>
                                                                       <div class="sliderdiv">
                                                                        <input type="text" name="fpstock_hidden" id="fpstock_hidden" value="" />
    									<div id="fpstock_div"></div>
									</div>
                                                                        <div class="sliderdiv">
                                                                        <input type="text" name="larc_stock_out_hidden" id="larc_stock_out_hidden" value="" />
    									<div id="larc_stock_out_div"></div>
									</div>
                                                                        
                                                                      
                                                                        
                                                                        <input type="submit" name="generate" value="GENERATE" />
                                                                        
								</div>
							</div>
						</div>			
					</div>

				<div class="clear"></div>
				<div class="hrGrey"></div>
				<div class="clear"></div>

				
				</div>
                            </form>

                        </div>

		<div class="clear"></div>
		<div class="hrGrey"></div>
		<div class="clear"></div>
		
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
		
        google.load("visualization", "1", {packages:["corechart", "treemap", "geochart","table"]});
        google.setOnLoadCallback(drawCharts);

      function drawCharts(){
       
        drawFPANDLARCProviding();
        drawFPFacsProviding();
        drawLARCFacsProviding();
        drawFacsHWTrained();
        drawChart13();
        drawFpStockOut();
        drawLarcStockOutImplants();
        drawTable();
        //ConvertToImage();
        //fpstock_hidden
      }

function drawTable() {
   

        var data = new google.visualization.DataTable();
       

        data.addColumn('number', '% with FP-trained HWs');
        data.addColumn('number', '% with LARC-trained HWs');
        data.addColumn('number', '% Providing FP');
        data.addColumn('number', '% Providing LARC');
        data.addRows([
            <?php
           
           $fp_trained_lgas = $this->fp_trained_lgas;
           $larc_trained_lgas = $this->larc_trained_lgas;
           $fp_prov_lgas = $this->fp_prov_lgas;
           $larc_prov_lgas = $this->larc_prov_lgas;
           $length = sizeof($larc_trained_lgas);
            //print_r($this->fp_trained_lgas);
            //print_r($this->larc_trained_lgas);exit;
           for($i=1;$i<6;$i++){
               if($fp_trained_lgas[$i]['percent']==0)$fp_trained_lgas[$i]['percent']=0; 
               if($larc_trained_lgas[$i]['percent']==0)$larc_trained_lgas[$i]['percent']=0; 
               
               $percent_fp_trained = round($fp_trained_lgas[$i]['percent']*100,1);
               $percent_larc_trained = round($larc_trained_lgas[$i]['percent']*100,1);
               
               $fptrained = $fp_trained_lgas[$i]['location']." (".$percent_fp_trained."%)";
               $larctrained = $larc_trained_lgas[$i]['location']." (".$percent_larc_trained."%)";
              
               if($fp_prov_lgas[$i]['percent']==0)$fp_prov_lgas[$i]['percent']=0;                   
               if($larc_prov_lgas[$i]['percent']==0)$larc_prov_lgas[$i]['percent']=0;  
               
               $percent_fp_prov = round($fp_prov_lgas[$i]['percent']*100,1);
               $percent_larc_prov = round($larc_prov_lgas[$i]['percent']*100,1);
               
               $fpprov = $fp_prov_lgas[$i]['location']." (".$percent_fp_prov."%)";
               $larcprov = $larc_prov_lgas[$i]['location']." (".$percent_larc_prov."%)";
               
               
               $larc_prov = "LGA ".$i."(%)";
               $fp_prov = "LGA ".$i."(%)";
               ?>
            [<?php echo "{v:$percent_fp_trained,f:'$fptrained'}"; ?>,<?php echo "{v:$percent_larc_trained,f:'$larctrained'}"; ?>,<?php echo "{v:$percent_fp_prov, f:'$fpprov'}"; ?>, <?php echo "{v:$percent_larc_prov, f:'$larcprov'}"; ?>],
          <?php  }
                  ?>
        ]);

        var table = new google.visualization.Table(document.getElementById('table_div'));
        //google.visualization.events.addListener(table, 'ready',tableChartReadyHandler);
 
        table.draw(data);
      
}

function drawLarcStockOutImplants() {
	  // Create and populate the data table.
	  var chartData = google.visualization.arrayToDataTable([

           ['Location', 'Percent', { role: 'style' }, { role: 'annotation' }],

                <?php
                        $percentData = $this->stock_out_larc_implants;
                        reset($percentData); 
                        $firstKey = key($percentData); 
                        end($percentData); $lastKey = key($percentData); 
                        reset($percentData); 
                        $color = '';
                        $counter = 0;
                        foreach ($percentData as $key=>$row){ 
                            $location = $row['location']; $percent = $row['percent']; 
                            $color = $firstKey == $key ? 'black' : '';
                            if($key==$firstKey || $key==$lastKey || $counter<=5){
                                $counter++;
                            $location = $row['location']; $percent = round($row['percent']*100,1); 
                            $annotation = $percent . '%';
                            if($firstKey == $key) $color = 'black';
                            else if ($lastKey == $key) $color = 'green';
                            else $color = 'red'; 
                ?>
                            [<?php echo "'$location'";  ?>, <?php echo $percent; ?>,<?php echo "'$color'"; ?>, <?php echo "'$annotation'"; ?>],
                <?php
                            }
                        }
                ?>

            ]);

	  var chartOptions = {
                  
                      width: 600,
                      height: 400,
                      fontSize:16,
                      annotations: {
     
    alwaysOutside: true
  },
                      bar: { width: '50%' },
		      titleTextStyle: { fontSize: 15 },
		      vAxis: {format: '#\'%\'', minValue: 4},
		      legend: 'none',
                      vAxis: {min: 0,gridlines: {count: 5},viewWindow:{min:0}},
		      //chartArea: {height: '50%', top: 55},
		};

	  var chart = new google.visualization.ColumnChart(document.getElementById('larc_stock_out_div'));	            
          google.visualization.events.addListener(chart, 'ready', function(){
                document.getElementById('larc_stock_out_hidden').value = chart.getImageURI();
            });
	  chart.draw(chartData, chartOptions);
    }
 

function drawFpStockOut() {
	  // Create and populate the data table.
	  var chartData = google.visualization.arrayToDataTable([

           ['Location', 'Percent', { role: 'style' }, { role: 'annotation' }],

                <?php
                        $percentData = $this->stock_out_fp_com_seven_days;
                        reset($percentData); 
                        $firstKey = key($percentData); 
                        end($percentData); $lastKey = key($percentData); 
                        
                        reset($percentData); 
                        $color = '';
                        $counter = 0;
                        foreach ($percentData as $key=>$row){ 
                            $location = $row['location']; $percent = $row['percent']; 
                            $color = $firstKey == $key ? 'black' : '';
                            if($key==$firstKey || $key==$lastKey || $counter<=5){
                                $counter++;
                            $location = $row['location']; $percent = round($row['percent']*100,1); 
                            $annotation = $percent . '%';
                            if($firstKey == $key) $color = 'black';
                            else if ($lastKey == $key) $color = 'green';
                            else $color = 'red'; 
                ?>
                            [<?php echo "'$location'";  ?>, <?php echo $percent; ?>,<?php echo "'$color'"; ?>, <?php echo "'$annotation'"; ?>],
                <?php
                            }
                        }
                ?>

            ]);

	  var chartOptions = {
                  
                      width: 600,
                      height: 400,
                      fontSize:16,
                      bar: { width: '50%' },
                      annotations: {
     
    alwaysOutside: true
  },
		      titleTextStyle: { fontSize: 15 },
		      vAxis: {format: '#\'%\'', minValue: 4},
		      legend: 'none',
                      vAxis: {min: 0,gridlines: {count: 5},viewWindow:{min:0}},
		      //chartArea: {height: '50%', top: 55},
		};

	  var chart = new google.visualization.ColumnChart(document.getElementById('fpstock_div'));	            
          google.visualization.events.addListener(chart, 'ready', function(){
                document.getElementById('fpstock_hidden').value = chart.getImageURI();
            });
	  chart.draw(chartData, chartOptions);
    }
    
    
      
      
 function drawFacsHWTrained(){
    //alert('This is from drwChart');
      //console.log('This is from drwChart'); 
      //var trainedHw = new Array();
      
      <?php //for($i=0; $i < $this->cumm_data; $i++) {?>
        
              //trainedHW.push(<?php //echo $this->data[$i]['tp_fp'], $this->data[$i]['tp_larc']; ?>);
      <?php //} ?>
 var state_name = document.getElementById("state_name").value;

      var chartData = google.visualization.arrayToDataTable([
         
        [' ',state_name , 'National'],
        //[' ', 'Total FP Trained', 'Total LARC Trained'],
        <?php
        $percentageData = $this->fp_percent_facprov;
        
        $nationalpercent = round($percentageData[0]['percent']*100,1);
        $fp_prov_percent = round($percentageData[1]['percent']*100,1);
       
        $category = "Providing FP";
         $annotation = $nationalpercent . '%';
                   
                        echo "['" . $category . "', " . $fp_prov_percent . ", " . $nationalpercent . " ],";
            //larc_percent_facprov            
       $percentageData_larc = $this->larc_percent_facprov;
        $nationalpercent = round($percentageData_larc[0]['percent']*100,1);
        $larc_prov_percent = round($percentageData_larc[1]['percent']*100,1);
        $state_name = "Abia";
        $category = "Providing LARC";
         $annotation = $nationalpercent . '%';
                   
                        echo "['" . $category . "', " . $larc_prov_percent . ", " . $nationalpercent . " ],";
                     
        ?>                                        
      ]);

 var view = new google.visualization.DataView(chartData);
    
    view.setColumns([0, 
                    1,{ calc: function(dt, row){
                            var percent1 = dt.getValue(row, 1)+"%";
                            return percent1;
                    },
                         sourceColumn: 1,
                         type: "string",
                         role: "annotation" },
                      
                    2,{ calc: function(dt, row){
                            var percent2 = dt.getValue(row, 2)+"%";
                            return percent2;
                    },
                         sourceColumn: 2,
                         type: "string",
                         role: "annotation" },
                   ]);
             
              var national_title = <?php echo "'$national_title'"; ?>;
              
              
      var chartOptions = {
                width: 600,
                height: 400,
                fontSize:16,
                annotations: {
     
    alwaysOutside: true
  },
                bar: { width: '50%' },
                titleTextStyle: { fontSize: 16 },
                series: {2: {type: "line", color: 'red'}},
               vAxis: {format: '#\'%\'', minValue: 4},
               vAxis: {min: 0,max:100,gridlines: {count: 5},viewWindow:{max:100,min:0}},
                 
                  gridlines: {count: 5},
                legend:{position:"bottom"}
                //seriesType: "bars",

              //  series: {2: {type: "line", color: 'red'}},
                //chartArea: {width: '50%', left: 80}//new       
                //tooltip: {'text' : 'both', isHtml : true}
      };

     var chart = new google.visualization.ColumnChart(document.getElementById('fcs_div'));
      google.visualization.events.addListener(chart, 'ready', function(){
            document.getElementById("fcs_hidden").value = chart.getImageURI();
     });
     chart.draw(view, chartOptions);
      //sendChartsData();
        
 }
 

 
   
    function drawLARCFacsProviding() {
	  // Create and populate the data table.
	  var chartData = google.visualization.arrayToDataTable([

           ['Location', 'Percent', { role: 'style' }, { role: 'annotation' }],

                <?php
                        $percentData = $this->larc_percent_providing;
                        reset($percentData); 
                        $firstKey = key($percentData); 
                        end($percentData); $lastKey = key($percentData); 
                        reset($percentData); 
                        $color = '';
                        $counter = 0;
                        foreach ($percentData as $key=>$row){ 
                            $location = $row['location']; $percent = $row['percent']; 
                            $color = $firstKey == $key ? 'black' : '';
                            if($key==$firstKey || $key==$lastKey || $counter<=5){
                                $counter++;
                            $location = $row['location']; $percent = round($row['percent']*100,2); 
                            $annotation = $percent . '%';
                            if($firstKey == $key) $color = 'black';
                            else if ($lastKey == $key) $color = 'green';
                            else $color = 'red'; 
                ?>
                            [<?php echo "'$location'";  ?>, <?php echo $percent; ?>,<?php echo "'$color'"; ?>, <?php echo "'$annotation'"; ?>],
                <?php
                            }
                        }
                ?>

            ]);

	  var chartOptions = {
                   bar: { width: '50%' },
                      width: 600,
                      height: 400,
                      fontSize:16,
                      annotations: {
     
    alwaysOutside: true
  },
		      titleTextStyle: { fontSize: 15 },
		      vAxis: {format: '#\'%\'', minValue: 4},
                      vAxis: {min: 0,max:100,gridlines: {count: 5},viewWindow:{max:100,min:0}},
		      legend: 'none'
		      //chartArea: {height: '50%', top: 55},
		};

	  var chart = new google.visualization.ColumnChart(document.getElementById('larcprov_div'));	            
          google.visualization.events.addListener(chart, 'ready', function(){
                document.getElementById('larcprov_hidden').value = chart.getImageURI();
            });
	  chart.draw(chartData, chartOptions);
    }
    
    
    function drawFPFacsProviding() {
	  // Create and populate the data table.
	  var chartData = google.visualization.arrayToDataTable([

           ['Location', 'Percent', { role: 'style' }, { role: 'annotation' }],

                <?php
                        $percentData = $this->fp_percent_providing;
                        reset($percentData); 
                        $firstKey = key($percentData); 
                        end($percentData); $lastKey = key($percentData); 
                        reset($percentData); 
                        $color = '';
                        $counter = 0;
                        foreach ($percentData as $key=>$row){ 
                            $location = $row['location']; $percent = $row['percent']; 
                            $color = $firstKey == $key ? 'black' : '';
                            if($key==$firstKey || $key==$lastKey || $counter<=5){
                             
                                $counter++;
                            $location = $row['location']; $percent = round($row['percent']*100,1); 
                            $annotation = $percent . '%';
                            if($firstKey == $key) $color = 'black';
                            else if ($lastKey == $key) $color = 'green';
                            else $color = 'red'; 
                ?>
                            [<?php echo "'$location'";  ?>, <?php echo $percent; ?>,<?php echo "'$color'"; ?>, <?php echo "'$annotation'"; ?>],
                <?php
                            }
                        }
                ?>

            ]);

	  var chartOptions = {
                      bar: { width: '50%' },
                      width: 600,
                      height: 400,
                      fontSize:16,
                      annotations: {
     
    alwaysOutside: true
  },
		      titleTextStyle: { fontSize: 15 },
		      vAxis: {format: '#\'%\'', minValue: 4},
		      legend: 'none'
		      //chartArea: {height: '50%', top: 55},
		};

	  var chart = new google.visualization.ColumnChart(document.getElementById('fpprov_div'));	            
          google.visualization.events.addListener(chart, 'ready', function(){
                document.getElementById('fpprov_hidden').value = chart.getImageURI();
            });
	  chart.draw(chartData, chartOptions);
    }
    
    
   function drawFPANDLARCProviding() {
      //alert('This is from drwChart');
      //console.log('This is from drwChart'); 
      //var trainedHw = new Array();
      
      <?php //for($i=0; $i < $this->cumm_data; $i++) {?>
        
              //trainedHW.push(<?php //echo $this->data[$i]['tp_fp'], $this->data[$i]['tp_larc']; ?>);
      <?php //} ?>
 var state_name = document.getElementById("state_name").value;

      var chartData = google.visualization.arrayToDataTable([
         
        [' ',state_name , 'National'],
        //[' ', 'Total FP Trained', 'Total LARC Trained'],
        <?php
        $percentageData = $this->fp_trained_in;
        $maxHundred = false;
        $nationalpercent = round($percentageData[0]['percent']*100,1);
        $fp_hw_percent_data = round($percentageData[1]['percent']*100,1);
       
        $category = "FP trained HW";
         $annotation = $nationalpercent . '%';
                   
                        echo "['" . $category . "', " . $fp_hw_percent_data . ", " . $nationalpercent . " ],";
                        if($nationalpercent>100 || $fp_hw_percent_data>100){
                       $maxHundred = true;
                   }
       $percentageData_larc = $this->larc_trained_in;
        $nationalpercent = round($percentageData_larc[0]['percent']*100,1);
        $larc_hw_percent_data = round($percentageData_larc[1]['percent']*100,1);
        //$state_name = "Abia";
        $category = "LARC trained HW";
         $annotation = $nationalpercent . '%';
                   if($nationalpercent>100 || $larc_hw_percent_data>100){
                       $maxHundred = true;
                   }
                        echo "['" . $category . "', " . $larc_hw_percent_data . ", " . $nationalpercent . " ],";
                     
        ?>                                        
      ]);

 var view = new google.visualization.DataView(chartData);
    
    view.setColumns([0, 
                    1,{ calc: function(dt, row){
                            var percent1 = dt.getValue(row, 1)+"%";
                            return percent1;
                    },
                         sourceColumn: 1,
                         type: "string",
                         role: "annotation" },
                      
                    2,{ calc: function(dt, row){
                            var percent2 = dt.getValue(row, 2)+"%";
                            return percent2;
                    },
                         sourceColumn: 2,
                         type: "string",
                         role: "annotation" },
                   ]);
             
              var national_title = <?php echo "'$national_title'"; ?>;
              
              
      var chartOptions = {
                width: 600,
                height: 400,
                fontSize:16,
                annotations: {
     
    alwaysOutside: true
  },
                bar: { width: '50%' },
                titleTextStyle: { fontSize: 16 },
                series: {2: {type: "line", color: 'red'}},
               vAxis: {format: '#\'%\'', viewWindow: {
        min: 0, 
     
       
    }
   },
                legend:{position:"bottom"}
                //seriesType: "bars",

              //  series: {2: {type: "line", color: 'red'}},
                //chartArea: {width: '50%', left: 80}//new       
                //tooltip: {'text' : 'both', isHtml : true}
      };

     var chart = new google.visualization.ColumnChart(document.getElementById('fac_hw_div'));
      google.visualization.events.addListener(chart, 'ready', function(){
            document.getElementById("fac_hw_hidden").value = chart.getImageURI();
     });
    
     chart.draw(view, chartOptions);
      //sendChartsData();
      
    }
   
   function drawChart13() {
        var data = google.visualization.arrayToDataTable([
          ['Year', 'Injectables',{role:'annotation'}, 'Implants',{role:'annotation'}],
          <?php
          $consumption_overtime = $this->consumption_overtime;
          foreach($consumption_overtime as $key=>$cummValues){
              $injectables = $cummValues['Injectables'];
              if($cummValues['Injectables']==""){
                  $injectables = 0;
              }
              $implants = $cummValues['Implants'];
              if($cummValues['Implants']==""){
                  $implants = 0;
              }
              echo "['".$key."',".$injectables.",".$injectables.",".$implants.",".$implants."],";
          }
          ?>
         
        ]);

        var options = {
       
        pointSize:10,
         width: 900,
         fontSize:16,
         height: 450
          
        };

       
      var formatter = new google.visualization.NumberFormat(
  {groupingSymbol:','});
  var formating = new google.visualization.NumberFormat(
  {pattern:'###,###,##0'});

formatter.format(data, 1);
formating.format(data, 1);

formatter.format(data, 2);
formating.format(data, 2);


formatter.format(data, 3);
formating.format(data, 3);

formatter.format(data, 4);
formating.format(data, 4);
 var chart = new google.visualization.LineChart(document.getElementById('chart13_div'));
        google.visualization.events.addListener(chart, 'ready', function(){
            document.getElementById("chart13_hidden").value = chart.getImageURI();
     });
        chart.draw(data, options);
      }
    </script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>